import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "网络性能与瓶颈调优";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-performance-tuning-congestion-control-bbr",
    stageId: "network-performance-tuning",
    order: 1,
    eyebrowStage: eyebrow,
    title: "TCP 拥塞控制：Cubic vs BBR",
    concept: "Cubic 是 Linux 默认的 loss-based 拥塞控制，把丢包当作拥塞信号并按三次函数收敛；BBR 是 Google 提出的 model-based 算法，主动估算瓶颈带宽 (BtlBw) 与最小 RTT (RTprop)，在浅缓冲和有随机丢包的链路上吞吐更高。切换算法通过 `net.ipv4.tcp_congestion_control` 内核参数完成。",
    points: ["Cubic 丢包驱动，BBR 模型驱动", "BBR 用 BtlBw × RTprop 估算 pacing", "sysctl 可热切换算法"],
    memoryHook: "丢包=Cubic 缩窗，模型=BBR 探带宽",
    fileName: "switch-to-bbr.sh",
    code: `# 查看当前拥塞控制算法\nsysctl net.ipv4.tcp_congestion_control\n# net.ipv4.tcp_congestion_control = cubic\n\n# 查看内核支持的算法\nsysctl net.ipv4.tcp_available_congestion_control\n# net.ipv4.tcp_available_congestion_control = reno cubic bbr\n\n# 切换到 BBR（需要 Linux 4.9+）\nsudo modprobe tcp_bbr\nsudo sysctl -w net.ipv4.tcp_congestion_control=bbr\nsudo sysctl -w net.core.default_qdisc=fq\n\n# 验证一条连接实际使用的算法\nss -tin state established | head -n 4\n# ESTAB 0 0 10.0.0.2:443 10.0.0.9:52344\n#   bbr wscale:7,7 rto:212 rtt:11.3/2.1 mss:1448 pacing_rate 92.4Mbps`,
    prompt: "在存在随机丢包（如无线链路）的场景下，为什么 BBR 通常比 Cubic 吞吐更高？",
    correct: "BBR 用带宽 × RTT 模型判断拥塞，不把偶发丢包直接当作拥塞信号，因此不会盲目缩窗",
    wrong: "BBR 会自动禁用重传，所以丢包不影响吞吐",
    output: "net.ipv4.tcp_congestion_control = bbr\npacing_rate 92.4Mbps",
    lanes: ["检查现状", "切换算法", "验证连接"],
    laneValues: ["cubic", "sysctl=bbr", "ss 显示 bbr"],
    log: ["当前算法 cubic", "sysctl 切换为 bbr", "ss -tin 显示 bbr pacing_rate=92.4Mbps"],
    summary: ["Cubic 丢包=拥塞，BBR 模型驱动", "sysctl+fq qdisc 才能生效 pacing", "ss -tin 是最快的验证方法"],
    sourceTitle: "BBR: Congestion-Based Congestion Control (Google Research)",
    sourceUrl: "https://research.google/pubs/bbr-congestion-based-congestion-control/"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-slow-start-initcwnd",
    stageId: "network-performance-tuning",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Slow Start 与 initcwnd",
    concept: "TCP 建立连接后进入 Slow Start：拥塞窗口 (cwnd) 从 initcwnd 开始，每收到一个 ACK 翻倍增长。RFC 6928 建议 initcwnd=10 段 (~14KB)，对于首屏资源不到 14KB 的站点可以一次 RTT 全部传完；把 initcwnd 调大可缩短小对象首字节到完成的时间。",
    points: ["Slow Start 从 initcwnd 指数增长", "RFC 6928 推荐 initcwnd=10", "iproute2 可按路由粒度调整"],
    memoryHook: "首窗越大，短请求越快到齐",
    fileName: "check-initcwnd.sh",
    code: `# 查看默认路由的拥塞窗口\nip route show default\n# default via 10.0.0.1 dev eth0\n\n# 查看/修改 initcwnd 与 initrwnd\nip route change default via 10.0.0.1 dev eth0 initcwnd 10 initrwnd 10\nip route show default\n# default via 10.0.0.1 dev eth0 initcwnd 10 initrwnd 10\n\n# 用抓包验证首个 RTT 发送的段数\ntshark -r first-request.pcap -Y \"tcp.stream eq 0 && tcp.len > 0\" \\\n  -T fields -e frame.number -e tcp.len | head -n 12\n# 1 1448\n# 2 1448\n# ...\n# 10 1448   # Slow Start 首 RTT 打出 10 个 MSS`,
    prompt: "把 initcwnd 从 10 调到 40 是否总能加速？",
    correct: "不一定：initcwnd 过大在浅缓冲链路会立即丢包并回退，先测 RTT/丢包再调整",
    wrong: "只要带宽够，initcwnd 越大越好，可以一次性把响应全部推出去",
    output: "default via 10.0.0.1 dev eth0 initcwnd 10 initrwnd 10",
    lanes: ["查看路由", "调整 initcwnd", "抓包验证"],
    laneValues: ["default 10.0.0.1", "initcwnd=10", "首 RTT 10 段"],
    log: ["ip route show default", "ip route change initcwnd 10", "tshark 观察首 RTT 10 个 MSS"],
    summary: ["Slow Start 每 RTT 窗口翻倍", "initcwnd=10 是 RFC 6928 现代默认", "调大要配合链路容量评估"],
    sourceTitle: "RFC 6928 · Increasing TCP's Initial Window",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc6928"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-tcp-fast-open",
    stageId: "network-performance-tuning",
    order: 3,
    eyebrowStage: eyebrow,
    title: "TCP Fast Open (TFO)",
    concept: "TCP Fast Open 允许在 SYN 报文中携带应用层数据：客户端第一次握手时服务器颁发 TFO Cookie，后续再次连接时客户端把 Cookie 与数据一起放进 SYN，服务器验证通过后在 SYN-ACK 前就可开始处理请求，节省 1 个 RTT。",
    points: ["首次握手拿 Cookie，二次握手带数据", "内核 sysctl 与 socket 选项两处开启", "中间盒不透传会回退到普通三次握手"],
    memoryHook: "SYN 里塞数据，省一个 RTT",
    fileName: "enable-tfo.sh",
    code: `# 内核开启：位掩码 1=客户端 2=服务端 3=双端\nsudo sysctl -w net.ipv4.tcp_fastopen=3\n\n# Nginx 服务端开启\ncat >> /etc/nginx/nginx.conf <<'EOF'\nlisten 443 ssl fastopen=200;   # 队列长度\nEOF\nsudo nginx -s reload\n\n# curl 客户端强制 TFO\ncurl --tcp-fastopen https://api.example.com/health -v 2>&1 | grep -i \"fast\"\n# * Using TCP Fast Open\n\n# 抓包验证 SYN 里带了数据\ntshark -r tfo.pcap -Y \"tcp.flags.syn==1 && tcp.len>0\" \\\n  -T fields -e ip.src -e tcp.len -e tcp.options.tfo\n# 10.0.0.2 512 04:00:...   # SYN 携带 512B 数据 + TFO Cookie`,
    prompt: "TFO 已经在内核和 Nginx 都开启了，为什么抓包却看不到 SYN 携带数据？",
    correct: "路径上的 NAT/防火墙可能剥掉 TFO 选项或不放行带 payload 的 SYN，导致回退到普通握手",
    wrong: "TFO 只对 IPv6 生效，IPv4 上必须使用 QUIC 才能省 RTT",
    output: "* Using TCP Fast Open\ntcp.len=512 tcp.options.tfo=04:00:...",
    lanes: ["开启内核", "开启服务端", "抓包验证"],
    laneValues: ["tcp_fastopen=3", "nginx fastopen=200", "SYN 带 512B"],
    log: ["sysctl tcp_fastopen=3", "nginx listen fastopen=200 reload", "抓包看到 SYN 携带数据 + TFO cookie"],
    summary: ["TFO 用 Cookie 免二次握手 RTT", "客户端与服务端必须都开", "中间盒不透传就会回退"],
    sourceTitle: "RFC 7413 · TCP Fast Open",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc7413"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-nagle-delayed-ack",
    stageId: "network-performance-tuning",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Nagle 与 delayed ACK 交互",
    concept: "Nagle 算法会把小包缓存到有未确认数据的段一起发；delayed ACK 又会把 ACK 拖延最多 40ms 以合并回复。二者叠加时，请求-响应型协议 (如 RPC) 会出现约 40ms 的莫名停顿——典型解法是给短交互连接开启 `TCP_NODELAY` 关闭 Nagle。",
    points: ["Nagle 攒小包，delayed ACK 攒确认", "叠加产生 ~40ms 的写-读停顿", "短交互一律开 TCP_NODELAY"],
    memoryHook: "写小 + 缓 ACK = 40ms 卡顿",
    fileName: "nodelay.ts",
    code: `import { createServer, Socket } from \"node:net\";\n\ncreateServer((socket: Socket) => {\n  // 关闭 Nagle：短消息立即发送，避免与对端 delayed ACK 叠加\n  socket.setNoDelay(true);\n\n  socket.on(\"data\", (chunk) => {\n    const reply = Buffer.from(\`ack:\${chunk.length}\\n\`);\n    // 关掉 Nagle 后，即使 reply 只有 6 字节也会立刻上路\n    socket.write(reply);\n  });\n}).listen(9000);\n\n// 验证：\n// 1) 未开 TCP_NODELAY 时，tcpdump 会看到大量 40ms 左右的 ACK 延迟\n// 2) 开启后，ACK/响应几乎与请求同一个 RTT`,
    prompt: "一个 gRPC 服务在长连接上稳定出现 ~40ms 的 P99 抖动，最可能的原因是？",
    correct: "对端仍在使用 Nagle，本端又启用了 delayed ACK，二者叠加产生 40ms 停顿",
    wrong: "Node.js 事件循环延迟固定为 40ms，无法优化",
    output: "socket TCP_NODELAY=1\nack:12",
    lanes: ["建立连接", "写入短消息", "对端确认"],
    laneValues: ["accept", "TCP_NODELAY 立即发", "ACK 同 RTT"],
    log: ["新连接接入", "setNoDelay(true) 关闭 Nagle", "响应与请求同一个 RTT，无 40ms 停顿"],
    summary: ["Nagle 与 delayed ACK 叠加=交互性能杀手", "短交互连接开 TCP_NODELAY", "抓包上出现 40ms 空档即定位"],
    sourceTitle: "RFC 896 · Congestion Control in IP/TCP (Nagle)",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc896"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-bufferbloat-fq-codel",
    stageId: "network-performance-tuning",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Bufferbloat 与 fq_codel",
    concept: "Bufferbloat 指路由器/NIC 缓冲队列过深导致排队时延剧增：带宽满载时 RTT 从 20ms 涨到几百 ms，语音/游戏卡顿。fq_codel 用公平队列 + CoDel AQM 主动早丢弃过老的包，把队列时延压回 5ms 量级，是现代 Linux 的默认 qdisc。",
    points: ["缓冲越深，队列时延越大", "fq_codel = 公平队列 + CoDel AQM", "配合 BBR 才能实际打满带宽"],
    memoryHook: "队列越深，卡顿越深",
    fileName: "fq-codel.sh",
    code: `# 查看网卡当前 qdisc\ntc qdisc show dev eth0\n# qdisc pfifo_fast 0: root refcnt 2 bands 3\n\n# 切换为 fq_codel（Linux 3.6+ 默认）\nsudo tc qdisc replace dev eth0 root fq_codel\ntc qdisc show dev eth0\n# qdisc fq_codel 8001: root refcnt 2 limit 10240p flows 1024 quantum 1514 target 5ms interval 100ms\n\n# 用 flent 打满上下行并观察时延\nflent rrul -H test.example.com -l 30 -o rrul.png\n# Ping (ms) avg 22 -> 24  (fq_codel 生效)\n# Ping (ms) avg 22 -> 380 (pfifo_fast 出现 bufferbloat)`,
    prompt: "视频会议在打大文件上传时严重卡顿，本地路由器 qdisc 是 pfifo_fast，最合适的第一步优化是？",
    correct: "把出口 qdisc 换成 fq_codel/cake，让 AQM 早丢包避免队列时延爆炸",
    wrong: "升级带宽套餐，只要带宽足够 bufferbloat 就不存在",
    output: "qdisc fq_codel 8001: root ... target 5ms interval 100ms",
    lanes: ["查看 qdisc", "切换 fq_codel", "flent 验证"],
    laneValues: ["pfifo_fast", "fq_codel", "满载 RTT 稳定"],
    log: ["现状 pfifo_fast", "tc qdisc replace root fq_codel", "flent rrul 显示满载 RTT 从 380ms 降到 24ms"],
    summary: ["Bufferbloat 是队列时延不是带宽问题", "fq_codel 用 CoDel 主动早丢", "flent/rrul 是标准测量工具"],
    sourceTitle: "RFC 8290 · The FlowQueue-CoDel Packet Scheduler and AQM",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8290"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-keepalive-pooling",
    stageId: "network-performance-tuning",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Keep-Alive 与连接池",
    concept: "每次新建 TCP+TLS 至少要 2 个 RTT，是短请求最大的隐藏成本。HTTP Keep-Alive 在应答后保持连接，客户端用连接池按目标 host 缓存并复用 socket；正确设置 `keepAlive`、`maxSockets`、`maxFreeSockets` 才能同时避免握手成本与 socket 泄漏。",
    points: ["每次新连接=2 个 RTT 起步", "http.Agent 按 host 池化 socket", "keepAlive+maxSockets 决定复用率"],
    memoryHook: "池化连接=省 RTT",
    fileName: "http-agent.ts",
    code: `import http from \"node:http\";\nimport { setTimeout as sleep } from \"node:timers/promises\";\n\nconst agent = new http.Agent({\n  keepAlive: true,\n  keepAliveMsecs: 30_000,\n  maxSockets: 64,          // 每个 host 的最大并发连接\n  maxFreeSockets: 16       // 空闲连接池上限\n});\n\nasync function call(i: number) {\n  return new Promise<number>((resolve) => {\n    const req = http.request(\n      { host: \"api.internal\", port: 80, path: \`/ping?i=\${i}\`, agent },\n      (res) => {\n        res.resume();\n        res.on(\"end\", () => resolve(res.socket?.bytesRead ?? 0));\n      }\n    );\n    req.end();\n  });\n}\n\nfor (let i = 0; i < 5; i++) {\n  await call(i);\n  await sleep(50);\n}\nconsole.log(\"free sockets:\", agent.freeSockets[\"api.internal:80:\"]?.length ?? 0);`,
    prompt: "内部服务间调用把 `http.Agent({ keepAlive: false })` 保留为默认，会带来什么后果？",
    correct: "每次请求都要重新握手，P50/P99 上升，且连接快速耗尽本机临时端口",
    wrong: "keepAlive=false 会自动启用连接池，性能与 true 没有差别",
    output: "free sockets: 1",
    lanes: ["创建池化 Agent", "复用连接", "观察空闲池"],
    laneValues: ["agent keepAlive", "复用同一 socket", "freeSockets=1"],
    log: ["Agent keepAlive=true", "连续 5 次请求命中同一个 socket", "空闲池保留 1 条待复用"],
    summary: ["新连接是 2 个 RTT 的税", "按 host 池化并显式设 maxSockets", "监控 freeSockets 判定复用率"],
    sourceTitle: "Node.js http.Agent",
    sourceUrl: "https://nodejs.org/api/http.html#class-httpagent"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-ttfb-early-hints",
    stageId: "network-performance-tuning",
    order: 7,
    eyebrowStage: eyebrow,
    title: "TTFB 优化：dns-prefetch / preconnect / 103",
    concept: "首字节 (TTFB) 由 DNS + TCP + TLS + 服务端处理组成。浏览器端可用 `<link rel=\"dns-prefetch\">` 预解析、`<link rel=\"preconnect\">` 提前握手；服务端在真正的 200 之前先回一个 103 Early Hints，把关键 CSS/JS 的 preload 头下发给浏览器，让它在业务处理时就并行拉取。",
    points: ["dns-prefetch 只做 DNS，preconnect 走到 TLS", "103 Early Hints 让 preload 提前发出", "只对关键资源使用，避免带宽争抢"],
    memoryHook: "先握手，再 103，最后 200",
    fileName: "early-hints.ts",
    code: `import { createServer } from \"node:http\";\n\ncreateServer((req, res) => {\n  if (req.url === \"/\") {\n    // 1) 先下发 103 Early Hints，让浏览器在业务处理时并行拉取关键资源\n    res.writeEarlyHints({\n      link: [\n        \"</assets/app.css>; rel=preload; as=style\",\n        \"</assets/app.js>; rel=preload; as=script\",\n        \"<https://cdn.example.com>; rel=preconnect\"\n      ]\n    });\n\n    // 2) 模拟真实业务耗时后再返回 200\n    setTimeout(() => {\n      res.writeHead(200, { \"content-type\": \"text/html\" });\n      res.end(\`<!doctype html><link rel=\\\"stylesheet\\\" href=\\\"/assets/app.css\\\"><script src=\\\"/assets/app.js\\\"></script>\`);\n    }, 120);\n    return;\n  }\n  res.writeHead(404).end();\n}).listen(3000);\n\n// curl -sv http://localhost:3000/ 2>&1 | grep -E \"^< HTTP|^< link\"\n// < HTTP/1.1 103 Early Hints\n// < link: </assets/app.css>; rel=preload; as=style\n// < HTTP/1.1 200 OK`,
    prompt: "首页 TTFB 高达 800ms，其中 500ms 是数据库查询，最能加快用户看到首屏的手段是？",
    correct: "在 200 之前用 103 Early Hints 下发关键 CSS/JS 的 preload，让浏览器并行拉取",
    wrong: "把所有静态资源都 `<link rel=\"preload\">`，越多越好",
    output: "< HTTP/1.1 103 Early Hints\n< link: </assets/app.css>; rel=preload; as=style\n< HTTP/1.1 200 OK",
    lanes: ["下发 103", "服务端处理", "返回 200"],
    laneValues: ["writeEarlyHints", "查询 120ms", "text/html"],
    log: ["writeEarlyHints 下发 preload/preconnect", "业务处理 120ms", "200 OK 主文档返回"],
    summary: ["dns-prefetch<preconnect<preload 三级预热", "103 让 preload 提前一个 RTT", "只对关键资源用，别撑爆带宽"],
    sourceTitle: "RFC 8297 · An HTTP Status Code for Indicating Hints (103)",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8297"
  }),
  createNetworkLesson({
    id: "network-performance-tuning-core-web-vitals",
    stageId: "network-performance-tuning",
    order: 8,
    eyebrowStage: eyebrow,
    title: "RUM 指标：LCP / INP / CLS",
    concept: "Core Web Vitals 是 Google 定义的现场 (RUM) 指标：LCP 衡量最大内容渲染 (<=2.5s 为 Good)，INP 衡量所有交互到下一帧的最慢延迟 (<=200ms 为 Good，2024 起取代 FID)，CLS 衡量视口内累计布局偏移 (<=0.1)。用 web-vitals 库上报，聚合观察 P75。",
    points: ["LCP 看渲染，INP 看交互，CLS 看稳定", "P75 是官方评分口径", "现场 RUM 与实验室指标不能混用"],
    memoryHook: "看得快 LCP，点得稳 INP，不跳 CLS",
    fileName: "vitals.ts",
    code: `import { onLCP, onINP, onCLS, type Metric } from \"web-vitals\";\n\nfunction send(metric: Metric) {\n  const body = JSON.stringify({\n    name: metric.name,\n    value: metric.value,\n    rating: metric.rating,   // good | needs-improvement | poor\n    id: metric.id,\n    navType: metric.navigationType\n  });\n  navigator.sendBeacon(\"/rum\", body);\n}\n\nonLCP(send);   // 目标 P75 <= 2.5s\nonINP(send);   // 目标 P75 <= 200ms\nonCLS(send);   // 目标 P75 <= 0.1\n\n// 上报后端聚合示例（每分钟一次）：\n// SELECT name, quantileTDigest(0.75)(value) AS p75\n// FROM rum WHERE ts > now() - INTERVAL 1 MINUTE GROUP BY name;`,
    prompt: "灰度发布后仪表盘显示 INP P75 从 160ms 上升到 340ms，最直接的解读是？",
    correct: "75% 用户的最慢交互从 Good 掉到 Poor，需要立即回滚或定位阻塞主线程的脚本",
    wrong: "平均值只涨了一点，问题不大，可以下周再看",
    output: "{ name: 'INP', value: 340, rating: 'poor' }",
    lanes: ["采集指标", "上报后端", "P75 聚合"],
    laneValues: ["onLCP/onINP/onCLS", "sendBeacon", "p75=340ms"],
    log: ["web-vitals 监听 3 个指标", "sendBeacon 上报到 /rum", "后端聚合 INP P75=340ms 触发告警"],
    summary: ["Core Web Vitals 用 P75 打分", "INP 2024 起取代 FID", "RUM 数据反映真实用户体验"],
    sourceTitle: "web.dev · Core Web Vitals",
    sourceUrl: "https://web.dev/articles/vitals"
  })
];

const project = createNetworkStageProject({
  id: "network-performance-tuning-project",
  stageId: "network-performance-tuning",
  eyebrowStage: eyebrow,
  title: "端到端性能瀑布诊断",
  brief: "为一个真实站点建立从浏览器到源站的端到端性能瀑布：Navigation Timing / Resource Timing → HAR → 边缘/源站 access log → 内核抓包，把 DNS、连接、TTFB、下载、渲染各阶段的 P75/P95 与瓶颈来源串起来，形成可复现的诊断报告。",
  concept: "把本阶段知识点组装成闭环：dns-prefetch/preconnect/103 减少握手与等待、Keep-Alive/连接池减少重复握手、Cubic→BBR/initcwnd/fq_codel 处理链路瓶颈、Core Web Vitals 校验最终用户体验，用一个瀑布视图让每一层的优化都有证据。",
  points: ["按 DNS/TCP/TLS/TTFB/下载/渲染分层归因", "同时打通 HAR + access log + RUM", "每次优化都要能复现前后对比"],
  memoryHook: "分层瀑布 + 三源证据 + 对比复现",
  fileName: "perf-waterfall.ts",
  code: `import { chromium } from \"playwright\";\nimport { writeFileSync } from \"node:fs\";\n\ntype Phase = { name: string; startMs: number; durationMs: number };\n\nasync function diagnose(url: string) {\n  const browser = await chromium.launch();\n  const context = await browser.newContext();\n  const page = await context.newPage();\n\n  // 1) 收集 Navigation Timing + Resource Timing\n  const [navEntry, resources] = await Promise.all([\n    page.goto(url, { waitUntil: \"networkidle\" }).then(() =>\n      page.evaluate(() => JSON.parse(JSON.stringify(performance.getEntriesByType(\"navigation\")[0])))\n    ),\n    page.evaluate(() => performance.getEntriesByType(\"resource\").map((r) => JSON.parse(JSON.stringify(r))))\n  ]);\n\n  // 2) 收集 Core Web Vitals（RUM 侧）\n  const vitals = await page.evaluate(async () => {\n    const { onLCP, onINP, onCLS } = await import(\"https://unpkg.com/web-vitals?module\");\n    return await new Promise<Record<string, number>>((resolve) => {\n      const out: Record<string, number> = {};\n      const done = () => Object.keys(out).length >= 3 && resolve(out);\n      onLCP((m) => { out.LCP = m.value; done(); });\n      onINP((m) => { out.INP = m.value; done(); });\n      onCLS((m) => { out.CLS = m.value; done(); });\n      setTimeout(() => resolve(out), 8000);\n    });\n  });\n\n  // 3) 分层归因：把 Navigation Timing 拆成六段\n  const phases: Phase[] = [\n    { name: \"DNS\",      startMs: navEntry.domainLookupStart, durationMs: navEntry.domainLookupEnd - navEntry.domainLookupStart },\n    { name: \"TCP\",      startMs: navEntry.connectStart,      durationMs: navEntry.connectEnd - navEntry.connectStart },\n    { name: \"TLS\",      startMs: navEntry.secureConnectionStart || 0, durationMs: navEntry.connectEnd - (navEntry.secureConnectionStart || navEntry.connectEnd) },\n    { name: \"TTFB\",     startMs: navEntry.requestStart,      durationMs: navEntry.responseStart - navEntry.requestStart },\n    { name: \"Download\", startMs: navEntry.responseStart,     durationMs: navEntry.responseEnd - navEntry.responseStart },\n    { name: \"Render\",   startMs: navEntry.responseEnd,       durationMs: navEntry.loadEventEnd - navEntry.responseEnd }\n  ];\n\n  const report = { url, phases, vitals, resourceCount: resources.length };\n  writeFileSync(\"perf-report.json\", JSON.stringify(report, null, 2));\n  await browser.close();\n  return report;\n}\n\nconst report = await diagnose(\"https://www.example.com\");\nfor (const p of report.phases) {\n  console.log(\`\${p.name.padEnd(9)} \${p.durationMs.toFixed(0).padStart(5)} ms\`);\n}\nconsole.log(\"vitals:\", report.vitals);`,
  prompt: "报告显示 TTFB=520ms、LCP=3.8s，但 access log 里源站处理只有 60ms。下一步最该做什么？",
  correct: "把 TTFB 与源站处理时间对齐，重点排查 CDN/边缘、DNS、TLS 与队列时延，避免只优化源站",
  wrong: "直接加大源站数据库连接池，反正 TTFB 只可能是后端慢",
  correctFeedback: "正确：TTFB 与源站处理差值就是链路开销，可能来自 DNS/TLS/边缘队列，需要按瀑布分层归因。",
  wrongFeedback: "错误：源站只用 60ms，TTFB 却 520ms，问题几乎一定不在数据库连接池。",
  additionalWrong: {
    label: "先把所有静态资源都 preload，再看指标",
    feedback: "错误：无差别 preload 会挤占带宽，反而拖慢 LCP，应先定位瓶颈层再针对性优化。"
  },
  lanes: ["采集 Timing", "分层归因", "对比复现"],
  laneValues: ["Navigation+Resource", "6 段瀑布", "优化前后对比"],
  log: ["Playwright 采集 Navigation/Resource Timing 与 RUM", "拆分为 DNS/TCP/TLS/TTFB/Download/Render 六段", "写入 perf-report.json 供优化前后对比"],
  summary: ["性能优化以证据为先，不靠猜", "浏览器/CDN/源站三源必须对齐", "每次改动都要留下前后对比报告"],
  sourceTitle: "MDN · Link prefetching FAQ",
  sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ"
});

export const networkStageSevenPerformanceTuningLessons: LessonSpec[] = [...knowledgeLessons, project];
