import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "TLS 与传输安全";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-tls-security-handshake-flow",
    stageId: "network-tls-security",
    order: 1,
    eyebrowStage: eyebrow,
    title: "TLS 1.3 握手完整流程",
    concept: "TLS 1.3 把握手压缩到 1-RTT：ClientHello 就带上 key_share，服务端一次性回 ServerHello + EncryptedExtensions + Certificate + CertificateVerify + Finished，之后立即切到应用数据。相比 TLS 1.2 少了一次往返，且握手消息全部加密。",
    points: ["1-RTT 完成握手", "key_share 随 ClientHello 一起发", "ServerHello 之后消息全部加密"],
    memoryHook: "TLS 1.3 = 一趟握手，密钥先行",
    fileName: "tls13-handshake.ts",
    code: `import tls from \"node:tls\";\nimport fs from \"node:fs\";\n\nconst socket = tls.connect({\n  host: \"example.com\",\n  port: 443,\n  minVersion: \"TLSv1.3\",\n  maxVersion: \"TLSv1.3\",\n  ca: fs.readFileSync(\"/etc/ssl/certs/ca-certificates.crt\")\n}, () => {\n  console.log(\"protocol:\", socket.getProtocol());\n  console.log(\"cipher:\", socket.getCipher().name);\n  socket.write(\"GET / HTTP/1.1\\r\\nHost: example.com\\r\\n\\r\\n\");\n});\n\nsocket.on(\"secureConnect\", () => {\n  console.log(\"authorized:\", socket.authorized);\n});`,
    prompt: "TLS 1.3 相比 TLS 1.2 在握手上最大的改进是什么？",
    correct: "把握手压到 1-RTT，ClientHello 就带 key_share，且握手消息大部分加密",
    wrong: "只是把加密算法换成 AEAD，握手轮次没有变化",
    output: "protocol: TLSv1.3\ncipher: TLS_AES_128_GCM_SHA256\nauthorized: true",
    lanes: ["ClientHello", "ServerHello+密钥", "AppData"],
    laneValues: ["带 key_share", "加密握手 + Finished", "TLSv1.3 established"],
    log: ["发出 ClientHello (含 key_share)", "收到加密 ServerHello + Certificate + Finished", "1-RTT 完成，切换到应用数据"],
    summary: ["TLS 1.3 只需 1-RTT", "ClientHello 就要带 key_share", "ServerHello 之后的握手消息全部加密"],
    sourceTitle: "RFC 8446 - TLS 1.3",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8446"
  }),
  createNetworkLesson({
    id: "network-tls-security-cert-chain",
    stageId: "network-tls-security",
    order: 2,
    eyebrowStage: eyebrow,
    title: "证书链验证与 CA 信任",
    concept: "浏览器/Node 收到 Server Certificate 后，会顺着链一路验证到本地信任的根 CA：校验签名、有效期、Subject/SAN、Key Usage、以及是否被吊销。任何一环失败都会阻断连接。Let’s Encrypt 的 ISRG Root X1 就是主流可信根之一。",
    points: ["证书是链，不是单张", "校验签名 + 有效期 + SAN", "根 CA 必须在本地信任列表"],
    memoryHook: "服务器证书 → 中间 CA → 根 CA，缺一环都断",
    fileName: "verify-chain.ts",
    code: `import tls from \"node:tls\";\nimport { X509Certificate } from \"node:crypto\";\n\nconst socket = tls.connect({ host: \"letsencrypt.org\", port: 443, servername: \"letsencrypt.org\" }, () => {\n  const peer = socket.getPeerX509Certificate();\n  let cert: X509Certificate | undefined = peer;\n  const chain: string[] = [];\n  while (cert) {\n    chain.push(\`\${cert.subject} <- \${cert.issuer}\`);\n    cert = cert.issuerCertificate === cert ? undefined : cert.issuerCertificate;\n  }\n  console.log(\"authorized:\", socket.authorized);\n  console.log(\"chain:\", chain);\n  socket.end();\n});`,
    prompt: "浏览器验证服务器证书时，为什么必须一路验到根 CA？",
    correct: "只有根 CA 是本地预置的信任锚，任何中间证书都必须被上一级签名才算可信",
    wrong: "只要服务器证书本身没过期且域名匹配就可以直接信任",
    output: "authorized: true\nchain: [ 'CN=letsencrypt.org <- CN=R3', 'CN=R3 <- CN=ISRG Root X1' ]",
    lanes: ["收到服务器证书", "沿链验证", "匹配根 CA"],
    laneValues: ["leaf: letsencrypt.org", "中间证书: R3", "根: ISRG Root X1"],
    log: ["拿到叶子证书 letsencrypt.org", "验证中间证书 R3 签名", "根 CA ISRG Root X1 已在本地信任"],
    summary: ["证书验证是链式的，缺任何一环都失败", "SAN/有效期/签名三项必须全部通过", "根 CA 必须来自本地信任存储"],
    sourceTitle: "Let’s Encrypt 证书兼容性",
    sourceUrl: "https://letsencrypt.org/docs/certificate-compatibility/"
  }),
  createNetworkLesson({
    id: "network-tls-security-sni-alpn",
    stageId: "network-tls-security",
    order: 3,
    eyebrowStage: eyebrow,
    title: "SNI 与 ALPN 协商",
    concept: "同一个 IP:443 上通常挂着多个虚拟主机，ClientHello 里的 SNI 扩展告诉服务端要访问哪个域名，服务端据此挑选证书。ALPN 则在握手内协商上层协议（h2/http/1.1/h3），避免再来一次 HTTP Upgrade。",
    points: ["SNI 决定服务端返回哪张证书", "ALPN 在握手内协商 h2/h3", "两者都在 ClientHello 里"],
    memoryHook: "SNI 挑证书，ALPN 挑协议",
    fileName: "sni-alpn.ts",
    code: `import tls from \"node:tls\";\n\nconst socket = tls.connect({\n  host: \"www.cloudflare.com\",\n  port: 443,\n  servername: \"www.cloudflare.com\", // 触发 SNI\n  ALPNProtocols: [\"h2\", \"http/1.1\"]\n}, () => {\n  console.log(\"servername:\", socket.servername);\n  console.log(\"alpn:\", socket.alpnProtocol);\n  console.log(\"cert CN:\", socket.getPeerCertificate().subject.CN);\n  socket.end();\n});`,
    prompt: "客户端不发 SNI，直接连一个共享 IP 上的 HTTPS 站点会怎样？",
    correct: "服务端不知道要用哪张证书，通常返回默认证书导致域名不匹配而握手失败",
    wrong: "服务端会按 TCP 目标 IP 自动挑选正确证书，不受 SNI 影响",
    output: "servername: www.cloudflare.com\nalpn: h2\ncert CN: cloudflare.com",
    lanes: ["ClientHello", "服务端选证书", "协商 ALPN"],
    laneValues: ["SNI=www.cloudflare.com", "命中 cloudflare 证书", "选中 h2"],
    log: ["ClientHello 带 SNI 与 ALPN 列表", "服务端按 SNI 挑证书", "ALPN 协商结果: h2"],
    summary: ["SNI 是多租户 HTTPS 的前提", "ALPN 让 h2/h3 无需 Upgrade", "两个扩展都在 ClientHello 中发送"],
    sourceTitle: "Node.js tls 模块",
    sourceUrl: "https://nodejs.org/api/tls.html"
  }),
  createNetworkLesson({
    id: "network-tls-security-pfs-ecdhe",
    stageId: "network-tls-security",
    order: 4,
    eyebrowStage: eyebrow,
    title: "前向保密（PFS）与 ECDHE",
    concept: "前向保密要求即便长期私钥泄露，历史会话也无法解密。做法是每次握手用临时的 ECDHE 密钥对协商共享秘密，长期证书私钥只用来签名不用于加密。TLS 1.3 强制所有套件都提供 PFS。",
    points: ["每次握手临时 ECDHE 密钥", "证书私钥只签名不加密", "TLS 1.3 强制 PFS"],
    memoryHook: "临时密钥每次换，历史流量永安全",
    fileName: "pfs-ecdhe.ts",
    code: `import tls from \"node:tls\";\n\nconst socket = tls.connect({\n  host: \"www.google.com\",\n  port: 443,\n  minVersion: \"TLSv1.3\"\n}, () => {\n  const info = socket.getCipher();\n  const ephemeral = socket.getEphemeralKeyInfo();\n  console.log(\"cipher:\", info.name);\n  console.log(\"kex:\", ephemeral?.type, ephemeral?.name, ephemeral?.size);\n  socket.end();\n});`,
    prompt: "前向保密（PFS）主要防御的是哪种威胁？",
    correct: "服务器长期私钥未来被泄露时，攻击者仍无法解密以前抓到的密文",
    wrong: "防止中间人在握手期间伪造证书导致的解密攻击",
    output: "cipher: TLS_AES_128_GCM_SHA256\nkex: ECDH X25519 253",
    lanes: ["生成临时 ECDHE", "协商共享秘密", "派生会话密钥"],
    laneValues: ["X25519 keypair", "ECDHE 交换", "派生 traffic secret"],
    log: ["生成一次性 X25519 密钥对", "与对端 ECDHE 交换", "派生本次会话密钥"],
    summary: ["PFS 关键在于临时密钥每次换", "证书私钥仅用于身份签名", "TLS 1.3 所有套件都强制 PFS"],
    sourceTitle: "RFC 8446 - TLS 1.3",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8446"
  }),
  createNetworkLesson({
    id: "network-tls-security-hsts-preload",
    stageId: "network-tls-security",
    order: 5,
    eyebrowStage: eyebrow,
    title: "HSTS + Preload 列表",
    concept: "HSTS 头 `Strict-Transport-Security` 告诉浏览器在 max-age 时间内只用 HTTPS 访问该域名。加入 Preload 列表后，浏览器出厂就带这条策略，避免首访明文那一次被劫持的窗口期。要求 max-age≥31536000、includeSubDomains 且 preload。",
    points: ["HSTS 首访仍有明文窗口", "Preload 让浏览器出厂即知", "上榜要求 max-age≥1 年 + 全子域"],
    memoryHook: "HSTS 关掉 http 回退，Preload 关掉首访窗口",
    fileName: "hsts.ts",
    code: `import http from \"node:http\";\n\nconst server = http.createServer((req, res) => {\n  res.setHeader(\n    \"Strict-Transport-Security\",\n    \"max-age=63072000; includeSubDomains; preload\"\n  );\n  res.setHeader(\"Content-Type\", \"text/plain\");\n  res.end(\"ok\");\n});\n\n// 生产环境应放在 HTTPS 反向代理之后，仅对 https 响应返回该头。\nserver.listen(3000, () => console.log(\"listening on 3000\"));`,
    prompt: "只在 HTTPS 站点上加 HSTS 头，用户第一次通过 http:// 访问仍可能被劫持，如何彻底关掉这个窗口？",
    correct: "把域名加入 HSTS Preload 列表，浏览器出厂就强制走 HTTPS",
    wrong: "把 max-age 调到极大即可，浏览器就会永远记住策略",
    output: "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload",
    lanes: ["响应带 HSTS", "浏览器记住策略", "加入 Preload"],
    laneValues: ["max-age=2y", "本地缓存策略", "浏览器出厂即知"],
    log: ["响应写入 Strict-Transport-Security", "浏览器缓存 2 年 HSTS", "域名上榜 hstspreload.org"],
    summary: ["HSTS 阻止 http 回退", "首访窗口靠 Preload 关闭", "上榜需要 max-age≥1 年 + includeSubDomains + preload"],
    sourceTitle: "HSTS Preload List",
    sourceUrl: "https://hstspreload.org/"
  }),
  createNetworkLesson({
    id: "network-tls-security-ct-ocsp",
    stageId: "network-tls-security",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Certificate Transparency + OCSP Stapling",
    concept: "CT 要求 CA 把签发的证书写入公开日志，浏览器验证 SCT 才认可证书；OCSP Stapling 让服务端定期取最新的吊销状态并随握手一起下发，避免客户端再向 CA 发查询请求，兼顾隐私和性能。",
    points: ["CT 让签发行为可审计", "SCT 是浏览器信任的凭据", "OCSP Stapling 由服务端代查代发"],
    memoryHook: "CT 记签发，OCSP 记吊销，Stapling 顺路带",
    fileName: "ocsp-stapling.ts",
    code: `import https from \"node:https\";\nimport fs from \"node:fs\";\n\nconst server = https.createServer({\n  key: fs.readFileSync(\"key.pem\"),\n  cert: fs.readFileSync(\"cert.pem\"),\n  requestOCSP: true\n}, (req, res) => res.end(\"ok\"));\n\nserver.on(\"OCSPRequest\", (cert, issuer, callback) => {\n  // 生产环境应缓存并异步刷新 OCSP 响应\n  fetchOcspResponse(cert, issuer).then((resp) => callback(null, resp));\n});\n\nserver.listen(8443);\ndeclare function fetchOcspResponse(cert: Buffer, issuer: Buffer): Promise<Buffer>;`,
    prompt: "为什么大多数生产站点会开启 OCSP Stapling 而不是让浏览器自己去查 OCSP？",
    correct: "服务端代查代发能减少一跳网络，同时避免把访问站点信息泄露给 CA",
    wrong: "只是为了让浏览器不再校验证书吊销状态，节省流量",
    output: "TLSv1.3, cipher=TLS_AES_128_GCM_SHA256, OCSP=stapled",
    lanes: ["证书上 CT 日志", "服务端预取 OCSP", "握手内一起下发"],
    laneValues: ["SCT 附在证书", "OCSP 响应缓存", "Stapling 命中"],
    log: ["证书带 SCT，写入 CT 日志", "服务端定期拉取 OCSP 响应", "握手时随证书一并下发"],
    summary: ["CT 让 CA 行为可审计", "SCT 是浏览器认可证书的必要条件", "OCSP Stapling 提升性能并保护隐私"],
    sourceTitle: "Certificate Transparency",
    sourceUrl: "https://certificate.transparency.dev/"
  }),
  createNetworkLesson({
    id: "network-tls-security-post-quantum",
    stageId: "network-tls-security",
    order: 7,
    eyebrowStage: eyebrow,
    title: "Post-Quantum 就绪（ML-KEM）",
    concept: "为对抗未来量子计算“先抓后解”攻击，Chrome/Cloudflare/Google 已在 TLS 1.3 里默认启用混合密钥交换 `X25519MLKEM768`：把经典 ECDHE 和后量子 KEM 的共享秘密拼在一起派生会话密钥，任一算法安全整体就安全。",
    points: ["威胁是先抓密文再解", "混合 KEM = 经典 + 后量子", "任一算法安全则整体安全"],
    memoryHook: "先抓后解怕量子，混合 KEM 保安全",
    fileName: "pq-hybrid.ts",
    code: `import tls from \"node:tls\";\n\n// Node 需要启用支持 PQ 曲线的构建 (Node 24+ / OpenSSL 3.5)\nconst socket = tls.connect({\n  host: \"pq.cloudflareresearch.com\",\n  port: 443,\n  minVersion: \"TLSv1.3\",\n  // 优先协商混合曲线，回落到经典 X25519\n  // 对应 OpenSSL groups 字符串\n  // @ts-expect-error Node 新增字段\n  groups: \"X25519MLKEM768:X25519:P-256\"\n}, () => {\n  const kex = socket.getEphemeralKeyInfo();\n  console.log(\"kex:\", kex?.name);\n  socket.end();\n});`,
    prompt: "为什么现在就要在 TLS 里部署后量子密钥交换，即使实用量子计算机还没到？",
    correct: "攻击者可以现在抓走密文等未来量子机成熟再解密（Harvest Now, Decrypt Later）",
    wrong: "后量子算法比 ECDHE 更快，纯粹是为了性能收益",
    output: "kex: X25519MLKEM768",
    lanes: ["ClientHello", "协商混合曲线", "派生共享秘密"],
    laneValues: ["groups=X25519MLKEM768,...", "双方支持则命中", "hybrid secret"],
    log: ["ClientHello 声明 X25519MLKEM768 优先", "服务端选择混合曲线", "混合共享秘密派生会话密钥"],
    summary: ["“先抓后解”是现实威胁", "混合 KEM 保证任一算法安全整体就安全", "浏览器和主流 CDN 已默认启用"],
    sourceTitle: "RFC 8446 - TLS 1.3",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8446"
  }),
  createNetworkLesson({
    id: "network-tls-security-mtls-device",
    stageId: "network-tls-security",
    order: 8,
    eyebrowStage: eyebrow,
    title: "mTLS 与设备证书",
    concept: "双向 TLS 让服务端也校验客户端证书，常用于零信任网关、服务网格与 IoT 设备接入。服务端配 `requestCert: true` + `rejectUnauthorized: true`，客户端出示由内部 CA 签发的证书；证书轮转与吊销通过短有效期或 CRL/OCSP 管理。",
    points: ["双方都出示证书", "服务端 rejectUnauthorized 兜底", "短有效期比吊销更好用"],
    memoryHook: "服务端也要看客户端的证",
    fileName: "mtls.ts",
    code: `import https from \"node:https\";\nimport fs from \"node:fs\";\n\nconst server = https.createServer({\n  key: fs.readFileSync(\"server.key\"),\n  cert: fs.readFileSync(\"server.crt\"),\n  ca: fs.readFileSync(\"internal-ca.crt\"),\n  requestCert: true,\n  rejectUnauthorized: true\n}, (req, res) => {\n  const peer = (req.socket as import(\"tls\").TLSSocket).getPeerCertificate();\n  res.end(\`hello \${peer.subject.CN}\`);\n});\n\nserver.listen(8443, () => console.log(\"mTLS listening on 8443\"));`,
    prompt: "服务端开了 mTLS 却把 `rejectUnauthorized` 设为 false，会带来什么风险？",
    correct: "任何客户端即便证书无效也能建连，等于事实上关闭了双向认证",
    wrong: "只是日志里少一条警告，安全性并没有本质变化",
    output: "hello device-042.factory.internal",
    lanes: ["服务端要求证书", "客户端出示证书", "服务端校验"],
    laneValues: ["requestCert=true", "device-042 证书", "内部 CA 通过"],
    log: ["服务端要求客户端证书", "客户端发送 device-042 证书", "内部 CA 校验通过，允许建连"],
    summary: ["mTLS = 双向证书认证", "rejectUnauthorized 必须为 true", "短有效期比 CRL 更利于运维"],
    sourceTitle: "Node.js tls 模块",
    sourceUrl: "https://nodejs.org/api/tls.html"
  })
];

const project = createNetworkStageProject({
  id: "network-tls-security-project",
  stageId: "network-tls-security",
  eyebrowStage: eyebrow,
  title: "为服务加固 TLS 1.3 + HSTS + mTLS",
  brief: "把一个既有 HTTPS 服务升级到生产级安全基线：仅允许 TLS 1.3、强制 ECDHE PFS、返回严格 HSTS 头、对内部管理接口启用 mTLS，并输出握手证据供审计。",
  concept: "串联本阶段知识点：TLS 1.3 握手、证书链、SNI/ALPN、PFS、HSTS、CT/OCSP、后量子曲线与 mTLS，形成一份可复现的服务安全加固清单。",
  points: ["最小版本 TLS 1.3 + PFS", "HSTS preload 头 + 重定向", "内部接口 mTLS 拦截未授权客户端"],
  memoryHook: "TLS 1.3 打底，HSTS 收口，mTLS 兜底",
  fileName: "harden-tls.ts",
  code: `import https from \"node:https\";\nimport fs from \"node:fs\";\nimport tls from \"node:tls\";\n\nconst secureContext = tls.createSecureContext({\n  key: fs.readFileSync(\"server.key\"),\n  cert: fs.readFileSync(\"server.crt\"),\n  ca: fs.readFileSync(\"internal-ca.crt\"),\n  minVersion: \"TLSv1.3\",\n  ciphers: \"TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384\"\n});\n\nconst server = https.createServer({\n  SNICallback: (_name, cb) => cb(null, secureContext),\n  ALPNProtocols: [\"h2\", \"http/1.1\"],\n  requestCert: true,\n  rejectUnauthorized: false // 只对 /admin 做严格 mTLS\n}, (req, res) => {\n  res.setHeader(\n    \"Strict-Transport-Security\",\n    \"max-age=63072000; includeSubDomains; preload\"\n  );\n  const sock = req.socket as tls.TLSSocket;\n\n  if (req.url?.startsWith(\"/admin\")) {\n    if (!sock.authorized) {\n      res.statusCode = 401;\n      return res.end(\"client cert required\");\n    }\n    const peer = sock.getPeerCertificate();\n    return res.end(\`admin: \${peer.subject.CN}\`);\n  }\n\n  res.setHeader(\"Content-Type\", \"application/json\");\n  res.end(JSON.stringify({\n    protocol: sock.getProtocol(),\n    cipher: sock.getCipher().name,\n    alpn: sock.alpnProtocol,\n    peer: sock.authorized ? sock.getPeerCertificate().subject.CN : null\n  }));\n});\n\nserver.listen(8443, () => console.log(\"hardened HTTPS on 8443\"));`,
  prompt: "把服务从 TLS 1.2 迁到 TLS 1.3 + HSTS + mTLS 时，最容易被忽略但必须验证的一项是什么？",
  correct: "验证证书链、SAN、SNI、ALPN、HSTS 头和 mTLS 客户端拒绝行为都符合预期",
  wrong: "只要浏览器地址栏有小锁标志就算完成迁移",
  correctFeedback: "正确：安全加固必须用抓包或 openssl s_client 逐项确认协议、证书和策略头，不能只看 UI 提示。",
  wrongFeedback: "错误：小锁只代表建连成功，无法告诉你 TLS 版本、HSTS、mTLS 是否按预期生效。",
  additionalWrong: {
    label: "只把 minVersion 改成 TLSv1.3 即可，其它保持默认",
    feedback: "错误：还需要显式配置 HSTS、SNI、ALPN 与 mTLS 策略，才能覆盖生产级安全基线。"
  },
  lanes: ["TLS 1.3 建连", "HSTS 头下发", "mTLS 校验"],
  laneValues: ["TLSv1.3 + h2", "Strict-Transport-Security 已发", "/admin 强制客户端证书"],
  log: ["TLS 1.3 握手完成，选中 h2", "响应写入 HSTS preload", "/admin 校验客户端证书通过/拒绝"],
  summary: ["强制 TLS 1.3 是基础", "HSTS preload 关闭首访窗口", "mTLS 保护内部管理面"],
  sourceTitle: "MDN Strict-Transport-Security",
  sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security"
});

export const networkStageFiveTlsSecurityLessons: LessonSpec[] = [...knowledgeLessons, project];
