import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "零信任与云原生网络";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-zero-trust-beyondcorp-principles",
    stageId: "network-zero-trust",
    order: 1,
    eyebrowStage: eyebrow,
    title: "BeyondCorp 核心原则",
    concept: "零信任模型放弃“内网可信、外网不可信”的边界假设，改为 `never trust, always verify`：每次访问都要同时校验用户身份、设备状态与请求上下文，由策略引擎签发短期凭证，网络位置不再作为授权依据。",
    points: ["取消隐式内网信任", "每次请求都做身份+设备+上下文校验", "策略引擎发放短期凭证"],
    memoryHook: "无内外网，只有可信请求",
    fileName: "beyondcorp-flow.ts",
    code: `type AccessContext = {\n  user: { id: string; groups: string[] };\n  device: { id: string; osUpdated: boolean; managed: boolean };\n  request: { url: string; ip: string; ua: string };\n};\n\nfunction evaluate(ctx: AccessContext) {\n  if (!ctx.device.managed || !ctx.device.osUpdated) {\n    return { allow: false, reason: "device_untrusted" };\n  }\n  if (!ctx.user.groups.includes("finance")) {\n    return { allow: false, reason: "not_in_group" };\n  }\n  return { allow: true, ttlSeconds: 300 };\n}\n\nconst decision = evaluate({\n  user: { id: "u_88", groups: ["finance"] },\n  device: { id: "d_12", osUpdated: true, managed: true },\n  request: { url: "https://erp.corp/reports", ip: "203.0.113.9", ua: "Chrome" }\n});\nconsole.log(decision);`,
    prompt: "在 BeyondCorp 模型下，一个员工从公司内网访问 ERP，应该如何决定是否放行？",
    correct: "仍然评估用户身份、设备合规状态与请求上下文，网络位置不作为授权依据",
    wrong: "只要请求来自公司内网 IP 就直接放行，跳过设备与身份校验",
    output: "{ allow: true, ttlSeconds: 300 }",
    lanes: ["收集上下文", "策略引擎评估", "签发短期凭证"],
    laneValues: ["user+device+request", "policy=allow", "ttl=300s"],
    log: ["收集 user/device/request 上下文", "策略命中 finance 组 + 设备合规", "签发 5 分钟凭证"],
    summary: ["网络位置不再是信任依据", "身份+设备+上下文三要素缺一不可", "凭证短期化限制横向移动"],
    sourceTitle: "Google BeyondCorp",
    sourceUrl: "https://cloud.google.com/beyondcorp"
  }),
  createNetworkLesson({
    id: "network-zero-trust-iap-sase",
    stageId: "network-zero-trust",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Identity-aware Proxy 与 SASE",
    concept: "IAP 把应用暴露到公网背后，由代理统一做身份认证、设备检查与授权，再回源到内网应用。SASE 把 IAP、SWG、CASB、ZTNA 与 SD-WAN 合成云端安全服务栈，用户从任意位置接入都走同一策略面。",
    points: ["IAP = 应用前置身份网关", "SASE = 云化安全栈聚合", "策略面与数据面统一治理"],
    memoryHook: "IAP 守门，SASE 全景守边",
    fileName: "iap-proxy.ts",
    code: `import { NextRequest, NextResponse } from "next/server";\n\nexport async function middleware(req: NextRequest) {\n  const token = req.headers.get("x-goog-iap-jwt-assertion");\n  if (!token) return NextResponse.redirect("https://iap.example.com/login");\n\n  const claims = await verifyIapJwt(token, {\n    audience: "/projects/123/global/backendServices/erp",\n    issuer: "https://cloud.google.com/iap"\n  });\n  if (!claims.email_verified) return new NextResponse("forbidden", { status: 403 });\n\n  const res = NextResponse.next();\n  res.headers.set("x-user", claims.email);\n  return res;\n}\n\nexport const config = { matcher: ["/((?!_next|favicon.ico).*)"] };`,
    prompt: "为什么把应用放在 IAP 后面比放在传统 VPN 后面更符合零信任？",
    correct: "IAP 对每个请求都独立校验身份/设备/上下文，避免 VPN 一旦接通就获得网段级信任",
    wrong: "IAP 只是给 VPN 加了 HTTPS，本质与传统 VPN 一样按网段授权",
    output: "middleware: allow email=alice@corp",
    lanes: ["请求进入 IAP", "校验 JWT", "回源应用"],
    laneValues: ["/reports 请求", "iap-jwt=valid", "转发到内网服务"],
    log: ["请求到达 IAP", "校验 x-goog-iap-jwt-assertion", "回源到内网 ERP"],
    summary: ["IAP 让应用面向公网也能收敛访问", "SASE 把多种安全服务合并为一张策略面", "策略与用户位置解耦"],
    sourceTitle: "Google BeyondCorp",
    sourceUrl: "https://cloud.google.com/beyondcorp"
  }),
  createNetworkLesson({
    id: "network-zero-trust-mtls-spiffe",
    stageId: "network-zero-trust",
    order: 3,
    eyebrowStage: eyebrow,
    title: "mTLS 与 SPIFFE 身份",
    concept: "服务间通信不再靠 IP 或 hostname 信任，而是用短期 X.509 证书承载 SPIFFE ID（`spiffe://trust-domain/workload`）。SPIRE Agent 通过节点+workload attestation 自动签发并轮换证书，双向 TLS 完成身份校验。",
    points: ["SPIFFE ID = 工作负载身份 URI", "SPIRE 自动签发与轮换 X.509", "mTLS 双向校验替代网络位置"],
    memoryHook: "身份是 SPIFFE，通道是 mTLS",
    fileName: "spiffe-mtls.ts",
    code: `import { X509SvidClient } from "@spiffe/svid-x509";\nimport https from "node:https";\n\nconst client = await X509SvidClient.create({ socketPath: "/run/spire/agent.sock" });\nconst svid = await client.fetchX509Svid();\n\nconst agent = new https.Agent({\n  cert: svid.certChainPem,\n  key: svid.privateKeyPem,\n  ca: svid.trustBundlePem,\n  requestCert: true,\n  rejectUnauthorized: true\n});\n\nconst req = https.request(\n  { host: "billing.svc", port: 8443, path: "/charge", method: "POST", agent },\n  (res) => console.log("peer spiffe:", res.socket.getPeerCertificate().subject)\n);\nreq.end(JSON.stringify({ orderId: "10086" }));`,
    prompt: "微服务 A 调用微服务 B 时，最符合零信任的身份方案是什么？",
    correct: "由 SPIRE 签发短期 X.509 承载 SPIFFE ID，用 mTLS 双向校验对端身份",
    wrong: "在 Header 里带一个共享 API Key，A、B 都能识别就足够安全",
    output: "peer spiffe: spiffe://prod/ns/billing/sa/charger",
    lanes: ["获取 SVID", "建立 mTLS", "校验对端 SPIFFE ID"],
    laneValues: ["fetchX509Svid", "TLS 双向握手", "spiffe://prod/ns/billing/sa/charger"],
    log: ["从 SPIRE Agent 拉取 SVID", "与 billing.svc 完成 mTLS 握手", "对端身份 = billing/charger"],
    summary: ["身份用 SPIFFE URI 表达", "SPIRE 自动轮换避免长期密钥", "mTLS 让 IP/DNS 不再是信任依据"],
    sourceTitle: "SPIFFE Overview",
    sourceUrl: "https://spiffe.io/docs/latest/spiffe-about/overview/"
  }),
  createNetworkLesson({
    id: "network-zero-trust-networkpolicy-microsegmentation",
    stageId: "network-zero-trust",
    order: 4,
    eyebrowStage: eyebrow,
    title: "NetworkPolicy 微分段",
    concept: "K8s `NetworkPolicy` 是命名空间内基于 Pod 标签的 L3/L4 白名单。默认命名空间下 Pod 之间互通，一旦选中的 Pod 命中至少一条 policy，其余方向自动 deny，从而实现服务级 microsegmentation。",
    points: ["podSelector 命中即启用白名单", "ingress/egress 分别声明", "需 CNI 支持才生效（如 Calico/Cilium）"],
    memoryHook: "policy 未命中 = 全通，一命中 = 白名单",
    fileName: "billing-networkpolicy.yaml",
    code: `apiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: billing-allow-checkout\n  namespace: prod\nspec:\n  podSelector:\n    matchLabels:\n      app: billing\n  policyTypes:\n    - Ingress\n    - Egress\n  ingress:\n    - from:\n        - podSelector:\n            matchLabels:\n              app: checkout\n      ports:\n        - protocol: TCP\n          port: 8443\n  egress:\n    - to:\n        - podSelector:\n            matchLabels:\n              app: postgres\n      ports:\n        - protocol: TCP\n          port: 5432\n    - to:\n        - namespaceSelector:\n            matchLabels:\n              purpose: kube-system\n      ports:\n        - protocol: UDP\n          port: 53`,
    prompt: "只给 billing Pod 加了一条 ingress policy 允许 checkout 访问，其它命名空间来的流量会怎样？",
    correct: "会被拒绝，因为 Pod 被 policy 选中后未列出的入站方向默认 deny",
    wrong: "仍然全部放行，NetworkPolicy 只是叠加了额外允许规则",
    output: "checkout → billing:8443 allow；others → billing deny",
    lanes: ["policy 选中 Pod", "匹配 ingress 白名单", "其余流量 deny"],
    laneValues: ["podSelector=billing", "from=checkout", "default deny"],
    log: ["policy 生效 app=billing", "checkout 命中白名单 → allow", "其余来源 → deny"],
    summary: ["policy 命中即白名单模式", "ingress/egress 需分别声明", "生效依赖具备 policy 支持的 CNI"],
    sourceTitle: "Kubernetes NetworkPolicy",
    sourceUrl: "https://kubernetes.io/docs/concepts/services-networking/network-policies/"
  }),
  createNetworkLesson({
    id: "network-zero-trust-istio-authorization",
    stageId: "network-zero-trust",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Istio 授权策略",
    concept: "Istio `AuthorizationPolicy` 在 sidecar/ingress 层做 L7 授权。规则可以引用 mTLS 身份 (`source.principals`)、请求方法、路径、Header 等，`action: DENY` 优先于 `ALLOW`，同一 workload 上多条 policy 取并集。",
    points: ["基于 mTLS 身份而不是 IP", "DENY 优先于 ALLOW", "支持 method/path/header L7 条件"],
    memoryHook: "身份+方法+路径，DENY 先跑",
    fileName: "billing-authz.yaml",
    code: `apiVersion: security.istio.io/v1\nkind: AuthorizationPolicy\nmetadata:\n  name: billing-allow-checkout\n  namespace: prod\nspec:\n  selector:\n    matchLabels:\n      app: billing\n  action: ALLOW\n  rules:\n    - from:\n        - source:\n            principals:\n              - "cluster.local/ns/prod/sa/checkout"\n      to:\n        - operation:\n            methods: ["POST"]\n            paths: ["/charge", "/refund"]\n      when:\n        - key: request.headers[x-trace-id]\n          notValues: [""]\n---\napiVersion: security.istio.io/v1\nkind: AuthorizationPolicy\nmetadata:\n  name: billing-deny-legacy\n  namespace: prod\nspec:\n  selector:\n    matchLabels:\n      app: billing\n  action: DENY\n  rules:\n    - from:\n        - source:\n            notPrincipals: ["cluster.local/ns/prod/sa/checkout"]`,
    prompt: "同一个 workload 上同时命中一条 ALLOW 和一条 DENY 时，Istio 会怎么裁决？",
    correct: "DENY 优先，只要命中任一 DENY 规则请求就被拒绝",
    wrong: "按 policy 创建时间排序，先建的规则获胜",
    output: "checkout POST /charge → allow；其他 SA → deny",
    lanes: ["解析 mTLS 身份", "评估 DENY", "评估 ALLOW"],
    laneValues: ["principal=checkout", "无 DENY 命中", "命中 ALLOW"],
    log: ["mTLS 身份 = prod/checkout", "DENY 规则未命中", "ALLOW 规则命中 → 放行"],
    summary: ["身份来自 mTLS 而不是 IP", "DENY 永远优先", "L7 条件让授权更精细"],
    sourceTitle: "Istio AuthorizationPolicy",
    sourceUrl: "https://istio.io/latest/docs/reference/config/security/authorization-policy/"
  }),
  createNetworkLesson({
    id: "network-zero-trust-egress-dns-policy",
    stageId: "network-zero-trust",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Egress 与 DNS 策略",
    concept: "Egress 控制的核心是把出站请求收敛到可枚举的白名单域名。Cilium 等 CNI 支持基于 FQDN 的 DNS 感知策略：数据面拦截 DNS 响应，动态把解析出的 IP 加入允许集合，避免手工维护 IP 列表。",
    points: ["Egress 白名单以域名为主", "DNS 感知策略自动跟随解析", "拒绝未知域名可拦截外泄通道"],
    memoryHook: "出站按域名，DNS 顺带鉴权",
    fileName: "egress-fqdn.yaml",
    code: `apiVersion: cilium.io/v2\nkind: CiliumNetworkPolicy\nmetadata:\n  name: billing-egress\n  namespace: prod\nspec:\n  endpointSelector:\n    matchLabels:\n      app: billing\n  egress:\n    - toEndpoints:\n        - matchLabels:\n            "k8s:io.kubernetes.pod.namespace": kube-system\n            "k8s:k8s-app": kube-dns\n      toPorts:\n        - ports:\n            - port: "53"\n              protocol: UDP\n          rules:\n            dns:\n              - matchPattern: "*.stripe.com"\n              - matchName: "api.openai.com"\n    - toFQDNs:\n        - matchPattern: "*.stripe.com"\n        - matchName: "api.openai.com"\n      toPorts:\n        - ports:\n            - port: "443"\n              protocol: TCP`,
    prompt: "只允许 billing 出站访问 `*.stripe.com` 和 `api.openai.com`，最稳的实现是什么？",
    correct: "用 DNS 感知的 FQDN egress 策略，让数据面根据 DNS 响应动态放行 IP",
    wrong: "手工维护一份 Stripe/OpenAI 的 IP 白名单，定期人肉更新",
    output: "billing → api.stripe.com:443 allow；billing → evil.com:443 deny",
    lanes: ["截获 DNS 请求", "匹配 FQDN 白名单", "放行对应 IP"],
    laneValues: ["查询 api.stripe.com", "匹配 *.stripe.com", "TCP 443 allow"],
    log: ["DNS 查询 api.stripe.com", "命中 FQDN 白名单", "对解析出的 IP 放行 443"],
    summary: ["egress 白名单是防外泄的第一道门", "DNS 感知策略免除手工维护 IP", "未知域名默认拒绝"],
    sourceTitle: "Kubernetes NetworkPolicy",
    sourceUrl: "https://kubernetes.io/docs/concepts/services-networking/network-policies/"
  }),
  createNetworkLesson({
    id: "network-zero-trust-wireguard-vpn",
    stageId: "network-zero-trust",
    order: 7,
    eyebrowStage: eyebrow,
    title: "WireGuard 现代 VPN",
    concept: "WireGuard 用 Noise IKpsk2 握手 + ChaCha20-Poly1305 数据面，配置极简：每个 peer 用一对 Curve25519 密钥表示身份，通过 `AllowedIPs` 做 cryptokey routing，任何伪造源 IP 的报文因为密钥不匹配都会被静默丢弃。",
    points: ["Noise 协议 + ChaCha20-Poly1305", "peer 用公钥表示身份", "AllowedIPs 决定路由与鉴权"],
    memoryHook: "公钥即身份，AllowedIPs 即路由",
    fileName: "wg0.conf",
    code: `[Interface]\nPrivateKey = uJ8+3W4Xq6nO6d2qvJvB6yQoS3Y3v5o5uQvKq4nZ4X0=\nAddress = 10.8.0.2/24\nListenPort = 51820\n\n# 办公网出口：负责路由 10.20.0.0/16 内网段\n[Peer]\nPublicKey = mB3xW1KpDkC7Q0v9jSj2m3nQeR5W6yYd0uHjK3nX9nA=\nAllowedIPs = 10.20.0.0/16\nEndpoint = vpn.corp.example.com:51820\nPersistentKeepalive = 25\n\n# 单个协同工作站：只允许其源地址 10.8.0.9/32\n[Peer]\nPublicKey = pQ2v6yQe4gH0nR6qBz9x3kL5mYc8dJ7wS2vN4rXfKzc=\nAllowedIPs = 10.8.0.9/32`,
    prompt: "对端伪造源 IP 为 10.8.0.9 但用别的私钥发包，WireGuard 会怎么处理？",
    correct: "报文因公钥与 AllowedIPs 绑定关系不匹配被静默丢弃，日志级别很低",
    wrong: "只要源 IP 落在 AllowedIPs 内，就按对应 peer 解密并放行",
    output: "packet from 10.8.0.9 pubkey=xxx dropped: not in AllowedIPs mapping",
    lanes: ["接收 UDP 报文", "查 peer 密钥", "验 AllowedIPs 绑定"],
    laneValues: ["udp:51820", "pubkey=xxx", "AllowedIPs mismatch"],
    log: ["收到 UDP:51820", "尝试解密到 peer xxx", "AllowedIPs 不匹配 → 丢弃"],
    summary: ["WireGuard 用公钥而非用户名/密码", "AllowedIPs 同时定义路由与鉴权", "极简实现更容易审计"],
    sourceTitle: "WireGuard Protocol",
    sourceUrl: "https://www.wireguard.com/protocol/"
  }),
  createNetworkLesson({
    id: "network-zero-trust-cloud-perimeter",
    stageId: "network-zero-trust",
    order: 8,
    eyebrowStage: eyebrow,
    title: "云原生零信任边界",
    concept: "Cloudflare Access、Google BeyondCorp Enterprise 等 ZTNA 平台，把身份提供方（IdP）、设备状态（EDR/MDM）、访问策略与边缘 PoP 组合成云端网关：应用只从边缘暴露，用户走 IdP 登录后由边缘签发短期会话，再回源到内网。",
    points: ["IdP + 设备信号 + 策略三方决策", "应用只在边缘暴露不再直接上公网", "会话短期化 + 全量审计日志"],
    memoryHook: "边缘做门，IdP 发身份，设备表态",
    fileName: "cloudflare-access.ts",
    code: `import { verify } from "@tsndr/cloudflare-worker-jwt";\n\nexport default {\n  async fetch(req: Request, env: { AUD: string; TEAM: string }) {\n    const jwt = req.headers.get("cf-access-jwt-assertion");\n    if (!jwt) return new Response("no access token", { status: 401 });\n\n    const ok = await verify(jwt, await getPublicKey(env.TEAM), {\n      algorithm: "RS256",\n      audience: env.AUD,\n      issuer: \`https://\${env.TEAM}.cloudflareaccess.com\`\n    });\n    if (!ok) return new Response("invalid access token", { status: 403 });\n\n    const url = new URL(req.url);\n    url.hostname = "origin.internal";\n    return fetch(url.toString(), { headers: req.headers });\n  }\n};`,
    prompt: "把内部应用放在 Cloudflare Access 后面，比直接暴露 + IP 白名单强在哪里？",
    correct: "每次请求都由 IdP + 设备状态 + 策略共同决策，并留下全量审计日志",
    wrong: "只是多了一层 CDN 缓存，安全模型上和 IP 白名单等价",
    output: "GET /admin cf-access-jwt=valid → 200",
    lanes: ["用户到边缘", "IdP + 策略评估", "回源应用"],
    laneValues: ["/admin 请求", "cf-access-jwt=valid", "origin.internal 回源"],
    log: ["请求到达 Cloudflare 边缘", "校验 cf-access-jwt-assertion", "回源到内部 origin"],
    summary: ["ZTNA 让应用只从边缘暴露", "IdP+设备+策略是三方共识", "审计日志覆盖每一次访问"],
    sourceTitle: "Cloudflare One",
    sourceUrl: "https://developers.cloudflare.com/cloudflare-one/"
  })
];

const project = createNetworkStageProject({
  id: "network-zero-trust-project",
  stageId: "network-zero-trust",
  eyebrowStage: eyebrow,
  title: "K8s 微服务零信任访问闭环",
  brief: "为 `prod` 命名空间的 checkout → billing → postgres 链路搭建零信任闭环：前置 IAP 校验用户身份，服务间用 SPIFFE mTLS，K8s NetworkPolicy 做 L3/L4 微分段，Istio AuthorizationPolicy 做 L7 授权，egress 只允许 `*.stripe.com`，最后打通审计日志。",
  concept: "组合本阶段的 BeyondCorp、SPIFFE、NetworkPolicy、Istio AuthZ 与 Egress 策略，让每一跳都有独立身份与授权判定，任何一环失效都不会打通整条链路。",
  points: ["用户入口用 IAP/ZTNA 校验", "服务身份用 SPIFFE + mTLS", "L3/L4 微分段 + L7 授权 + 出站白名单叠加"],
  memoryHook: "身份+分段+授权+审计，四层同时在线",
  fileName: "zero-trust-stack.yaml",
  code: `# 1) L3/L4 微分段：billing 只允许 checkout 入站，出站只到 postgres 与 stripe\napiVersion: networking.k8s.io/v1\nkind: NetworkPolicy\nmetadata:\n  name: billing-l4\n  namespace: prod\nspec:\n  podSelector: { matchLabels: { app: billing } }\n  policyTypes: [Ingress, Egress]\n  ingress:\n    - from: [{ podSelector: { matchLabels: { app: checkout } } }]\n      ports: [{ protocol: TCP, port: 8443 }]\n  egress:\n    - to: [{ podSelector: { matchLabels: { app: postgres } } }]\n      ports: [{ protocol: TCP, port: 5432 }]\n    - to: [{ namespaceSelector: { matchLabels: { purpose: kube-system } } }]\n      ports: [{ protocol: UDP, port: 53 }]\n---\n# 2) L7 授权：只有 checkout 的 SPIFFE 身份可以调 POST /charge\napiVersion: security.istio.io/v1\nkind: AuthorizationPolicy\nmetadata:\n  name: billing-l7\n  namespace: prod\nspec:\n  selector: { matchLabels: { app: billing } }\n  action: ALLOW\n  rules:\n    - from:\n        - source:\n            principals: ["cluster.local/ns/prod/sa/checkout"]\n      to:\n        - operation:\n            methods: ["POST"]\n            paths: ["/charge"]\n      when:\n        - key: request.headers[traceparent]\n          notValues: [""]\n---\n# 3) FQDN egress：billing 出站只允许 stripe，禁止访问其他外网\napiVersion: cilium.io/v2\nkind: CiliumNetworkPolicy\nmetadata:\n  name: billing-egress-fqdn\n  namespace: prod\nspec:\n  endpointSelector: { matchLabels: { app: billing } }\n  egress:\n    - toEndpoints:\n        - matchLabels:\n            "k8s:io.kubernetes.pod.namespace": kube-system\n            "k8s:k8s-app": kube-dns\n      toPorts:\n        - ports: [{ port: "53", protocol: UDP }]\n          rules:\n            dns:\n              - matchPattern: "*.stripe.com"\n    - toFQDNs:\n        - matchPattern: "*.stripe.com"\n      toPorts:\n        - ports: [{ port: "443", protocol: TCP }]\n---\n# 4) 入口：Cloudflare Access / IAP 前置校验用户身份，再回源到 checkout Service\napiVersion: networking.istio.io/v1\nkind: Gateway\nmetadata:\n  name: checkout-edge\n  namespace: prod\nspec:\n  selector: { istio: ingressgateway }\n  servers:\n    - port: { number: 443, name: https, protocol: HTTPS }\n      tls: { mode: SIMPLE, credentialName: checkout-tls }\n      hosts: ["shop.corp.example.com"]`,
  prompt: "零信任闭环上线后，最应该保留哪一项作为“最后一道防线”？",
  correct: "全量审计日志：入口 IAP、mTLS 握手、AuthorizationPolicy 决策、egress 命中都要落日志并串到 traceparent",
  wrong: "只保留入口 IAP 登录日志，内部服务间调用日志按需再补",
  correctFeedback: "正确：零信任的价值不仅是拦截，还要在事后能证明每一次访问的身份与授权路径。",
  wrongFeedback: "错误：一旦事故发生，只有入口日志无法回答“服务间是谁调了谁、被哪条策略放行”。",
  additionalWrong: {
    label: "为了性能，关闭 mTLS 只保留 NetworkPolicy 就够了",
    feedback: "错误：只有 L3/L4 微分段无法防伪造身份，mTLS 才能让每一跳都能被密码学校验。"
  },
  lanes: ["入口 IAP 校验", "服务间 mTLS + 授权", "egress + 审计"],
  laneValues: ["cf-access-jwt=valid", "checkout→billing allow", "*.stripe.com allow + 审计"],
  log: ["用户登录经 Cloudflare Access 通过", "checkout 用 SPIFFE mTLS 调 billing 命中 ALLOW", "billing 出站命中 *.stripe.com 白名单并写审计"],
  summary: ["入口 + 服务间 + 出站三层策略叠加", "身份、分段、授权、审计一个都不能少", "审计日志是零信任的最后一道防线"],
  sourceTitle: "Google BeyondCorp",
  sourceUrl: "https://cloud.google.com/beyondcorp"
});

export const networkStageTenZeroTrustLessons: LessonSpec[] = [...knowledgeLessons, project];
