import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "CDN 与边缘计算";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-cdn-edge-pop-distribution",
    stageId: "network-cdn-edge",
    order: 1,
    eyebrowStage: eyebrow,
    title: "CDN 分发原理与 POP 节点",
    concept: "CDN 通过全球 POP（Point of Presence）节点缓存源站内容，DNS 或 Anycast 把用户请求路由到最近节点，命中缓存直接返回，未命中回源。POP 越靠近用户，RTT 越低、TTFB 越短。",
    points: ["POP 节点在网络边缘缓存内容", "DNS/Anycast 就近调度用户", "命中缓存不再回源，回源走 fill"],
    memoryHook: "POP 越近越快，命中就不回源",
    fileName: "cdn-pop.ts",
    code: `// 观察 CDN 命中：Cloudflare 会返回 cf-cache-status 与 cf-ray（含 POP 三字母代码）\nconst res = await fetch(\"https://cdn.example.com/hero.jpg\");\n\nconsole.log(\"status:\", res.status);\nconsole.log(\"cf-cache-status:\", res.headers.get(\"cf-cache-status\")); // HIT / MISS / EXPIRED\nconsole.log(\"cf-ray:\", res.headers.get(\"cf-ray\"));                   // 例：8f2a1b3c4d5e6f7g-SJC\nconsole.log(\"age:\", res.headers.get(\"age\"));                          // 已在边缘缓存的秒数\nconsole.log(\"server-timing:\", res.headers.get(\"server-timing\"));      // 含 cdn-cache;desc=HIT`,
    prompt: "CDN 命中率 90% 意味着什么？",
    correct: "90% 的请求被 POP 节点直接返回，只有 10% 需要回源",
    wrong: "90% 的用户能访问到 CDN，10% 被墙",
    output: "cf-cache-status: HIT | cf-ray: 8f2a1b3c4d5e6f7g-SJC | age: 3421",
    lanes: ["用户请求", "POP 命中", "返回响应"],
    laneValues: ["GET /hero.jpg", "cf-cache-status=HIT", "TTFB 18ms"],
    log: ["DNS 解析到最近 POP (SJC)", "cf-cache-status=HIT age=3421", "边缘节点直接返回 200"],
    summary: ["POP 是边缘缓存的物理载体", "命中率决定回源压力与用户体验", "cf-cache-status/age 是最直接的命中证据"],
    sourceTitle: "Cloudflare Cache 文档",
    sourceUrl: "https://developers.cloudflare.com/cache/"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-cache-key-design",
    stageId: "network-cdn-edge",
    order: 2,
    eyebrowStage: eyebrow,
    title: "缓存键设计：Vary 与查询归一化",
    concept: "CDN 缓存键默认为 method+host+path+query，`Vary` 头会把响应按指定请求头再分桶（如 `Accept-Encoding`、`Accept-Language`）。查询串顺序、无关追踪参数（utm_*）会撑爆缓存，必须归一化。",
    points: ["Vary 决定按哪些请求头分桶", "utm_* 之类追踪参数应剔除", "query 需按字典序排序归一化"],
    memoryHook: "键要归一化，Vary 要克制",
    fileName: "cache-key.ts",
    code: `// Cloudflare Cache Rules / Workers 里对缓存键做归一化\nexport function normalizeCacheKey(url: URL): URL {\n  const drop = [\"utm_source\", \"utm_medium\", \"utm_campaign\", \"gclid\", \"fbclid\"];\n  drop.forEach((k) => url.searchParams.delete(k));\n\n  // 按字典序排序，保证 ?a=1&b=2 与 ?b=2&a=1 命中同一键\n  const sorted = new URLSearchParams([...url.searchParams].sort(([a], [b]) => a.localeCompare(b)));\n  url.search = sorted.toString();\n  return url;\n}\n\n// 源站响应：只对真正影响 payload 的头做 Vary\n// Vary: Accept-Encoding                 ✅ 影响 gzip/br 版本\n// Vary: User-Agent                      ❌ 基数几百万，缓存瞬间碎片化\nconsole.log(normalizeCacheKey(new URL(\"https://x.com/p?b=2&utm_source=x&a=1\")).toString());`,
    prompt: "为什么不建议在 Vary 中加入 `User-Agent`？",
    correct: "User-Agent 基数极大，会把同一 URL 切成成千上万份缓存副本，命中率暴跌",
    wrong: "User-Agent 有隐私风险，浏览器会拒绝缓存包含它的响应",
    output: "https://x.com/p?a=1&b=2",
    lanes: ["接收请求", "归一化键", "查缓存桶"],
    laneValues: ["原始 URL", "去 utm/排序", "命中同一桶"],
    log: ["原始 query=?b=2&utm_source=x&a=1", "归一化为 ?a=1&b=2", "命中同一缓存键"],
    summary: ["缓存键决定命中率", "Vary 越窄命中越高", "追踪参数必须在边缘剔除"],
    sourceTitle: "Cloudflare Cache Keys",
    sourceUrl: "https://developers.cloudflare.com/cache/how-to/cache-keys/"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-cache-control-swr",
    stageId: "network-cdn-edge",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Cache-Control 与 stale-while-revalidate",
    concept: "`Cache-Control: s-maxage=60, stale-while-revalidate=300` 让共享缓存在 60s 内视为新鲜；60~360s 之间仍能返回旧内容并异步回源刷新（RFC 5861）。用户永远看不到回源延迟。",
    points: ["s-maxage 只作用于共享缓存", "SWR 允许后台异步回源", "stale-if-error 兜底源站故障"],
    memoryHook: "先返回旧的，后台悄悄刷新",
    fileName: "swr.ts",
    code: `// 源站响应头示例\nreturn new Response(json, {\n  headers: {\n    \"content-type\": \"application/json\",\n    // 浏览器 30s、边缘 60s、SWR 5min、错误兜底 1h\n    \"cache-control\": \"public, max-age=30, s-maxage=60, stale-while-revalidate=300, stale-if-error=3600\"\n  }\n});\n\n// 观察响应生命周期\n// t=0s   : MISS，回源，写入缓存\n// t=45s  : HIT，age=45 < 60\n// t=90s  : STALE，命中旧内容立即返回，后台异步 revalidate\n// t=91s  : HIT，新副本已写入`,
    prompt: "开启 `stale-while-revalidate=300` 后，用户在 s-maxage 过期后的下一次请求会经历什么？",
    correct: "立即拿到旧副本，边缘后台异步回源，下次请求就是新副本",
    wrong: "必须等回源完成才能拿到响应，用户感知一次慢请求",
    output: "cf-cache-status: STALE | age: 90 | 后台 revalidate 已完成",
    lanes: ["首次回源", "过期后请求", "后台刷新"],
    laneValues: ["MISS→写入", "STALE 立即返回", "revalidate 完成"],
    log: ["t=0 MISS，回源写入", "t=90 STALE，返回旧副本", "后台 revalidate，写入新副本"],
    summary: ["SWR 把回源延迟从用户路径挪走", "RFC 5861 定义 SWR/SIE 语义", "s-maxage 才是 CDN 真正听的字段"],
    sourceTitle: "RFC 5861: HTTP Cache-Control Extensions",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc5861"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-shield-origin-cloaking",
    stageId: "network-cdn-edge",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Shield 与 Origin Cloaking",
    concept: "多 POP 独立回源会把冷启动流量放大 N 倍。Shield（Cloudflare Tiered Cache / Fastly Origin Shield）在中间加一层区域缓存节点，所有边缘先回 shield 再回源，回源请求归一，源站压力骤降。",
    points: ["无 shield 时每个 POP 独立回源", "Shield 把回源收敛到区域节点", "源站只暴露给 shield 网段"],
    memoryHook: "边缘先问 shield，再打源站",
    fileName: "shield.ts",
    code: `// Cloudflare Tiered Cache 开启示例（wrangler.toml / dashboard）\n// [cache]\n// tiered_cache = { enabled = true, topology = \"smart\" }\n\n// 源站只允许 Cloudflare Shield 网段回源\n// nginx.conf:\n//   allow 173.245.48.0/20;   # Cloudflare 公示的边缘/Shield 网段\n//   allow 103.21.244.0/22;\n//   deny  all;\n\n// 观察回源请求头：命中 shield 的回源会带 cf-visitor / cf-connecting-ip\nconsole.log(\"回源来源 IP 集中在 Shield 节点，源站 QPS 从 800 降到 60\");`,
    prompt: "启用 Origin Shield 前源站 QPS 800，启用后降到 60，最合理的解释是？",
    correct: "多个 POP 的回源被收敛到 Shield 节点合并，源站只承担 miss 后的单份回源",
    wrong: "Shield 直接把边缘缓存复制到源站，源站不再需要处理请求",
    output: "源站 QPS: 800 → 60，回源来源集中于 Shield 段",
    lanes: ["边缘 miss", "Shield 汇聚", "源站单份回源"],
    laneValues: ["3 个 POP miss", "Shield 合并", "源站只处理 1 次"],
    log: ["3 个 POP 同时 miss", "Shield 合并成 1 次回源", "源站 QPS 从 800 降到 60"],
    summary: ["无 Shield 会放大回源", "Shield 是回源合并层", "源站白名单只放 Shield 网段"],
    sourceTitle: "Cloudflare Tiered Cache",
    sourceUrl: "https://developers.cloudflare.com/cache/how-to/tiered-cache/"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-edge-workers",
    stageId: "network-cdn-edge",
    order: 5,
    eyebrowStage: eyebrow,
    title: "边缘计算：Cloudflare Workers / Vercel Edge",
    concept: "边缘计算把代码运行在离用户最近的 POP 节点，冷启动毫秒级、请求不必回原区域。适合鉴权、A/B、灰度、SSR、图片改写等场景；限制在 CPU 时间与内存，禁止长连接与大依赖。",
    points: ["运行时在 V8 isolate，冷启动毫秒级", "全球 POP 就近执行，无区域延迟", "CPU/内存受限，不适合长任务"],
    memoryHook: "边缘 = V8 Isolate + 就近执行",
    fileName: "worker.ts",
    code: `// Cloudflare Worker：按国家做 A/B 灰度并注入响应头\nexport default {\n  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {\n    const country = (request as any).cf?.country ?? \"US\";\n    const bucket = country === \"CN\" ? \"cn\" : \"row\";\n\n    const origin = new URL(request.url);\n    origin.hostname = bucket === \"cn\" ? \"cn.origin.example.com\" : \"origin.example.com\";\n\n    const res = await fetch(origin.toString(), request);\n    const headers = new Headers(res.headers);\n    headers.set(\"x-edge-bucket\", bucket);\n    headers.set(\"x-edge-pop\", request.headers.get(\"cf-ray\")?.split(\"-\").pop() ?? \"\");\n    return new Response(res.body, { status: res.status, headers });\n  }\n};`,
    prompt: "为什么 Cloudflare Workers 采用 V8 isolate 而不是容器？",
    correct: "isolate 冷启动毫秒级、内存开销低，允许在同机上密集多租户运行",
    wrong: "isolate 提供了完整的 Linux 内核能力，容器无法胜任",
    output: "x-edge-bucket: cn | x-edge-pop: HKG",
    lanes: ["请求到 Worker", "读取地理", "改写并回源"],
    laneValues: ["cf.country=CN", "bucket=cn", "回源 cn.origin"],
    log: ["Worker 冷启动 <5ms", "读取 cf.country=CN", "回源到 cn.origin，注入 x-edge-bucket"],
    summary: ["边缘代码 = 全球就近执行", "V8 isolate 决定了受限的运行模型", "适合改写/路由/鉴权，不适合长任务"],
    sourceTitle: "Cloudflare Workers 文档",
    sourceUrl: "https://developers.cloudflare.com/workers/"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-asset-optimization",
    stageId: "network-cdn-edge",
    order: 6,
    eyebrowStage: eyebrow,
    title: "图片与静态资源优化：AVIF/WebP 与 Brotli",
    concept: "现代浏览器普遍支持 AVIF/WebP 与 Brotli：AVIF 比 JPEG 省 30~50% 体积；Brotli 比 gzip 再省 15~25%。用 `Accept` 内容协商挑格式、用 `Accept-Encoding` 协商压缩，配合 CDN 边缘转码。",
    points: ["按 Accept 返回 AVIF/WebP/JPEG", "Brotli 压缩比优于 gzip", "边缘转码避免源站算力开销"],
    memoryHook: "看 Accept 挑图，看 AE 挑压缩",
    fileName: "asset-negotiation.ts",
    code: `// 边缘 Worker：按 Accept 头返回不同图片格式\nfunction pickImage(accept: string): string {\n  if (accept.includes(\"image/avif\")) return \"/hero.avif\";\n  if (accept.includes(\"image/webp\")) return \"/hero.webp\";\n  return \"/hero.jpg\";\n}\n\nexport default {\n  async fetch(req: Request) {\n    const path = pickImage(req.headers.get(\"accept\") ?? \"\");\n    const res = await fetch(new URL(path, \"https://origin.example.com\"), req);\n    const headers = new Headers(res.headers);\n    headers.set(\"vary\", \"Accept, Accept-Encoding\"); // 声明分桶维度\n    headers.set(\"cache-control\", \"public, max-age=31536000, immutable\");\n    return new Response(res.body, { status: res.status, headers });\n  }\n};`,
    prompt: "同一张封面图既要发 AVIF 也要发 JPEG，缓存层必须做什么才能不串桶？",
    correct: "在响应中声明 `Vary: Accept`，让 CDN 按 Accept 分桶缓存",
    wrong: "把 AVIF 和 JPEG 塞到同一 URL 让浏览器自己选择格式",
    output: "GET /hero → AVIF 128KB (Chrome) / JPEG 260KB (Safari 旧版)",
    lanes: ["解析 Accept", "挑选格式", "写 Vary 分桶"],
    laneValues: ["image/avif,webp", "hero.avif", "Vary: Accept"],
    log: ["Chrome Accept 含 avif", "命中 hero.avif 128KB", "响应 Vary: Accept, Accept-Encoding"],
    summary: ["内容协商靠 Accept / Accept-Encoding", "Vary 必须覆盖协商维度", "Brotli+AVIF 是现代前端带宽优化默认"],
    sourceTitle: "web.dev: 面向现代浏览器提供现代代码",
    sourceUrl: "https://web.dev/articles/serve-modern-code-to-modern-browsers"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-cache-purge",
    stageId: "network-cdn-edge",
    order: 7,
    eyebrowStage: eyebrow,
    title: "缓存刷新：URL purge 与 Tag purge",
    concept: "内容更新后需要主动失效边缘缓存。URL purge 精准但难以批量；Tag purge 在响应打上 `Cache-Tag: product-42,category-shoes`，可一键失效整个标签集合，是电商/CMS 的标配。",
    points: ["URL purge 精准但难批量", "Tag purge 按标签批量失效", "Purge 是异步、跨 POP 传播"],
    memoryHook: "小改用 URL，大改用 Tag",
    fileName: "purge.ts",
    code: `// 源站响应打 Cache-Tag（Cloudflare Enterprise / Fastly Surrogate-Key）\nfunction productResponse(product: { id: number; category: string }, body: string) {\n  return new Response(body, {\n    headers: {\n      \"content-type\": \"application/json\",\n      \"cache-control\": \"public, s-maxage=300, stale-while-revalidate=600\",\n      \"cache-tag\": \`product-\${product.id},category-\${product.category},all-products\`\n    }\n  });\n}\n\n// 后台任务：商品 42 改价后按 tag 刷新\nawait fetch(\"https://api.cloudflare.com/client/v4/zones/{zone}/purge_cache\", {\n  method: \"POST\",\n  headers: { authorization: \`Bearer \${env.CF_TOKEN}\`, \"content-type\": \"application/json\" },\n  body: JSON.stringify({ tags: [\"product-42\"] })\n});`,
    prompt: "电商全站换季，10 万个商品页面需要失效，最合适的做法是？",
    correct: "在响应上打 category/all-products 之类 Cache-Tag，用 Tag purge 一次失效",
    wrong: "遍历 10 万条 URL 逐个调用 URL purge 接口",
    output: "purge tags=[product-42] → success, propagated to 320 POPs in 2s",
    lanes: ["写入 Cache-Tag", "触发 Tag purge", "全网失效"],
    laneValues: ["product-42, category-shoes", "purge tag=product-42", "320 POP 已生效"],
    log: ["响应带 cache-tag", "调用 Tag purge", "2s 内 320 POP 生效"],
    summary: ["URL purge 精准但不适合规模", "Tag purge 是批量失效的答案", "Purge 需要监控传播延迟"],
    sourceTitle: "Cloudflare Cache Purge",
    sourceUrl: "https://developers.cloudflare.com/cache/how-to/purge-cache/"
  }),
  createNetworkLesson({
    id: "network-cdn-edge-edge-auth-waf",
    stageId: "network-cdn-edge",
    order: 8,
    eyebrowStage: eyebrow,
    title: "边缘鉴权与 WAF",
    concept: "把鉴权、限流、注入检测下沉到 CDN 边缘，恶意流量在最外层被拒，源站只收到干净请求。JWT/HMAC 校验、Bot Score、SQLi/XSS 规则、Rate Limit 都在边缘完成，延迟只增加几毫秒。",
    points: ["JWT/HMAC 在边缘校验", "WAF 拦截 OWASP Top10", "Rate Limit 在边缘统计"],
    memoryHook: "脏流量止于边缘，源站只见干净请求",
    fileName: "edge-auth.ts",
    code: `// Cloudflare Worker：边缘 JWT 校验 + 简易速率限制\nimport { jwtVerify } from \"jose\";\n\nexport default {\n  async fetch(req: Request, env: { JWT_SECRET: string; RL: KVNamespace }) {\n    const token = req.headers.get(\"authorization\")?.replace(\"Bearer \", \"\");\n    if (!token) return new Response(\"unauthorized\", { status: 401 });\n\n    try {\n      const { payload } = await jwtVerify(token, new TextEncoder().encode(env.JWT_SECRET));\n      const key = \`rl:\${payload.sub}\`;\n      const count = Number((await env.RL.get(key)) ?? 0) + 1;\n      if (count > 60) return new Response(\"rate limited\", { status: 429 });\n      await env.RL.put(key, String(count), { expirationTtl: 60 });\n    } catch {\n      return new Response(\"invalid token\", { status: 401 });\n    }\n\n    return fetch(req); // 干净流量放行到源站\n  }\n};`,
    prompt: "把 JWT 校验从源站挪到边缘 Worker 的核心收益是？",
    correct: "非法请求在最外层被拒，源站 QPS 与带宽都不再被消耗",
    wrong: "JWT 校验放到边缘更安全，源站不再需要 HTTPS",
    output: "invalid token → 401 at edge, origin never sees the request",
    lanes: ["边缘校验", "限流计数", "干净流量回源"],
    laneValues: ["JWT verify", "count 45/60", "fetch origin"],
    log: ["边缘 JWT 校验通过", "1 分钟内 45/60 次", "干净流量到达源站"],
    summary: ["边缘鉴权+WAF 是纵深防御的第一层", "Rate Limit 在边缘更公平", "源站只处理干净流量"],
    sourceTitle: "Cloudflare Workers 文档",
    sourceUrl: "https://developers.cloudflare.com/workers/"
  })
];

const project = createNetworkStageProject({
  id: "network-cdn-edge-project",
  stageId: "network-cdn-edge",
  eyebrowStage: eyebrow,
  title: "带 SWR + Tag Purge 的多层缓存",
  brief: "为一个电商商品接口搭建：源站 → Origin Shield → 全球 POP 三层缓存；响应携带 `Cache-Control: s-maxage + stale-while-revalidate` 与 `Cache-Tag`；后台改动商品后按 tag 精准失效。",
  concept: "把本阶段知识点串起来：合理的缓存键归一化、SWR 使用户永不等待回源、Shield 汇聚回源、Tag purge 支撑高频更新、边缘 Worker 注入鉴权/A/B。",
  points: ["s-maxage + SWR 让用户不等回源", "Cache-Tag 支撑批量精准失效", "Shield 汇聚回源保护源站"],
  memoryHook: "SWR 抗延迟，Tag 抗批改，Shield 抗回源",
  fileName: "edge-cache-service.ts",
  code: `// 1) 边缘 Worker：归一化缓存键、注入 Cache-Tag、执行 SWR\nimport { normalizeCacheKey } from \"./cache-key\";\n\nexport default {\n  async fetch(req: Request, env: { CF_TOKEN: string; ZONE: string }, ctx: ExecutionContext) {\n    const url = normalizeCacheKey(new URL(req.url));\n    const cacheReq = new Request(url.toString(), req);\n    const cache = caches.default;\n\n    let res = await cache.match(cacheReq);\n    if (res) {\n      const age = Number(res.headers.get(\"age\") ?? 0);\n      if (age > 60) {\n        // 后台 revalidate（SWR）\n        ctx.waitUntil(revalidate(cacheReq, cache));\n      }\n      return withHeader(res, \"x-edge-cache\", \"HIT-SWR\");\n    }\n\n    res = await fetch(cacheReq); // 首次回源（会经 Shield / Tiered Cache）\n    const cloned = new Response(res.body, res);\n    cloned.headers.set(\"cache-control\", \"public, s-maxage=60, stale-while-revalidate=300\");\n    cloned.headers.set(\"cache-tag\", extractTags(url));\n    ctx.waitUntil(cache.put(cacheReq, cloned.clone()));\n    return withHeader(cloned, \"x-edge-cache\", \"MISS\");\n  }\n};\n\nasync function revalidate(req: Request, cache: Cache) {\n  const fresh = await fetch(req, { cf: { cacheEverything: true } });\n  await cache.put(req, fresh);\n}\n\nfunction extractTags(url: URL): string {\n  const m = url.pathname.match(/\\/api\\/product\\/(\\d+)/);\n  return m ? \`product-\${m[1]},all-products\` : \"all-products\";\n}\n\nfunction withHeader(res: Response, k: string, v: string) {\n  const h = new Headers(res.headers);\n  h.set(k, v);\n  return new Response(res.body, { status: res.status, headers: h });\n}\n\n// 2) 后台服务：商品更新后按 tag 精准失效\nexport async function purgeProduct(productId: number, env: { CF_TOKEN: string; ZONE: string }) {\n  const r = await fetch(\`https://api.cloudflare.com/client/v4/zones/\${env.ZONE}/purge_cache\`, {\n    method: \"POST\",\n    headers: { authorization: \`Bearer \${env.CF_TOKEN}\`, \"content-type\": \"application/json\" },\n    body: JSON.stringify({ tags: [\`product-\${productId}\`] })\n  });\n  if (!r.ok) throw new Error(\`purge failed: \${r.status}\`);\n}`,
  prompt: "多层缓存架构的验收标准里，为什么“P95 TTFB 不受回源延迟影响”比“命中率”更关键？",
  correct: "SWR 保证过期后仍立即返回旧副本，回源在后台，用户 P95 不再被回源尾延迟拖累",
  wrong: "命中率能自动保证 P95，只要命中率高就不用关心回源延迟",
  correctFeedback: "正确：SWR 让 P95 与回源解耦，源站慢也不会传导到用户，这是边缘架构的核心价值。",
  wrongFeedback: "错误：命中率再高，miss 一次就会打到源站；只有 SWR 才能把回源延迟隐藏在用户路径之外。",
  additionalWrong: {
    label: "只要开启 s-maxage=60，就不需要 Cache-Tag，Purge 直接改 URL 即可",
    feedback: "错误：批量更新（换季、下架）必须 Tag purge，靠 URL purge 无法覆盖 10 万级页面。"
  },
  lanes: ["边缘请求", "缓存决策", "Purge 传播"],
  laneValues: ["归一化 key", "HIT-SWR/异步 revalidate", "tag purge 生效"],
  log: ["请求命中缓存 age=90", "返回旧副本，后台 revalidate", "改价触发 tag purge，320 POP 生效"],
  summary: ["SWR 让用户永不等待回源", "Cache-Tag 支撑规模化失效", "Shield + 边缘 Worker 构成分层防线"],
  sourceTitle: "Vercel Edge Network Caching",
  sourceUrl: "https://vercel.com/docs/edge-network/caching"
});

export const networkStageSixCdnEdgeLessons: LessonSpec[] = [...knowledgeLessons, project];
