import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "网络可观测与抓包";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-observability-har-timeline",
    stageId: "network-observability",
    order: 1,
    eyebrowStage: eyebrow,
    title: "HAR 格式与浏览器时间轴解读",
    concept: "HAR 1.2 用 JSON 结构记录浏览器的每一次请求：`entries[].timings` 拆出 blocked/dns/connect/ssl/send/wait/receive，各段耗时相加加上 -1 段就是端到端时长。用它可以在没有服务器的情况下复现前端网络瓶颈。",
    points: ["timings 各段之和等于总耗时", "-1 表示该段不适用", "startedDateTime 决定并发瀑布"],
    memoryHook: "HAR = 请求快照 + 时间片",
    fileName: "har-analyze.ts",
    code: `import { readFileSync } from "node:fs";\n\ntype HarTimings = { blocked: number; dns: number; connect: number; ssl: number; send: number; wait: number; receive: number };\ntype HarEntry = { request: { url: string }; time: number; timings: HarTimings };\ntype Har = { log: { entries: HarEntry[] } };\n\nconst har = JSON.parse(readFileSync("home.har", "utf8")) as Har;\nconst slow = har.log.entries\n  .map((e) => ({ url: e.request.url, total: e.time, wait: e.timings.wait }))\n  .filter((e) => e.total > 500)\n  .sort((a, b) => b.total - a.total)\n  .slice(0, 5);\nconsole.log(\`Top slow requests: \${slow.length}\`);\nfor (const s of slow) {\n  console.log(\`\${s.total.toFixed(0)}ms wait=\${s.wait.toFixed(0)}ms \${s.url}\`);\n}`,
    prompt: "HAR entry 里 timings.wait 主要代表什么？",
    correct: "从请求头发送完成到收到首字节（TTFB），主要反映后端处理耗时",
    wrong: "整个 TCP 连接建立所花的时间，不包含服务端处理",
    output: "Top slow requests: 3\n842ms wait=612ms https://api.example.com/feed",
    lanes: ["读取 HAR", "拆解 timings", "输出慢请求"],
    laneValues: ["entries 加载", "wait/receive 拆分", "Top-5 打印"],
    log: ["加载 home.har", "计算每条 total/wait", "输出 Top-5 慢请求"],
    summary: ["HAR 时间轴段位可完整还原请求", "wait 高多为后端瓶颈", "receive 高多为响应体过大"],
    sourceTitle: "HAR 1.2 Spec",
    sourceUrl: "http://www.softwareishard.com/blog/har-12-spec/"
  }),
  createNetworkLesson({
    id: "network-observability-tcpdump-wireshark",
    stageId: "network-observability",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Wireshark / tcpdump 抓包基础",
    concept: "`tcpdump` 用 BPF 过滤器在服务端抓包，`-w file.pcap` 保存后交给 Wireshark 图形化分析。抓包时限定 host+port，避免抓到无关流量把磁盘打爆。Wireshark 用 Follow → TCP Stream 快速还原对话。",
    points: ["tcpdump -w 保存 pcap", "BPF 过滤 host/port 减少体积", "Wireshark Follow TCP Stream 还原会话"],
    memoryHook: "先过滤再落盘，别抓全网",
    fileName: "capture.ts",
    code: `import { spawn } from "node:child_process";\n\nfunction capture(host: string, port: number, outfile: string, seconds: number) {\n  const filter = \`host \${host} and port \${port}\`;\n  const proc = spawn(\"tcpdump\", [\"-i\", \"any\", \"-s\", \"0\", \"-w\", outfile, filter], {\n    stdio: [\"ignore\", \"inherit\", \"inherit\"]\n  });\n  setTimeout(() => proc.kill(\"SIGINT\"), seconds * 1000);\n  proc.on(\"exit\", (code) => {\n    console.log(\`tcpdump exited with \${code}, pcap=\${outfile}\`);\n  });\n}\n\ncapture(\"api.example.com\", 443, \"api.pcap\", 30);`,
    prompt: "在生产机上 tcpdump 长时间抓包最需要注意什么？",
    correct: "用 BPF 过滤器限定 host/port，避免落盘过多流量把磁盘写满",
    wrong: "抓的越全越好，直接 tcpdump -i any 全量落盘方便后续分析",
    output: "tcpdump exited with 0, pcap=api.pcap",
    lanes: ["构造过滤器", "启动 tcpdump", "定时结束"],
    laneValues: ["host+port", "spawn tcpdump", "SIGINT kill"],
    log: ["过滤 host+port", "tcpdump 开始写 pcap", "30s 后退出"],
    summary: ["tcpdump 是命令行抓包首选", "Wireshark 分析 pcap 更直观", "抓包必先过滤减少噪声"],
    sourceTitle: "Wireshark 用户指南",
    sourceUrl: "https://www.wireshark.org/docs/wsug_html_chunked/"
  }),
  createNetworkLesson({
    id: "network-observability-server-timing",
    stageId: "network-observability",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Server-Timing header 与后端耗时上报",
    concept: "W3C `Server-Timing` 头把后端各阶段耗时透出给浏览器：`Server-Timing: db;dur=42.3, cache;dur=1.2, app;dur=8.5`。前端 PerformanceResourceTiming.serverTiming 直接可读，让 RUM 数据穿透浏览器到服务端。",
    points: ["header 格式为 name;dur=ms, ...", "字段名/单位由服务方约定", "浏览器只在同源或 Timing-Allow-Origin 下暴露"],
    memoryHook: "后端耗时抬头就报，不用另开接口",
    fileName: "server-timing.ts",
    code: `import { createServer } from \"node:http\";\n\ncreateServer(async (req, res) => {\n  const t0 = performance.now();\n  const rows = await queryDb();\n  const t1 = performance.now();\n  const html = renderPage(rows);\n  const t2 = performance.now();\n  res.setHeader(\n    \"Server-Timing\",\n    \`db;dur=\${(t1 - t0).toFixed(1)}, render;dur=\${(t2 - t1).toFixed(1)}, total;dur=\${(t2 - t0).toFixed(1)}\`\n  );\n  res.setHeader(\"Timing-Allow-Origin\", \"*\");\n  res.end(html);\n}).listen(3000);\n\nasync function queryDb() { return [{ id: 1 }]; }\nfunction renderPage(rows: unknown[]) { return \`<html>rows=\${(rows as any[]).length}</html>\`; }`,
    prompt: "跨域场景下浏览器为什么读不到 Server-Timing？",
    correct: "需要服务端加 Timing-Allow-Origin，否则跨域资源的 timing 被浏览器屏蔽",
    wrong: "Server-Timing 属于普通响应头，跨域一定可读",
    output: "Server-Timing: db;dur=42.3, render;dur=8.5, total;dur=50.8",
    lanes: ["测量各阶段", "拼接 header", "浏览器读取"],
    laneValues: ["db/render 计时", "setHeader", "PerformanceEntry"],
    log: ["测量 db/render", "写入 Server-Timing", "浏览器 RUM 采集"],
    summary: ["Server-Timing 让后端耗时被前端直接看见", "跨域必须配 Timing-Allow-Origin", "配合 RUM 建立端到端时延视图"],
    sourceTitle: "W3C Server-Timing",
    sourceUrl: "https://www.w3.org/TR/server-timing/"
  }),
  createNetworkLesson({
    id: "network-observability-traceparent-propagation",
    stageId: "network-observability",
    order: 4,
    eyebrowStage: eyebrow,
    title: "W3C traceparent 与后端 OTel 传播",
    concept: "`traceparent: 00-<trace-id 32hex>-<span-id 16hex>-<flags 2hex>` 是 W3C Trace Context 标准。前端生成或延续 trace-id，服务端 OTel SDK 用 W3CTraceContextPropagator 提取并绑定当前 span，跨系统串成一棵调用树。",
    points: ["version-traceid-spanid-flags 四段", "trace-id 32 hex/span-id 16 hex", "flags 最低位 1=sampled"],
    memoryHook: "同一 trace-id 才能串跨系统调用",
    fileName: "traceparent.ts",
    code: `import { randomBytes } from \"node:crypto\";\n\nfunction makeTraceparent(sampled = true) {\n  const traceId = randomBytes(16).toString(\"hex\");\n  const spanId = randomBytes(8).toString(\"hex\");\n  const flags = sampled ? \"01\" : \"00\";\n  return \`00-\${traceId}-\${spanId}-\${flags}\`;\n}\n\nasync function callDownstream(url: string) {\n  const traceparent = makeTraceparent();\n  const res = await fetch(url, { headers: { traceparent } });\n  console.log(\`sent traceparent=\${traceparent} status=\${res.status}\`);\n}\n\nawait callDownstream(\"https://api.example.com/order/42\");`,
    prompt: "服务端收到 traceparent 后正确的做法是什么？",
    correct: "作为 parent span 继续派生子 span，保持同一 trace-id 串起来",
    wrong: "为了避免 ID 冲突，服务端应该生成全新的 trace-id 并回写响应头",
    output: "sent traceparent=00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01 status=200",
    lanes: ["生成 trace-id", "写入请求头", "下游延续"],
    laneValues: ["16B trace/8B span", "header traceparent", "OTel extract"],
    log: ["生成 trace/span", "fetch 带 traceparent", "下游延续同一 trace"],
    summary: ["W3C Trace Context 是跨语言事实标准", "trace-id 决定是否串成同一棵树", "flags 控制采样决策"],
    sourceTitle: "W3C Trace Context",
    sourceUrl: "https://www.w3.org/TR/trace-context/"
  }),
  createNetworkLesson({
    id: "network-observability-rum-vs-synthetic",
    stageId: "network-observability",
    order: 5,
    eyebrowStage: eyebrow,
    title: "RUM vs Synthetic monitoring",
    concept: "RUM（Real User Monitoring）采集真实用户浏览器上报的 PerformanceEntry，反映真实分布；Synthetic 是在固定机器/网络上定时跑脚本，反映基线。二者互补：RUM 找真实问题，Synthetic 找回归。",
    points: ["RUM 数据来自真实用户", "Synthetic 提供可复现基线", "对比两者可定位环境差异"],
    memoryHook: "RUM 看真人，Synthetic 看基线",
    fileName: "rum-report.ts",
    code: `type Nav = PerformanceNavigationTiming;\n\nfunction reportRum() {\n  const nav = performance.getEntriesByType(\"navigation\")[0] as Nav | undefined;\n  if (!nav) return;\n  const ttfb = nav.responseStart - nav.requestStart;\n  const domReady = nav.domContentLoadedEventEnd - nav.startTime;\n  navigator.sendBeacon(\"/rum\", JSON.stringify({\n    url: location.pathname,\n    ttfb,\n    domReady,\n    serverTiming: nav.serverTiming ?? []\n  }));\n}\n\naddEventListener(\"load\", reportRum);`,
    prompt: "线上某接口 Synthetic 一直是 200ms，RUM p95 却是 2s，最可能原因？",
    correct: "真实用户网络/设备差异更大，Synthetic 探测点带宽好覆盖不到长尾",
    wrong: "Synthetic 数据错了，应该以 Synthetic 为准立即忽略 RUM",
    output: "beacon sent { url: '/home', ttfb: 118, domReady: 842 }",
    lanes: ["浏览器采集", "组织指标", "上报后端"],
    laneValues: ["PerformanceEntry", "ttfb/domReady", "sendBeacon"],
    log: ["读取 navigation entry", "计算 ttfb/domReady", "sendBeacon 上报"],
    summary: ["RUM 呈现真实分布", "Synthetic 提供受控基线", "两者一起看才能定位环境类问题"],
    sourceTitle: "MDN PerformanceNavigationTiming",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming"
  }),
  createNetworkLesson({
    id: "network-observability-sslkeylog-decrypt",
    stageId: "network-observability",
    order: 6,
    eyebrowStage: eyebrow,
    title: "sslkeylog 解密 TLS 抓包",
    concept: "浏览器/Node/curl 都支持 `SSLKEYLOGFILE` 环境变量，把每次 TLS 握手的对称密钥写入日志文件。Wireshark 在 Preferences → TLS → (Pre)-Master-Secret log filename 加载后就能解密对应 pcap。",
    points: ["SSLKEYLOGFILE 记录会话密钥", "Wireshark 加载后自动解密", "仅在授权调试环境启用"],
    memoryHook: "有 keylog 才能看明文",
    fileName: "sslkeylog.ts",
    code: `import { spawn } from \"node:child_process\";\n\nconst env = {\n  ...process.env,\n  SSLKEYLOGFILE: \"/tmp/sslkeys.log\"\n};\n\nconst node = spawn(process.execPath, [\"app.js\"], { env, stdio: \"inherit\" });\nnode.on(\"exit\", (code) => {\n  console.log(\`app exited code=\${code}\`);\n  console.log(\"Wireshark → Preferences → Protocols → TLS → 加载 /tmp/sslkeys.log\");\n});`,
    prompt: "为什么禁止把 SSLKEYLOGFILE 用在生产用户机器上？",
    correct: "keylog 泄露等于把所有 HTTPS 流量的明文交出去，只允许在受控调试机使用",
    wrong: "keylog 只是调试日志，泄露没有实质风险，可长期开启加速排障",
    output: "app exited code=0\nWireshark → Preferences → Protocols → TLS → 加载 /tmp/sslkeys.log",
    lanes: ["设置环境变量", "运行应用", "Wireshark 解密"],
    laneValues: ["SSLKEYLOGFILE", "spawn node", "加载 keylog"],
    log: ["设置 SSLKEYLOGFILE", "运行 Node 应用", "Wireshark 加载 keylog 解密"],
    summary: ["SSLKEYLOGFILE 是标准调试通道", "Wireshark 加载即可看明文", "严格限定调试环境"],
    sourceTitle: "Wireshark TLS Decryption",
    sourceUrl: "https://wiki.wireshark.org/TLS"
  }),
  createNetworkLesson({
    id: "network-observability-ebpf-networking",
    stageId: "network-observability",
    order: 7,
    eyebrowStage: eyebrow,
    title: "eBPF 网络观测（Pixie/Cilium 简介）",
    concept: "eBPF 在内核挂载沙箱程序，可以在不改应用、不停机的情况下观测网络：tcp_connect/kprobe 抓连接，socket filter 抓 payload，uprobe 挂到 SSL_write 读明文。Pixie/Cilium Hubble 建立在 eBPF 之上给出集群级视图。",
    points: ["内核挂载不侵入应用", "kprobe/uprobe 覆盖内核与用户态", "Cilium Hubble 提供 L7 可视化"],
    memoryHook: "eBPF = 内核级 tcpdump + 应用可视",
    fileName: "ebpf-probe.ts",
    code: `import { spawn } from \"node:child_process\";\n\n// bpftrace 一行探针：观察每次 tcp_connect 的 PID/comm/目标端口\nconst script = \`tracepoint:syscalls:sys_enter_connect { printf(\"%s pid=%d\\\\n\", comm, pid); }\`;\nconst bt = spawn(\"bpftrace\", [\"-e\", script], { stdio: \"inherit\" });\n\nsetTimeout(() => bt.kill(\"SIGINT\"), 5000);\nbt.on(\"exit\", (code) => console.log(\`bpftrace exited \${code}\`));`,
    prompt: "eBPF 相较传统抓包最独特的能力是？",
    correct: "内核挂载不改应用，可同时观察系统调用/内核与用户态函数",
    wrong: "只能在用户态运行，本质上就是更花哨的 tcpdump 替代品",
    output: "node pid=41231\ncurl pid=41232\nbpftrace exited 0",
    lanes: ["加载 BPF", "内核触发", "输出观测"],
    laneValues: ["bpftrace -e", "sys_enter_connect", "打印 comm/pid"],
    log: ["bpftrace 加载脚本", "捕获 connect 系统调用", "打印进程与 PID"],
    summary: ["eBPF 让内核可编程", "适合零侵入观测", "Pixie/Cilium 是生产级抽象"],
    sourceTitle: "What is eBPF",
    sourceUrl: "https://ebpf.io/what-is-ebpf/"
  }),
  createNetworkLesson({
    id: "network-observability-fault-scenarios",
    stageId: "network-observability",
    order: 8,
    eyebrowStage: eyebrow,
    title: "网络故障场景剖析（DNS/超时/CORS/证书）",
    concept: "常见故障要按“最先能看到证据的层”排查：DNS 用 `dig +trace`、超时看 tcpdump 是否收到 SYN-ACK、CORS 看 OPTIONS 预检响应头、证书用 `openssl s_client -showcerts` 看链和到期。经验就是先分层，再定位工具。",
    points: ["DNS 用 dig +trace 看递归链", "超时靠抓包分层判定断点", "CORS 看预检响应头是否命中"],
    memoryHook: "先分层，再选工具",
    fileName: "diagnose.ts",
    code: `import { execFileSync } from \"node:child_process\";\n\nfunction diagnose(host: string) {\n  const dns = execFileSync(\"dig\", [\"+short\", host]).toString().trim();\n  const cert = execFileSync(\"bash\", [\n    \"-lc\",\n    \`echo | openssl s_client -connect \${host}:443 -servername \${host} 2>/dev/null | openssl x509 -noout -dates\`\n  ]).toString().trim();\n  return { dns, cert };\n}\n\nconsole.log(diagnose(\"example.com\"));`,
    prompt: "浏览器报 CORS 错误但服务端日志里根本没有该请求，最可能原因？",
    correct: "OPTIONS 预检就被拒绝，浏览器直接拦截了后续真实请求",
    wrong: "服务端日志漏采集，其实请求已经到达并成功",
    output: "{ dns: '93.184.216.34', cert: 'notBefore=Feb  ...\\nnotAfter=Mar ...' }",
    lanes: ["解析 DNS", "校验证书", "汇总结果"],
    laneValues: ["dig +short", "openssl s_client", "对象输出"],
    log: ["dig 查询 A 记录", "openssl 查看证书有效期", "打印诊断结果"],
    summary: ["故障分层再定位工具", "DNS/超时/CORS/证书是四大高频类别", "证据链一次抓齐再下结论"],
    sourceTitle: "Wireshark 用户指南",
    sourceUrl: "https://www.wireshark.org/docs/wsug_html_chunked/"
  })
];

const project = createNetworkStageProject({
  id: "network-observability-diagnostic-hub",
  stageId: "network-observability",
  eyebrowStage: eyebrow,
  title: "HAR + Server-Timing + Trace 汇总诊断器",
  brief: "构建一个网络诊断器：读取浏览器 HAR、解析 Server-Timing 头、合并同 trace-id 的后端 span，输出端到端时延和瓶颈定位。",
  concept: "把本阶段的 HAR 时间轴、Server-Timing 后端耗时、W3C traceparent 三条证据汇总到同一个 trace-id 下，形成从浏览器到后端的完整诊断视图。",
  points: ["HAR 提供浏览器视角时间轴", "Server-Timing 拆分后端阶段", "traceparent 串联跨服务 span"],
  memoryHook: "诊断器 = HAR + Timing + Trace",
  fileName: "diagnostic-hub.ts",
  code: `import { readFileSync } from \"node:fs\";\n\ntype HarEntry = {\n  request: { url: string; headers: { name: string; value: string }[] };\n  response: { headers: { name: string; value: string }[] };\n  time: number;\n  timings: { wait: number; receive: number };\n};\ntype Har = { log: { entries: HarEntry[] } };\ntype Span = { traceId: string; name: string; durationMs: number };\n\nfunction headerOf(headers: { name: string; value: string }[], name: string) {\n  return headers.find((h) => h.name.toLowerCase() === name)?.value;\n}\n\nfunction parseServerTiming(value: string | undefined) {\n  if (!value) return [] as { name: string; dur: number }[];\n  return value.split(\",\").map((part) => {\n    const [name, ...rest] = part.trim().split(\";\");\n    const dur = rest.find((r) => r.startsWith(\"dur=\"));\n    return { name, dur: dur ? Number(dur.slice(4)) : 0 };\n  });\n}\n\nfunction parseTraceparent(value: string | undefined) {\n  if (!value) return undefined;\n  const [, traceId] = value.split(\"-\");\n  return traceId;\n}\n\nexport function diagnose(harPath: string, spans: Span[]) {\n  const har = JSON.parse(readFileSync(harPath, \"utf8\")) as Har;\n  const spansByTrace = new Map<string, Span[]>();\n  for (const s of spans) {\n    const arr = spansByTrace.get(s.traceId) ?? [];\n    arr.push(s);\n    spansByTrace.set(s.traceId, arr);\n  }\n\n  return har.log.entries.map((entry) => {\n    const traceId = parseTraceparent(headerOf(entry.request.headers, \"traceparent\"));\n    const serverTiming = parseServerTiming(headerOf(entry.response.headers, \"server-timing\"));\n    const backend = traceId ? spansByTrace.get(traceId) ?? [] : [];\n    const backendMs = backend.reduce((sum, s) => sum + s.durationMs, 0);\n    return {\n      url: entry.request.url,\n      total: entry.time,\n      wait: entry.timings.wait,\n      serverTiming,\n      traceId,\n      backendMs\n    };\n  });\n}\n\nconst report = diagnose(\"home.har\", [\n  { traceId: \"4bf92f3577b34da6a3ce929d0e0e4736\", name: \"db.query\", durationMs: 42 },\n  { traceId: \"4bf92f3577b34da6a3ce929d0e0e4736\", name: \"cache.get\", durationMs: 3 }\n]);\nconsole.log(JSON.stringify(report[0], null, 2));`,
  prompt: "为什么诊断器要以 trace-id 作为主键把 HAR / Server-Timing / 后端 span 汇总？",
  correct: "trace-id 是 W3C 标准里跨浏览器与多个后端服务唯一稳定的关联键",
  wrong: "URL 已经足够唯一，用 URL 拼接汇总更简单也更可靠",
  correctFeedback: "正确：trace-id 保证同一次真实用户操作可以横跨浏览器与多层后端。",
  wrongFeedback: "错误：同一个 URL 会被重放、缓存、并发多次，无法唯一标识一次调用。",
  additionalWrong: {
    label: "只看 HAR 的 timings 就够，不需要合并后端 span",
    feedback: "错误：HAR 只覆盖浏览器到入口的耗时，看不到多个后端服务内部的分段。"
  },
  lanes: ["解析 HAR", "抽取 header", "汇总 trace"],
  laneValues: ["JSON.parse", "traceparent/Server-Timing", "按 trace-id 合并"],
  log: ["读取 home.har", "提取 traceparent 与 Server-Timing", "按 trace-id 合并后端 span"],
  summary: ["HAR/Server-Timing/Trace 是同一次调用的三面视图", "trace-id 是稳定的关联主键", "诊断器要把浏览器与后端证据合并输出"],
  sourceTitle: "OpenTelemetry Context Propagators",
  sourceUrl: "https://opentelemetry.io/docs/specs/otel/context/api-propagators/"
});

export const networkStageEightObservabilityLessons: LessonSpec[] = [...knowledgeLessons, project];
