import type { LessonSpec } from "../../../lib/curriculum/types";
import { createNetworkLesson, createNetworkStageProject } from "./network-lesson-factory";

const eyebrow = "WebRTC 与 P2P";

const knowledgeLessons: LessonSpec[] = [
  createNetworkLesson({
    id: "network-p2p-webrtc-three-apis",
    stageId: "network-p2p-webrtc",
    order: 1,
    eyebrowStage: eyebrow,
    title: "WebRTC 三大 API",
    concept: "WebRTC 由三大 API 组成：`navigator.mediaDevices.getUserMedia` 采集本地音视频、`RTCPeerConnection` 建立端到端会话并搬运媒体轨、`RTCDataChannel` 复用同一条链路传输任意二进制数据。三者分别对应输入、传输、旁路数据面。",
    points: ["getUserMedia 拿到 MediaStream", "RTCPeerConnection 是会话核心", "RTCDataChannel 走 SCTP-over-DTLS"],
    memoryHook: "采集 / 通话 / 数据 = 三条 API",
    fileName: "three-apis.ts",
    code: `const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });\n\nconst pc = new RTCPeerConnection({\n  iceServers: [{ urls: "stun:stun.l.google.com:19302" }]\n});\n\nstream.getTracks().forEach((track) => pc.addTrack(track, stream));\n\nconst dc = pc.createDataChannel("chat", { ordered: true });\ndc.onopen = () => dc.send("hello peer");\ndc.onmessage = (e) => console.log("recv:", e.data);\n\npc.ontrack = (event) => {\n  const [remote] = event.streams;\n  console.log(\`收到远端轨道 \${event.track.kind}\`);\n  remoteVideoEl.srcObject = remote;\n};`,
    prompt: "为什么要把本地媒体轨通过 `addTrack` 挂到 RTCPeerConnection 上，而不是直接把 MediaStream 传过去？",
    correct: "RTCPeerConnection 只感知 Sender/Receiver 与轨道，addTrack 才会驱动 SDP 中新增 m=section 并触发 renegotiation",
    wrong: "只要把 MediaStream 传进构造器 WebRTC 就会自动帮你协商轨道",
    output: "收到远端轨道 video / 收到远端轨道 audio",
    lanes: ["采集本地媒体", "建立 PeerConnection", "开通 DataChannel"],
    laneValues: ["getUserMedia 返回", "addTrack 两条", "chat 通道 open"],
    log: ["getUserMedia 拿到 stream", "addTrack video/audio", "DataChannel chat 打开"],
    summary: ["三大 API 分别负责采集、通话、数据", "addTrack 才是媒体协商的入口", "DataChannel 与媒体共享同一条 PeerConnection"],
    sourceTitle: "MDN WebRTC API",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-signaling-channel",
    stageId: "network-p2p-webrtc",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Signaling 通道",
    concept: "WebRTC 标准刻意不定义信令协议：SDP、ICE 候选、房间成员关系必须由应用自选通道传递，通常用 WebSocket（双向低延迟）或 SSE + POST（受限网络回退）。信令只是把描述搬到对端，媒体仍走 P2P。",
    points: ["WebRTC 只协商，不搬运信令", "WebSocket 是主流选择", "SSE + POST 可穿越只允许 HTTP 的网络"],
    memoryHook: "信令自建，媒体自走",
    fileName: "signaling.ts",
    code: `const ws = new WebSocket("wss://signal.example.com/room/42");\nconst pc = new RTCPeerConnection();\n\npc.onicecandidate = ({ candidate }) => {\n  if (candidate) ws.send(JSON.stringify({ type: "ice", candidate }));\n};\n\nws.onmessage = async (event) => {\n  const msg = JSON.parse(event.data);\n  if (msg.type === "offer") {\n    await pc.setRemoteDescription(msg.sdp);\n    const answer = await pc.createAnswer();\n    await pc.setLocalDescription(answer);\n    ws.send(JSON.stringify({ type: "answer", sdp: pc.localDescription }));\n  } else if (msg.type === "ice") {\n    await pc.addIceCandidate(msg.candidate);\n  }\n};`,
    prompt: "WebRTC 官方为什么不规定信令协议？",
    correct: "让业务复用现有身份/房间/推送体系，SDP+ICE 只是需要透传的载荷",
    wrong: "因为浏览器已经内置了默认信令服务器，业务无需关心",
    output: "signal ← offer / signal → answer / signal ↔ ice*",
    lanes: ["建立信令连接", "透传 SDP", "透传 ICE"],
    laneValues: ["WebSocket open", "offer/answer 交换", "candidate 双向流"],
    log: ["WebSocket 打开", "收到 offer 并生成 answer", "转发 ICE candidate"],
    summary: ["信令是应用职责", "WebSocket 是主流通道", "SDP 与 ICE 都要走信令搬运"],
    sourceTitle: "MDN Signaling & Video Calling",
    sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-sdp-offer-answer",
    stageId: "network-p2p-webrtc",
    order: 3,
    eyebrowStage: eyebrow,
    title: "SDP Offer/Answer 协商",
    concept: "JSEP（RFC 8829）规定 offer/answer 状态机：主叫 createOffer → setLocalDescription → 信令 → setRemoteDescription；被叫反之。任何 addTrack、变更编解码都会让 signalingState 回到 have-local-offer 触发重协商。",
    points: ["createOffer/Answer 只生成 SDP", "setLocal/RemoteDescription 才推进状态机", "signalingState 是判断阶段的唯一依据"],
    memoryHook: "生成 → 落地 → 协商三步曲",
    fileName: "sdp-offer-answer.ts",
    code: `async function makeOffer(pc: RTCPeerConnection, signal: WebSocket) {\n  const offer = await pc.createOffer();\n  await pc.setLocalDescription(offer);\n  console.log("state after local:", pc.signalingState);\n  signal.send(JSON.stringify({ type: "offer", sdp: pc.localDescription }));\n}\n\npc.onnegotiationneeded = async () => {\n  if (pc.signalingState !== "stable") return;\n  await makeOffer(pc, signal);\n};\n\nasync function acceptAnswer(pc: RTCPeerConnection, sdp: RTCSessionDescriptionInit) {\n  await pc.setRemoteDescription(sdp);\n  console.log("state after remote:", pc.signalingState);\n}`,
    prompt: "调用 `pc.addTrack` 之后浏览器最先做什么？",
    correct: "触发 negotiationneeded，应用需要主动 createOffer 才会重新协商",
    wrong: "浏览器会自动重新发送 offer 并把新的轨道加进 SDP",
    output: "state after local: have-local-offer / state after remote: stable",
    lanes: ["生成 offer", "本地落地", "远端应答"],
    laneValues: ["createOffer 完成", "signalingState=have-local-offer", "setRemote 后 stable"],
    log: ["createOffer 生成 SDP", "setLocalDescription 成功", "收到 answer 变回 stable"],
    summary: ["offer/answer 是显式状态机", "变更轨道要走 negotiationneeded", "signalingState 决定下一步动作"],
    sourceTitle: "RFC 8829 · JSEP",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8829"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-ice-candidates",
    stageId: "network-p2p-webrtc",
    order: 4,
    eyebrowStage: eyebrow,
    title: "ICE 候选与优先级",
    concept: "ICE（RFC 8445）为每一对端点收集 host / srflx / relay 候选，按 `priority = 2^24·type + 2^8·local + component` 排序并配对，然后做 STUN 连接性检查，选出延迟最低的通路。Trickle ICE 让候选边发现边发送。",
    points: ["三类候选：host/srflx/relay", "优先级公式偏爱 host 与低延迟", "Trickle ICE 减少建连等待"],
    memoryHook: "本地 > 反射 > 中继",
    fileName: "ice-candidates.ts",
    code: `pc.onicecandidate = ({ candidate }) => {\n  if (!candidate) {\n    console.log("ICE gathering complete");\n    return;\n  }\n  const { type, protocol, address, port, priority } = candidate;\n  console.log(\`candidate \${type} \${protocol}://\${address}:\${port} prio=\${priority}\`);\n  signal.send(JSON.stringify({ type: "ice", candidate }));\n};\n\npc.oniceconnectionstatechange = () => {\n  console.log("ice state:", pc.iceConnectionState);\n  if (pc.iceConnectionState === "connected") {\n    pc.getStats().then((stats) => {\n      stats.forEach((r) => {\n        if (r.type === "candidate-pair" && r.state === "succeeded") {\n          console.log("selected pair rtt=", r.currentRoundTripTime);\n        }\n      });\n    });\n  }\n};`,
    prompt: "两端同网段直连时 ICE 最先选中的候选类型通常是什么？",
    correct: "host 候选（本地 IP），因为优先级最高、无需 NAT 反射",
    wrong: "relay 候选，因为通过 TURN 中继最稳定所以优先",
    output: "candidate host udp://192.168.1.10:57892 prio=2130706431 / ice state: connected",
    lanes: ["收集候选", "配对检查", "选中通路"],
    laneValues: ["host+srflx+relay", "priority 排序配对", "succeeded pair"],
    log: ["gathering 3 类候选", "配对 6 组做 STUN 检查", "选中 host↔host RTT=8ms"],
    summary: ["ICE 用 priority 决定顺序", "getStats 能拿到实际选中的 pair", "Trickle ICE 允许边采集边协商"],
    sourceTitle: "RFC 8445 · ICE",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8445"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-stun-nat-traversal",
    stageId: "network-p2p-webrtc",
    order: 5,
    eyebrowStage: eyebrow,
    title: "STUN 与 NAT 穿越",
    concept: "STUN 服务器只做一件事：告诉客户端“我从公网看到你的地址是 X:Y”。客户端把这个反射地址作为 srflx 候选发给对端，两端同时向对方 srflx 发包，路由器 hole-punching 建立双向 UDP 通道，无需服务器中继媒体。",
    points: ["STUN 返回 XOR-MAPPED-ADDRESS", "srflx 候选来自 STUN 结果", "对称 NAT 会让 hole-punching 失败"],
    memoryHook: "STUN 只报地址，打洞靠对端同时发包",
    fileName: "stun.ts",
    code: `const pc = new RTCPeerConnection({\n  iceServers: [\n    { urls: ["stun:stun.l.google.com:19302", "stun:global.stun.twilio.com:3478"] }\n  ]\n});\n\npc.onicecandidate = ({ candidate }) => {\n  if (!candidate) return;\n  if (candidate.type === "srflx") {\n    console.log(\`公网映射地址：\${candidate.address}:\${candidate.port}\`);\n  }\n};\n\n// 抓包验证：STUN Binding Request → Binding Success Response\n// 服务器仅返回 XOR-MAPPED-ADDRESS，不承担媒体流量`,
    prompt: "两端都在对称 NAT（Symmetric NAT）背后时，纯 STUN 通常会怎样？",
    correct: "hole-punching 失败，srflx 候选无法直连，需要 TURN 中继兜底",
    wrong: "STUN 会自动升级为 TURN 中继模式，媒体一样能通",
    output: "公网映射地址：203.0.113.42:57892 / candidate pair srflx↔srflx failed",
    lanes: ["发 STUN Binding", "拿到映射地址", "尝试打洞"],
    laneValues: ["stun.l.google.com", "203.0.113.42:57892", "对端 srflx 直连"],
    log: ["向 STUN 发 Binding Request", "收到 XOR-MAPPED-ADDRESS", "对端同时打洞"],
    summary: ["STUN 只汇报公网映射", "srflx 候选是打洞前提", "对称 NAT 必须降级到 TURN"],
    sourceTitle: "WebRTC.org 官方入门",
    sourceUrl: "https://webrtc.org/getting-started/overview"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-turn-relay",
    stageId: "network-p2p-webrtc",
    order: 6,
    eyebrowStage: eyebrow,
    title: "TURN 中继与费用权衡",
    concept: "TURN（RFC 8656）在 STUN 之上加了 Allocate/Send/Data 消息，让服务器代收代发媒体。它是最后的兜底，但流量成本按 GB 计费，因此生产上通常配置为 `iceTransportPolicy: 'all'`，让 host/srflx 先试，实在不通再走 relay。",
    points: ["TURN 是 STUN 的超集", "credential 通常按短时鉴权发放", "iceTransportPolicy=relay 会强制中继（贵）"],
    memoryHook: "TURN 是最后一根救命稻草",
    fileName: "turn.ts",
    code: `const pc = new RTCPeerConnection({\n  iceServers: [\n    { urls: "stun:stun.l.google.com:19302" },\n    {\n      urls: ["turn:turn.example.com:3478?transport=udp", "turns:turn.example.com:5349?transport=tcp"],\n      username: shortLivedUser,\n      credential: shortLivedSecret\n    }\n  ],\n  iceTransportPolicy: "all"\n});\n\npc.getStats().then((stats) => {\n  stats.forEach((r) => {\n    if (r.type === "candidate-pair" && r.state === "succeeded" && r.nominated) {\n      const local = stats.get(r.localCandidateId);\n      console.log(\`selected via \${local?.candidateType}\`);\n      if (local?.candidateType === "relay") console.warn("TURN 中继：注意带宽计费");\n    }\n  });\n});`,
    prompt: "生产环境把 `iceTransportPolicy` 设为 `relay` 会带来什么后果？",
    correct: "所有会话强制走 TURN 中继，带宽成本上升且时延增加",
    wrong: "浏览器会更快建连，因为跳过了 host/srflx 尝试",
    output: "selected via relay / TURN 中继：注意带宽计费",
    lanes: ["Allocate 中继端口", "Peer 通过 TURN 收发", "统计 relay 用量"],
    laneValues: ["TURN Allocate 成功", "Send/Data 转发", "getStats bytesSent"],
    log: ["TURN Allocate 拿到端口", "媒体经 TURN 转发", "candidate-pair type=relay"],
    summary: ["TURN 兜底所有 NAT 场景", "凭证要短时化避免被盗刷", "尽量让通话走非 relay 通路"],
    sourceTitle: "RFC 8656 · TURN",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc8656"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-sfu-vs-mcu",
    stageId: "network-p2p-webrtc",
    order: 7,
    eyebrowStage: eyebrow,
    title: "SFU 与 MCU 架构对比",
    concept: "多方会议不再纯 P2P：MCU（Multipoint Control Unit）在服务器混流再下发，带宽小但 CPU 贵；SFU（Selective Forwarding Unit）只做包转发，端上按 Simulcast/SVC 订阅不同层，扩展性好，是主流选择（如 Jitsi、mediasoup、LiveKit）。",
    points: ["Mesh 只适合 3-4 人以内", "MCU 混流省下行带宽但成本高", "SFU 转发 + Simulcast/SVC 是主流"],
    memoryHook: "SFU 转发选层，MCU 混流吃 CPU",
    fileName: "sfu-vs-mcu.ts",
    code: `// SFU 客户端：为每条视频轨发三层 Simulcast\nconst sender = pc.addTransceiver("video", {\n  direction: "sendonly",\n  sendEncodings: [\n    { rid: "q", maxBitrate: 150_000, scaleResolutionDownBy: 4 },\n    { rid: "h", maxBitrate: 500_000, scaleResolutionDownBy: 2 },\n    { rid: "f", maxBitrate: 1_500_000 }\n  ]\n});\n\n// SFU 侧根据订阅者带宽选择转发哪一层\nfunction pickLayer(availableBps: number) {\n  if (availableBps < 300_000) return "q";\n  if (availableBps < 900_000) return "h";\n  return "f";\n}\nconsole.log("下行 400kbps → 转发层:", pickLayer(400_000));`,
    prompt: "SFU 相比 MCU 的最大优势是什么？",
    correct: "只做包转发，配合 Simulcast/SVC 可按订阅端能力灵活选层，服务器成本低、扩展性强",
    wrong: "SFU 会在服务器上混流，因此比 MCU 省下行带宽",
    output: "下行 400kbps → 转发层: h",
    lanes: ["发布 Simulcast", "SFU 选层", "订阅端拉流"],
    laneValues: ["3 层编码", "按带宽选 h", "订阅端播放 h"],
    log: ["Simulcast q/h/f 上行", "SFU 根据 400kbps 选 h", "订阅端渲染 640×360"],
    summary: ["Mesh/MCU/SFU 各有场景", "SFU 是大规模会议的默认选择", "Simulcast/SVC 让弱网也能加入"],
    sourceTitle: "webrtcHacks · SFU vs MCU",
    sourceUrl: "https://webrtchacks.com/sfu-vs-mcu/"
  }),
  createNetworkLesson({
    id: "network-p2p-webrtc-congestion-control",
    stageId: "network-p2p-webrtc",
    order: 8,
    eyebrowStage: eyebrow,
    title: "拥塞控制 GCC 与 TWCC",
    concept: "WebRTC 默认使用 Google Congestion Control：接收端根据帧间抖动估算带宽（REMB / TWCC），发送端结合丢包与延迟做 AIMD 调节比特率。TWCC（Transport-wide CC）把序号与到达时间反馈给发送方，让 RTCP 反馈精度更高。",
    points: ["GCC 结合丢包 + 延迟做估算", "TWCC 反馈每个包的到达时间", "码率变化通过 setParameters 落地"],
    memoryHook: "TWCC 报每包到达，GCC 决定发多少",
    fileName: "congestion-control.ts",
    code: `setInterval(async () => {\n  const stats = await pc.getStats();\n  stats.forEach((r) => {\n    if (r.type === "outbound-rtp" && r.kind === "video") {\n      console.log(\`bitrate=\${r.targetBitrate ?? "n/a"} lost=\${r.packetsLost}\`);\n    }\n    if (r.type === "candidate-pair" && r.state === "succeeded") {\n      console.log(\`rtt=\${r.currentRoundTripTime}s avail=\${r.availableOutgoingBitrate}\`);\n    }\n  });\n}, 2000);\n\n// 主动限速：把最高层降到 800kbps\nconst params = sender.getParameters();\nparams.encodings[2].maxBitrate = 800_000;\nawait sender.setParameters(params);`,
    prompt: "WebRTC 在弱网下调整发送码率的核心信号来自哪里？",
    correct: "TWCC/REMB 反馈的延迟与丢包，GCC 据此做 AIMD 调整",
    wrong: "浏览器根据 CPU 使用率单独决定，不依赖网络反馈",
    output: "bitrate=1200000 lost=3 / rtt=0.042s avail=850000",
    lanes: ["采集 TWCC", "GCC 估算带宽", "调整比特率"],
    laneValues: ["每包到达时间", "AIMD 输出 850kbps", "setParameters 限速"],
    log: ["TWCC 反馈 200 包", "GCC 估算 850kbps", "限速 top layer 到 800kbps"],
    summary: ["TWCC 是主流反馈机制", "GCC 用延迟+丢包做 AIMD", "getStats + setParameters 是调优抓手"],
    sourceTitle: "WebRTC.org 官方入门",
    sourceUrl: "https://webrtc.org/getting-started/overview"
  })
];

const project = createNetworkStageProject({
  id: "network-p2p-webrtc-project",
  stageId: "network-p2p-webrtc",
  eyebrowStage: eyebrow,
  title: "SFU 视频会议诊断台",
  brief: "搭建一个 SFU 视频会议的诊断台：接入 mediasoup/LiveKit 客户端 → 采集 ICE candidate、selected pair、Simulcast 层、TWCC 带宽、RTT 与丢包 → 输出可回溯的会话报告，快速定位是网络、NAT 还是编码问题。",
  concept: "把本阶段全部知识点串起来：三大 API 建立会话、信令搬运 SDP/ICE、STUN/TURN 完成穿越、SFU + Simulcast 支撑多人、TWCC + GCC 调整码率，全流程用 getStats 采样落成报告。",
  points: ["把 signalingState/iceConnectionState/connectionState 三态入库", "从 getStats 里抽取 candidate-pair + outbound-rtp 关键指标", "按会话生成诊断报告：网络 / NAT / 编码 三分类"],
  memoryHook: "诊断台 = 状态机 + getStats + 分类结论",
  fileName: "sfu-diagnostics.ts",
  code: `import { types as MediasoupTypes } from "mediasoup-client";\n\ntype Sample = { ts: number; rtt?: number; avail?: number; sendLayer?: string; lost?: number; relay?: boolean };\n\nexport class SessionDiagnostics {\n  private samples: Sample[] = [];\n  constructor(private pc: RTCPeerConnection, private sender: RTCRtpSender) {}\n\n  start() {\n    this.pc.oniceconnectionstatechange = () =>\n      console.log("ice:", this.pc.iceConnectionState);\n    this.pc.onconnectionstatechange = () =>\n      console.log("conn:", this.pc.connectionState);\n    const timer = setInterval(() => this.sample(), 2000);\n    return () => clearInterval(timer);\n  }\n\n  private async sample() {\n    const stats = await this.pc.getStats();\n    const s: Sample = { ts: Date.now() };\n    stats.forEach((r) => {\n      if (r.type === "candidate-pair" && r.state === "succeeded" && r.nominated) {\n        s.rtt = r.currentRoundTripTime;\n        s.avail = r.availableOutgoingBitrate;\n        const local = stats.get(r.localCandidateId);\n        s.relay = local?.candidateType === "relay";\n      }\n      if (r.type === "outbound-rtp" && r.kind === "video") {\n        s.lost = r.packetsLost;\n        s.sendLayer = (r as any).rid;\n      }\n    });\n    this.samples.push(s);\n  }\n\n  report() {\n    const last = this.samples.at(-1);\n    if (!last) return { category: "unknown" };\n    if (last.relay) return { category: "network/NAT", detail: "选中 relay，需要检查是否可以打洞" };\n    if ((last.lost ?? 0) > 20) return { category: "network", detail: \`丢包 \${last.lost} 触发降级\` };\n    if ((last.avail ?? Infinity) < 300_000) return { category: "encoding", detail: "可用带宽不足，需降层" };\n    return { category: "healthy", detail: \`rtt=\${last.rtt}s avail=\${last.avail}\` };\n  }\n}\n\nconst diag = new SessionDiagnostics(pc, videoSender);\nconst stop = diag.start();\nsetTimeout(() => { console.log(diag.report()); stop(); }, 10_000);`,
  prompt: "SFU 会议诊断台第一步最应该采集的信号是什么？",
  correct: "iceConnectionState + connectionState + selected candidate-pair 的类型（host/srflx/relay），先定位链路是否建成",
  wrong: "只看视频渲染是否流畅，用户没抱怨就当没问题",
  correctFeedback: "正确：链路层信号是所有后续判断的前提，缺了链路数据其他指标都无法解释。",
  wrongFeedback: "错误：主观流畅感落后于问题几十秒，且无法归因是网络、NAT 还是编码问题。",
  additionalWrong: {
    label: "只保存最终 SDP 文本，认为 SDP 里已经包含所有诊断信息",
    feedback: "错误：SDP 是协商结果的快照，不含运行时 RTT、丢包、TWCC 带宽等关键动态数据。"
  },
  lanes: ["会话建连", "指标采样", "分类归因"],
  laneValues: ["ice/conn 状态", "getStats 每 2s", "报告 network/encoding"],
  log: ["ice=connected conn=connected", "采样 5 次 getStats", "报告 category=network detail=丢包 32"],
  summary: ["链路状态是第一手证据", "getStats 是 WebRTC 的通用观测入口", "把结果分类落成报告可回溯"],
  sourceTitle: "MDN WebRTC API",
  sourceUrl: "https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API"
});

export const networkStageNineP2pWebrtcLessons: LessonSpec[] = [...knowledgeLessons, project];
