import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAgentLesson, createAiAgentStageProject } from "./ai-agent-lesson-factory";

const eyebrow = "工具链与工具编排";

const knowledgeLessons: LessonSpec[] = [
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-function-calling-contract",
    stageId: "ai-agent-tool-orchestration",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Function Calling 契约",
    concept: "Function Calling 通过 JSON Schema 描述工具的入参与出参，让 LLM 稳定生成结构化调用。`tools` 由 name/description/parameters 组成，parameters 必须是 valid JSON Schema，模型才能可靠地填槽。",
    points: ["name/description 是模型选择依据", "parameters 必须是 valid JSON Schema", "required 数组约束必填参数"],
    memoryHook: "工具契约 = 名字 + 说明 + Schema",
    fileName: "function-calling.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst tools = [{\n  type: "function" as const,\n  function: {\n    name: "get_weather",\n    description: "查询指定城市的实时天气",\n    parameters: {\n      type: "object",\n      properties: {\n        city: { type: "string", description: "城市名，如 Beijing" },\n        unit: { type: "string", enum: ["celsius", "fahrenheit"] }\n      },\n      required: ["city"]\n    }\n  }\n}];\n\nconst res = await openai.chat.completions.create({\n  model: "gpt-4o-mini",\n  messages: [{ role: "user", content: "北京今天多少度？" }],\n  tools\n});\nconsole.log(res.choices[0].message.tool_calls);`,
    prompt: "Function Calling 中 parameters 字段为什么必须是 JSON Schema？",
    correct: "只有 valid JSON Schema 才能让 LLM 稳定生成结构化参数并触发验证",
    wrong: "parameters 可以是任意自然语言描述，模型会自动推断格式",
    output: "[{ id: 'call_1', function: { name: 'get_weather', arguments: '{\"city\":\"Beijing\"}' } }]",
    lanes: ["注册工具", "模型决策", "生成 tool_call"],
    laneValues: ["get_weather schema", "选中 get_weather", "arguments=Beijing"],
    log: ["注册 1 个工具", "模型选择 get_weather", "arguments={\"city\":\"Beijing\"}"],
    summary: ["JSON Schema 是模型可靠调用的前提", "description 影响工具选中概率", "required 强约束避免漏参"],
    sourceTitle: "OpenAI Function Calling",
    sourceUrl: "https://platform.openai.com/docs/guides/function-calling"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-parallel-tools",
    stageId: "ai-agent-tool-orchestration",
    order: 2,
    eyebrowStage: eyebrow,
    title: "并行工具执行",
    concept: "当 assistant 返回多个 `tool_calls[]` 且工具之间没有依赖时，应用 `Promise.all` 并行执行，避免串行等待累计时延。串行只在存在数据依赖时才必要。",
    points: ["tool_calls[] 天然支持并行", "Promise.all 收集所有结果", "有依赖再退回串行"],
    memoryHook: "无依赖就并行，有依赖才串行",
    fileName: "parallel-tools.ts",
    code: `import type OpenAI from "openai";\n\ntype ToolCall = OpenAI.Chat.Completions.ChatCompletionMessageToolCall;\n\nconst registry: Record<string, (args: any) => Promise<string>> = {\n  get_weather: async ({ city }) => \`\${city} 26°C\`,\n  get_traffic: async ({ city }) => \`\${city} 畅通\`\n};\n\nasync function runToolCalls(calls: ToolCall[]) {\n  const results = await Promise.all(\n    calls.map(async (c) => {\n      const args = JSON.parse(c.function.arguments);\n      const output = await registry[c.function.name](args);\n      return { tool_call_id: c.id, role: "tool" as const, content: output };\n    })\n  );\n  return results;\n}`,
    prompt: "assistant 一次返回 3 个独立 tool_calls，应该如何执行？",
    correct: "用 Promise.all 并行执行，等待所有结果一起回传给模型",
    wrong: "严格按数组顺序 await 串行执行，避免竞争",
    output: "[{ tool_call_id: 'c1', content: 'Beijing 26°C' }, { tool_call_id: 'c2', content: 'Beijing 畅通' }]",
    lanes: ["接收 tool_calls", "并行调度", "收集结果"],
    laneValues: ["2 个调用", "Promise.all 并发", "回传 tool 消息"],
    log: ["收到 2 个 tool_calls", "并发触发 get_weather/get_traffic", "全部完成"],
    summary: ["独立工具并行显著降低时延", "Promise.all 需要处理单点失败", "串行只在数据依赖存在时用"],
    sourceTitle: "OpenAI Function Calling",
    sourceUrl: "https://platform.openai.com/docs/guides/function-calling"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-tool-composition",
    stageId: "ai-agent-tool-orchestration",
    order: 3,
    eyebrowStage: eyebrow,
    title: "工具组合与依赖",
    concept: "当工具 A 的输出是工具 B 的输入时，LLM 通常分多轮 tool_calls 完成依赖。复杂 DAG 场景可用 LangGraph 等编排引擎显式声明节点与边，避免让模型自己规划长链条。",
    points: ["多轮 tool_calls 天然表达依赖", "DAG 场景交给 LangGraph 编排", "把中间结果压回 messages"],
    memoryHook: "依赖用多轮，DAG 用图引擎",
    fileName: "tool-composition.ts",
    code: `import { StateGraph, END } from "@langchain/langgraph";\n\ntype State = { query: string; userId?: string; profile?: any };\n\nconst graph = new StateGraph<State>({\n  channels: { query: null, userId: null, profile: null }\n})\n  .addNode("lookup_user", async (s) => ({ userId: await findUser(s.query) }))\n  .addNode("fetch_profile", async (s) => ({ profile: await getProfile(s.userId!) }))\n  .addEdge("lookup_user", "fetch_profile")\n  .addEdge("fetch_profile", END)\n  .setEntryPoint("lookup_user")\n  .compile();\n\nconst result = await graph.invoke({ query: "查一下张三的最新画像" });\nconsole.log(result.profile);`,
    prompt: "工具 B 依赖工具 A 输出时，最稳的编排方式是什么？",
    correct: "用多轮 tool_calls 或显式图引擎，让依赖关系被系统保证",
    wrong: "把两个工具合并成一个 prompt 让模型一次输出全部结果",
    output: "{ name: '张三', tags: ['VIP', '沪 A'] }",
    lanes: ["解析查询", "查用户 ID", "取画像"],
    laneValues: ["query=张三", "lookup_user → uid_88", "fetch_profile 完成"],
    log: ["运行 lookup_user", "得到 uid_88", "fetch_profile 返回画像"],
    summary: ["依赖关系用系统保证，不靠模型自觉", "LangGraph 用节点+边显式表达", "中间结果回填 messages 供后续步骤"],
    sourceTitle: "LangGraph 官方文档",
    sourceUrl: "https://langchain-ai.github.io/langgraph/"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-tool-selection",
    stageId: "ai-agent-tool-orchestration",
    order: 4,
    eyebrowStage: eyebrow,
    title: "工具选择策略",
    concept: "工具很少时可以全部挂给 LLM 自主选择；工具达到几十上百个时，先用 embedding 检索出候选子集再让 LLM 决策，兼顾准确率与上下文成本。",
    points: ["少量工具直接挂给模型", "大量工具先做向量召回", "planner/router 兜底难判定的意图"],
    memoryHook: "工具多先召回，工具少直接挑",
    fileName: "tool-selection.ts",
    code: `import { OpenAIEmbeddings } from "@langchain/openai";\n\nconst embeddings = new OpenAIEmbeddings();\nconst toolIndex: { name: string; embedding: number[]; schema: any }[] = await loadIndex();\n\nasync function selectTools(query: string, topK = 5) {\n  const [vec] = await embeddings.embedDocuments([query]);\n  return toolIndex\n    .map((t) => ({ tool: t, score: cosine(t.embedding, vec) }))\n    .sort((a, b) => b.score - a.score)\n    .slice(0, topK)\n    .map((x) => x.tool.schema);\n}\n\nconst tools = await selectTools("退款订单 #10086");\nconsole.log(tools.map((t) => t.function.name));`,
    prompt: "工具库有 200+ 个工具时最合适的策略是什么？",
    correct: "先用 embedding 检索候选 Top-K，再把候选工具挂给 LLM 决策",
    wrong: "把 200 个工具全部挂到 tools 参数里，让模型自己筛选",
    output: "['refund_order', 'query_order', 'notify_user']",
    lanes: ["生成 query embedding", "向量召回候选", "挂载给 LLM"],
    laneValues: ["1 条 query", "Top-5 工具", "tools=5 项"],
    log: ["生成 query 向量", "检索到 5 个候选工具", "挂给 LLM 决策"],
    summary: ["工具数量决定策略选择", "embedding 召回控制上下文长度", "router 处理长尾意图"],
    sourceTitle: "LangChain Tools",
    sourceUrl: "https://python.langchain.com/docs/concepts/tools/"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-error-retry",
    stageId: "ai-agent-tool-orchestration",
    order: 5,
    eyebrowStage: eyebrow,
    title: "工具错误重试",
    concept: "工具调用失败需要分类：网络超时、5xx 等可重试；参数校验、4xx 等不可重试。可重试路径用指数退避 + 抖动，避免同时爆破下游服务。",
    points: ["按错误类型分流重试", "指数退避 + 抖动避免同步风暴", "不可重试直接回传给模型让其修正"],
    memoryHook: "先分类，再退避，最后抖动",
    fileName: "retry.ts",
    code: `class RetryableError extends Error {}\n\nasync function callWithRetry<T>(fn: () => Promise<T>, max = 3): Promise<T> {\n  let lastErr: unknown;\n  for (let attempt = 0; attempt < max; attempt++) {\n    try {\n      return await fn();\n    } catch (err) {\n      lastErr = err;\n      if (!(err instanceof RetryableError)) throw err;\n      const backoff = Math.min(1000 * 2 ** attempt, 8000);\n      const jitter = Math.random() * 250;\n      await new Promise((r) => setTimeout(r, backoff + jitter));\n    }\n  }\n  throw lastErr;\n}\n\nconst data = await callWithRetry(() => fetchInventory("SKU-42"));`,
    prompt: "工具返回 400 参数错误时应该怎么处理？",
    correct: "不重试，把错误信息回传给模型让它修正参数再调用",
    wrong: "用指数退避重试 3 次直到成功",
    output: "{ sku: 'SKU-42', stock: 17 }",
    lanes: ["首次调用", "分类错误", "退避重试"],
    laneValues: ["fetchInventory", "RetryableError=true", "第 2 次成功"],
    log: ["第 1 次超时", "退避 1250ms", "第 2 次返回 stock=17"],
    summary: ["区分可重试与不可重试是第一步", "指数退避 + 抖动是行业默认", "把错误消息回给模型可自愈参数错误"],
    sourceTitle: "Anthropic Tool Use",
    sourceUrl: "https://docs.anthropic.com/en/docs/build-with-claude/tool-use"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-sandbox-side-effects",
    stageId: "ai-agent-tool-orchestration",
    order: 6,
    eyebrowStage: eyebrow,
    title: "工具沙箱与副作用",
    concept: "读操作（查询、检索）可以让 Agent 自由调用；写操作（发送邮件、扣款、删除数据）需 dry-run 预览影响面并请求二次确认，避免不可逆错误。",
    points: ["读写分级：读自由/写受控", "写工具支持 dry-run 模式", "关键写操作需人工二次确认"],
    memoryHook: "读随便调，写必确认",
    fileName: "sandbox.ts",
    code: `type WriteContext = { dryRun: boolean; approved: boolean };\n\nasync function sendEmail(args: { to: string; body: string }, ctx: WriteContext) {\n  const preview = { to: args.to, chars: args.body.length };\n  if (ctx.dryRun) return { status: "dry-run", preview };\n  if (!ctx.approved) {\n    return { status: "needs_approval", preview };\n  }\n  await mailer.send(args);\n  return { status: "sent", preview };\n}\n\nconst first = await sendEmail({ to: "vip@x.com", body: "退款已处理" }, { dryRun: true, approved: false });\nconsole.log(first);`,
    prompt: "Agent 想发送一封退款通知邮件，最稳妥的路径是？",
    correct: "先 dry-run 预览影响面，人工或规则批准后再真正发送",
    wrong: "为了体验流畅，直接把邮件工具挂上让 Agent 自主发送",
    output: "{ status: 'dry-run', preview: { to: 'vip@x.com', chars: 8 } }",
    lanes: ["接收调用", "干跑预览", "等待批准"],
    laneValues: ["sendEmail 请求", "dry-run 返回", "needs_approval"],
    log: ["dryRun=true", "生成预览", "等待人工批准"],
    summary: ["写操作是不可逆边界", "dry-run 让影响面可见", "关键写操作需 approval 流"],
    sourceTitle: "OpenAI Agents 指南",
    sourceUrl: "https://platform.openai.com/docs/guides/agents"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-tool-versioning",
    stageId: "ai-agent-tool-orchestration",
    order: 7,
    eyebrowStage: eyebrow,
    title: "工具版本化",
    concept: "工具 schema 演进（新增字段、变更语义）应显式版本化：同一逻辑挂出 `search_v1` 与 `search_v2`，兼容期共存并观察调用比例，稳定后再下线旧版。",
    points: ["schema 变更用版本号显式声明", "兼容期同时暴露新旧版本", "按调用比例决定下线时机"],
    memoryHook: "工具改字段 = 出新版本 + 兼容期",
    fileName: "versioning.ts",
    code: `const toolsV1 = [{\n  type: "function" as const,\n  function: {\n    name: "search_v1",\n    description: "[deprecated] 按关键词搜索，仅返回标题",\n    parameters: { type: "object", properties: { q: { type: "string" } }, required: ["q"] }\n  }\n}];\n\nconst toolsV2 = [{\n  type: "function" as const,\n  function: {\n    name: "search_v2",\n    description: "按关键词搜索，返回标题+片段+分数",\n    parameters: {\n      type: "object",\n      properties: { q: { type: "string" }, topK: { type: "integer" } },\n      required: ["q"]\n    }\n  }\n}];\n\nconst tools = [...toolsV1, ...toolsV2];\nawait metrics.increment("tool.version.exposed", { count: tools.length });`,
    prompt: "工具 schema 需要新增必填字段时最稳的做法是？",
    correct: "发布 v2 并在兼容期与 v1 共存，等调用切完再下线 v1",
    wrong: "直接修改 v1 的 parameters，让所有调用者立刻升级",
    output: "tool.version.exposed count=2",
    lanes: ["定义 v1", "定义 v2", "共存暴露"],
    laneValues: ["search_v1", "search_v2", "tools=2"],
    log: ["挂载 search_v1", "挂载 search_v2", "共存观察"],
    summary: ["schema 变更 = 版本切换", "兼容期共存降低回归风险", "调用比例是下线依据"],
    sourceTitle: "LangChain Tools",
    sourceUrl: "https://python.langchain.com/docs/concepts/tools/"
  }),
  createAiAgentLesson({
    id: "ai-agent-tool-orchestration-trace-attribution",
    stageId: "ai-agent-tool-orchestration",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Tool trace 归因",
    concept: "每次 tool_call 都要记录 input/output/duration/status，串成 trace 树。链路失败时才能快速定位是模型选错工具、参数错误还是下游超时。",
    points: ["记录 input/output/duration/status", "trace 用 parent_id 串成树", "失败定位靠链路可视化"],
    memoryHook: "无 trace 不 debug，无 span 不归因",
    fileName: "trace.ts",
    code: `type Span = {\n  id: string; parentId?: string; name: string;\n  input: unknown; output?: unknown; status: "ok" | "error";\n  startedAt: number; durationMs?: number;\n};\n\nasync function traced<T>(name: string, input: unknown, fn: () => Promise<T>, parentId?: string) {\n  const span: Span = { id: crypto.randomUUID(), parentId, name, input, status: "ok", startedAt: Date.now() };\n  try {\n    const output = await fn();\n    span.output = output;\n    return output;\n  } catch (err) {\n    span.status = "error";\n    span.output = String(err);\n    throw err;\n  } finally {\n    span.durationMs = Date.now() - span.startedAt;\n    await tracer.emit(span);\n  }\n}\n\nawait traced("get_weather", { city: "Beijing" }, () => fetchWeather("Beijing"));`,
    prompt: "线上 Agent 报“工具链失败”，最先要看的证据是什么？",
    correct: "调出该次会话的 trace 树，按 span 状态与耗时定位失败节点",
    wrong: "让工程师逐条重放 messages 数组去猜哪个工具挂了",
    output: "{ name: 'get_weather', status: 'ok', durationMs: 128 }",
    lanes: ["开启 span", "执行工具", "回写 span"],
    laneValues: ["span=get_weather", "调用完成 128ms", "emit trace"],
    log: ["span 开始 get_weather", "调用完成 128ms", "写入 tracer"],
    summary: ["每次 tool_call 都要有 span", "parent_id 串出调用树", "trace 是链路 debug 的第一入口"],
    sourceTitle: "OpenAI Cookbook: Function Calling",
    sourceUrl: "https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models"
  })
];

const project = createAiAgentStageProject({
  id: "ai-agent-tool-orchestration-project",
  stageId: "ai-agent-tool-orchestration",
  eyebrowStage: eyebrow,
  title: "工具编排调度器",
  brief: "构建一个 Agent 工具调度器：接收用户请求 → 让 LLM 决策工具序列 → 独立工具并行执行、依赖工具串行 → 全流程 trace 记录 → 返回结构化结果。",
  concept: "串联本阶段知识点：Function Calling 契约、并行执行、依赖组合、错误重试、trace 归因，形成一个可交付的调度器骨架。",
  points: ["用 Function Calling 让 LLM 决策", "独立 tool_calls 并行、依赖串行", "全程 span 记录便于回溯"],
  memoryHook: "调度器 = 契约 + 并行 + Trace",
  fileName: "orchestrator.ts",
  code: `import OpenAI from "openai";\nimport { traced } from "./trace";\nimport { tools, registry } from "./tools";\n\nconst openai = new OpenAI();\n\nexport async function runAgent(userQuery: string) {\n  const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [\n    { role: "system", content: "你是订单助手，必要时调用工具。" },\n    { role: "user", content: userQuery }\n  ];\n\n  for (let step = 0; step < 5; step++) {\n    const res = await traced("llm.chat", { step }, () =>\n      openai.chat.completions.create({ model: "gpt-4o-mini", messages, tools })\n    );\n    const msg = res.choices[0].message;\n    messages.push(msg);\n    if (!msg.tool_calls?.length) return { answer: msg.content, steps: step + 1 };\n\n    const results = await Promise.all(\n      msg.tool_calls.map((call) =>\n        traced(call.function.name, call.function.arguments, async () => {\n          const args = JSON.parse(call.function.arguments);\n          const output = await registry[call.function.name](args);\n          return { tool_call_id: call.id, role: "tool" as const, content: JSON.stringify(output) };\n        })\n      )\n    );\n    messages.push(...results);\n  }\n  throw new Error("超过最大工具调用轮数");\n}\n\nconst result = await runAgent("帮我查订单 #10086 的物流并发一条通知");\nconsole.log(result);`,
  prompt: "调度器为什么要设置最大工具调用轮数上限？",
  correct: "防止模型在错误信号下无限循环调用工具，形成成本失控和堆栈耗尽",
  wrong: "只是为了让日志更整齐，实际生产可以去掉这个限制",
  correctFeedback: "正确：轮数上限是 Agent 循环的硬边界，配合 trace 可以快速识别死循环。",
  wrongFeedback: "错误：没有上限的循环在参数错误或模型幻觉下会直接烧钱并打爆下游。",
  additionalWrong: {
    label: "只要模型足够强，就不需要 trace 记录，直接看最终回答即可",
    feedback: "错误：没有 trace 的调度器一旦出错就是黑盒，无法定位是哪个工具或哪一轮出问题。"
  },
  lanes: ["LLM 决策", "工具执行", "trace 汇总"],
  laneValues: ["决策 tool_calls", "并行/串行执行", "写入 span"],
  log: ["LLM 返回 2 个 tool_calls", "并行执行 query_order/send_notice", "trace 写入 3 个 span"],
  summary: ["调度器要显式声明轮数上限", "独立 tool_calls 并行执行", "全流程 trace 是排障底座"],
  sourceTitle: "OpenAI Cookbook: Function Calling",
  sourceUrl: "https://cookbook.openai.com/examples/how_to_call_functions_with_chat_models"
});

export const aiAgentStageFourToolOrchestrationLessons: LessonSpec[] = [...knowledgeLessons, project];
