import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "平台工程与 IDP";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-platform-engineering-k8s-core-objects",
    stageId: "server-platform-engineering",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Kubernetes 基础对象（Pod/Deployment/Service）",
    concept: "Kubernetes 用声明式 API 编排容器：Pod 是最小调度单元，Deployment 通过 ReplicaSet 保证副本数与滚动更新，Service 提供稳定的虚拟 IP 与负载均衡入口，把易变的 Pod IP 屏蔽在 selector 之后。",
    points: ["Deployment 保证副本数与滚动策略", "Service 用 selector 屏蔽 Pod IP", "readinessProbe 决定是否加入 endpoints"],
    memoryHook: "Pod 生死无常，Service selector 才是入口",
    fileName: "web-deployment.yaml",
    code: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web\n  labels:\n    app: web\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: web\n  strategy:\n    type: RollingUpdate\n    rollingUpdate:\n      maxSurge: 1\n      maxUnavailable: 0\n  template:\n    metadata:\n      labels:\n        app: web\n    spec:\n      containers:\n      - name: web\n        image: registry.example.com/web:v1.4.2\n        ports:\n        - containerPort: 8080\n        readinessProbe:\n          httpGet:\n            path: /healthz\n            port: 8080\n          periodSeconds: 5\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: web\nspec:\n  type: ClusterIP\n  selector:\n    app: web\n  ports:\n  - port: 80\n    targetPort: 8080`,
    prompt: "为什么客户端调用应该指向 Service 而不是 Pod IP？",
    correct: "Pod IP 会随重启和扩缩容变化，Service 通过 selector 提供稳定虚拟 IP 与负载均衡",
    wrong: "Pod IP 在 Deployment 下是永久不变的，直接调用更省一次转发",
    output: "service/web created; deployment.apps/web created (3/3 ready)",
    lanes: ["Deployment 拉起 Pod", "readinessProbe 就绪", "Service endpoints 挂载"],
    laneValues: ["3 副本调度中", "3/3 ready", "endpoints=3"],
    log: ["Deployment web 创建 3 个 Pod", "3 个 Pod readinessProbe 通过", "Service web 挂载 3 个 endpoints"],
    summary: ["Deployment 负责期望副本数与滚动更新", "Service 用 selector 屏蔽易变 Pod IP", "readinessProbe 决定何时接流量"],
    sourceTitle: "Kubernetes Deployments",
    sourceUrl: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"
  }),
  createServerLesson({
    id: "server-platform-engineering-helm-chart",
    stageId: "server-platform-engineering",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Helm Chart 与配置管理",
    concept: "Helm 把 Kubernetes 资源打包成 Chart：`templates/` 里是 Go template 化的 YAML，`values.yaml` 提供默认值，安装时用 `-f values.prod.yaml` 覆盖。同一 Chart 可以派生多套环境实例，避免手工复制粘贴 manifest。",
    points: ["Chart = templates + values 契约", "环境差异用 values.<env>.yaml 覆盖", "helm upgrade --install 保证幂等"],
    memoryHook: "模板不变，values 环境化",
    fileName: "web-chart-values.yaml",
    code: `# Chart.yaml\napiVersion: v2\nname: web\nversion: 0.3.0\nappVersion: "1.4.2"\n\n---\n# values.yaml (默认)\nreplicaCount: 2\nimage:\n  repository: registry.example.com/web\n  tag: v1.4.2\nresources:\n  requests: { cpu: 100m, memory: 128Mi }\n  limits:   { cpu: 500m, memory: 512Mi }\n\n---\n# values.prod.yaml (生产覆盖)\nreplicaCount: 6\nresources:\n  requests: { cpu: 500m, memory: 512Mi }\n  limits:   { cpu: 2, memory: 2Gi }\n\n---\n# templates/deployment.yaml (Go template)\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ include "web.fullname" . }}\nspec:\n  replicas: {{ .Values.replicaCount }}\n  template:\n    spec:\n      containers:\n      - name: web\n        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"\n        resources: {{ toYaml .Values.resources | nindent 12 }}\n\n# helm upgrade --install web ./charts/web -f values.prod.yaml -n prod`,
    prompt: "生产和预发的资源规格不同，最合适的 Helm 做法是？",
    correct: "共享同一份 templates，用 values.prod.yaml / values.staging.yaml 分别覆盖差异",
    wrong: "为每个环境复制一份 Chart 单独维护，避免 values 层的复杂度",
    output: "Release \"web\" has been upgraded. STATUS: deployed. REVISION: 4",
    lanes: ["渲染模板", "合并 values", "apply 到集群"],
    laneValues: ["templates/*.yaml", "values.prod.yaml 覆盖", "REVISION=4"],
    log: ["Helm 渲染 templates", "合并默认+prod values", "apply 后 REVISION=4"],
    summary: ["Chart 是可复用的部署单元", "多环境差异靠 values 分层", "helm upgrade --install 幂等升级"],
    sourceTitle: "Helm Charts",
    sourceUrl: "https://helm.sh/docs/topics/charts/"
  }),
  createServerLesson({
    id: "server-platform-engineering-gitops-argocd",
    stageId: "server-platform-engineering",
    order: 3,
    eyebrowStage: eyebrow,
    title: "GitOps 与 ArgoCD",
    concept: "GitOps 把 Git 仓库作为集群期望状态的唯一真源。ArgoCD 持续 diff Git 与集群实际状态，发现漂移自动或手工同步。任何变更都走 PR，回滚就是 revert commit，审计与合规天然满足。",
    points: ["Git 是期望状态唯一真源", "Application CR 声明源仓库与目标集群", "syncPolicy.automated 决定是否自愈"],
    memoryHook: "改集群 = 提 PR，回滚 = revert",
    fileName: "argocd-application.yaml",
    code: `apiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: web-prod\n  namespace: argocd\nspec:\n  project: default\n  source:\n    repoURL: https://github.com/acme/platform-manifests.git\n    targetRevision: main\n    path: apps/web/overlays/prod\n  destination:\n    server: https://kubernetes.default.svc\n    namespace: prod\n  syncPolicy:\n    automated:\n      prune: true\n      selfHeal: true\n    syncOptions:\n      - CreateNamespace=true\n    retry:\n      limit: 5\n      backoff:\n        duration: 5s\n        factor: 2\n        maxDuration: 3m`,
    prompt: "生产集群出现被 kubectl edit 手改的资源，ArgoCD 开启 selfHeal 会怎么做？",
    correct: "检测到与 Git 不一致后自动把资源回滚到 Git 声明的状态",
    wrong: "尊重最新的 kubectl edit，把 Git 也自动更新到集群实际状态",
    output: "web-prod  Synced   Healthy   revision=abc1234",
    lanes: ["Git 变更", "ArgoCD diff", "集群同步"],
    laneValues: ["commit abc1234", "OutOfSync 检测", "Synced/Healthy"],
    log: ["main 分支 commit abc1234", "ArgoCD 发现 OutOfSync", "同步后状态 Synced/Healthy"],
    summary: ["Git 是集群状态的唯一真源", "selfHeal 让漂移自动收敛", "回滚只是一次 git revert"],
    sourceTitle: "Argo CD Documentation",
    sourceUrl: "https://argo-cd.readthedocs.io/en/stable/"
  }),
  createServerLesson({
    id: "server-platform-engineering-backstage-scaffolder",
    stageId: "server-platform-engineering",
    order: 4,
    eyebrowStage: eyebrow,
    title: "服务模板与脚手架（Backstage）",
    concept: "Backstage 把内部工具聚合成开发者门户：Software Catalog 统一登记服务与所有权，Scaffolder 用 Template 生成新服务仓库并注册回目录，让新服务从 0 到可上线的时间从 “几天” 压缩到 “几分钟”。",
    points: ["Catalog 沉淀服务与 owner 元数据", "Template 一键生成仓库+CI+manifest", "publish 后自动 register 回目录"],
    memoryHook: "有目录才有归属，有模板才有一致",
    fileName: "backstage-template.yaml",
    code: `apiVersion: scaffolder.backstage.io/v1beta3\nkind: Template\nmetadata:\n  name: nodejs-service\n  title: Node.js 微服务模板\n  description: 生成含 CI、Dockerfile、Helm chart 的 Node.js 服务\nspec:\n  owner: platform-team\n  type: service\n  parameters:\n    - title: 服务信息\n      required: [name, owner]\n      properties:\n        name:\n          title: 服务名\n          type: string\n        owner:\n          title: 所属团队\n          type: string\n  steps:\n    - id: fetch\n      name: 拉取骨架\n      action: fetch:template\n      input:\n        url: ./skeleton\n        values:\n          name: \${{ parameters.name }}\n          owner: \${{ parameters.owner }}\n    - id: publish\n      name: 发布到 Git\n      action: publish:github\n      input:\n        repoUrl: github.com?owner=acme&repo=\${{ parameters.name }}\n    - id: register\n      name: 注册到目录\n      action: catalog:register\n      input:\n        repoContentsUrl: \${{ steps.publish.output.repoContentsUrl }}\n        catalogInfoPath: /catalog-info.yaml`,
    prompt: "内部平台团队为什么要提供 Backstage Scaffolder 模板，而不是让每个团队自由 fork？",
    correct: "模板保证 CI、可观测、安全基线一致，同时把新服务自动登记到 Catalog 建立所有权",
    wrong: "只是为了统一 README 风格，实际工程价值不大",
    output: "Created repository acme/orders-service; registered in Backstage catalog",
    lanes: ["填写参数", "生成仓库", "注册目录"],
    laneValues: ["name=orders-service", "publish:github 完成", "catalog:register 完成"],
    log: ["用户填写 name=orders-service", "publish:github 创建仓库", "catalog:register 登记 owner"],
    summary: ["Catalog 让服务与所有权可查", "Template 内嵌一致的工程基线", "publish+register 一步到位"],
    sourceTitle: "What is Backstage",
    sourceUrl: "https://backstage.io/docs/overview/what-is-backstage"
  }),
  createServerLesson({
    id: "server-platform-engineering-terraform-iac",
    stageId: "server-platform-engineering",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Terraform IaC",
    concept: "Terraform 用 HCL 声明云资源，`plan` 展示 diff，`apply` 通过 provider 调 API 达到期望状态，state 文件记录已知资源。远端 state（S3+锁）是团队协作的必需品，避免并发 apply 撕裂 state。",
    points: ["plan/apply 分离让变更可预览", "state 存远端并加锁避免并发覆盖", "modules 抽象可复用的资源集合"],
    memoryHook: "先 plan 后 apply，state 必须远端锁",
    fileName: "main.tf",
    code: `terraform {\n  required_version = ">= 1.6.0"\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n  backend "s3" {\n    bucket         = "acme-tf-state"\n    key            = "platform/prod.tfstate"\n    region         = "ap-northeast-1"\n    dynamodb_table = "tf-lock"\n    encrypt        = true\n  }\n}\n\nprovider "aws" {\n  region = var.region\n}\n\nmodule "web_cluster" {\n  source          = "./modules/eks"\n  cluster_name    = "web-\${var.env}"\n  node_group_size = var.env == "prod" ? 6 : 2\n  tags = {\n    Env   = var.env\n    Owner = "platform-team"\n  }\n}\n\n# terraform plan  -var env=prod\n# terraform apply -var env=prod`,
    prompt: "多人共同维护同一份 Terraform 项目时，state 应该怎么放？",
    correct: "放到远端后端（如 S3+DynamoDB 锁），apply 前自动加锁避免并发写坏",
    wrong: "各自本地一份 terraform.tfstate，方便快速调试和回滚",
    output: "Apply complete! Resources: 8 added, 2 changed, 0 destroyed.",
    lanes: ["加载 provider", "生成 plan", "apply 变更"],
    laneValues: ["backend=s3+lock", "8 add / 2 change", "Apply complete"],
    log: ["初始化 provider 与远端 state", "plan: 8 add / 2 change", "apply 完成 8+2 项资源"],
    summary: ["plan/apply 分离让变更审计友好", "远端 state + 锁是团队协作前提", "modules 抽象可复用的资源积木"],
    sourceTitle: "Terraform Tutorials",
    sourceUrl: "https://developer.hashicorp.com/terraform/tutorials"
  }),
  createServerLesson({
    id: "server-platform-engineering-multi-env",
    stageId: "server-platform-engineering",
    order: 6,
    eyebrowStage: eyebrow,
    title: "多环境管理（dev/staging/prod）",
    concept: "dev/staging/prod 使用同一份 base manifest，靠 Kustomize overlay 或 Helm values 覆盖差异（副本数、资源、密钥引用）。变更遵循 dev → staging → prod 逐环境晋升，每级都在 GitOps 中留下可审计的 commit。",
    points: ["base + overlays 保证结构一致", "环境差异集中在 overlay/values", "变更按 dev→staging→prod 晋升"],
    memoryHook: "base 不动，overlay 分环境",
    fileName: "kustomization.yaml",
    code: `# base/kustomization.yaml\nresources:\n  - deployment.yaml\n  - service.yaml\ncommonLabels:\n  app: web\n\n---\n# overlays/dev/kustomization.yaml\nnamespace: dev\nresources:\n  - ../../base\npatches:\n  - path: replicas-patch.yaml\n images:\n  - name: web\n    newTag: dev-latest\n\n---\n# overlays/prod/kustomization.yaml\nnamespace: prod\nresources:\n  - ../../base\npatches:\n  - path: replicas-patch.yaml\n  - path: resources-patch.yaml\nimages:\n  - name: web\n    newTag: v1.4.2\n\n---\n# overlays/prod/replicas-patch.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web\nspec:\n  replicas: 6\n\n# kubectl apply -k overlays/prod`,
    prompt: "prod 需要临时改一个 CPU 限制，最应该在哪里改？",
    correct: "在 overlays/prod 的 patch 中修改并走 PR，让 GitOps 同步到集群",
    wrong: "直接 kubectl edit 生产 Deployment，事后再补个 commit",
    output: "kubectl apply -k overlays/prod ⇒ deployment.apps/web configured",
    lanes: ["加载 base", "叠加 overlay", "apply 环境"],
    laneValues: ["base/*.yaml", "overlays/prod patches", "namespace=prod"],
    log: ["加载 base manifests", "叠加 prod overlay patches", "apply 到 prod namespace"],
    summary: ["base 定义结构，overlay 表达环境差异", "所有变更走 GitOps 保证审计", "逐环境晋升降低生产事故"],
    sourceTitle: "Argo CD Documentation",
    sourceUrl: "https://argo-cd.readthedocs.io/en/stable/"
  }),
  createServerLesson({
    id: "server-platform-engineering-idp-api-dx",
    stageId: "server-platform-engineering",
    order: 7,
    eyebrowStage: eyebrow,
    title: "内部平台 API 与开发者体验（DX）",
    concept: "IDP 把 “创建服务、申请数据库、上线一次发布” 抽象成自助 API，屏蔽底层 K8s/云细节。开发者只声明高层意图（如 `kind: Service`），平台负责翻译成 Deployment/Service/Ingress/告警规则，衡量指标是 lead time 与心智负担。",
    points: ["平台 API 表达业务意图而非底层资源", "自助入口替代工单，降低前置等待", "以 lead time / self-service rate 衡量 DX"],
    memoryHook: "平台卖抽象，抽象越薄开发越爽",
    fileName: "platform-api.ts",
    code: `import express from "express";\nimport { z } from "zod";\nimport { renderServiceManifests, commitToGit } from "./platform";\n\nconst ServiceSpec = z.object({\n  name: z.string().min(3),\n  owner: z.string(),\n  runtime: z.enum(["node20", "python312", "go122"]),\n  env: z.enum(["dev", "staging", "prod"]),\n  cpu: z.string().default("200m"),\n  memory: z.string().default("256Mi"),\n  replicas: z.number().int().min(1).max(20).default(2)\n});\n\nconst app = express();\napp.use(express.json());\n\napp.post("/v1/services", async (req, res) => {\n  const spec = ServiceSpec.parse(req.body);\n  const manifests = renderServiceManifests(spec);\n  const commit = await commitToGit({\n    repo: "platform-manifests",\n    branch: \`onboard/\${spec.name}\`,\n    files: manifests,\n    message: \`feat(\${spec.env}): onboard \${spec.name}\`\n  });\n  res.status(202).json({ status: "queued", commit, argocdApp: \`\${spec.name}-\${spec.env}\` });\n});\n\napp.listen(8080);`,
    prompt: "平台 API 直接暴露 K8s Deployment 字段（affinity/tolerations 等）会带来什么问题？",
    correct: "抽象泄漏会让业务团队被迫理解底层细节，DX 变差且平台后续升级空间被锁死",
    wrong: "字段越丰富越好，业务能自由控制一切细节才代表平台强大",
    output: "202 { status: 'queued', commit: 'a1b2c3', argocdApp: 'orders-prod' }",
    lanes: ["校验意图", "生成 manifest", "提交 GitOps"],
    laneValues: ["ServiceSpec 通过", "渲染 4 份 YAML", "commit a1b2c3"],
    log: ["ServiceSpec 校验通过", "渲染 Deployment/Service/Ingress/Alert 4 份 YAML", "提交 commit a1b2c3 触发 ArgoCD"],
    summary: ["平台 API 表达业务意图而非底层资源", "自助流程压缩 lead time", "抽象泄漏是 DX 头号敌人"],
    sourceTitle: "What is Backstage",
    sourceUrl: "https://backstage.io/docs/overview/what-is-backstage"
  }),
  createServerLesson({
    id: "server-platform-engineering-finops",
    stageId: "server-platform-engineering",
    order: 8,
    eyebrowStage: eyebrow,
    title: "FinOps 与成本追踪",
    concept: "FinOps 用 “Inform → Optimize → Operate” 三阶段治理云成本：先按 team/service label 归因账单，再基于用量优化（rightsize、Spot、闲置回收），最后把预算与告警接入日常运营，让工程师对成本负责。",
    points: ["按 label/tag 归因成本到 team/service", "rightsize + Spot 是主要优化杠杆", "预算告警把成本纳入日常运营"],
    memoryHook: "先看清账单，再动手优化，最后常态运营",
    fileName: "finops-report.ts",
    code: `type Usage = {\n  team: string;\n  service: string;\n  env: "dev" | "staging" | "prod";\n  cpuCoreHours: number;\n  memGbHours: number;\n};\n\nconst PRICE = { cpuCoreHour: 0.031, memGbHour: 0.004 };\n\nfunction cost(u: Usage) {\n  return u.cpuCoreHours * PRICE.cpuCoreHour + u.memGbHours * PRICE.memGbHour;\n}\n\nexport function monthlyReport(usages: Usage[]) {\n  const byTeam = new Map<string, number>();\n  for (const u of usages) {\n    byTeam.set(u.team, (byTeam.get(u.team) ?? 0) + cost(u));\n  }\n  const rows = [...byTeam.entries()]\n    .map(([team, total]) => ({ team, usd: Number(total.toFixed(2)) }))\n    .sort((a, b) => b.usd - a.usd);\n  const budgetAlerts = rows.filter((r) => r.usd > 5000);\n  return { rows, budgetAlerts };\n}\n\nconst report = monthlyReport(await loadUsageFromPrometheus());\nconsole.log(report.rows.slice(0, 5));`,
    prompt: "云账单每月超支，最先要做的 FinOps 动作是？",
    correct: "先按 team/service 标签把成本归因清楚，再决定优化哪些工作负载",
    wrong: "直接把所有非生产环境副本数砍半，快速止血再说",
    output: "[{ team: 'search', usd: 8421.30 }, { team: 'orders', usd: 5210.44 }]",
    lanes: ["采集用量", "归因成本", "触发预算告警"],
    laneValues: ["Prometheus 用量", "按 team 汇总", "1 个团队超预算"],
    log: ["从 Prometheus 拉用量数据", "按 team 汇总成本", "search 团队超过 5000 USD 触发告警"],
    summary: ["Inform 阶段先把账单归因清楚", "Optimize 用 rightsize/Spot 降本", "Operate 把预算告警纳入日常"],
    sourceTitle: "FinOps Framework",
    sourceUrl: "https://www.finops.org/framework/"
  })
];

const project = createServerStageProject({
  id: "server-platform-engineering-project",
  stageId: "server-platform-engineering",
  eyebrowStage: eyebrow,
  title: "构建 GitOps 驱动的内部开发者平台",
  brief: "串联本阶段能力，交付一个最小可用的 IDP：开发者通过平台 API 声明服务 → 渲染 Helm/Kustomize manifest → 提交到 platform-manifests 仓库 → ArgoCD 自动同步到 dev/staging/prod → Backstage 目录显示状态与成本，形成从意图到运行的闭环。",
  concept: "把 Kubernetes 对象、Helm、GitOps、Backstage、Terraform、多环境、平台 API、FinOps 组合成一条 “自助上线” 流水线，突出声明式、可审计、可回滚三大原则。",
  points: ["平台 API 生成 manifest 并提交 GitOps 仓库", "ArgoCD 按 overlay 同步到多环境", "Backstage 汇总目录、状态、成本"],
    memoryHook: "IDP = 意图 API + GitOps 同步 + 目录可视",
  fileName: "platform.yaml",
  code: `# 1. 平台 API 接收开发者意图\n# POST /v1/services\n# { name: "orders", owner: "team-order", runtime: "node20",\n#   envs: ["dev","staging","prod"], replicas: { dev:1, staging:2, prod:6 } }\n\n---\n# 2. 生成 platform-manifests 仓库结构\n# apps/orders/base/{deployment.yaml,service.yaml,helm-values.yaml}\n# apps/orders/overlays/{dev,staging,prod}/kustomization.yaml\n\n---\n# 3. ArgoCD Application (每个环境一份)\napiVersion: argoproj.io/v1alpha1\nkind: Application\nmetadata:\n  name: orders-prod\n  namespace: argocd\nspec:\n  project: default\n  source:\n    repoURL: https://github.com/acme/platform-manifests.git\n    targetRevision: main\n    path: apps/orders/overlays/prod\n  destination:\n    server: https://kubernetes.default.svc\n    namespace: prod\n  syncPolicy:\n    automated: { prune: true, selfHeal: true }\n\n---\n# 4. Backstage catalog-info.yaml (由脚手架自动生成)\napiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: orders\n  annotations:\n    argocd/app-name: orders-prod\n    finops/cost-center: team-order\nspec:\n  type: service\n  lifecycle: production\n  owner: team-order\n\n---\n# 5. FinOps 侧车：按 label 抓 Prometheus 用量 -> 每日推送 team-order 频道\n# report := monthlyReport(usages).filter(cost-center=team-order)`,
  prompt: "IDP 的核心价值是什么？最应该优先建设的能力是？",
  correct: "把 “从意图到生产” 的路径变成声明式自助流水线，优先建立 GitOps + 目录 + 平台 API 的最小闭环",
  wrong: "先把所有 K8s、Terraform、CI/CD 的 UI 换一遍皮肤，让开发者觉得平台好看",
  correctFeedback: "正确：IDP 的核心是缩短 lead time 且保持可审计，声明式意图 + GitOps + 目录是不可省略的骨架。",
  wrongFeedback: "错误：换皮不改路径无法解决 lead time 与所有权问题，反而增加维护成本。",
  additionalWrong: {
    label: "把所有 K8s 字段原样透出给业务团队，让平台变薄以降低维护成本",
    feedback: "错误：抽象泄漏会把 K8s 复杂度扔回业务侧，DX 立刻变差，也让平台后续演进空间被锁死。"
  },
  lanes: ["平台 API 接单", "生成并提交 manifest", "ArgoCD 同步 + 目录更新"],
  laneValues: ["ServiceSpec orders", "commit 到 platform-manifests", "orders-prod Synced"],
  log: ["平台 API 校验 ServiceSpec orders", "渲染并提交 3 份 overlay manifest", "ArgoCD 同步完成，Backstage 目录更新状态"],
  summary: ["平台 API 抽象业务意图，屏蔽底层细节", "GitOps 让每次变更可审计可回滚", "Backstage + FinOps 让服务、所有权、成本可视"],
  sourceTitle: "What is Backstage",
  sourceUrl: "https://backstage.io/docs/overview/what-is-backstage"
});

export const serverEngineeringStageTenPlatformEngineeringLessons: LessonSpec[] = [...knowledgeLessons, project];
