import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "CI/CD 与发布策略";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-ci-cd-github-actions-workflow",
    stageId: "server-ci-cd",
    order: 1,
    eyebrowStage: eyebrow,
    title: "GitHub Actions workflow 结构",
    concept: "一个 workflow 由 `on`（触发器）、`jobs`（并行作业）、`steps`（顺序步骤）组成。job 默认并行，用 `needs` 声明依赖；step 之间共享 workspace，跨 job 传值要走 artifact 或 outputs。",
    points: ["on 决定触发时机与事件过滤", "jobs 默认并行，needs 声明依赖", "step 内共享工作目录跨 job 需 artifact"],
    memoryHook: "on 触发，jobs 并行，needs 串行",
    fileName: "ci.yml",
    code: `name: ci\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm test -- --reporter=json > report.json\n      - uses: actions/upload-artifact@v4\n        with:\n          name: test-report\n          path: report.json\n\n  build:\n    needs: test\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm run build\n      - run: echo \"sha=\${{ github.sha }}\" >> \$GITHUB_OUTPUT`,
    prompt: "两个 job 之间要传一个测试报告文件，最合适的方式是？",
    correct: "上游 job 用 upload-artifact 上传，下游 job 用 download-artifact 拉取",
    wrong: "把文件写到 /tmp 由下一个 job 直接读取即可",
    output: "test 完成 → artifact test-report 上传 → build job 拉取继续",
    lanes: ["解析 on 事件", "调度 jobs", "跨 job 传值"],
    laneValues: ["push:main 命中", "test/build 依赖 needs", "artifact test-report"],
    log: ["push 事件触发 workflow", "test job 完成上传 artifact", "build job needs test 继续"],
    summary: ["job 之间默认相互隔离运行", "needs 是唯一显式依赖机制", "跨 job 数据靠 artifact 或 outputs"],
    sourceTitle: "GitHub Actions Quickstart",
    sourceUrl: "https://docs.github.com/en/actions/writing-workflows/quickstart"
  }),
  createServerLesson({
    id: "server-ci-cd-docker-multi-stage-cache",
    stageId: "server-ci-cd",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Docker 多阶段构建与镜像层缓存",
    concept: "多阶段构建把编译工具链留在 builder 阶段，最终 image 只 COPY 产物，显著缩小镜像体积。层缓存按 Dockerfile 指令顺序命中，`COPY package.json` 应放在源码 COPY 之前，让依赖层稳定复用。",
    points: ["builder/runtime 分层剥离工具链", "先 COPY 依赖清单再装依赖", "源码 COPY 放在依赖层之后"],
    memoryHook: "先依赖再源码，缓存才复用",
    fileName: "Dockerfile",
    code: `# syntax=docker/dockerfile:1.7\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package.json package-lock.json ./\nRUN --mount=type=cache,target=/root/.npm npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine AS runtime\nWORKDIR /app\nENV NODE_ENV=production\nCOPY --from=builder /app/package.json ./\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY --from=builder /app/dist ./dist\nUSER node\nEXPOSE 3000\nCMD [\"node\", \"dist/server.js\"]`,
    prompt: "只改一行源码却每次都要重装 node_modules，最可能的原因是？",
    correct: "COPY 源码放在了 COPY package.json 之前，破坏了依赖层缓存",
    wrong: "Docker 缓存机制不可靠，必须清理后重新拉基础镜像",
    output: "builder 完成 → 产物 COPY 到 runtime → 最终镜像 180MB",
    lanes: ["拉取基础镜像", "构建 builder", "组装 runtime"],
    laneValues: ["node:20-alpine", "npm ci + build", "COPY 产物 180MB"],
    log: ["命中 npm 依赖层缓存", "builder 输出 dist/", "runtime 镜像最小化打包"],
    summary: ["多阶段构建剥离工具链降低体积", "层顺序决定缓存命中率", "BuildKit cache mount 加速依赖安装"],
    sourceTitle: "Docker Multi-stage Builds",
    sourceUrl: "https://docs.docker.com/build/building/multi-stage/"
  }),
  createServerLesson({
    id: "server-ci-cd-blue-green-deployment",
    stageId: "server-ci-cd",
    order: 3,
    eyebrowStage: eyebrow,
    title: "蓝绿部署（blue-green）",
    concept: "蓝绿部署维护两套完全相同的生产环境，只有一套（蓝）承接流量。新版本先部署到绿，健康检查通过后切换 Service selector，切流量瞬时完成。出问题只需把 selector 切回蓝即可回滚。",
    points: ["双环境常驻，只有一套接流量", "Service selector 切换即切流量", "回滚等价于把 selector 切回"],
    memoryHook: "两套常驻，切一下 selector",
    fileName: "blue-green.yml",
    code: `# 生产 Service，通过 selector.version 决定流量指向\napiVersion: v1\nkind: Service\nmetadata:\n  name: web\nspec:\n  selector:\n    app: web\n    version: blue      # 切换点：改成 green 即完成切流\n  ports:\n    - port: 80\n      targetPort: 3000\n---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-blue\nspec:\n  replicas: 3\n  selector:\n    matchLabels: { app: web, version: blue }\n  template:\n    metadata:\n      labels: { app: web, version: blue }\n    spec:\n      containers:\n        - name: web\n          image: registry/web:1.0.0\n          readinessProbe:\n            httpGet: { path: /healthz, port: 3000 }\n---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-green\nspec:\n  replicas: 3\n  selector:\n    matchLabels: { app: web, version: green }\n  template:\n    metadata:\n      labels: { app: web, version: green }\n    spec:\n      containers:\n        - name: web\n          image: registry/web:1.1.0\n          readinessProbe:\n            httpGet: { path: /healthz, port: 3000 }`,
    prompt: "蓝绿部署上线后 30 秒发现严重问题，最快的回滚动作是？",
    correct: "把 Service 的 selector.version 从 green 切回 blue，流量瞬时回到旧版",
    wrong: "触发 CI 重新构建蓝环境的旧镜像并 rolling update 回滚",
    output: "green 就绪 → selector 切到 green → 蓝集群保留待回滚",
    lanes: ["部署 green", "健康检查", "切换 selector"],
    laneValues: ["web:1.1.0 就绪", "readiness 全 pass", "selector=green"],
    log: ["green Deployment 3/3 就绪", "readiness 探活全部通过", "Service selector 切到 green"],
    summary: ["蓝绿的核心是流量的瞬时切换", "回滚成本 ≈ 一次 selector 修改", "常驻双环境是资源代价换回滚速度"],
    sourceTitle: "Martin Fowler: BlueGreenDeployment",
    sourceUrl: "https://martinfowler.com/bliki/BlueGreenDeployment.html"
  }),
  createServerLesson({
    id: "server-ci-cd-canary-release",
    stageId: "server-ci-cd",
    order: 4,
    eyebrowStage: eyebrow,
    title: "灰度发布（canary）",
    concept: "灰度按流量百分比逐步放量新版本：5% → 25% → 50% → 100%。每一步之间设置 pause，观察错误率与延迟指标；异常时 Argo Rollouts 会自动 abort 并回滚到上一个 stable 版本。",
    points: ["流量按 step 逐步放量", "step 之间用 analysis 判定放行", "指标异常触发 abort 回滚"],
    memoryHook: "小步放量，指标放行",
    fileName: "canary-rollout.yml",
    code: `apiVersion: argoproj.io/v1alpha1\nkind: Rollout\nmetadata:\n  name: web\nspec:\n  replicas: 10\n  strategy:\n    canary:\n      steps:\n        - setWeight: 5\n        - pause: { duration: 2m }\n        - analysis:\n            templates:\n              - templateName: error-rate-check\n        - setWeight: 25\n        - pause: { duration: 5m }\n        - setWeight: 50\n        - pause: { duration: 10m }\n        - setWeight: 100\n  selector:\n    matchLabels: { app: web }\n  template:\n    metadata:\n      labels: { app: web }\n    spec:\n      containers:\n        - name: web\n          image: registry/web:1.2.0\n---\napiVersion: argoproj.io/v1alpha1\nkind: AnalysisTemplate\nmetadata:\n  name: error-rate-check\nspec:\n  metrics:\n    - name: error-rate\n      interval: 30s\n      successCondition: result[0] < 0.01\n      failureLimit: 3\n      provider:\n        prometheus:\n          address: http://prometheus:9090\n          query: |\n            sum(rate(http_requests_total{status=~\"5..\",service=\"web\"}[1m]))\n              / sum(rate(http_requests_total{service=\"web\"}[1m]))`,
    prompt: "canary 到 25% 时错误率升到 3%，应该由谁决定回滚？",
    correct: "AnalysisRun 命中 failure 阈值自动 abort，Rollouts 把流量切回 stable",
    wrong: "等值班人肉盯 Grafana 面板，判断后手动 kubectl 回滚",
    output: "5% → 25% → analysis 失败 → abort → 流量回到 stable",
    lanes: ["放 5% 流量", "运行 analysis", "自动 abort"],
    laneValues: ["setWeight=5", "error-rate=3%", "回滚到 stable"],
    log: ["canary setWeight=5 完成", "analysis 检测 error-rate=3%", "abort 触发流量回到 stable"],
    summary: ["灰度是流量 + 时间 + 指标的组合决策", "analysis 是自动放行/回滚的钥匙", "失败 3 次是常用 abort 阈值"],
    sourceTitle: "Argo Rollouts Canary",
    sourceUrl: "https://argoproj.github.io/rollouts/"
  }),
  createServerLesson({
    id: "server-ci-cd-feature-flags",
    stageId: "server-ci-cd",
    order: 5,
    eyebrowStage: eyebrow,
    title: "特性开关（feature flags）",
    concept: "特性开关把发布（deploy）与释放（release）解耦：代码先上线但功能关闭，通过 flag 服务按用户/租户/百分比动态开启。灰度用户命中新代码路径，其他人走旧路径，出问题一键关灯。",
    points: ["deploy 与 release 解耦", "flag 按用户/百分比命中", "一键关灯回退无需重新发布"],
    memoryHook: "先部署后放灯，关灯代替回滚",
    fileName: "feature-flag.ts",
    code: `type FlagContext = { userId: string; tenant?: string };\n\nasync function isEnabled(flag: string, ctx: FlagContext): Promise<boolean> {\n  const rule = await flagStore.get(flag);\n  if (!rule || rule.status === \"off\") return false;\n  if (rule.allowlist?.includes(ctx.userId)) return true;\n  if (rule.tenantAllowlist?.includes(ctx.tenant ?? \"\")) return true;\n  const bucket = hash(\`\${flag}:\${ctx.userId}\`) % 100;\n  return bucket < (rule.rolloutPercent ?? 0);\n}\n\nexport async function checkout(order: Order, ctx: FlagContext) {\n  if (await isEnabled(\"new-pricing-engine\", ctx)) {\n    return newPricing(order);\n  }\n  return legacyPricing(order);\n}\n\n// 灯亮 5% → 观察指标 → 逐步 25/50/100，出问题直接把 status 置 off`,
    prompt: "开启 flag 后线上新路径出现异常，最应该先做的动作是？",
    correct: "在 flag 平台把开关关闭，让所有流量立刻走回旧路径",
    wrong: "紧急提交一个 revert PR，走完 CI/CD 再重新部署",
    output: "flag=on 5% → 用户命中新路径 → 关灯后 0% 命中",
    lanes: ["加载 flag", "命中判断", "路由分支"],
    laneValues: ["new-pricing-engine=5%", "bucket=3<5", "走 newPricing"],
    log: ["拉取 flag 规则", "用户 bucket=3 命中", "调用 newPricing 分支"],
    summary: ["flag 让 release 从代码发布中剥离", "灰度粒度可到用户级别", "关灯是最快的功能级回滚"],
    sourceTitle: "Martin Fowler: FeatureToggle",
    sourceUrl: "https://martinfowler.com/articles/feature-toggles.html"
  }),
  createServerLesson({
    id: "server-ci-cd-database-migration",
    stageId: "server-ci-cd",
    order: 6,
    eyebrowStage: eyebrow,
    title: "数据库迁移策略（online / backward compatible）",
    concept: "在线迁移必须做到双写兼容：先加新字段（可空）→ 应用层同时读写新旧字段 → 回填历史数据 → 应用层只读新字段 → 删除旧字段。每一步都必须让新老代码都能运行，禁止一次性 rename/drop。",
    points: ["新字段先 add 且可空", "应用层双写过渡", "旧字段最后一步才 drop"],
    memoryHook: "先加后填再切，最后才删",
    fileName: "expand-contract.ts",
    code: `// Step 1: expand — 新增可空列，向后兼容\nawait sql\`ALTER TABLE orders ADD COLUMN customer_id_v2 BIGINT NULL\`;\n\n// Step 2: 应用层双写（新老代码同时在线，读旧写双）\nasync function createOrder(o: Order) {\n  await sql\`INSERT INTO orders (customer_id, customer_id_v2, amount)\n            VALUES (\${o.legacyId}, \${o.newId}, \${o.amount})\`;\n}\n\n// Step 3: 回填历史数据（分批，避免锁表）\nfor (let offset = 0; ; offset += 1000) {\n  const rows = await sql\`SELECT id, customer_id FROM orders\n                         WHERE customer_id_v2 IS NULL LIMIT 1000\`;\n  if (rows.length === 0) break;\n  await sql\`UPDATE orders SET customer_id_v2 = customer_id\n            WHERE id = ANY(\${rows.map((r) => r.id)})\`;\n}\n\n// Step 4: 切读到新列（保留双写一段时间观察）\n// Step 5: contract — 旧代码全部下线后再执行\nawait sql\`ALTER TABLE orders DROP COLUMN customer_id\`;`,
    prompt: "为什么不能在一次上线里直接 rename 一个正在被读写的字段？",
    correct: "老实例仍在运行会读到不存在的列，双写兼容 + 分步切换才能安全过渡",
    wrong: "只要 DDL 在低峰期执行且加了 IF EXISTS 就没问题",
    output: "add column → 双写 → 回填 → 切读 → drop 旧列",
    lanes: ["加新字段", "双写回填", "切读并 drop"],
    laneValues: ["ADD customer_id_v2", "回填 1M 行完成", "DROP customer_id"],
    log: ["ALTER TABLE 添加可空列", "应用层双写并回填历史", "确认无引用后 DROP 旧列"],
    summary: ["Expand-Contract 是在线迁移的默认套路", "每一步都要兼容新老实例并行", "破坏性 DDL 永远放到最后一步"],
    sourceTitle: "Martin Fowler: ParallelChange",
    sourceUrl: "https://martinfowler.com/bliki/ParallelChange.html"
  }),
  createServerLesson({
    id: "server-ci-cd-rollback-automation",
    stageId: "server-ci-cd",
    order: 7,
    eyebrowStage: eyebrow,
    title: "Rollback 机制与自动回滚触发",
    concept: "自动回滚由 SLO 违规触发：错误率 > 1%、P99 延迟 > 500ms、饱和度指标恶化等，连续 N 个观测窗口命中即回滚。前提是每次发布都留有已知稳定版本（image tag / helm revision），回滚等于切回上一版。",
    points: ["回滚由 SLO 指标触发", "连续 N 窗口命中避免抖动误判", "保留稳定版本作为回滚锚点"],
    memoryHook: "指标越界 + 连续命中 = 回滚",
    fileName: "auto-rollback.ts",
    code: `type ReleaseState = { version: string; previousVersion: string };\n\nasync function watchAndRollback(state: ReleaseState) {\n  let breachWindows = 0;\n  const THRESHOLD_ERROR_RATE = 0.01;\n  const THRESHOLD_P99_MS = 500;\n  const REQUIRED_BREACH_WINDOWS = 3;\n\n  for (;;) {\n    const m = await prometheus.query({ version: state.version });\n    const breached = m.errorRate > THRESHOLD_ERROR_RATE || m.p99Ms > THRESHOLD_P99_MS;\n    breachWindows = breached ? breachWindows + 1 : 0;\n\n    if (breachWindows >= REQUIRED_BREACH_WINDOWS) {\n      await argocd.rollback({ app: \"web\", toRevision: state.previousVersion });\n      await alerts.page(\`auto-rollback: \${state.version} → \${state.previousVersion}\`);\n      return;\n    }\n    await sleep(30_000);\n  }\n}`,
    prompt: "为什么自动回滚要求连续多个窗口都命中阈值？",
    correct: "单窗口抖动经常误报，连续窗口命中才是真实趋势，避免频繁回滚",
    wrong: "只要一次错误率超阈值就立刻回滚，越快越安全",
    output: "窗口1 命中 → 窗口2 命中 → 窗口3 命中 → 触发回滚",
    lanes: ["采集指标", "命中次数累计", "触发回滚"],
    laneValues: ["errorRate=2%", "breachWindows=3", "argocd rollback"],
    log: ["errorRate=2% p99=620ms", "连续 3 窗口命中阈值", "回滚到 previousVersion 完成"],
    summary: ["回滚必须由客观指标触发", "连续窗口过滤瞬时抖动", "上一稳定版本是回滚可行的前提"],
    sourceTitle: "Google SRE Book: Release Engineering",
    sourceUrl: "https://sre.google/sre-book/release-engineering/"
  }),
  createServerLesson({
    id: "server-ci-cd-supply-chain-security",
    stageId: "server-ci-cd",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Supply Chain 安全（SBOM, image scanning）",
    concept: "供应链安全要求每次构建都产出 SBOM（软件物料清单），并对镜像做漏洞扫描。SLSA 框架定义了从源码到制品的溯源要求：签名的 provenance、可复现构建、依赖锁定，缺一不可发布。",
    points: ["SBOM 记录所有依赖及版本", "镜像扫描阻断高危漏洞", "SLSA provenance 建立可溯源链"],
    memoryHook: "有 SBOM 才知装了啥，扫过才敢上",
    fileName: "supply-chain.yml",
    code: `name: release\non:\n  push:\n    tags: [\"v*\"]\n\npermissions:\n  contents: read\n  id-token: write         # 用于 cosign keyless 签名\n  packages: write\n\njobs:\n  build-and-attest:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/build-push-action@v6\n        id: build\n        with:\n          push: true\n          tags: ghcr.io/org/web:\${{ github.ref_name }}\n          provenance: true              # SLSA provenance\n          sbom: true                    # 生成 SPDX SBOM\n\n      - name: Scan image (Trivy)\n        uses: aquasecurity/trivy-action@0.24.0\n        with:\n          image-ref: ghcr.io/org/web:\${{ github.ref_name }}\n          severity: CRITICAL,HIGH\n          exit-code: 1                  # 命中高危漏洞失败\n\n      - name: Sign image (Cosign keyless)\n        run: cosign sign --yes ghcr.io/org/web@\${{ steps.build.outputs.digest }}`,
    prompt: "只做镜像漏洞扫描是否足够满足供应链安全？",
    correct: "不够，还需 SBOM 记录依赖来源、签名建立 provenance 才形成完整链",
    wrong: "只要扫描不报 CRITICAL 就可以放心发布",
    output: "build → SBOM 输出 → Trivy 扫描通过 → cosign 签名",
    lanes: ["构建并生成 SBOM", "漏洞扫描", "签名与推送"],
    laneValues: ["provenance+sbom=true", "Trivy 0 CRITICAL", "cosign sign 完成"],
    log: ["镜像构建携带 SBOM 与 provenance", "Trivy 扫描无 CRITICAL/HIGH", "cosign 完成 keyless 签名"],
    summary: ["SBOM 是可解释供应链的基础", "扫描应在流水线内阻断高危", "SLSA provenance 建立源码到制品链"],
    sourceTitle: "SLSA Supply-chain Levels",
    sourceUrl: "https://slsa.dev/"
  })
];

const project = createServerStageProject({
  id: "server-ci-cd-project",
  stageId: "server-ci-cd",
  eyebrowStage: eyebrow,
  title: "构建带 canary + 自动回滚的部署流水线",
  brief: "串联本阶段知识点：GitHub Actions 触发构建 → 多阶段镜像 + SBOM + 签名 → Argo Rollouts 灰度放量 → analysis 指标兜底 → 违规自动回滚，形成一条可交付的端到端流水线。",
  concept: "把 CI（构建、扫描、签名）与 CD（灰度、指标、回滚）合成一条可解释的流水线：任何一步失败都能停在有据可查的检查点，任何一次异常都能自动回到已知稳定版本。",
  points: ["CI 侧构建 + SBOM + 签名不可跳过", "CD 侧灰度按 analysis 放行", "指标违规自动 abort 回滚"],
  memoryHook: "构建有签名，放量看指标，异常自回滚",
  fileName: "pipeline.yml",
  code: `# .github/workflows/deploy.yml —— CI\nname: deploy\non:\n  push:\n    branches: [main]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    permissions: { contents: read, id-token: write, packages: write }\n    outputs:\n      digest: \${{ steps.build.outputs.digest }}\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/build-push-action@v6\n        id: build\n        with:\n          push: true\n          tags: ghcr.io/org/web:\${{ github.sha }}\n          provenance: true\n          sbom: true\n      - uses: aquasecurity/trivy-action@0.24.0\n        with:\n          image-ref: ghcr.io/org/web:\${{ github.sha }}\n          severity: CRITICAL,HIGH\n          exit-code: 1\n      - run: cosign sign --yes ghcr.io/org/web@\${{ steps.build.outputs.digest }}\n\n  rollout:\n    needs: build\n    runs-on: ubuntu-latest\n    steps:\n      - run: |\n          argocd app set web --helm-set image.tag=\${{ github.sha }}\n          argocd app sync web\n---\n# argo-rollouts.yaml —— CD\napiVersion: argoproj.io/v1alpha1\nkind: Rollout\nmetadata: { name: web }\nspec:\n  replicas: 10\n  strategy:\n    canary:\n      steps:\n        - setWeight: 5\n        - pause: { duration: 2m }\n        - analysis: { templates: [{ templateName: slo-guard }] }\n        - setWeight: 50\n        - pause: { duration: 5m }\n        - analysis: { templates: [{ templateName: slo-guard }] }\n        - setWeight: 100\n---\napiVersion: argoproj.io/v1alpha1\nkind: AnalysisTemplate\nmetadata: { name: slo-guard }\nspec:\n  metrics:\n    - name: error-rate\n      interval: 30s\n      successCondition: result[0] < 0.01\n      failureLimit: 3\n      provider:\n        prometheus:\n          address: http://prometheus:9090\n          query: |\n            sum(rate(http_requests_total{status=~\"5..\",service=\"web\"}[1m]))\n              / sum(rate(http_requests_total{service=\"web\"}[1m]))`,
  prompt: "整条流水线里最不能被跳过的检查点是哪一个？",
  correct: "镜像扫描 + 签名 与 canary analysis：前者守出厂质量，后者守发布过程",
  wrong: "只要有 canary 灰度就够了，构建阶段的扫描和签名可以按需跳过",
  correctFeedback: "正确：CI 侧检查决定“是否可发”，CD 侧 analysis 决定“是否继续放量”，二者是不同边界的守门。",
  wrongFeedback: "错误：没有签名与扫描的镜像即使灰度成功，也无法证明来源可信、无高危漏洞。",
  additionalWrong: {
    label: "只要 CI 全绿，就可以直接 setWeight: 100 一步到位",
    feedback: "错误：CI 无法保证真实流量下的表现，跳过 canary 会把所有用户暴露在未验证的版本上。"
  },
  lanes: ["CI 构建与签名", "CD 灰度放量", "指标兜底与回滚"],
  laneValues: ["build + sbom + sign", "canary 5% → 50%", "analysis 失败自动回滚"],
  log: ["构建镜像并附 SBOM/签名通过扫描", "Argo Rollouts 灰度到 50%", "analysis 命中阈值触发自动回滚"],
  summary: ["CI 与 CD 各守一段安全边界", "canary 是流量真值下的最后一道确认", "自动回滚让平均故障恢复时间可预期"],
  sourceTitle: "Argo Rollouts",
  sourceUrl: "https://argoproj.github.io/rollouts/"
});

export const serverEngineeringStageEightCiCdLessons: LessonSpec[] = [...knowledgeLessons, project];
