import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "消息队列深入";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-message-queue-kafka-partitions-groups",
    stageId: "server-message-queue",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Kafka 分区与消费者组",
    concept: "Kafka 的并行度由 partition 决定：一个 partition 在同一 consumer group 内只会被一个消费者持有，所以 group 内消费者数量不应超过 partition 数，否则多余消费者会闲置。跨 group 的消费者互相独立，各自维护 offset。",
    points: ["partition 是并行度上限", "group 内消费者一对多绑定 partition", "跨 group 消费互不影响 offset"],
    memoryHook: "分区决定并行，Group 决定隔离",
    fileName: "kafka-consumer-group.ts",
    code: `import { Kafka } from "kafkajs";\n\nconst kafka = new Kafka({ clientId: "orders", brokers: ["broker:9092"] });\nconst consumer = kafka.consumer({ groupId: "order-projector" });\n\nawait consumer.connect();\nawait consumer.subscribe({ topic: "orders", fromBeginning: false });\n\nawait consumer.run({\n  eachMessage: async ({ topic, partition, message }) => {\n    console.log(\`[\${topic}#\${partition}] offset=\${message.offset} key=\${message.key?.toString()}\`);\n  }\n});`,
    prompt: "topic 有 6 个 partition，consumer group 里启动 10 个实例，会发生什么？",
    correct: "6 个消费者各拿到 1 个 partition，剩下 4 个闲置直到有 partition 释放",
    wrong: "10 个消费者会均分 6 个 partition，每人处理 60% 的消息",
    output: "[orders#3] offset=812 key=order-10086",
    lanes: ["订阅 topic", "分配 partition", "拉取消息"],
    laneValues: ["subscribe orders", "assigned p0-p5", "poll offset=812"],
    log: ["订阅 orders topic", "group 分配到 partition 0-5", "拉取到 offset=812"],
    summary: ["partition 数量是并行度硬上限", "同 group 消费者与 partition 是一对多", "跨 group 是独立消费流"],
    sourceTitle: "Kafka Consumer 官方文档",
    sourceUrl: "https://kafka.apache.org/documentation/#consumerconfigs"
  }),
  createServerLesson({
    id: "server-message-queue-offset-management",
    stageId: "server-message-queue",
    order: 2,
    eyebrowStage: eyebrow,
    title: "offset 管理策略",
    concept: "auto commit 会按 `auto.commit.interval.ms` 周期性提交最新拉取到的 offset，处理失败也会被跳过，导致丢消息。手动 commit 在业务处理成功后再 commit，能保证 at-least-once，代价是要自己处理重复消费。",
    points: ["auto commit 可能丢消息", "手动 commit 提供 at-least-once", "重复消费用幂等抵消"],
    memoryHook: "自动省心会丢，手动可靠会重",
    fileName: "kafka-manual-commit.ts",
    code: `import { Kafka } from "kafkajs";\n\nconst kafka = new Kafka({ clientId: "billing", brokers: ["broker:9092"] });\nconst consumer = kafka.consumer({ groupId: "billing-worker" });\n\nawait consumer.connect();\nawait consumer.subscribe({ topic: "payments" });\n\nawait consumer.run({\n  autoCommit: false,\n  eachMessage: async ({ topic, partition, message }) => {\n    await handlePayment(JSON.parse(message.value!.toString()));\n    await consumer.commitOffsets([{ topic, partition, offset: (BigInt(message.offset) + 1n).toString() }]);\n  }\n});`,
    prompt: "支付回调处理必须“至少成功一次”，应该选哪种 offset 策略？",
    correct: "关掉 autoCommit，业务成功后手动 commit，并对重复消费做幂等处理",
    wrong: "保留 autoCommit 并把 interval 调到 100ms，几乎不会丢消息",
    output: "committed payments#0 offset=4211",
    lanes: ["拉取消息", "处理业务", "提交 offset"],
    laneValues: ["poll offset=4210", "handlePayment 成功", "commit 4211"],
    log: ["拉取 offset=4210", "业务处理成功", "手动 commit offset=4211"],
    summary: ["auto commit 丢消息风险来自异步提交", "at-least-once 需手动 commit", "重复消费必须幂等承接"],
    sourceTitle: "KafkaJS Consuming",
    sourceUrl: "https://kafka.js.org/docs/consuming"
  }),
  createServerLesson({
    id: "server-message-queue-exactly-once",
    stageId: "server-message-queue",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Exactly-once 语义",
    concept: "Kafka 通过 producer idempotence（PID + sequence number）避免重试导致的重复写入，再用 transactional producer 把“写多个 topic + 提交 consumer offset”打包为原子事务，形成 read-process-write 的 exactly-once。",
    points: ["idempotence 消除重试重复", "transaction 打包多 topic 写入", "consumer 必须 read_committed"],
    memoryHook: "幂等去重，事务闭环",
    fileName: "kafka-eos.ts",
    code: `import { Kafka } from "kafkajs";\n\nconst kafka = new Kafka({ clientId: "eos", brokers: ["broker:9092"] });\nconst producer = kafka.producer({ idempotent: true, transactionalId: "order-tx-1" });\n\nawait producer.connect();\nconst tx = await producer.transaction();\ntry {\n  await tx.send({ topic: "orders.paid", messages: [{ key: "10086", value: JSON.stringify({ amount: 99 }) }] });\n  await tx.sendOffsets({\n    consumerGroupId: "order-worker",\n    topics: [{ topic: "orders.new", partitions: [{ partition: 0, offset: "512" }] }]\n  });\n  await tx.commit();\n} catch (err) {\n  await tx.abort();\n  throw err;\n}`,
    prompt: "已经开启 `idempotent: true` 后，为什么还需要 transactional producer？",
    correct: "idempotence 只保证单 partition 不重复，跨 topic 写入 + offset 提交要靠事务原子化",
    wrong: "开启 idempotent 后已经是 exactly-once，事务只是为了性能优化",
    output: "transaction committed: orders.paid + offsets",
    lanes: ["开启事务", "写入下游 topic", "提交 offset"],
    laneValues: ["beginTransaction", "send orders.paid", "sendOffsets + commit"],
    log: ["开启事务 tx=order-tx-1", "写入 orders.paid", "提交下游 offset 并 commit"],
    summary: ["idempotent 解决单分区重复", "transaction 原子化多 topic + offset", "消费端要 read_committed 才闭环"],
    sourceTitle: "Confluent Kafka Design",
    sourceUrl: "https://docs.confluent.io/kafka/design/index.html"
  }),
  createServerLesson({
    id: "server-message-queue-rabbitmq-topology",
    stageId: "server-message-queue",
    order: 4,
    eyebrowStage: eyebrow,
    title: "RabbitMQ 拓扑三件套",
    concept: "RabbitMQ 的路由由三部分组成：producer 发送到 exchange，exchange 按 routing key 与 binding 规则分发到 queue，consumer 只订阅 queue。direct/topic/fanout/headers 四种 exchange 决定分发策略，queue 才是真正持有消息的实体。",
    points: ["producer 只跟 exchange 交互", "routing key 决定命中哪些 queue", "queue 是消息的持久化边界"],
    memoryHook: "Exchange 路由，Queue 持有",
    fileName: "rabbitmq-topology.ts",
    code: `import amqp from "amqplib";\n\nconst conn = await amqp.connect("amqp://localhost");\nconst ch = await conn.createChannel();\n\nawait ch.assertExchange("orders.events", "topic", { durable: true });\nawait ch.assertQueue("orders.paid.billing", { durable: true });\nawait ch.bindQueue("orders.paid.billing", "orders.events", "order.*.paid");\n\nch.publish("orders.events", "order.retail.paid", Buffer.from(JSON.stringify({ id: 10086 })), {\n  persistent: true\n});\n\nawait ch.consume("orders.paid.billing", (msg) => {\n  if (!msg) return;\n  console.log("received", msg.fields.routingKey, msg.content.toString());\n  ch.ack(msg);\n});`,
    prompt: "同一条订单事件需要被“账单服务”和“积分服务”都消费到，最合适的拓扑是？",
    correct: "一个 topic exchange 绑定两个独立 queue，各自消费不干扰",
    wrong: "两个服务共用同一个 queue，靠不同消费者 tag 区分",
    output: "received order.retail.paid {\"id\":10086}",
    lanes: ["声明 exchange", "绑定 queue", "发布/消费"],
    laneValues: ["orders.events topic", "orders.paid.billing", "routingKey=order.retail.paid"],
    log: ["声明 topic exchange", "queue 绑定 order.*.paid", "消费到 order.retail.paid"],
    summary: ["exchange + routing key 决定分发", "queue 是消息副本的边界", "多消费者需要多 queue 隔离"],
    sourceTitle: "RabbitMQ Tutorial One (JS)",
    sourceUrl: "https://www.rabbitmq.com/tutorials/tutorial-one-javascript.html"
  }),
  createServerLesson({
    id: "server-message-queue-dlq-retry",
    stageId: "server-message-queue",
    order: 5,
    eyebrowStage: eyebrow,
    title: "死信队列与重试策略",
    concept: "消息处理失败时，直接 `nack(requeue=true)` 会陷入无限重试。生产做法是把队列绑定 dead-letter-exchange（DLX）与延迟重试队列，超过最大重试次数后进入 DLQ，由人工或补偿流程接管，避免毒消息拖垮消费者。",
    points: ["无限 requeue 会形成毒消息", "重试用延迟队列 + 计数", "达到上限后落入 DLQ 人工处理"],
    memoryHook: "退避重试有限，最终落 DLQ",
    fileName: "rabbitmq-dlq.ts",
    code: `import amqp from "amqplib";\n\nconst conn = await amqp.connect("amqp://localhost");\nconst ch = await conn.createChannel();\n\nawait ch.assertExchange("orders.dlx", "fanout", { durable: true });\nawait ch.assertQueue("orders.dlq", { durable: true });\nawait ch.bindQueue("orders.dlq", "orders.dlx", "");\n\nawait ch.assertQueue("orders.work", {\n  durable: true,\n  arguments: {\n    "x-dead-letter-exchange": "orders.dlx",\n    "x-delivery-limit": 5\n  }\n});\n\nawait ch.consume("orders.work", async (msg) => {\n  if (!msg) return;\n  try {\n    await handleOrder(JSON.parse(msg.content.toString()));\n    ch.ack(msg);\n  } catch (err) {\n    ch.reject(msg, false);\n  }\n});`,
    prompt: "消费者反复处理同一条消息失败，最合理的兜底策略是？",
    correct: "配置 DLX + 重试上限，超限后进入 DLQ 由人工/补偿流程处理",
    wrong: "捕获异常后 requeue=true，让 broker 一直重投直到某次成功",
    output: "message routed to orders.dlq after 5 retries",
    lanes: ["消费失败", "延迟重试", "落入 DLQ"],
    laneValues: ["reject requeue=false", "重试计数+1", "超限进入 orders.dlq"],
    log: ["消费失败 reject", "重试次数达到 5", "消息路由到 orders.dlq"],
    summary: ["无限 requeue 是生产事故的常见根因", "DLX + 计数是标准兜底", "DLQ 消息需要独立监控与处理流程"],
    sourceTitle: "RabbitMQ Dead Letter Exchanges",
    sourceUrl: "https://www.rabbitmq.com/dlx.html"
  }),
  createServerLesson({
    id: "server-message-queue-concurrency-ordering",
    stageId: "server-message-queue",
    order: 6,
    eyebrowStage: eyebrow,
    title: "消费者并发与顺序性",
    concept: "Kafka 顺序性只在单个 partition 内保证，若业务需要“同一订单事件严格有序”，就要把该订单的 key hash 到固定 partition。RabbitMQ 用 single active consumer 或按 hash 路由到不同 queue 达到同等效果，纯并发会打乱顺序。",
    points: ["Kafka 顺序限定 partition 内", "同 key hash 到同 partition", "并发数不能超越顺序边界"],
    memoryHook: "同 Key 同分区，顺序才成立",
    fileName: "ordered-consumer.ts",
    code: `import { Kafka, Partitioners } from "kafkajs";\n\nconst kafka = new Kafka({ clientId: "orders", brokers: ["broker:9092"] });\nconst producer = kafka.producer({ createPartitioner: Partitioners.DefaultPartitioner });\n\nawait producer.connect();\nawait producer.send({\n  topic: "orders.events",\n  messages: [\n    { key: "order-10086", value: JSON.stringify({ step: "created" }) },\n    { key: "order-10086", value: JSON.stringify({ step: "paid" }) },\n    { key: "order-10086", value: JSON.stringify({ step: "shipped" }) }\n  ]\n});\n\nconsole.log("all events for order-10086 land on the same partition");`,
    prompt: "业务要求“同一订单事件严格按创建→支付→发货顺序消费”，最简洁的方案是？",
    correct: "以 orderId 作为 message key，让同一订单的事件落到同一 partition 顺序消费",
    wrong: "在消费者里加分布式锁，串行处理所有订单事件",
    output: "all events for order-10086 land on the same partition",
    lanes: ["设置 key", "hash 分区", "顺序消费"],
    laneValues: ["key=order-10086", "partition=2", "created→paid→shipped"],
    log: ["三条事件同 key 发送", "都落到 partition 2", "消费顺序 created→paid→shipped"],
    summary: ["顺序性靠 key 路由而非全局锁", "并发上限由 partition 决定", "跨 partition 无顺序保证"],
    sourceTitle: "Kafka Design: Message Ordering",
    sourceUrl: "https://docs.confluent.io/kafka/design/index.html"
  }),
  createServerLesson({
    id: "server-message-queue-backpressure",
    stageId: "server-message-queue",
    order: 7,
    eyebrowStage: eyebrow,
    title: "Backpressure 与流量控制",
    concept: "消费者处理慢于生产速度时，broker 侧会堆积，最终 OOM 或磁盘打满。生产做法是限制单次拉取批量、使用 prefetch/max.poll.records 控制在飞消息数，配合信号量/队列水位主动拒绝上游。",
    points: ["prefetch 控制在飞消息数", "限批避免消费者 OOM", "背压要向上游反馈拒绝"],
    memoryHook: "喝多少舀多少，不然会呛到",
    fileName: "backpressure.ts",
    code: `import amqp from "amqplib";\n\nconst conn = await amqp.connect("amqp://localhost");\nconst ch = await conn.createChannel();\n\nawait ch.prefetch(32);\nawait ch.assertQueue("orders.work", { durable: true });\n\nlet inFlight = 0;\nawait ch.consume("orders.work", async (msg) => {\n  if (!msg) return;\n  inFlight++;\n  try {\n    await handleOrder(JSON.parse(msg.content.toString()));\n    ch.ack(msg);\n  } finally {\n    inFlight--;\n    if (inFlight > 24) console.warn("backpressure: inFlight=", inFlight);\n  }\n});`,
    prompt: "消费者线上偶发 OOM，监控发现队列积压持续增长，第一步该调整什么？",
    correct: "降低 prefetch / max.poll.records，控制在飞消息数并观察是否稳定",
    wrong: "关掉 ack 让 broker 不再等待，减少内存等待时间",
    output: "backpressure: inFlight= 25",
    lanes: ["设置 prefetch", "拉取消息", "触发背压"],
    laneValues: ["prefetch=32", "并发处理 24 条", "inFlight>24 告警"],
    log: ["prefetch 设为 32", "并发处理 24 条", "触发背压告警"],
    summary: ["prefetch/poll 是背压第一道闸门", "在飞消息数要观测告警", "上游必须能感知拒绝信号"],
    sourceTitle: "RabbitMQ Consumer Prefetch",
    sourceUrl: "https://www.rabbitmq.com/consumer-prefetch.html"
  }),
  createServerLesson({
    id: "server-message-queue-messaging-patterns",
    stageId: "server-message-queue",
    order: 8,
    eyebrowStage: eyebrow,
    title: "事件驱动 / CQRS / Event Sourcing",
    concept: "event-driven 用事件解耦服务；CQRS 把读写模型分离，写入命令、读用投影；event sourcing 更进一步——事件本身是唯一真源，状态通过 replay 事件重建。三者层次递进，需要按业务复杂度选型。",
    points: ["event-driven 解耦生产/消费", "CQRS 分离读写模型", "event sourcing 用事件作真源"],
    memoryHook: "解耦→分离→溯源，逐层进阶",
    fileName: "event-sourcing.ts",
    code: `type OrderEvent =\n  | { type: "OrderCreated"; id: string; items: string[] }\n  | { type: "OrderPaid"; id: string; amount: number }\n  | { type: "OrderShipped"; id: string; tracking: string };\n\ntype OrderState = { id: string; status: string; amount?: number };\n\nfunction reduce(state: OrderState | undefined, event: OrderEvent): OrderState {\n  switch (event.type) {\n    case "OrderCreated": return { id: event.id, status: "created" };\n    case "OrderPaid":    return { ...state!, status: "paid", amount: event.amount };\n    case "OrderShipped": return { ...state!, status: "shipped" };\n  }\n}\n\nconst events: OrderEvent[] = await loadEvents("order-10086");\nconst view = events.reduce<OrderState | undefined>(reduce, undefined);\nconsole.log(view);`,
    prompt: "系统需要“任意时间点回放订单历史 + 审计每一步状态变化”，最合适的模式是？",
    correct: "采用 event sourcing，把事件作为唯一真源，用 replay 重建任意时刻状态",
    wrong: "在数据库表加 status 字段并写触发器记录旧值",
    output: "{ id: 'order-10086', status: 'shipped', amount: 99 }",
    lanes: ["加载事件流", "reduce 重建", "输出投影"],
    laneValues: ["events.length=3", "reduce 顺序应用", "status=shipped"],
    log: ["加载 3 条订单事件", "顺序 reduce 计算状态", "投影 status=shipped"],
    summary: ["event-driven 是入门层解耦", "CQRS 拆分读写解决扩展性", "event sourcing 提供审计与时间旅行"],
    sourceTitle: "microservices.io: Event Sourcing",
    sourceUrl: "https://microservices.io/patterns/data/event-sourcing.html"
  })
];

const project = createServerStageProject({
  id: "server-message-queue-project",
  stageId: "server-message-queue",
  eyebrowStage: eyebrow,
  title: "高可靠订单事件流水线",
  brief: "构建一条订单事件流水线：订单服务用 Kafka transactional producer 写入 `orders.events` → 计费服务 at-least-once 消费并幂等落库 → 失败进入 DLQ 由补偿服务处理 → 全链路记录 offset、trace 与积压指标。",
  concept: "串联本阶段：分区/消费者组、offset 管理、EOS 事务、DLQ 重试、顺序性、背压与消息模式，形成一条端到端可回溯的订单事件流水线。",
  points: ["以 orderId 作 key 保证顺序", "transactional producer 保证多 topic 原子写入", "DLQ + 指标构成可观测兜底"],
  memoryHook: "分区顺序 + 事务闭环 + DLQ 兜底",
  fileName: "order-pipeline.ts",
  code: `import { Kafka } from "kafkajs";\nimport { withIdempotency } from "./idempotency";\nimport { pushToDlq } from "./dlq";\n\nconst kafka = new Kafka({ clientId: "orders", brokers: ["broker:9092"] });\nconst producer = kafka.producer({ idempotent: true, transactionalId: "orders-tx" });\nconst consumer = kafka.consumer({ groupId: "billing-worker" });\n\nawait producer.connect();\nawait consumer.connect();\nawait consumer.subscribe({ topic: "orders.events", fromBeginning: false });\n\nexport async function publishOrderPaid(orderId: string, amount: number) {\n  const tx = await producer.transaction();\n  try {\n    await tx.send({\n      topic: "orders.events",\n      messages: [{ key: orderId, value: JSON.stringify({ type: "OrderPaid", orderId, amount }) }]\n    });\n    await tx.commit();\n  } catch (err) {\n    await tx.abort();\n    throw err;\n  }\n}\n\nawait consumer.run({\n  autoCommit: false,\n  eachMessage: async ({ topic, partition, message }) => {\n    const event = JSON.parse(message.value!.toString());\n    try {\n      await withIdempotency(\`billing:\${event.orderId}:\${message.offset}\`, () => chargeCard(event));\n      await consumer.commitOffsets([\n        { topic, partition, offset: (BigInt(message.offset) + 1n).toString() }\n      ]);\n    } catch (err) {\n      await pushToDlq({ topic, partition, offset: message.offset, event, error: String(err) });\n      await consumer.commitOffsets([\n        { topic, partition, offset: (BigInt(message.offset) + 1n).toString() }\n      ]);\n    }\n  }\n});`,
  prompt: "订单流水线里最容易被忽视但最伤业务的失败模式是？",
  correct: "消费者持续处理毒消息导致 offset 卡死、下游数据不一致且积压持续增长",
  wrong: "偶发的一次网络抖动导致某条消息延迟到达",
  correctFeedback: "正确：毒消息 + 无 DLQ 是生产事故的高发根因，必须靠重试上限与 DLQ 兜底。",
  wrongFeedback: "错误：偶发抖动由 broker 与消费者重试即可覆盖，不是最伤业务的模式。",
  additionalWrong: {
    label: "producer 偶尔重复写入一条消息，被下游多算了一次金额",
    feedback: "错误：这类问题在开启 idempotent + 事务 + 消费端幂等后基本能覆盖，不是最难处理的失败模式。"
  },
  lanes: ["事务写入", "消费落库", "DLQ 兜底"],
  laneValues: ["tx.send orders.events", "withIdempotency 计费", "毒消息进入 DLQ"],
  log: ["事务写入 OrderPaid", "幂等计费成功并提交 offset", "毒消息写入 orders.dlq"],
  summary: ["顺序性靠 key 与 partition 保证", "at-least-once + 幂等等价于业务侧 EOS", "DLQ 与指标是流水线的最后防线"],
  sourceTitle: "Kafka Documentation",
  sourceUrl: "https://kafka.apache.org/documentation/"
});

export const serverEngineeringStageSixMessageQueueLessons: LessonSpec[] = [...knowledgeLessons, project];
