import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "分布式数据与一致性";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-distributed-data-cap-tradeoffs",
    stageId: "server-distributed-data",
    order: 1,
    eyebrowStage: eyebrow,
    title: "CAP 定理与工程权衡",
    concept: "CAP 定理指出：网络分区发生时，系统只能在一致性（C）与可用性（A）之间二选一。工程上不是 CP/AP 二元对立，而是按业务边界选择：支付/库存倾向 CP，Feed/推荐倾向 AP，且大部分系统在无分区时同时提供 C 和 A。",
    points: ["分区发生时才在 C 与 A 之间取舍", "支付/库存偏 CP，Feed/推荐偏 AP", "无分区时可同时提供 C 和 A"],
    memoryHook: "分区时才二选一，无分区可兼得",
    fileName: "cap-tradeoffs.ts",
    code: `type WriteMode = \"strong\" | \"eventual\";\n\nfunction pickMode(businessKind: \"payment\" | \"feed\" | \"cart\"): WriteMode {\n  // 支付类：宁可拒写，也要保证一致\n  if (businessKind === \"payment\") return \"strong\";\n  // Feed 类：可短暂不一致，但要保证可用\n  if (businessKind === \"feed\") return \"eventual\";\n  // 购物车：容忍最终一致，UI 层做合并\n  return \"eventual\";\n}\n\nasync function writeOrder(orderId: string, mode: WriteMode) {\n  if (mode === \"strong\") {\n    // 走多数派同步复制，分区时可能返回 503\n    return quorumWrite(orderId);\n  }\n  // 主节点写入即返回，异步同步到其它副本\n  return leaderWrite(orderId);\n}\n\nconsole.log(pickMode(\"payment\"));`,
    prompt: "在网络分区期间要求支付服务能同时保证强一致与高可用，这个目标可行吗？",
    correct: "不可行，分区时 C 和 A 只能取其一，支付业务应选择拒写以保 C",
    wrong: "只要机器足够多、副本足够快，就能同时满足 C 和 A",
    output: "strong",
    lanes: ["识别业务类型", "选择一致性模式", "写入策略"],
    laneValues: ["payment", "strong", "quorumWrite"],
    log: ["业务类型=payment", "选择 strong 模式", "触发 quorumWrite 多数派同步"],
    summary: ["CAP 只在分区期间才是取舍问题", "业务类型决定 CP/AP 倾向", "无分区场景 C 与 A 可同时成立"],
    sourceTitle: "Patterns of Distributed Systems",
    sourceUrl: "https://martinfowler.com/articles/patterns-of-distributed-systems/"
  }),
  createServerLesson({
    id: "server-distributed-data-sharding-key",
    stageId: "server-distributed-data",
    order: 2,
    eyebrowStage: eyebrow,
    title: "分片键与 Hash/Range 策略",
    concept: "分片把数据按 key 打散到多个节点。Hash 分片写入均匀但不利于范围扫描，Range 分片支持范围查询但易出现热点。分片键一旦选定极难变更，选择时优先看主查询模式与热点分布。",
    points: ["Hash 分片写入均匀但难范围扫描", "Range 分片支持范围查询但易热点", "分片键要匹配主查询模式"],
    memoryHook: "Hash 均匀无范围，Range 有序易热点",
    fileName: "sharding.ts",
    code: `import crypto from \"node:crypto\";\n\nconst SHARDS = 16;\n\nfunction hashShard(key: string): number {\n  const digest = crypto.createHash(\"md5\").update(key).digest();\n  return digest.readUInt32BE(0) % SHARDS;\n}\n\nfunction rangeShard(userId: number): number {\n  // 按 userId 区间划分，便于\"某段用户\"批量扫描\n  if (userId < 1_000_000) return 0;\n  if (userId < 5_000_000) return 1;\n  return 2;\n}\n\nconst orderId = \"order-\" + Date.now();\nconsole.log(\"hash shard =\", hashShard(orderId));\nconsole.log(\"range shard =\", rangeShard(4_200_000));`,
    prompt: "订单表主要查询是\"按 user_id 查该用户所有订单\"，分片键最合适的选择是？",
    correct: "选用 user_id 做分片键，保证同一用户订单落在同一分片，避免跨分片 fan-out",
    wrong: "选用 order_id 时间戳，写入更均匀，反正后续可以再迁移分片键",
    output: "hash shard = 7\nrange shard = 1",
    lanes: ["选择分片键", "决定分片策略", "路由到分片"],
    laneValues: ["user_id", "hash", "shard=7"],
    log: ["选择分片键=user_id", "策略=hash 均匀分布", "路由到 shard=7"],
    summary: ["分片键决定后续所有查询的形状", "Hash 抗热点但牺牲范围查询", "分片键几乎不可迁移，选前先看主 query"],
    sourceTitle: "MongoDB Sharding 官方文档",
    sourceUrl: "https://docs.mongodb.com/manual/sharding/"
  }),
  createServerLesson({
    id: "server-distributed-data-replication-lag",
    stageId: "server-distributed-data",
    order: 3,
    eyebrowStage: eyebrow,
    title: "主从复制与延迟",
    concept: "主从复制分同步（sync）和异步（async）：同步复制保证从库和主库一致，但主库写延迟等于最慢从库；异步复制主库写完即返回，副本可能存在延迟（replication lag），读从库可能读到旧数据。",
    points: ["sync 复制强一致但主库写延迟高", "async 复制吞吐好但存在 lag", "读从库要考虑 read-your-write 语义"],
    memoryHook: "同步保一致，异步保吞吐，读从需防旧",
    fileName: "replication.ts",
    code: `type Row = { id: number; version: number; value: string };\n\nasync function writePrimary(row: Row) {\n  await primaryDb.query(\"UPDATE t SET value=$1, version=version+1 WHERE id=$2\", [row.value, row.id]);\n  return row.version + 1;\n}\n\nasync function readWithFreshness(id: number, minVersion: number) {\n  // 从库可能存在 replication lag，需比对 version\n  const row = await replicaDb.query(\"SELECT version, value FROM t WHERE id=$1\", [id]);\n  if (row.version < minVersion) {\n    // fallback：回主库读，保证 read-your-write\n    return primaryDb.query(\"SELECT version, value FROM t WHERE id=$1\", [id]);\n  }\n  return row;\n}\n\nconst v = await writePrimary({ id: 1, version: 3, value: \"paid\" });\nconst r = await readWithFreshness(1, v);\nconsole.log(r);`,
    prompt: "用户提交订单后立刻刷新订单列表却看不到，最可能的原因是？",
    correct: "读请求打到了异步复制的从库，存在 replication lag，需回主库或按 version 兜底",
    wrong: "主库写入失败，只是没抛错，需要在业务层加重试即可",
    output: "{ version: 4, value: 'paid' }",
    lanes: ["主库写入", "复制到从库", "版本校验读"],
    laneValues: ["writePrimary", "async replicate", "version>=4"],
    log: ["写入主库 version=4", "异步复制到从库", "从库 version<4 回退主库"],
    summary: ["async 复制的 lag 是常态而不是异常", "read-your-write 要用 version/时间戳兜底", "关键业务读写路径应显式指定主库"],
    sourceTitle: "PostgreSQL High Availability 官方文档",
    sourceUrl: "https://www.postgresql.org/docs/current/high-availability.html"
  }),
  createServerLesson({
    id: "server-distributed-data-raft-consensus",
    stageId: "server-distributed-data",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Raft 共识算法",
    concept: "Raft 通过 Leader 选举 + 日志复制达成多数派共识：任何写入必须被多数节点复制成功才 commit。相比 Paxos 更易理解与实现，广泛用于 etcd、Consul、TiKV 等系统。",
    points: ["Leader 唯一负责接收写入", "写入需多数派 append 才 commit", "任期号（term）用于识别过期 Leader"],
    memoryHook: "选主 + 日志复制 + 多数派 = Raft",
    fileName: "raft.ts",
    code: `type LogEntry = { term: number; index: number; cmd: string };\n\nclass RaftNode {\n  term = 0;\n  role: \"leader\" | \"follower\" | \"candidate\" = \"follower\";\n  log: LogEntry[] = [];\n  commitIndex = 0;\n\n  async appendEntries(entry: LogEntry, followers: RaftNode[]) {\n    this.log.push(entry);\n    // 只有多数派确认才推进 commitIndex\n    const acks = await Promise.all(followers.map((f) => f.replicate(entry)));\n    const success = acks.filter(Boolean).length + 1; // +1 = 自己\n    if (success > (followers.length + 1) / 2) {\n      this.commitIndex = entry.index;\n      return \"committed\";\n    }\n    return \"pending\";\n  }\n\n  async replicate(entry: LogEntry): Promise<boolean> {\n    this.log.push(entry);\n    return true;\n  }\n}\n\nconst leader = new RaftNode();\nleader.role = \"leader\";\nconst status = await leader.appendEntries({ term: 1, index: 1, cmd: \"SET x=1\" }, [new RaftNode(), new RaftNode()]);\nconsole.log(status);`,
    prompt: "Raft 集群 5 节点，其中 2 台宕机，还能继续对外提供写服务吗？",
    correct: "能，5 节点多数派是 3，剩余 3 节点仍可选主并复制日志达成 commit",
    wrong: "不能，只要有节点宕机 Raft 就会拒绝所有写入以保证一致性",
    output: "committed",
    lanes: ["Leader 接收写入", "多数派复制", "推进 commit"],
    laneValues: ["append cmd=SET x=1", "2/3 副本 ACK", "commitIndex=1"],
    log: ["Leader 追加日志 index=1", "2 个 follower 完成复制", "多数派达成 commitIndex=1"],
    summary: ["写入必须多数派 ACK 才 commit", "n 节点集群可容忍 (n-1)/2 故障", "term 用于识别脑裂后的过期 Leader"],
    sourceTitle: "Raft 官方站点",
    sourceUrl: "https://raft.github.io/"
  }),
  createServerLesson({
    id: "server-distributed-data-distributed-transactions",
    stageId: "server-distributed-data",
    order: 5,
    eyebrowStage: eyebrow,
    title: "分布式事务：2PC vs Saga vs TCC",
    concept: "2PC 强一致但阻塞、单点协调器脆弱；Saga 通过一系列本地事务 + 补偿实现最终一致，适合长事务；TCC（Try/Confirm/Cancel）在业务层做资源预留和确认，一致性介于两者之间。",
    points: ["2PC 强一致但同步阻塞", "Saga 用补偿达成最终一致", "TCC 通过业务预留降低锁粒度"],
    memoryHook: "2PC 阻塞强一致，Saga 补偿最终一致，TCC 预留",
    fileName: "distributed-tx.ts",
    code: `type SagaStep<T> = {\n  action: () => Promise<T>;\n  compensate: (result: T) => Promise<void>;\n};\n\nasync function runSaga<T>(steps: SagaStep<T>[]) {\n  const done: { step: SagaStep<T>; result: T }[] = [];\n  try {\n    for (const step of steps) {\n      const result = await step.action();\n      done.push({ step, result });\n    }\n    return \"committed\";\n  } catch (err) {\n    // 逆序补偿已执行的步骤\n    for (const { step, result } of done.reverse()) {\n      await step.compensate(result);\n    }\n    throw err;\n  }\n}\n\nconst status = await runSaga([\n  { action: async () => reserveInventory(\"SKU-1\"), compensate: async (id) => releaseInventory(id) },\n  { action: async () => chargePayment(100), compensate: async (id) => refundPayment(id) },\n  { action: async () => createShipment(), compensate: async (id) => cancelShipment(id) }\n]);\nconsole.log(status);`,
    prompt: "跨订单/库存/支付/物流四个服务的下单流程，最合适的分布式事务方案是？",
    correct: "用 Saga：每步本地事务 + 反向补偿，避免长时间跨服务锁",
    wrong: "用 2PC 保证 ACID，让协调器锁定四个服务直到全部提交",
    output: "committed",
    lanes: ["执行 Saga 步骤", "记录已提交", "失败触发补偿"],
    laneValues: ["reserve/charge/ship", "3 步完成", "无需补偿"],
    log: ["执行 reserveInventory", "执行 chargePayment", "执行 createShipment 全部成功"],
    summary: ["2PC 保证强一致但代价是阻塞与单点", "Saga 用业务补偿换取吞吐", "TCC 通过 Try 预留降低事务粒度"],
    sourceTitle: "Microservices.io: Saga Pattern",
    sourceUrl: "https://microservices.io/patterns/data/saga.html"
  }),
  createServerLesson({
    id: "server-distributed-data-crdt-lww",
    stageId: "server-distributed-data",
    order: 6,
    eyebrowStage: eyebrow,
    title: "最终一致与冲突解决",
    concept: "最终一致系统必须定义冲突合并策略。LWW（Last-Write-Wins）用时间戳择优，简单但会丢更新；CRDT（Conflict-free Replicated Data Type）通过数学性质（交换律/幂等律/结合律）保证任意合并顺序结果一致。",
    points: ["LWW 简单但会覆盖并发更新", "CRDT 用代数性质做无冲突合并", "购物车/计数场景优先考虑 CRDT"],
    memoryHook: "LWW 择时丢更新，CRDT 交换律不丢",
    fileName: "crdt.ts",
    code: `// G-Counter：只增计数器，合并即取每节点最大值\nclass GCounter {\n  state: Record<string, number> = {};\n\n  increment(nodeId: string, delta = 1) {\n    this.state[nodeId] = (this.state[nodeId] ?? 0) + delta;\n  }\n\n  value(): number {\n    return Object.values(this.state).reduce((a, b) => a + b, 0);\n  }\n\n  merge(other: GCounter) {\n    for (const [node, count] of Object.entries(other.state)) {\n      this.state[node] = Math.max(this.state[node] ?? 0, count);\n    }\n  }\n}\n\nconst a = new GCounter();\nconst b = new GCounter();\na.increment(\"node-a\", 3);\nb.increment(\"node-b\", 5);\na.merge(b);\nb.merge(a);\nconsole.log(a.value(), b.value());`,
    prompt: "多端购物车在离线场景下并发添加了不同商品，同步时用哪种策略最不容易丢数据？",
    correct: "用 CRDT（如 OR-Set）保证并发添加/删除可无冲突合并，避免 LWW 的覆盖问题",
    wrong: "使用 LWW 时间戳最新的版本覆盖，简单又高效",
    output: "8 8",
    lanes: ["本地各自更新", "交换副本", "合并收敛"],
    laneValues: ["a=3, b=5", "merge()", "value=8"],
    log: ["node-a 增 3", "node-b 增 5", "双向 merge 后一致 value=8"],
    summary: ["LWW 只是最简单最粗暴的策略", "CRDT 用数学保证任意合并顺序等价", "购物车/计数/文档协作优先 CRDT"],
    sourceTitle: "Patterns of Distributed Systems",
    sourceUrl: "https://martinfowler.com/articles/patterns-of-distributed-systems/"
  }),
  createServerLesson({
    id: "server-distributed-data-idempotency-key",
    stageId: "server-distributed-data",
    order: 7,
    eyebrowStage: eyebrow,
    title: "幂等性设计",
    concept: "网络重试是分布式系统的常态，写接口必须幂等：客户端传 Idempotency-Key，服务端首次执行并记录结果，重复请求返回上次结果而非再次执行。Key 应有 TTL，覆盖典型重试窗口。",
    points: ["写接口必须接受 Idempotency-Key", "首次执行落表，后续查表返回", "Key 需有 TTL 且覆盖重试窗口"],
    memoryHook: "带 Key 存结果，重试查而不做",
    fileName: "idempotency.ts",
    code: `import type { RedisClientType } from \"redis\";\n\nasync function chargeIdempotent(\n  redis: RedisClientType,\n  key: string,\n  charge: () => Promise<{ txId: string }>\n) {\n  const cached = await redis.get(\`idem:\${key}\`);\n  if (cached) return JSON.parse(cached) as { txId: string };\n\n  // SET NX 抢占：并发重试只有一个能真正执行\n  const locked = await redis.set(\`idem:lock:\${key}\`, \"1\", { NX: true, EX: 30 });\n  if (!locked) throw new Error(\"processing\");\n\n  const result = await charge();\n  await redis.set(\`idem:\${key}\`, JSON.stringify(result), { EX: 24 * 3600 });\n  return result;\n}\n\nconst r1 = await chargeIdempotent(redis, \"order-1001\", async () => ({ txId: \"tx-1\" }));\nconst r2 = await chargeIdempotent(redis, \"order-1001\", async () => ({ txId: \"tx-2\" }));\nconsole.log(r1.txId === r2.txId);`,
    prompt: "支付网关超时后客户端自动重试，服务端已经扣款但没返回，应该如何避免二次扣款？",
    correct: "服务端按 Idempotency-Key 查缓存，命中即返回首次结果，不再执行扣款",
    wrong: "在客户端做本地 flag 防止重复点击，就能避免服务端二次执行",
    output: "true",
    lanes: ["查 Key 缓存", "抢占执行锁", "落库并缓存结果"],
    laneValues: ["idem:order-1001", "SET NX 成功", "缓存 txId"],
    log: ["首次请求未命中缓存", "抢占锁成功执行扣款", "重试请求命中缓存返回 tx-1"],
    summary: ["幂等 Key 是重试安全的基础", "首次结果要落持久存储", "Key TTL 需覆盖客户端最大重试窗口"],
    sourceTitle: "Patterns of Distributed Systems",
    sourceUrl: "https://martinfowler.com/articles/patterns-of-distributed-systems/"
  }),
  createServerLesson({
    id: "server-distributed-data-backup-pitr",
    stageId: "server-distributed-data",
    order: 8,
    eyebrowStage: eyebrow,
    title: "备份与灾难恢复",
    concept: "完整的灾备包含：全量快照 + 增量 WAL 归档，支持 PITR（Point-in-Time Recovery）恢复到任意时刻；跨 Region 副本抵御机房级故障。RTO/RPO 是灾备设计的核心 SLO，需定期演练 restore。",
    points: ["全量快照 + WAL 归档支持 PITR", "跨 Region 副本抵御机房故障", "定期演练 restore 验证有效性"],
    memoryHook: "有备份不算数，恢复成功才算数",
    fileName: "backup.ts",
    code: `type BackupPlan = {\n  fullBackupCron: string; // 每日全量\n  walArchiveIntervalSec: number; // 增量 WAL 频率\n  crossRegion: string[]; // 跨 Region 副本目标\n  rtoMinutes: number; // 恢复时间目标\n  rpoSeconds: number; // 数据丢失容忍\n};\n\nconst plan: BackupPlan = {\n  fullBackupCron: \"0 3 * * *\",\n  walArchiveIntervalSec: 60,\n  crossRegion: [\"cn-north-1\", \"cn-south-1\"],\n  rtoMinutes: 30,\n  rpoSeconds: 60\n};\n\nasync function restoreToPointInTime(target: Date) {\n  const baseSnapshot = await findLatestSnapshotBefore(target);\n  await restoreSnapshot(baseSnapshot);\n  await replayWalUntil(target);\n  return \`restored to \${target.toISOString()}\`;\n}\n\nconsole.log(await restoreToPointInTime(new Date(\"2026-01-01T12:00:00Z\")));`,
    prompt: "数据库因为误操作在 10:15 被 DROP TABLE，PITR 恢复的正确步骤是？",
    correct: "先恢复 10:15 之前最近的全量快照，再回放 WAL 到 10:14:59 停止",
    wrong: "直接切到从库继续提供服务，误操作已经通过复制传播到从库",
    output: "restored to 2026-01-01T12:00:00.000Z",
    lanes: ["查找基准快照", "还原全量数据", "回放 WAL 到目标点"],
    laneValues: ["找最近快照", "restoreSnapshot", "replay WAL"],
    log: ["定位 10:00 全量快照", "还原快照数据", "回放 WAL 到 10:14:59"],
    summary: ["PITR = 全量快照 + 增量 WAL 回放", "跨 Region 副本是机房级故障的兜底", "未演练的备份等于没有备份"],
    sourceTitle: "PostgreSQL High Availability 官方文档",
    sourceUrl: "https://www.postgresql.org/docs/current/high-availability.html"
  })
];

const project = createServerStageProject({
  id: "server-distributed-data-project",
  stageId: "server-distributed-data",
  eyebrowStage: eyebrow,
  title: "分片 + 幂等的订单系统",
  brief: "构建一个订单系统：按 user_id 分片路由 → 幂等 Key 防重复下单 → Saga 编排跨服务事务 → WAL + 快照支持 PITR，形成可对外交付的分布式数据骨架。",
  concept: "串联本阶段知识点：分片路由、幂等接口、Saga 事务、PITR 备份，形成一个可上线的分布式订单系统雏形。",
  points: ["按 user_id 一致性哈希路由分片", "Idempotency-Key 防止重复扣款", "Saga 编排订单/库存/支付/物流"],
  memoryHook: "分片路由 + 幂等 Key + Saga 补偿 = 生产订单系统",
  fileName: "order-system.ts",
  code: `import type { RedisClientType } from \"redis\";\n\nconst SHARDS = 16;\nfunction routeShard(userId: string): number {\n  let h = 0;\n  for (const c of userId) h = (h * 31 + c.charCodeAt(0)) >>> 0;\n  return h % SHARDS;\n}\n\ntype PlaceOrderInput = {\n  userId: string;\n  sku: string;\n  amount: number;\n  idempotencyKey: string;\n};\n\nexport async function placeOrder(input: PlaceOrderInput, redis: RedisClientType) {\n  // 1) 幂等短路\n  const cached = await redis.get(\`idem:\${input.idempotencyKey}\`);\n  if (cached) return JSON.parse(cached);\n\n  // 2) 路由到用户所在分片\n  const shard = routeShard(input.userId);\n  const db = getShardDb(shard);\n\n  // 3) Saga 编排跨服务事务\n  const done: Array<() => Promise<void>> = [];\n  try {\n    const order = await db.insertOrder(input);\n    done.push(async () => db.cancelOrder(order.id));\n\n    const reserve = await reserveInventory(input.sku, 1);\n    done.push(async () => releaseInventory(reserve.id));\n\n    const tx = await chargePayment(input.userId, input.amount);\n    done.push(async () => refundPayment(tx.id));\n\n    await createShipment(order.id);\n\n    const result = { orderId: order.id, shard, txId: tx.id };\n    await redis.set(\`idem:\${input.idempotencyKey}\`, JSON.stringify(result), { EX: 24 * 3600 });\n    return result;\n  } catch (err) {\n    for (const compensate of done.reverse()) await compensate();\n    throw err;\n  }\n}\n\nconst out = await placeOrder(\n  { userId: \"u-1001\", sku: \"SKU-42\", amount: 199, idempotencyKey: \"req-9527\" },\n  redis\n);\nconsole.log(out);`,
  prompt: "订单系统的 Idempotency-Key 应该由哪一端生成？",
  correct: "由客户端生成并跨重试保持一致，服务端仅做去重和结果存储",
  wrong: "由服务端生成返回给客户端，客户端下次重试直接复用",
  correctFeedback: "正确：只有客户端能识别\"这是同一次业务意图的重试\"，服务端无法感知网络中断。",
  wrongFeedback: "错误：服务端生成的 Key 在网络中断时客户端根本收不到，重试仍然会产生新 Key 导致重复扣款。",
  additionalWrong: {
    label: "不需要 Idempotency-Key，靠数据库唯一索引就能防重",
    feedback: "错误：唯一索引只能约束到具体字段冲突，无法覆盖\"整个下单流程被完整执行两次\"这种业务级重复。"
  },
  lanes: ["幂等短路", "分片路由", "Saga 编排"],
  laneValues: ["查 idem:req-9527", "shard=7", "3 步全部完成"],
  log: ["幂等 Key 未命中缓存", "路由到 shard=7", "Saga 3 步完成并缓存结果"],
  summary: ["分片键路由是水平扩展的起点", "幂等 Key 是重试安全的底座", "Saga 用补偿抵御跨服务失败"],
  sourceTitle: "Microservices.io: Saga Pattern",
  sourceUrl: "https://microservices.io/patterns/data/saga.html"
});

export const serverEngineeringStageFiveDistributedDataLessons: LessonSpec[] = [...knowledgeLessons, project];
