import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "安全与认证";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-security-auth-oauth2-pkce",
    stageId: "server-security-auth",
    order: 1,
    eyebrowStage: eyebrow,
    title: "OAuth 2.0 授权码 + PKCE",
    concept: "OAuth 2.0 授权码流程通过 `redirect_uri` 将短寿命 `code` 交回客户端，再由后端换取 `access_token`。公共客户端（SPA/移动端）没有安全存储 client_secret，因此必须叠加 PKCE：授权请求携带 `code_challenge`，令牌请求回传 `code_verifier`，服务器校验二者匹配后才放行。",
    points: ["授权码短寿命且一次性使用", "PKCE 用 verifier/challenge 绑定客户端", "公共客户端禁止使用隐式流程"],
    memoryHook: "先 challenge 换码，再 verifier 换令牌",
    fileName: "oauth-pkce.ts",
    code: `import { createHash, randomBytes } from "node:crypto";\n\nconst codeVerifier = randomBytes(32).toString("base64url");\nconst codeChallenge = createHash("sha256").update(codeVerifier).digest("base64url");\n\nconst authorizeUrl = new URL("https://idp.example.com/authorize");\nauthorizeUrl.searchParams.set("response_type", "code");\nauthorizeUrl.searchParams.set("client_id", "spa-app");\nauthorizeUrl.searchParams.set("redirect_uri", "https://app.example.com/cb");\nauthorizeUrl.searchParams.set("code_challenge", codeChallenge);\nauthorizeUrl.searchParams.set("code_challenge_method", "S256");\n\n// 回调拿到 code 后换 token\nasync function exchange(code: string) {\n  const res = await fetch("https://idp.example.com/token", {\n    method: "POST",\n    headers: { "content-type": "application/x-www-form-urlencoded" },\n    body: new URLSearchParams({\n      grant_type: "authorization_code",\n      code,\n      client_id: "spa-app",\n      redirect_uri: "https://app.example.com/cb",\n      code_verifier: codeVerifier\n    })\n  });\n  return res.json();\n}`,
    prompt: "SPA 客户端接入 OAuth 2.0 时最安全的授权模式是？",
    correct: "使用授权码 + PKCE，让 code_verifier 绑定同一次会话",
    wrong: "使用隐式流程（response_type=token）直接从 URL 拿 access_token",
    output: "{ access_token: 'eyJhbGci...', token_type: 'Bearer', expires_in: 3600 }",
    lanes: ["生成 challenge", "换取授权码", "校验 verifier"],
    laneValues: ["challenge=abc", "code=xyz", "token 签发"],
    log: ["生成 code_verifier/challenge", "重定向后拿到 code=xyz", "verifier 校验通过签发 token"],
    summary: ["授权码流程是 OAuth 主推模式", "PKCE 是公共客户端必备加固", "隐式流程已被 IETF 建议弃用"],
    sourceTitle: "RFC 6749 - OAuth 2.0",
    sourceUrl: "https://datatracker.ietf.org/doc/html/rfc6749"
  }),
  createServerLesson({
    id: "server-security-auth-oidc-id-token",
    stageId: "server-security-auth",
    order: 2,
    eyebrowStage: eyebrow,
    title: "OpenID Connect 与 ID Token",
    concept: "OIDC 在 OAuth 2.0 之上引入 `id_token`（一个 JWT）用于身份认证。客户端通过 `iss/aud/exp/nonce` 校验签发方、受众、过期和防重放，再从 `sub` 得到稳定的用户标识。scope 中包含 `openid` 才会触发 OIDC 语义。",
    points: ["id_token 是 JWT，携带身份声明", "iss/aud/exp/nonce 必须逐项校验", "scope 必须包含 openid"],
    memoryHook: "OAuth 管授权，OIDC 管身份",
    fileName: "oidc-verify.ts",
    code: `import { createRemoteJWKSet, jwtVerify } from "jose";\n\nconst JWKS = createRemoteJWKSet(new URL("https://idp.example.com/.well-known/jwks.json"));\n\nexport async function verifyIdToken(idToken: string, expectedNonce: string) {\n  const { payload } = await jwtVerify(idToken, JWKS, {\n    issuer: "https://idp.example.com",\n    audience: "spa-app"\n  });\n\n  if (payload.nonce !== expectedNonce) {\n    throw new Error("nonce mismatch: possible replay");\n  }\n\n  return {\n    userId: payload.sub as string,\n    email: payload.email as string | undefined,\n    expiresAt: new Date((payload.exp ?? 0) * 1000)\n  };\n}`,
    prompt: "OIDC 客户端拿到 id_token 后必须完成哪一组校验？",
    correct: "验证签名并逐项校验 iss/aud/exp/nonce，再读取 sub 作为用户标识",
    wrong: "只 base64 解码 payload 拿到 sub 字段即可信任",
    output: "{ userId: 'user-8842', email: 'lee@example.com', expiresAt: 2026-07-24T12:00:00.000Z }",
    lanes: ["拉取 JWKS", "校验 claims", "识别 sub"],
    laneValues: ["JWKS 缓存命中", "iss/aud 通过", "sub=user-8842"],
    log: ["加载 JWKS", "iss/aud/exp/nonce 校验通过", "解析出 sub=user-8842"],
    summary: ["id_token 与 access_token 用途不同", "nonce 用于绑定授权请求防重放", "JWKS 应缓存并周期刷新"],
    sourceTitle: "OpenID Connect Core 1.0",
    sourceUrl: "https://openid.net/specs/openid-connect-core-1_0.html"
  }),
  createServerLesson({
    id: "server-security-auth-jwt-structure",
    stageId: "server-security-auth",
    order: 3,
    eyebrowStage: eyebrow,
    title: "JWT 结构与签名/验签",
    concept: "JWT 由 `header.payload.signature` 三段 base64url 组成。签名可用对称 HS256 或非对称 RS256/ES256；验签必须以服务器端配置的算法为准，绝不能信任 header 中的 `alg`，否则会踩 `alg=none` 与 HS/RS 混淆漏洞。",
    points: ["三段结构：header/payload/signature", "算法必须服务端锁定，不信 header", "对称密钥仅限内部服务共享"],
    memoryHook: "签名靠算法，算法不能听请求",
    fileName: "jwt-sign.ts",
    code: `import { SignJWT, jwtVerify, importPKCS8, importSPKI } from "jose";\nimport { readFileSync } from "node:fs";\n\nconst privateKey = await importPKCS8(readFileSync("./keys/private.pem", "utf8"), "RS256");\nconst publicKey = await importSPKI(readFileSync("./keys/public.pem", "utf8"), "RS256");\n\nexport async function issue(userId: string) {\n  return new SignJWT({ role: "editor" })\n    .setProtectedHeader({ alg: "RS256", kid: "2026-07" })\n    .setSubject(userId)\n    .setIssuer("https://api.example.com")\n    .setAudience("web-app")\n    .setExpirationTime("15m")\n    .sign(privateKey);\n}\n\nexport async function verify(token: string) {\n  const { payload } = await jwtVerify(token, publicKey, {\n    algorithms: ["RS256"], // 关键：锁死允许的算法\n    issuer: "https://api.example.com",\n    audience: "web-app"\n  });\n  return payload;\n}`,
    prompt: "验签 JWT 时最危险的做法是什么？",
    correct: "把 `algorithms` 显式锁定为服务端支持的集合，忽略 header.alg",
    wrong: "读取 header.alg，用它去选择对应的公钥或对称密钥进行验签",
    output: "{ sub: 'user-42', role: 'editor', iss: 'https://api.example.com', aud: 'web-app' }",
    lanes: ["载入密钥", "签发 JWT", "锁算法验签"],
    laneValues: ["RS256 私钥", "token 已签发", "algorithms=['RS256']"],
    log: ["载入 RS256 密钥对", "签发 sub=user-42 的 JWT", "锁定算法完成验签"],
    summary: ["header.alg 只是元数据不可信任", "签名密钥必须与算法家族匹配", "kid 用于密钥轮换定位"],
    sourceTitle: "RFC 7519 - JSON Web Token",
    sourceUrl: "https://www.rfc-editor.org/rfc/rfc7519"
  }),
  createServerLesson({
    id: "server-security-auth-rbac-abac",
    stageId: "server-security-auth",
    order: 4,
    eyebrowStage: eyebrow,
    title: "RBAC vs ABAC 授权模型",
    concept: "RBAC 以“角色”聚合权限，管理简单但表达力有限；ABAC 以“主体/资源/环境属性”动态判定，可表达“同部门 && 工作时间 && 非高敏”这类复合规则。生产系统常以 RBAC 打底，敏感场景叠加 ABAC 策略引擎（OPA/Cedar）。",
    points: ["RBAC 角色即权限集合", "ABAC 按属性动态判定", "复杂场景交给策略引擎"],
    memoryHook: "角色定粗粒度，属性定细粒度",
    fileName: "authorize.ts",
    code: `type Subject = { id: string; roles: string[]; dept: string };\ntype Resource = { id: string; owner: string; sensitivity: "low" | "high" };\ntype Env = { hour: number };\n\nconst rbac: Record<string, string[]> = {\n  admin: ["order:*"],\n  editor: ["order:read", "order:update"],\n  viewer: ["order:read"]\n};\n\nexport function authorize(sub: Subject, action: string, res: Resource, env: Env) {\n  // RBAC 打底\n  const allowed = sub.roles.some((r) =>\n    (rbac[r] ?? []).some((p) => p === action || p.endsWith(":*"))\n  );\n  if (!allowed) return { allow: false, reason: "rbac-denied" };\n\n  // ABAC 叠加：高敏资源仅限所有者 + 工作时间\n  if (res.sensitivity === "high") {\n    if (res.owner !== sub.id) return { allow: false, reason: "not-owner" };\n    if (env.hour < 9 || env.hour >= 19) return { allow: false, reason: "off-hours" };\n  }\n  return { allow: true };\n}`,
    prompt: "只有 RBAC 时怎么表达“同部门 + 工作时间 + 高敏资源”这类规则？",
    correct: "叠加 ABAC 用属性做二次判定，或把决策交给 OPA/Cedar 策略引擎",
    wrong: "把所有组合展开成新的角色，例如 `sales_high_workhour_reader`",
    output: "{ allow: false, reason: 'off-hours' }",
    lanes: ["RBAC 判定", "ABAC 属性检查", "输出决策"],
    laneValues: ["role=editor 命中", "sensitivity=high", "reason=off-hours"],
    log: ["RBAC 命中 order:update", "ABAC 检查所有者/时段", "决策拒绝：off-hours"],
    summary: ["RBAC 简单但难表达复合条件", "ABAC 用属性表达业务规则", "策略引擎负责规则热更新与审计"],
    sourceTitle: "OWASP Authorization Cheat Sheet",
    sourceUrl: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html"
  }),
  createServerLesson({
    id: "server-security-auth-secret-management",
    stageId: "server-security-auth",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Secret 管理（Vault/KMS/env）",
    concept: "机密不应写入代码或明文配置：`.env` 只适合本地开发，云环境使用 KMS 加密并交由 Secret Manager（Vault、AWS Secrets Manager、GCP Secret Manager）动态下发。理想做法是短寿命凭据 + 客户端只拿到 handle，运行时才解密使用。",
    points: [".env 仅限本地开发", "生产用 Vault/KMS 集中管理", "短寿命凭据 + 定期轮换"],
    memoryHook: "代码里没密钥，运行时才解密",
    fileName: "secrets.ts",
    code: `import { SecretsManagerClient, GetSecretValueCommand } from "@aws-sdk/client-secrets-manager";\n\nconst client = new SecretsManagerClient({ region: process.env.AWS_REGION });\nconst cache = new Map<string, { value: string; fetchedAt: number }>();\nconst TTL_MS = 5 * 60 * 1000;\n\nexport async function getSecret(name: string): Promise<string> {\n  const cached = cache.get(name);\n  if (cached && Date.now() - cached.fetchedAt < TTL_MS) {\n    return cached.value;\n  }\n  const res = await client.send(new GetSecretValueCommand({ SecretId: name }));\n  const value = res.SecretString ?? "";\n  cache.set(name, { value, fetchedAt: Date.now() });\n  return value;\n}\n\n// 使用示例：仅在需要时解引用，避免驻留在全局作用域\nasync function connectDb() {\n  const password = await getSecret("prod/db/password");\n  return openConnection({ user: "app", password });\n}`,
    prompt: "生产环境保存数据库密码最不可接受的做法是？",
    correct: "把密钥硬编码在仓库或明文写入 `.env` 并随镜像发布",
    wrong: "使用 KMS 加密后由 Secret Manager 下发，短 TTL 缓存",
    output: "{ secret: '****', fetchedAt: 1_753_366_400_000 }",
    lanes: ["读取 handle", "KMS 解密", "缓存 + 使用"],
    laneValues: ["SecretId=prod/db/password", "SecretString 返回", "TTL 5min"],
    log: ["请求 SecretId=prod/db/password", "KMS 解密返回明文", "写入 5min 缓存"],
    summary: ["密钥永远不进代码库", "Secret Manager 集中管理与轮换", "缓存要有 TTL 与失效兜底"],
    sourceTitle: "HashiCorp Vault Docs",
    sourceUrl: "https://developer.hashicorp.com/vault/docs"
  }),
  createServerLesson({
    id: "server-security-auth-mtls",
    stageId: "server-security-auth",
    order: 6,
    eyebrowStage: eyebrow,
    title: "TLS 双向认证 (mTLS)",
    concept: "普通 TLS 只验证服务端证书；mTLS 让服务端反过来验证客户端证书，常用于内部服务/机器身份。Node 的 `tls` 与 `https` 模块通过 `requestCert: true` 与 `rejectUnauthorized: true` 开启，客户端则通过 `cert`/`key` 提供自身证书。",
    points: ["双向证书 = 双向身份", "服务端需 requestCert + rejectUnauthorized", "证书轮换配合短有效期"],
    memoryHook: "TLS 认服务端，mTLS 双向认",
    fileName: "mtls-server.ts",
    code: `import https from "node:https";\nimport { readFileSync } from "node:fs";\n\nconst server = https.createServer({\n  key: readFileSync("./certs/server.key"),\n  cert: readFileSync("./certs/server.crt"),\n  ca: readFileSync("./certs/client-ca.crt"),\n  requestCert: true,\n  rejectUnauthorized: true\n}, (req, res) => {\n  const peer = (req.socket as import("node:tls").TLSSocket).getPeerCertificate();\n  res.writeHead(200, { "content-type": "application/json" });\n  res.end(JSON.stringify({ ok: true, peerCN: peer.subject?.CN }));\n});\n\nserver.listen(8443, () => {\n  console.log("mTLS server listening on :8443");\n});`,
    prompt: "内部服务需要相互确认调用方身份，最合适的传输层方案是？",
    correct: "启用 mTLS，服务端通过 requestCert + rejectUnauthorized 校验客户端证书",
    wrong: "只开单向 TLS，靠共享 API Key 在 header 里区分调用方",
    output: "{ ok: true, peerCN: 'orders-service' }",
    lanes: ["加载证书", "TLS 握手", "校验对端 CN"],
    laneValues: ["server.crt + ca", "requestCert=true", "peerCN=orders-service"],
    log: ["加载 server/ca 证书", "握手请求客户端证书", "校验通过 peerCN=orders-service"],
    summary: ["mTLS 提供机器身份而非仅通道加密", "客户端 CA 独立于服务端 CA", "证书应短寿命并自动轮换"],
    sourceTitle: "Node.js TLS/SSL",
    sourceUrl: "https://nodejs.org/api/tls.html"
  }),
  createServerLesson({
    id: "server-security-auth-audit-log",
    stageId: "server-security-auth",
    order: 7,
    eyebrowStage: eyebrow,
    title: "审计日志与不可篡改存储",
    concept: "审计日志用于事后取证，必须保证“写入即封存”。常见做法是以哈希链把每条记录 `hash = sha256(prev_hash + payload)` 串接，落到 append-only 存储（S3 Object Lock、WORM 磁带、Kafka 只读 topic），并把 root hash 周期性上链或签名保管。",
    points: ["记录以哈希链形成防篡改", "落 append-only / WORM 存储", "root hash 周期性外部见证"],
    memoryHook: "写不可删，改不可藏",
    fileName: "audit-chain.ts",
    code: `import { createHash } from "node:crypto";\n\ntype AuditEvent = {\n  ts: string;\n  actor: string;\n  action: string;\n  resource: string;\n};\n\ntype ChainedRecord = AuditEvent & { prevHash: string; hash: string };\n\nlet lastHash = "GENESIS";\n\nexport function append(event: AuditEvent): ChainedRecord {\n  const payload = JSON.stringify(event);\n  const hash = createHash("sha256").update(lastHash + payload).digest("hex");\n  const record: ChainedRecord = { ...event, prevHash: lastHash, hash };\n  lastHash = hash;\n  // 落到 append-only 存储（例如 S3 Object Lock / Kafka compacted=false topic）\n  auditSink.write(record);\n  return record;\n}\n\ndeclare const auditSink: { write(r: ChainedRecord): void };`,
    prompt: "运维想删除某条审计日志“修正误操作”，最应该拒绝的理由是？",
    correct: "审计存储是 append-only，任何删除都会打断哈希链、破坏事后取证的可信性",
    wrong: "允许运维用 root 权限直接改写记录，只要记录本次修改就行",
    output: "{ ts: '2026-07-24T02:11:07Z', actor: 'u-42', action: 'order.refund', hash: '9f3c...' }",
    lanes: ["构造事件", "计算哈希链", "写入 WORM"],
    laneValues: ["actor=u-42", "prevHash+payload → hash", "sink.write 成功"],
    log: ["收到 order.refund 事件", "哈希链计算完成", "写入 append-only sink"],
    summary: ["哈希链让篡改可检测", "WORM 存储让删除物理不可行", "root hash 外部见证抬升信任"],
    sourceTitle: "AWS S3 Object Lock",
    sourceUrl: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html"
  }),
  createServerLesson({
    id: "server-security-auth-owasp-top10",
    stageId: "server-security-auth",
    order: 8,
    eyebrowStage: eyebrow,
    title: "OWASP Top 10 防护",
    concept: "服务端最常见的三类漏洞：Injection（SQL/命令注入）用参数化查询与最小权限杜绝；IDOR（越权访问）在数据层强制以 `owner_id` 或行级策略过滤；SSRF（服务端伪造请求）用出站白名单 + 拒绝 127/169.254 等内网段防御。",
    points: ["Injection：参数化 + 最小权限", "IDOR：数据层强制归属校验", "SSRF：出站白名单 + 内网拒绝"],
    memoryHook: "参数化、归属查、白名单",
    fileName: "owasp-guard.ts",
    code: `import { URL } from "node:url";\nimport net from "node:net";\n\n// 1) Injection：参数化查询\nexport async function findOrder(db: any, id: string) {\n  return db.query("SELECT id, user_id, amount FROM orders WHERE id = $1", [id]);\n}\n\n// 2) IDOR：强制归属\nexport async function getOrderForUser(db: any, id: string, userId: string) {\n  const row = await db.query(\n    "SELECT * FROM orders WHERE id = $1 AND user_id = $2",\n    [id, userId]\n  );\n  if (!row) throw new Error("forbidden");\n  return row;\n}\n\n// 3) SSRF：出站白名单 + 拒绝内网\nconst ALLOWED_HOSTS = new Set(["api.partner.com", "cdn.partner.com"]);\nexport async function safeFetch(input: string) {\n  const url = new URL(input);\n  if (!ALLOWED_HOSTS.has(url.hostname)) throw new Error("host not allowed");\n  if (net.isIP(url.hostname) && url.hostname.startsWith("169.254")) {\n    throw new Error("metadata endpoint blocked");\n  }\n  return fetch(url, { redirect: "error" });\n}`,
    prompt: "同一接口既要防 SQL 注入又要防 IDOR，应如何组合？",
    correct: "参数化查询防注入，同时在 WHERE 里强制 user_id 过滤防越权",
    wrong: "只做参数化查询即可，IDOR 属于前端范畴由页面隐藏按钮解决",
    output: "{ id: 'o-88', user_id: 'u-42', amount: 129.00 }",
    lanes: ["参数化查询", "归属校验", "出站白名单"],
    laneValues: ["$1 绑定 id", "user_id=u-42", "host in ALLOWED_HOSTS"],
    log: ["执行参数化 SELECT", "user_id 匹配才返回", "出站命中白名单放行"],
    summary: ["注入靠参数化和最小权限双保险", "IDOR 必须在数据层校验归属", "SSRF 要拒绝云元数据地址"],
    sourceTitle: "OWASP Top 10",
    sourceUrl: "https://owasp.org/www-project-top-ten/"
  })
];

const project = createServerStageProject({
  id: "server-security-auth-project",
  stageId: "server-security-auth",
  eyebrowStage: eyebrow,
  title: "带 OAuth + RBAC + Audit 的 API",
  brief: "构建一个订单查询 API：OAuth 2.0 + PKCE 登录换取 JWT，网关校验签名与算法后注入用户身份，RBAC 判定操作权限，敏感读写全部落入哈希链审计日志。",
  concept: "串联本阶段知识点：OAuth/OIDC 拿身份、JWT 校验做无状态鉴权、RBAC 做授权、审计链做事后取证，形成一个可交付的安全基线。",
  points: ["登录走 OAuth + PKCE 拿 JWT", "网关锁算法校验并注入身份", "RBAC 判定 + 审计链落盘"],
  memoryHook: "认证 → 授权 → 审计，缺一不可",
  fileName: "secure-api.ts",
  code: `import express from "express";\nimport { jwtVerify, createRemoteJWKSet } from "jose";\nimport { authorize } from "./authorize";\nimport { append } from "./audit-chain";\n\nconst JWKS = createRemoteJWKSet(new URL("https://idp.example.com/.well-known/jwks.json"));\nconst app = express();\n\napp.use(async (req, res, next) => {\n  try {\n    const token = (req.headers.authorization ?? "").replace(/^Bearer\\s+/i, "");\n    const { payload } = await jwtVerify(token, JWKS, {\n      algorithms: ["RS256"], // 锁死算法\n      issuer: "https://idp.example.com",\n      audience: "orders-api"\n    });\n    (req as any).user = { id: payload.sub as string, roles: (payload.roles as string[]) ?? [] };\n    next();\n  } catch {\n    res.status(401).json({ error: "invalid_token" });\n  }\n});\n\napp.get("/orders/:id", async (req, res) => {\n  const user = (req as any).user as { id: string; roles: string[] };\n  const order = await db.getOrder(req.params.id, user.id); // IDOR 归属校验\n  const decision = authorize(\n    { id: user.id, roles: user.roles, dept: "sales" },\n    "order:read",\n    { id: order.id, owner: order.userId, sensitivity: order.sensitivity },\n    { hour: new Date().getHours() }\n  );\n\n  append({\n    ts: new Date().toISOString(),\n    actor: user.id,\n    action: "order.read",\n    resource: order.id\n  });\n\n  if (!decision.allow) return res.status(403).json({ error: decision.reason });\n  res.json(order);\n});\n\ndeclare const db: { getOrder(id: string, userId: string): Promise<any> };\napp.listen(3000);`,
  prompt: "这个 API 为什么要在 JWT 校验之后还叠加 RBAC 与审计？",
  correct: "JWT 只说明“你是谁”，RBAC 判定“能不能做”，审计确保“做过什么可追溯”",
  wrong: "只要 JWT 校验通过就代表已授权，可以直接返回数据以提升性能",
  correctFeedback: "正确：认证、授权、审计是三层独立能力，缺一都会留下攻击面或取证盲区。",
  wrongFeedback: "错误：JWT 是身份凭证，不含业务权限；跳过 RBAC 与审计等于把权限外壳全部撕掉。",
  additionalWrong: {
    label: "审计日志可以异步批量写入且允许运维覆盖，方便修正误录",
    feedback: "错误：允许覆盖会打断哈希链，审计一旦可改就失去司法与合规价值。"
  },
  lanes: ["认证校验", "授权判定", "审计落盘"],
  laneValues: ["JWT algorithms=RS256", "RBAC+ABAC 通过", "audit hash 链追加"],
  log: ["JWT 校验并注入 user", "RBAC/ABAC 判定通过", "审计事件写入哈希链"],
  summary: ["OAuth/OIDC 完成身份识别", "RBAC 叠加 ABAC 做细粒度授权", "审计链让所有敏感操作可回放"],
  sourceTitle: "OWASP Top 10",
  sourceUrl: "https://owasp.org/www-project-top-ten/"
});

export const serverEngineeringStageSevenSecurityAuthLessons: LessonSpec[] = [...knowledgeLessons, project];
