import type { LessonSpec } from "../../../lib/curriculum/types";
import { createServerLesson, createServerStageProject } from "./server-engineering-lesson-factory";

const eyebrow = "可观测性三支柱";

const knowledgeLessons: LessonSpec[] = [
  createServerLesson({
    id: "server-observability-structured-logging",
    stageId: "server-observability",
    order: 1,
    eyebrowStage: eyebrow,
    title: "结构化日志",
    concept: "结构化日志用 JSON 字段替代自由文本，让日志可被机器索引与检索。生产环境必须携带 correlation-id（trace_id / request_id），才能把同一请求跨服务的日志串起来。",
    points: ["JSON 字段替代自由文本", "correlation-id 串联跨服务日志", "级别、时间、服务名是必备字段"],
    memoryHook: "无 correlation-id 的日志 = 断线的珠子",
    fileName: "logger.ts",
    code: `import pino from \"pino\";\nimport { AsyncLocalStorage } from \"node:async_hooks\";\n\nconst als = new AsyncLocalStorage<{ traceId: string }>();\nconst logger = pino({ level: \"info\", base: { service: \"order-api\" } });\n\nexport function withTrace<T>(traceId: string, fn: () => Promise<T>) {\n  return als.run({ traceId }, fn);\n}\n\nexport function log(msg: string, extra: Record<string, unknown> = {}) {\n  const ctx = als.getStore();\n  logger.info({ trace_id: ctx?.traceId, ...extra }, msg);\n}\n\nawait withTrace(\"trace-9f2a\", async () => {\n  log(\"order.created\", { order_id: \"O-10086\", amount: 128 });\n});`,
    prompt: "生产环境的日志为什么必须携带 correlation-id？",
    correct: "只有 correlation-id 才能把同一请求在多个服务里的日志串成完整链路",
    wrong: "自由文本日志加上时间戳就足够定位问题，无需额外字段",
    output: "{\"level\":\"info\",\"service\":\"order-api\",\"trace_id\":\"trace-9f2a\",\"order_id\":\"O-10086\",\"msg\":\"order.created\"}",
    lanes: ["请求进入", "写结构化日志", "跨服务串联"],
    laneValues: ["trace-9f2a", "JSON 落盘", "按 trace_id 检索"],
    log: ["注入 trace_id=trace-9f2a", "写入 order.created", "ES 按 trace_id 聚合"],
    summary: ["JSON 结构化让日志可查询", "correlation-id 是链路串联的基础", "字段规范化优先于富文本"],
    sourceTitle: "OpenTelemetry Logs",
    sourceUrl: "https://opentelemetry.io/docs/concepts/signals/logs/"
  }),
  createServerLesson({
    id: "server-observability-prometheus-metrics",
    stageId: "server-observability",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Prometheus 指标模型",
    concept: "Prometheus 有四种基础指标：Counter 只增不减（如请求数）、Gauge 可增可减（如内存占用）、Histogram 分桶采样（如延迟分布）、Summary 客户端分位。选错类型会让告警和 SLO 直接失真。",
    points: ["Counter 累计事件次数", "Gauge 观察瞬时值", "Histogram 分桶统计分布"],
    memoryHook: "累计选 Counter，快照选 Gauge，分布选 Histogram",
    fileName: "metrics.ts",
    code: `import client from \"prom-client\";\n\nconst registry = new client.Registry();\n\nconst httpRequests = new client.Counter({\n  name: \"http_requests_total\",\n  help: \"HTTP 请求总数\",\n  labelNames: [\"method\", \"route\", \"status\"],\n  registers: [registry]\n});\n\nconst inflight = new client.Gauge({\n  name: \"http_inflight_requests\",\n  help: \"正在处理中的请求数\",\n  registers: [registry]\n});\n\nconst latency = new client.Histogram({\n  name: \"http_request_duration_seconds\",\n  help: \"HTTP 请求耗时\",\n  buckets: [0.05, 0.1, 0.3, 1, 3],\n  registers: [registry]\n});\n\nhttpRequests.inc({ method: \"GET\", route: \"/orders\", status: \"200\" });\ninflight.set(3);\nlatency.observe(0.24);`,
    prompt: "记录 P99 请求延迟应该选择哪种 Prometheus 指标类型？",
    correct: "Histogram 分桶采样，配合 histogram_quantile 在服务端聚合出 P99",
    wrong: "用 Gauge 每次覆盖成最新耗时，再取一段时间的 max",
    output: "http_request_duration_seconds_bucket{le=\"0.3\"} 1",
    lanes: ["选择指标类型", "打点采集", "PromQL 聚合"],
    laneValues: ["Histogram", "observe 0.24s", "histogram_quantile 0.99"],
    log: ["定义 Histogram buckets", "observe 0.24s 落入 le=0.3", "PromQL 输出 P99"],
    summary: ["指标类型决定后续分析能力", "Histogram 才能算分位", "Gauge 只能表达瞬时值"],
    sourceTitle: "Prometheus Metric Types",
    sourceUrl: "https://prometheus.io/docs/concepts/metric_types/"
  }),
  createServerLesson({
    id: "server-observability-opentelemetry-trace",
    stageId: "server-observability",
    order: 3,
    eyebrowStage: eyebrow,
    title: "OpenTelemetry Trace/Span",
    concept: "OpenTelemetry 用 Trace 表示一次分布式调用，Trace 由多个 Span 组成，每个 Span 有 name、start/end、attributes、parent_span_id。context 通过 W3C traceparent 头跨进程传播，才能拼出完整调用树。",
    points: ["Trace = 一次分布式调用", "Span 是最小执行单元", "traceparent 头跨服务传播 context"],
    memoryHook: "Trace 是树，Span 是节点，parent_id 连成枝",
    fileName: "trace.ts",
    code: `import { trace, context, SpanStatusCode } from \"@opentelemetry/api\";\n\nconst tracer = trace.getTracer(\"order-service\");\n\nexport async function createOrder(userId: string) {\n  return tracer.startActiveSpan(\"order.create\", async (span) => {\n    span.setAttribute(\"user.id\", userId);\n    try {\n      const child = tracer.startSpan(\"db.insert\", undefined, context.active());\n      await db.insert({ userId });\n      child.end();\n      span.setStatus({ code: SpanStatusCode.OK });\n      return { ok: true };\n    } catch (err) {\n      span.recordException(err as Error);\n      span.setStatus({ code: SpanStatusCode.ERROR });\n      throw err;\n    } finally {\n      span.end();\n    }\n  });\n}`,
    prompt: "两个 Node 服务如何让 OpenTelemetry 把请求拼成一条 Trace？",
    correct: "上游把当前 span context 编码进 W3C traceparent 头，下游解析后继续 span",
    wrong: "两边各自生成 trace_id，在日志里按时间戳对齐即可",
    output: "traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01",
    lanes: ["开启 span", "注入 traceparent", "下游延续"],
    laneValues: ["order.create", "header 注入", "child span"],
    log: ["开启 span order.create", "注入 traceparent 头", "下游拼上 db.insert"],
    summary: ["Trace/Span 描述调用结构", "context 传播是跨服务前提", "recordException 让错误上链路"],
    sourceTitle: "OpenTelemetry Concepts",
    sourceUrl: "https://opentelemetry.io/docs/concepts/"
  }),
  createServerLesson({
    id: "server-observability-use-method",
    stageId: "server-observability",
    order: 4,
    eyebrowStage: eyebrow,
    title: "USE 方法（资源视角）",
    concept: "Brendan Gregg 的 USE 方法从资源视角回答“系统健不健康”：对每个资源检查 Utilization（使用率）、Saturation（饱和度/排队）、Errors（错误数）。适合排查主机、CPU、内存、磁盘、网络。",
    points: ["Utilization 描述资源使用率", "Saturation 描述排队/饱和", "Errors 描述硬性错误计数"],
    memoryHook: "USE 是资源体检表",
    fileName: "use_dashboard.md",
    code: `# 主机资源 USE 面板\n\n## CPU\n- Utilization: rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])\n- Saturation:  node_load1 / on() count(node_cpu_seconds_total{mode=\"idle\"})\n- Errors:      rate(node_cpu_thermal_throttle_total[5m])\n\n## Memory\n- Utilization: 1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\n- Saturation:  rate(node_vmstat_pgmajfault[1m])\n- Errors:      rate(node_edac_correctable_errors_total[5m])\n\n## Disk\n- Utilization: rate(node_disk_io_time_seconds_total[1m])\n- Saturation:  node_disk_io_now\n- Errors:      rate(node_disk_read_errors_total[5m])`,
    prompt: "USE 方法最适合排查哪类问题？",
    correct: "从资源维度快速定位 CPU/内存/磁盘/网络是否达到瓶颈或出错",
    wrong: "从用户接口维度判断某个 API 的成功率和延迟是否达标",
    output: "cpu.utilization=0.87 cpu.saturation=2.4 cpu.errors=0",
    lanes: ["列举资源", "为每个资源打 USE", "组成资源面板"],
    laneValues: ["CPU/Mem/Disk", "Util/Sat/Err", "USE 仪表盘"],
    log: ["盘点资源清单", "为 CPU 采 Util/Sat/Err", "输出 USE 面板"],
    summary: ["USE 面向资源，聚焦瓶颈", "Saturation 常比 Utilization 更敏感", "Errors 是硬告警来源"],
    sourceTitle: "Brendan Gregg: The USE Method",
    sourceUrl: "https://www.brendangregg.com/usemethod.html"
  }),
  createServerLesson({
    id: "server-observability-red-method",
    stageId: "server-observability",
    order: 5,
    eyebrowStage: eyebrow,
    title: "RED 方法（服务视角）",
    concept: "RED 方法从服务视角衡量在线接口：Rate（每秒请求数）、Errors（错误率）、Duration（延迟分布）。是 USE 的对偶面，微服务和 Web API 面板首选。",
    points: ["Rate 描述吞吐", "Errors 描述失败比例", "Duration 描述延迟分布"],
    memoryHook: "USE 看资源，RED 看请求",
    fileName: "red_queries.promql",
    code: `# Rate：每秒请求数\nsum(rate(http_requests_total{job=\"order-api\"}[1m])) by (route)\n\n# Errors：错误率\nsum(rate(http_requests_total{job=\"order-api\", status=~\"5..\"}[1m])) by (route)\n/\nsum(rate(http_requests_total{job=\"order-api\"}[1m])) by (route)\n\n# Duration：P50/P99 延迟\nhistogram_quantile(0.5,\n  sum(rate(http_request_duration_seconds_bucket{job=\"order-api\"}[5m])) by (le, route))\nhistogram_quantile(0.99,\n  sum(rate(http_request_duration_seconds_bucket{job=\"order-api\"}[5m])) by (le, route))`,
    prompt: "为一个 Web API 服务搭第一块仪表盘，应该覆盖哪三类指标？",
    correct: "Rate/Errors/Duration，直接对应用户体验：多快、多准、多顺",
    wrong: "只需要主机 CPU 使用率一张图，服务健康度就能一目了然",
    output: "rate=132/s errors=0.4% p99=280ms",
    lanes: ["采集 RED 指标", "PromQL 聚合", "生成服务面板"],
    laneValues: ["counter+histogram", "rate/quantile", "RED 面板"],
    log: ["counter 累计请求", "histogram 记录延迟", "PromQL 输出 RED"],
    summary: ["RED 从用户视角衡量服务", "错误率和延迟必须一起看", "USE 与 RED 互补"],
    sourceTitle: "Google SRE Workbook: Monitoring",
    sourceUrl: "https://sre.google/workbook/monitoring/"
  }),
  createServerLesson({
    id: "server-observability-sli-slo-error-budget",
    stageId: "server-observability",
    order: 6,
    eyebrowStage: eyebrow,
    title: "SLI / SLO / Error Budget",
    concept: "SLI 是可度量的服务指标（如成功率、P99 延迟），SLO 是对 SLI 设定的目标（如 99.9%），Error Budget = 1 − SLO，是允许的“可失败预算”。预算烧完就必须减速发布、优先稳定性。",
    points: ["SLI 是可度量的服务指标", "SLO 是对 SLI 的目标值", "Error Budget 决定发布节奏"],
    memoryHook: "SLO 定目标，预算烧完就停车",
    fileName: "error_budget.ts",
    code: `const SLO = 0.999; // 30 天内 99.9% 成功率\nconst BUDGET = 1 - SLO; // 0.1%\n\nfunction errorBudgetRemaining(totalReq: number, errorReq: number) {\n  const allowedErrors = totalReq * BUDGET;\n  const consumed = errorReq / allowedErrors;\n  return { consumed, remaining: 1 - consumed };\n}\n\nconst status = errorBudgetRemaining(10_000_000, 7_000);\nconsole.log(status);\nif (status.remaining < 0.2) {\n  console.warn(\"预算不足 20%，冻结非必要发布\");\n}`,
    prompt: "Error Budget 剩余 5% 时最正确的团队动作是？",
    correct: "冻结非必要发布，把工程带宽切到稳定性修复，直到预算恢复",
    wrong: "预算还没用完，可以继续发布新功能",
    output: "{ consumed: 0.7, remaining: 0.3 } — 预算充足",
    lanes: ["定义 SLI", "设定 SLO", "跟踪预算"],
    laneValues: ["成功率 SLI", "SLO=99.9%", "剩余 30%"],
    log: ["SLI=success_rate", "SLO=99.9%", "剩余预算 30%"],
    summary: ["SLI/SLO 让稳定性可量化", "Error Budget 是发布节奏的开关", "预算耗尽必须减速"],
    sourceTitle: "Google SRE Book: Service Level Objectives",
    sourceUrl: "https://sre.google/sre-book/service-level-objectives/"
  }),
  createServerLesson({
    id: "server-observability-symptom-based-alerts",
    stageId: "server-observability",
    order: 7,
    eyebrowStage: eyebrow,
    title: "告警设计与告警疲劳",
    concept: "SRE 主张 symptom-based alerting：告警要绑定用户可感知的症状（错误率、延迟违反 SLO），而不是绑定原因（CPU 高、进程重启）。原因型告警数量爆炸、噪声大，是告警疲劳的主要根源。",
    points: ["按症状告警，不按原因告警", "告警必须可操作", "多层去重与静默控制噪声"],
    memoryHook: "告警绑症状，原因留给排障",
    fileName: "alerts.yaml",
    code: `groups:\n- name: order-api-slo\n  rules:\n  - alert: OrderApiHighErrorRate\n    expr: |\n      sum(rate(http_requests_total{job=\"order-api\", status=~\"5..\"}[5m]))\n      /\n      sum(rate(http_requests_total{job=\"order-api\"}[5m]))\n      > 0.01\n    for: 10m\n    labels: { severity: page }\n    annotations:\n      summary: \"订单 API 5 分钟错误率 > 1%\"\n      runbook: \"https://runbook.example.com/order-api-errors\"\n  - alert: OrderApiHighLatency\n    expr: |\n      histogram_quantile(0.99,\n        sum(rate(http_request_duration_seconds_bucket{job=\"order-api\"}[5m])) by (le))\n      > 1\n    for: 10m\n    labels: { severity: page }`,
    prompt: "下列哪种告警最容易触发告警疲劳？",
    correct: "对每个进程重启、每次 CPU 抖动都发告警，让值班同学被噪声淹没",
    wrong: "只对错误率或延迟违反 SLO 触发告警，附带 runbook 链接",
    output: "alert=OrderApiHighErrorRate severity=page runbook=…",
    lanes: ["选择症状指标", "编写告警规则", "关联 runbook"],
    laneValues: ["错误率 > 1%", "for: 10m", "runbook 链接"],
    log: ["选中错误率 SLO", "写规则 for=10m", "关联 runbook 链接"],
    summary: ["告警必须绑症状", "每条告警都要有 runbook", "for/severity 控制告警密度"],
    sourceTitle: "Google SRE Workbook: Monitoring",
    sourceUrl: "https://sre.google/workbook/monitoring/"
  }),
  createServerLesson({
    id: "server-observability-grafana-dashboard",
    stageId: "server-observability",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Grafana 仪表盘设计",
    concept: "一块高价值 Grafana 仪表盘遵循倒金字塔：顶部是 SLO 与业务指标（一眼看健康），中部是 RED/USE 分组图，底部是可下钻的资源与依赖。模板变量（datasource、service、env）保证一个面板复用于多环境。",
    points: ["顶部放 SLO 与业务指标", "中部按 RED/USE 分组", "模板变量让面板可复用"],
    memoryHook: "面板结构 = 健康 → 服务 → 资源",
    fileName: "dashboard.json",
    code: `{\n  \"title\": \"order-api overview\",\n  \"templating\": {\n    \"list\": [\n      { \"name\": \"env\", \"type\": \"custom\", \"query\": \"prod,staging\" },\n      { \"name\": \"service\", \"type\": \"query\", \"query\": \"label_values(http_requests_total, job)\" }\n    ]\n  },\n  \"panels\": [\n    { \"title\": \"SLO 成功率\", \"type\": \"stat\", \"gridPos\": { \"h\": 4, \"w\": 6, \"x\": 0, \"y\": 0 },\n      \"targets\": [{ \"expr\": \"1 - sum(rate(http_requests_total{job=\\\"$service\\\", status=~\\\"5..\\\"}[5m])) / sum(rate(http_requests_total{job=\\\"$service\\\"}[5m]))\" }] },\n    { \"title\": \"RED: Rate\", \"type\": \"timeseries\", \"gridPos\": { \"h\": 8, \"w\": 8, \"x\": 0, \"y\": 4 },\n      \"targets\": [{ \"expr\": \"sum(rate(http_requests_total{job=\\\"$service\\\"}[1m])) by (route)\" }] },\n    { \"title\": \"RED: P99 延迟\", \"type\": \"timeseries\", \"gridPos\": { \"h\": 8, \"w\": 8, \"x\": 8, \"y\": 4 },\n      \"targets\": [{ \"expr\": \"histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\\\"$service\\\"}[5m])) by (le, route))\" }] }\n  ]\n}`,
    prompt: "Grafana 仪表盘顶部应该优先展示什么？",
    correct: "SLO 与业务指标，让值班同学一眼判断整体健康度",
    wrong: "把所有 PromQL 指标平铺展开，让读者自己找重点",
    output: "面板加载：SLO 成功率 99.94%，RED 三张图，USE 资源分组",
    lanes: ["定义模板变量", "分层放置面板", "配置数据源"],
    laneValues: ["env/service", "SLO → RED → USE", "Prometheus"],
    log: ["定义 env/service 变量", "顶部放 SLO stat", "中部放 RED 时序图"],
    summary: ["仪表盘要有阅读顺序", "模板变量降低维护成本", "SLO 优先于原始指标"],
    sourceTitle: "Grafana Dashboards",
    sourceUrl: "https://grafana.com/docs/grafana/latest/dashboards/"
  })
];

const project = createServerStageProject({
  id: "server-observability-project",
  stageId: "server-observability",
  eyebrowStage: eyebrow,
  title: "微服务端到端可观测性接入",
  brief: "为一个三节点微服务链路（gateway → order → payment）接入端到端可观测性：统一结构化日志 + trace_id、Prometheus RED 指标、OpenTelemetry Trace 传播，最后组装 Grafana SLO 面板并绑定 symptom-based 告警。",
  concept: "串联本阶段：结构化日志（含 correlation-id）、Prometheus 指标类型、OpenTelemetry Trace 传播、RED/USE、SLO/Error Budget、告警设计与 Grafana 面板，形成一个可交付的可观测性接入骨架。",
  points: ["日志/指标/Trace 共享同一 trace_id", "顶层看 SLO，下钻到 RED/USE", "告警只绑症状并关联 runbook"],
  memoryHook: "可观测性 = 日志 + 指标 + Trace + SLO",
  fileName: "observability-bootstrap.ts",
  code: `import { NodeSDK } from \"@opentelemetry/sdk-node\";\nimport { OTLPTraceExporter } from \"@opentelemetry/exporter-trace-otlp-http\";\nimport { PrometheusExporter } from \"@opentelemetry/exporter-prometheus\";\nimport { trace, context, propagation } from \"@opentelemetry/api\";\nimport pino from \"pino\";\nimport { AsyncLocalStorage } from \"node:async_hooks\";\n\nconst als = new AsyncLocalStorage<{ traceId: string }>();\nconst logger = pino({ base: { service: process.env.SERVICE_NAME } });\n\nnew NodeSDK({\n  traceExporter: new OTLPTraceExporter({ url: process.env.OTLP_URL }),\n  metricReader: new PrometheusExporter({ port: 9464 })\n}).start();\n\nconst tracer = trace.getTracer(process.env.SERVICE_NAME!);\n\nexport async function handleRequest(req: Request) {\n  const parent = propagation.extract(context.active(), Object.fromEntries(req.headers));\n  return tracer.startActiveSpan(\"http.server\", {}, parent, async (span) => {\n    const traceId = span.spanContext().traceId;\n    return als.run({ traceId }, async () => {\n      logger.info({ trace_id: traceId, path: new URL(req.url).pathname }, \"request.in\");\n      try {\n        const res = await routeAndCall(req);\n        span.setAttribute(\"http.status_code\", res.status);\n        return res;\n      } catch (err) {\n        span.recordException(err as Error);\n        logger.error({ trace_id: traceId, err: String(err) }, \"request.error\");\n        throw err;\n      } finally {\n        span.end();\n      }\n    });\n  });\n}`,
  prompt: "微服务链路已接入日志、指标、Trace，仪表盘搭好后最先要绑什么样的告警？",
  correct: "绑 SLO 症状告警（错误率/延迟违反 SLO），配 runbook，避免绑 CPU 等原因指标",
  wrong: "把每个进程重启、每次 CPU 抖动都设为 page 告警，覆盖越广越安全",
  correctFeedback: "正确：symptom-based 告警贴用户体验，且能与 Error Budget 联动决定发布节奏。",
  wrongFeedback: "错误：原因型告警噪声爆炸，会迅速产生告警疲劳并淹没真正的症状。",
  additionalWrong: {
    label: "只把 Trace 接进来就够了，日志和指标可以先不做",
    feedback: "错误：三支柱缺一不可，Trace 定位链路、指标看趋势、日志看细节，缺失任何一个都会形成排障盲区。"
  },
  lanes: ["接入三支柱", "组装 SLO 面板", "绑症状告警"],
  laneValues: ["log+metric+trace", "SLO → RED → USE", "错误率/延迟 SLO 告警"],
  log: ["gateway 注入 trace_id", "order/payment 延续 span", "Grafana 展示 SLO 99.94%"],
  summary: ["三支柱共享 trace_id 才能串起来", "SLO 面板决定值班第一眼", "告警只绑症状 + runbook"],
  sourceTitle: "OpenTelemetry Concepts",
  sourceUrl: "https://opentelemetry.io/docs/concepts/"
});

export const serverEngineeringStageNineObservabilityLessons: LessonSpec[] = [...knowledgeLessons, project];
