import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "成本与缓存";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-cost-caching-token-pricing",
    stageId: "ai-app-cost-caching",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Token 计价与 tiktoken 精算",
    concept: "LLM 计费以 token 为单位，input/output 单价通常不同。上线前应使用官方 tokenizer（如 tiktoken）离线精算 prompt token 数，避免依赖字符长度粗估，尤其是中文与代码场景。",
    points: ["input/output 单价分别计量", "用官方 tokenizer 精算而非字符估算", "中文与代码 token 密度差异极大"],
    memoryHook: "先 encode 再算钱，别拿字符数估",
    fileName: "token-pricing.ts",
    code: `import { encoding_for_model } from \"tiktoken\";\n\nconst enc = encoding_for_model(\"gpt-4o-mini\");\nconst prompt = \"帮我总结一下 Node.js 事件循环的六个阶段。\";\nconst inputTokens = enc.encode(prompt).length;\nconst expectedOutputTokens = 400;\n\nconst pricing = { inputPer1k: 0.00015, outputPer1k: 0.0006 };\nconst cost =\n  (inputTokens / 1000) * pricing.inputPer1k +\n  (expectedOutputTokens / 1000) * pricing.outputPer1k;\n\nconsole.log(\`input=\${inputTokens} tokens, est cost=$\${cost.toFixed(6)}\`);\nenc.free();`,
    prompt: "为什么不能用 `prompt.length` 直接估算 token 数？",
    correct: "字符数与 token 数不是线性关系，中文/代码密度差别大，只有 tokenizer 才准",
    wrong: "只要除以固定系数（如 4）就足够精确，tokenizer 是可选优化",
    output: "input=18 tokens, est cost=$0.000243",
    lanes: ["编码 prompt", "累加 input/output", "换算成本"],
    laneValues: ["tiktoken encode", "input=18 out=400", "cost=$0.000243"],
    log: ["加载 gpt-4o-mini 编码器", "input token=18", "估算成本 $0.000243"],
    summary: ["input/output 单价必须分别计算", "tokenizer 是唯一精确度量方式", "中文与代码要单独抽样标定"],
    sourceTitle: "tiktoken 官方仓库",
    sourceUrl: "https://github.com/openai/tiktoken"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-prompt-cache",
    stageId: "ai-app-cost-caching",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Prompt Caching 命中",
    concept: "OpenAI 与 Anthropic 都提供 prompt cache：把不变的 system/上下文放在 prompt 前缀，命中缓存的 token 按折扣计费（Anthropic 缓存写入 1.25x、命中 0.1x）。前缀稳定是命中的前提。",
    points: ["把稳定内容放 prompt 前缀", "命中前缀按折扣价计费", "前缀变化会立即失效缓存"],
    memoryHook: "稳定前缀 + 变化后缀 = 缓存命中",
    fileName: "prompt-cache.ts",
    code: `import Anthropic from \"@anthropic-ai/sdk\";\n\nconst client = new Anthropic();\nconst res = await client.messages.create({\n  model: \"claude-3-5-sonnet-latest\",\n  max_tokens: 512,\n  system: [\n    {\n      type: \"text\",\n      text: LARGE_KNOWLEDGE_BASE,\n      cache_control: { type: \"ephemeral\" }\n    }\n  ],\n  messages: [{ role: \"user\", content: userQuestion }]\n});\n\nconsole.log({\n  cache_creation: res.usage.cache_creation_input_tokens,\n  cache_read: res.usage.cache_read_input_tokens,\n  input: res.usage.input_tokens\n});`,
    prompt: "为什么把用户问题拼在 system 前面会导致 prompt cache 完全失效？",
    correct: "缓存以前缀完全一致为条件，用户问题变化会让所有后续 token 都无法命中",
    wrong: "只要 system 内容一样就会命中，位置不影响缓存 key",
    output: "{ cache_creation: 0, cache_read: 8421, input: 42 }",
    lanes: ["写入缓存", "后续请求", "读取命中"],
    laneValues: ["首次 8421 tokens", "相同前缀", "cache_read=8421"],
    log: ["首次调用写入缓存", "第二次前缀完全一致", "cache_read=8421 tokens"],
    summary: ["prompt cache 按前缀匹配", "稳定内容前置是设计约束", "usage 中的 cache_read 是核心指标"],
    sourceTitle: "Anthropic Prompt Caching",
    sourceUrl: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-semantic-cache",
    stageId: "ai-app-cost-caching",
    order: 3,
    eyebrowStage: eyebrow,
    title: "语义缓存",
    concept: "语义缓存把 query 嵌入为向量，检索历史 query 的 top-1；若余弦相似度超过阈值就复用历史答案。相较精确缓存能覆盖同义提问，但需谨慎设阈值避免错配。",
    points: ["用 embedding 索引历史 query", "相似度阈值决定命中率与错配", "关键任务需要人工回评样本"],
    memoryHook: "向量近似命中，阈值决定风险",
    fileName: "semantic-cache.ts",
    code: `import { OpenAIEmbeddings } from \"@langchain/openai\";\n\nconst embed = new OpenAIEmbeddings({ model: \"text-embedding-3-small\" });\nconst SIM_THRESHOLD = 0.92;\n\nasync function semanticLookup(query: string) {\n  const [vec] = await embed.embedDocuments([query]);\n  const hit = await vectorStore.similaritySearchVectorWithScore(vec, 1);\n  if (hit.length && hit[0][1] >= SIM_THRESHOLD) {\n    return { answer: hit[0][0].pageContent, cached: true, score: hit[0][1] };\n  }\n  const answer = await callLLM(query);\n  await vectorStore.addDocuments([{ pageContent: answer, metadata: { query } }]);\n  return { answer, cached: false };\n}\n\nconsole.log(await semanticLookup(\"怎么退掉 10086 号订单？\"));`,
    prompt: "语义缓存阈值设得太低会带来什么风险？",
    correct: "会把语义相近但意图不同的问题错配，返回错误答案",
    wrong: "阈值越低命中率越高，只要成本下降就是净收益",
    output: "{ answer: '退款流程为…', cached: true, score: 0.94 }",
    lanes: ["生成 query 向量", "近邻检索", "阈值判定"],
    laneValues: ["1 条 query", "top-1 score=0.94", "命中复用"],
    log: ["embed query", "检索 top-1 score=0.94", "命中并复用历史答案"],
    summary: ["语义缓存覆盖同义提问", "阈值是准确/成本的平衡点", "关键业务需人工评样"],
    sourceTitle: "LangChain LLM Caching",
    sourceUrl: "https://python.langchain.com/docs/how_to/llm_caching/"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-exact-cache",
    stageId: "ai-app-cost-caching",
    order: 4,
    eyebrowStage: eyebrow,
    title: "精确缓存与 Redis",
    concept: "精确缓存用 (model, params, prompt) 的哈希做 key，Redis SETEX 存 JSON 结果。命中率取决于 prompt 是否可标准化：去除时间戳、随机 UUID、trailing whitespace 是常规手段。",
    points: ["key = hash(model + params + prompt)", "TTL 由业务时效决定", "prompt 标准化决定命中率"],
    memoryHook: "标准化 prompt，再做哈希缓存",
    fileName: "exact-cache.ts",
    code: `import { createClient } from \"redis\";\nimport { createHash } from \"crypto\";\n\nconst redis = createClient({ url: process.env.REDIS_URL });\nawait redis.connect();\n\nfunction cacheKey(model: string, prompt: string, temperature: number) {\n  const norm = prompt.trim().replace(/\\s+/g, \" \");\n  const raw = JSON.stringify({ model, prompt: norm, temperature });\n  return \"llm:\" + createHash(\"sha256\").update(raw).digest(\"hex\");\n}\n\nasync function cachedCall(prompt: string) {\n  const key = cacheKey(\"gpt-4o-mini\", prompt, 0);\n  const hit = await redis.get(key);\n  if (hit) return { answer: JSON.parse(hit), cached: true };\n  const answer = await callLLM(prompt);\n  await redis.setEx(key, 3600, JSON.stringify(answer));\n  return { answer, cached: false };\n}`,
    prompt: "同一个问题命中率一直很低，最可能的原因是什么？",
    correct: "prompt 中带有时间戳/随机 ID 等噪声，哈希 key 每次都不同",
    wrong: "Redis 容量不足导致 key 立刻被驱逐，需要扩容",
    output: "{ answer: '事件循环包含...', cached: true }",
    lanes: ["标准化 prompt", "生成哈希 key", "读写 Redis"],
    laneValues: ["trim + collapse", "sha256 摘要", "SETEX 3600s"],
    log: ["标准化 prompt", "生成 key llm:xxxx", "SETEX 命中返回"],
    summary: ["精确缓存最简单也最稳定", "标准化决定命中率", "TTL 与业务时效强相关"],
    sourceTitle: "Redis Vector & Cache 指南",
    sourceUrl: "https://redis.io/docs/latest/develop/get-started/vector-database/"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-batch-api",
    stageId: "ai-app-cost-caching",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Batch API 与 50% 折扣",
    concept: "OpenAI Batch API 接受 JSONL 文件、异步在 24 小时内返回，价格为标准的 50%。适用于离线评测、数据标注、embedding 回填等对实时性不敏感的任务。",
    points: ["JSONL 一行一条请求", "24 小时窗口异步返回", "价格为标准的 50%"],
    memoryHook: "能等一天，直接对折",
    fileName: "batch-api.ts",
    code: `import OpenAI from \"openai\";\nimport { createReadStream } from \"fs\";\n\nconst openai = new OpenAI();\n\nconst file = await openai.files.create({\n  file: createReadStream(\"requests.jsonl\"),\n  purpose: \"batch\"\n});\n\nconst batch = await openai.batches.create({\n  input_file_id: file.id,\n  endpoint: \"/v1/chat/completions\",\n  completion_window: \"24h\"\n});\n\nconsole.log({ id: batch.id, status: batch.status });\n// 后续通过 openai.batches.retrieve(batch.id) 轮询状态\n// completed 后从 output_file_id 下载结果`,
    prompt: "什么样的任务最适合放到 Batch API？",
    correct: "对延迟不敏感的离线任务：评测集打分、embedding 回填、批量数据清洗",
    wrong: "所有面向用户的实时对话，因为 50% 折扣一定要用上",
    output: "{ id: 'batch_abc', status: 'validating' }",
    lanes: ["上传 JSONL", "创建 batch", "24h 内轮询"],
    laneValues: ["file.id=file_x", "batch_abc", "status=completed"],
    log: ["上传 JSONL 文件", "创建 batch 任务", "24 小时内完成"],
    summary: ["Batch API 用离线换 50% 成本", "只适用于非实时链路", "JSONL 与轮询是标准协议"],
    sourceTitle: "OpenAI Batch API",
    sourceUrl: "https://platform.openai.com/docs/guides/batch"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-stream-vs-blocking",
    stageId: "ai-app-cost-caching",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Stream vs 非 Stream 成本",
    concept: "Stream 与非 Stream 的 token 计费完全相同——按最终生成的 token 数计价。差别在体验（首 token 时延）与工程复杂度（增量解析、连接维持），而不是账单。",
    points: ["stream 与 blocking 单价一致", "stream 优化首 token 时延", "stream 增加连接与解析成本"],
    memoryHook: "stream 省时延不省钱",
    fileName: "stream-cost.ts",
    code: `import OpenAI from \"openai\";\n\nconst openai = new OpenAI();\n\nconst stream = await openai.chat.completions.create({\n  model: \"gpt-4o-mini\",\n  messages: [{ role: \"user\", content: \"解释 Node.js 事件循环\" }],\n  stream: true,\n  stream_options: { include_usage: true }\n});\n\nlet outputTokens = 0;\nfor await (const chunk of stream) {\n  if (chunk.choices[0]?.delta?.content) process.stdout.write(chunk.choices[0].delta.content);\n  if (chunk.usage) outputTokens = chunk.usage.completion_tokens;\n}\nconsole.log(\`\\n用量：output=\${outputTokens} tokens（stream 与 blocking 计费相同）\`);`,
    prompt: "为了降低 LLM 账单，把所有接口从 blocking 切成 stream 有效吗？",
    correct: "无效，stream 与 blocking 按相同的最终 token 数计费，只影响体验",
    wrong: "有效，stream 按 chunk 计费单价更低，总账单能下降 30%",
    output: "output=412 tokens（stream 与 blocking 计费相同）",
    lanes: ["建立 SSE 流", "累计增量", "结算 usage"],
    laneValues: ["stream=true", "增量输出", "usage=412"],
    log: ["开启 stream", "增量拼接 output", "结算 output=412"],
    summary: ["stream 只优化时延不影响账单", "stream_options.include_usage 拿到用量", "stream 增加连接稳定性成本"],
    sourceTitle: "OpenAI Chat Completions",
    sourceUrl: "https://platform.openai.com/docs/guides/prompt-caching"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-model-fallback",
    stageId: "ai-app-cost-caching",
    order: 7,
    eyebrowStage: eyebrow,
    title: "模型降级与预算护栏",
    concept: "生产系统应有分层策略：默认走低价模型（如 gpt-4o-mini），当置信度低或涉及复杂推理时升级到旗舰模型；同时对用户/租户设置日预算，超额降级或熔断。",
    points: ["默认低价模型，按需升级", "按租户设置日预算上限", "超额降级或熔断而非直接拒绝"],
    memoryHook: "先便宜后强，预算就是护栏",
    fileName: "model-fallback.ts",
    code: `type Ctx = { tenantId: string; complexity: \"low\" | \"high\" };\n\nasync function pickModel(ctx: Ctx) {\n  const spent = await budget.getTodaySpent(ctx.tenantId);\n  const cap = await budget.getDailyCap(ctx.tenantId);\n  if (spent >= cap) return { model: \"gpt-4o-mini\", reason: \"budget_exceeded\" };\n  if (ctx.complexity === \"high\" && spent < cap * 0.8) {\n    return { model: \"gpt-4o\", reason: \"high_complexity\" };\n  }\n  return { model: \"gpt-4o-mini\", reason: \"default\" };\n}\n\nconst choice = await pickModel({ tenantId: \"t_88\", complexity: \"high\" });\nawait metrics.increment(\"model.pick\", { model: choice.model, reason: choice.reason });`,
    prompt: "租户当日已超预算，最合理的处理是？",
    correct: "自动降级到低价模型或降级功能，同时向用户暴露状态",
    wrong: "直接返回 500 错误让用户重试，防止继续烧钱",
    output: "model.pick model=gpt-4o-mini reason=budget_exceeded",
    lanes: ["读取预算", "判断复杂度", "选择模型"],
    laneValues: ["spent=$9.8/$10", "high", "gpt-4o-mini"],
    log: ["读取 tenant 预算", "判定 budget_exceeded", "降级到 gpt-4o-mini"],
    summary: ["模型选择是策略层不是硬编码", "预算护栏防止意外爆表", "降级优于直接失败"],
    sourceTitle: "Anthropic Prompt Caching",
    sourceUrl: "https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching"
  }),
  createAiAppLesson({
    id: "ai-app-cost-caching-cost-monitoring",
    stageId: "ai-app-cost-caching",
    order: 8,
    eyebrowStage: eyebrow,
    title: "成本监控与告警",
    concept: "每次 LLM 调用应把 usage.input/output/cache_read 与 tenantId、route、model 一起写入时序数据库，按分钟聚合。告警至少覆盖：日预算达 80%、单请求成本异常、缓存命中率骤降。",
    points: ["按 tenant/route/model 打点", "分钟级聚合送入时序库", "三类告警：预算/异常/命中率"],
    memoryHook: "打点、聚合、告警三件套",
    fileName: "cost-monitoring.ts",
    code: `type Usage = {\n  tenantId: string; route: string; model: string;\n  inputTokens: number; outputTokens: number; cacheReadTokens: number;\n  costUsd: number;\n};\n\nasync function recordUsage(u: Usage) {\n  await metrics.histogram(\"llm.cost.usd\", u.costUsd, {\n    tenant: u.tenantId, route: u.route, model: u.model\n  });\n  await metrics.counter(\"llm.tokens.cache_read\", u.cacheReadTokens, { model: u.model });\n\n  const spentToday = await budget.addSpend(u.tenantId, u.costUsd);\n  const cap = await budget.getDailyCap(u.tenantId);\n  if (spentToday >= cap * 0.8) {\n    await alert.fire(\"budget.warning\", { tenant: u.tenantId, spent: spentToday, cap });\n  }\n}`,
    prompt: "只监控日总成本不监控租户维度会导致什么问题？",
    correct: "单个租户异常爆量会被总量平均掉，问题被隐藏且无法定位",
    wrong: "只看日总成本已经足够，租户维度是可选优化",
    output: "budget.warning fired: tenant=t_88 spent=$8.1 cap=$10",
    lanes: ["记录 usage", "聚合入库", "触发告警"],
    laneValues: ["cost=$0.004", "spent=$8.1", "warning fired"],
    log: ["写入 llm.cost.usd", "累计 spent=$8.1", "触发 budget.warning"],
    summary: ["每次调用都要留痕", "维度打点是排障基础", "告警要覆盖预算与异常波动"],
    sourceTitle: "OpenAI Prompt Caching",
    sourceUrl: "https://platform.openai.com/docs/guides/prompt-caching"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-cost-caching-project",
  stageId: "ai-app-cost-caching",
  eyebrowStage: eyebrow,
  title: "三层缓存架构",
  brief: "构建 exact → semantic → LLM 三层缓存：先查 Redis 精确匹配，再查向量语义匹配，最后回落 LLM 调用；每一层都打点成本与命中率，超过预算自动降级。",
  concept: "把 Prompt Caching、语义缓存、精确缓存、模型降级和成本监控串成一个完整调用链：多层过滤降低 LLM 调用次数，剩余请求靠 prompt cache 与降级压低单价。",
  points: ["三层顺序：exact → semantic → LLM", "每层单独打点命中率与成本", "预算超额触发模型降级"],
  memoryHook: "三层过滤 + 预算护栏 = 成本可控",
  fileName: "three-layer-cache.ts",
  code: `import { exactLookup, exactStore } from \"./exact-cache\";\nimport { semanticLookup, semanticStore } from \"./semantic-cache\";\nimport { pickModel } from \"./model-fallback\";\nimport { recordUsage } from \"./cost-monitoring\";\n\nexport async function askWithCache(tenantId: string, query: string) {\n  const hit1 = await exactLookup(query);\n  if (hit1) {\n    await metrics.increment(\"cache.hit\", { layer: \"exact\" });\n    return { answer: hit1, source: \"exact\" };\n  }\n\n  const hit2 = await semanticLookup(query);\n  if (hit2) {\n    await metrics.increment(\"cache.hit\", { layer: \"semantic\", score: hit2.score });\n    return { answer: hit2.answer, source: \"semantic\" };\n  }\n\n  const { model } = await pickModel({ tenantId, complexity: \"low\" });\n  const { answer, usage } = await callLLM(model, query);\n  await Promise.all([exactStore(query, answer), semanticStore(query, answer)]);\n  await recordUsage({\n    tenantId, route: \"ask\", model,\n    inputTokens: usage.input, outputTokens: usage.output,\n    cacheReadTokens: usage.cache_read ?? 0,\n    costUsd: usage.cost\n  });\n  return { answer, source: \"llm\" };\n}`,
  prompt: "三层缓存中，为什么必须先查 exact 再查 semantic？",
  correct: "exact 是 O(1) 且零错配，semantic 有阈值风险，顺序颠倒会白白引入错配概率",
  wrong: "两层顺序不重要，只要最终命中率高即可",
  correctFeedback: "正确：exact 是无损命中且延迟最低，语义命中放在其后可以最大化安全命中率。",
  wrongFeedback: "错误：语义缓存有错配概率，放在 exact 之前会让原本可无损命中的请求走风险路径。",
  additionalWrong: {
    label: "干脆只保留语义缓存，覆盖面更广也更省",
    feedback: "错误：语义缓存有阈值下限，会漏掉字符完全一致但相似度受词法影响未过阈值的场景，同时错配风险不可控。"
  },
  lanes: ["exact 命中", "semantic 命中", "回落 LLM"],
  laneValues: ["未命中", "未命中", "调用 gpt-4o-mini"],
  log: ["exact 未命中", "semantic 未命中", "回落 LLM 并写回两层缓存"],
  summary: ["缓存顺序按无损→有损→原始", "每层独立打点便于优化", "预算护栏与降级是最后一道防线"],
  sourceTitle: "LangChain LLM Caching",
  sourceUrl: "https://python.langchain.com/docs/how_to/llm_caching/"
});

export const aiApplicationStageEightCostCachingLessons: LessonSpec[] = [...knowledgeLessons, project];
