import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "端到端 AI 应用平台";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-production-platform-ingest-chunking",
    stageId: "ai-app-production-platform",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Ingest 层：采集与分片",
    concept: "文档采集是 AI 平台的原始入口。不同来源（PDF / HTML / Notion / GitHub）先归一为纯文本，再按语义边界切分并附上 `source_id / version / hash` 元数据，才能支持幂等重跑和增量更新。",
    points: ["多源 loader 归一为纯文本", "按语义边界切分而不是按字节", "metadata 携带 hash 支持增量"],
    memoryHook: "采集 = 归一化 + 切分 + 打指纹",
    fileName: "ingest.ts",
    code: `import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";\nimport crypto from "node:crypto";\n\ntype RawDoc = { sourceId: string; version: string; text: string };\ntype Chunk = { id: string; sourceId: string; version: string; hash: string; text: string };\n\nconst splitter = new RecursiveCharacterTextSplitter({\n  chunkSize: 800,\n  chunkOverlap: 120,\n  separators: ["\\n\\n", "\\n", "。", "！", "？", " ", ""]\n});\n\nexport async function ingest(doc: RawDoc): Promise<Chunk[]> {\n  const pieces = await splitter.splitText(doc.text);\n  return pieces.map((text, i) => {\n    const hash = crypto.createHash("sha1").update(text).digest("hex").slice(0, 12);\n    return {\n      id: \`\${doc.sourceId}#\${doc.version}#\${i}\`,\n      sourceId: doc.sourceId,\n      version: doc.version,\n      hash,\n      text\n    };\n  });\n}\n\nconst chunks = await ingest({ sourceId: "handbook", version: "v3", text: await loadHandbook() });\nconsole.log(\`ingested \${chunks.length} chunks\`);`,
    prompt: "Ingest 层为什么要给每个 chunk 打 `hash` 和 `version`？",
    correct: "版本 + hash 支持幂等重跑与增量更新，未变的 chunk 不必重嵌入",
    wrong: "只是方便日志排序，实际下游不会用到 hash",
    output: "ingested 42 chunks",
    lanes: ["加载文档", "语义切分", "打指纹"],
    laneValues: ["handbook v3", "42 段", "sha1 前 12 位"],
    log: ["加载 handbook v3", "切出 42 段", "写入 hash + version"],
    summary: ["多源统一到纯文本再切分", "语义分隔符优于固定字节", "hash + version 支持增量重嵌"],
    sourceTitle: "LangChain RAG Tutorial",
    sourceUrl: "https://python.langchain.com/docs/tutorials/rag/"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-rag-retrieve-rerank",
    stageId: "ai-app-production-platform",
    order: 2,
    eyebrowStage: eyebrow,
    title: "RAG 层：召回 + Rerank",
    concept: "生产 RAG = 向量粗召回 + cross-encoder 精排 + 上下文组装。仅靠向量 top-k 会带入噪声，rerank 用 cross-encoder 或 LLM 打分把最相关的几条前置，再拼装 citation 上下文。",
    points: ["粗召回 top-N 覆盖广", "精排 top-K 聚焦准确", "context 附 citation 供回溯"],
    memoryHook: "粗召回广，精排狠，citation 全",
    fileName: "rag.ts",
    code: `import { CohereRerank } from "@langchain/cohere";\nimport type { Chunk } from "./ingest";\n\nconst rerank = new CohereRerank({ topN: 5, model: "rerank-3.5" });\n\nexport async function retrieveWithRerank(query: string, candidates: Chunk[]) {\n  const scored = await rerank.compressDocuments(\n    candidates.map((c) => ({ pageContent: c.text, metadata: { id: c.id, source: c.sourceId } })),\n    query\n  );\n  return scored.map((doc) => ({\n    id: doc.metadata.id as string,\n    source: doc.metadata.source as string,\n    text: doc.pageContent,\n    score: (doc.metadata.relevanceScore as number) ?? 0\n  }));\n}\n\nexport function buildContext(hits: { id: string; source: string; text: string }[]) {\n  return hits\n    .map((h, i) => \`[\${i + 1}] (\${h.source}#\${h.id})\\n\${h.text}\`)\n    .join("\\n\\n---\\n\\n");\n}\n\nconst topK = await retrieveWithRerank("退款流程", await vectorSearch("退款流程", 40));\nconsole.log(buildContext(topK).slice(0, 200));`,
    prompt: "生产 RAG 为什么在向量召回后还要做 rerank？",
    correct: "向量召回擅长广度，cross-encoder rerank 提供精度，两者组合才稳",
    wrong: "向量库自带的 top-k 已经排序，rerank 只是重复计算",
    output: "[1] (handbook#handbook#v3#7)\\n退款需在下单 7 日内...",
    lanes: ["向量粗召回", "Rerank 精排", "组装 context"],
    laneValues: ["40 条候选", "Top-5 精排", "带 citation 拼接"],
    log: ["向量召回 40 条", "rerank 保留 Top-5", "拼装带 citation 上下文"],
    summary: ["向量召回是广度", "rerank 是精度", "citation 是可回溯的证据"],
    sourceTitle: "OpenAI RAG with Graph DB",
    sourceUrl: "https://cookbook.openai.com/examples/rag_with_graph_db"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-chain-langgraph",
    stageId: "ai-app-production-platform",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Chain 层：LangGraph 编排",
    concept: "一次生产请求通常需要 `plan → retrieve → generate → verify` 多步。LangGraph 用 `StateGraph` 显式声明节点与转移条件，可中断、可重放、可部分回滚，比让 LLM 自己规划链条更可控。",
    points: ["节点/边显式声明流程", "conditional edge 表达分支", "state 可持久化用于重放"],
    memoryHook: "复杂流程用图，不靠模型自觉",
    fileName: "chain.ts",
    code: `import { StateGraph, END } from "@langchain/langgraph";\nimport { retrieveWithRerank, buildContext } from "./rag";\n\ntype ChainState = {\n  query: string;\n  hits?: Awaited<ReturnType<typeof retrieveWithRerank>>;\n  draft?: string;\n  verified?: boolean;\n};\n\nconst graph = new StateGraph<ChainState>({\n  channels: { query: null, hits: null, draft: null, verified: null }\n})\n  .addNode("retrieve", async (s) => ({ hits: await retrieveWithRerank(s.query, await vectorSearch(s.query, 40)) }))\n  .addNode("generate", async (s) => ({ draft: await llmAnswer(s.query, buildContext(s.hits!)) }))\n  .addNode("verify", async (s) => ({ verified: await checkCitations(s.draft!, s.hits!) }))\n  .addConditionalEdges("verify", (s) => (s.verified ? END : "generate"))\n  .addEdge("retrieve", "generate")\n  .addEdge("generate", "verify")\n  .setEntryPoint("retrieve")\n  .compile({ checkpointer });\n\nconst result = await graph.invoke({ query: "怎么申请退款？" }, { configurable: { thread_id: "u42" } });\nconsole.log(result.draft);`,
    prompt: "生产环境为什么用 LangGraph 而不是让 LLM 直接规划工具链？",
    correct: "显式图让流程可中断、可重放、可回滚，异常时能定位到具体节点",
    wrong: "LangGraph 只是语法糖，实际执行和模型自己 chain 完全等价",
    output: "申请退款请在订单详情页点击 [1] 退款按钮...",
    lanes: ["retrieve 节点", "generate 节点", "verify 节点"],
    laneValues: ["召回 5 条", "生成草稿", "citation 校验通过"],
    log: ["retrieve 完成", "generate 生成草稿", "verify 通过"],
    summary: ["显式图比隐式规划更可控", "conditional edge 表达重试", "checkpointer 让 state 可持久化"],
    sourceTitle: "LangGraph Introduction",
    sourceUrl: "https://langchain-ai.github.io/langgraph/tutorials/introduction/"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-evaluation-ci",
    stageId: "ai-app-production-platform",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Evaluation 层：CI + Baseline",
    concept: "评测集必须钉在 CI 中运行。每个 PR 跑固定用例，对比 baseline 的准确率、召回命中率与成本，超过阈值直接 block merge。LangSmith / promptfoo / 自建 harness 都可，关键是有基线、有阈值。",
    points: ["评测集入 CI，PR 触发", "对比 baseline 指标", "回归超阈值直接 block"],
    memoryHook: "无 baseline 不叫评测，无 CI 不叫回归",
    fileName: "eval.ts",
    code: `import { evaluate } from "langsmith/evaluation";\nimport { runChain } from "./chain";\n\nconst BASELINE = { accuracy: 0.82, citationHit: 0.9, avgCostUsd: 0.012 };\nconst THRESHOLD = { accuracy: -0.03, citationHit: -0.05, avgCostUsd: 0.005 };\n\nasync function runEvaluation() {\n  const result = await evaluate((input: { query: string }) => runChain(input.query), {\n    data: "prod-eval-v3",\n    evaluators: ["qa-accuracy", "citation-hit"],\n    experimentPrefix: process.env.GIT_SHA ?? "local"\n  });\n\n  const metrics = result.aggregatedResults;\n  const regressions = [\n    metrics.accuracy - BASELINE.accuracy < THRESHOLD.accuracy && "accuracy",\n    metrics.citationHit - BASELINE.citationHit < THRESHOLD.citationHit && "citationHit",\n    metrics.avgCostUsd - BASELINE.avgCostUsd > THRESHOLD.avgCostUsd && "cost"\n  ].filter(Boolean);\n\n  if (regressions.length) {\n    console.error(\`Regressions: \${regressions.join(", ")}\`);\n    process.exit(1);\n  }\n}\n\nawait runEvaluation();`,
    prompt: "AI 应用的评测集应该在什么时候运行？",
    correct: "钉在 CI 中每个 PR 都跑，对比 baseline 指标，超阈值 block",
    wrong: "上线前手动跑一次即可，避免拖慢 CI 时间",
    output: "Regressions: accuracy",
    lanes: ["加载评测集", "运行链路", "比对 baseline"],
    laneValues: ["prod-eval-v3", "跑完 120 用例", "accuracy -0.04"],
    log: ["加载 prod-eval-v3", "运行 120 条用例", "accuracy 回退 0.04 → block"],
    summary: ["评测必须自动化", "baseline 是必需的锚点", "回归阈值决定 block 时机"],
    sourceTitle: "LangSmith Agent Evaluation",
    sourceUrl: "https://docs.smith.langchain.com/evaluation/tutorials/agents"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-safety-guardrails",
    stageId: "ai-app-production-platform",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Safety 层：Guardrails",
    concept: "输入侧检查 PII / 越权指令 / prompt injection，输出侧过滤有害内容、敏感话题、幻觉引用。两侧都过 moderation API 或规则引擎，命中直接短路并落审计日志。",
    points: ["输入侧防注入 + PII", "输出侧过有害 + 幻觉", "命中直接短路走 fallback"],
    memoryHook: "两头都要挡，中间才安全",
    fileName: "safety.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst BLOCK_PATTERNS = [/ignore previous/i, /reveal system prompt/i, /sk-[A-Za-z0-9]{20,}/];\n\nasync function preCheck(input: string) {\n  if (BLOCK_PATTERNS.some((p) => p.test(input))) {\n    return { pass: false, reason: "prompt_injection" as const };\n  }\n  const mod = await openai.moderations.create({ model: "omni-moderation-latest", input });\n  if (mod.results[0].flagged) return { pass: false, reason: "input_flagged" as const };\n  return { pass: true as const };\n}\n\nasync function postCheck(output: string) {\n  const mod = await openai.moderations.create({ model: "omni-moderation-latest", input: output });\n  return mod.results[0].flagged ? { pass: false, reason: "output_flagged" as const } : { pass: true as const };\n}\n\nexport async function guarded(input: string, run: (q: string) => Promise<string>) {\n  const pre = await preCheck(input);\n  if (!pre.pass) return { blocked: pre.reason, answer: "抱歉，此请求无法处理。" };\n  const answer = await run(input);\n  const post = await postCheck(answer);\n  if (!post.pass) return { blocked: post.reason, answer: "生成内容不合规，已转人工。" };\n  return { blocked: null, answer };\n}`,
    prompt: "AI 应用的安全防护为什么需要输入与输出双侧过滤？",
    correct: "输入侧防注入与 PII 泄露，输出侧防幻觉与有害内容，两者场景不同",
    wrong: "只挡输入侧即可，输出不会产生新的有害内容",
    output: "{ blocked: 'prompt_injection', answer: '抱歉，此请求无法处理。' }",
    lanes: ["输入检查", "模型生成", "输出检查"],
    laneValues: ["preCheck 命中", "短路 fallback", "跳过 postCheck"],
    log: ["preCheck 命中 prompt_injection", "短路返回 fallback", "落审计日志"],
    summary: ["输入输出双侧过滤", "命中直接 fallback", "所有拦截都要审计"],
    sourceTitle: "OpenAI Node Agent Cookbook",
    sourceUrl: "https://cookbook.openai.com/examples/how_to_build_an_agent_with_the_node_sdk"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-ops-canary-rollback",
    stageId: "ai-app-production-platform",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Ops 层：限流 + 灰度 + Rollback",
    concept: "LLM 调用要按 user / tenant / route 限流保护成本；新 prompt 或 model 分批灰度（1% → 10% → 100%）并对齐关键指标；异常时秒级 rollback 回上一稳定版本。",
    points: ["多维度限流保护成本", "按 hash 分桶灰度", "版本可秒级回滚"],
    memoryHook: "限流护成本，灰度控风险，rollback 兜底",
    fileName: "ops.ts",
    code: `import crypto from "node:crypto";\n\ntype Version = { id: string; percent: number; prompt: string; model: string };\nlet CURRENT: Version[] = [\n  { id: "v3", percent: 90, prompt: PROMPT_V3, model: "gpt-4o-mini" },\n  { id: "v4", percent: 10, prompt: PROMPT_V4, model: "gpt-4o" }\n];\nlet LAST_STABLE = "v3";\n\nfunction pickVersion(userId: string) {\n  const bucket = parseInt(crypto.createHash("md5").update(userId).digest("hex").slice(0, 8), 16) % 100;\n  let acc = 0;\n  for (const v of CURRENT) {\n    acc += v.percent;\n    if (bucket < acc) return v;\n  }\n  return CURRENT[0];\n}\n\nexport function rollback(reason: string) {\n  CURRENT = CURRENT.filter((v) => v.id === LAST_STABLE).map((v) => ({ ...v, percent: 100 }));\n  console.warn(\`rollback → \${LAST_STABLE}: \${reason}\`);\n}\n\nexport async function serve(userId: string, query: string) {\n  if (!(await rateLimiter.allow(\`u:\${userId}\`, 20, 60))) throw new Error("rate_limited");\n  const version = pickVersion(userId);\n  const start = Date.now();\n  const answer = await callLLM(version.model, version.prompt, query);\n  metrics.observe("llm.latency", Date.now() - start, { version: version.id });\n  return { version: version.id, answer };\n}`,
    prompt: "新 prompt 上线后错误率突增，最快恢复的手段是什么？",
    correct: "秒级 rollback 到上一稳定版本，再离线排查根因",
    wrong: "边上线边观察，等根因定位后再修复重发",
    output: "rollback → v3: eval regression",
    lanes: ["限流放行", "灰度分桶", "监控 rollback"],
    laneValues: ["u:42 通过", "命中 v4 灰度", "指标异常回滚"],
    log: ["限流放行 u:42", "分桶命中 v4", "指标异常触发 rollback"],
    summary: ["限流是成本第一防线", "灰度按 hash 稳定分桶", "rollback 优先于修复"],
    sourceTitle: "Vercel AI SDK",
    sourceUrl: "https://sdk.vercel.ai/docs/introduction"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-ui-streaming-citations",
    stageId: "ai-app-production-platform",
    order: 7,
    eyebrowStage: eyebrow,
    title: "UI 层：Streaming + Citations",
    concept: "生产 AI UI 四件套：流式渲染（TTFB↓）、citation 展示（可信度↑）、反馈按钮（thumbs up/down）、消息可编辑重跑。Vercel AI SDK 的 `streamText` + `useChat` 提供从 tool_call 到 UI stream 的完整链路。",
    points: ["streamText 边生成边推送", "message.parts 附 citation", "onFinish 收集反馈信号"],
    memoryHook: "流式 + 引用 + 反馈 = 三件必备",
    fileName: "chat-route.ts",
    code: `import { streamText, convertToCoreMessages } from "ai";\nimport { openai } from "@ai-sdk/openai";\nimport { retrieveWithRerank, buildContext } from "./rag";\n\nexport async function POST(req: Request) {\n  const { messages, userId } = await req.json();\n  const query = messages.at(-1)?.content ?? "";\n  const hits = await retrieveWithRerank(query, await vectorSearch(query, 40));\n\n  const result = streamText({\n    model: openai("gpt-4o-mini"),\n    system: "回答基于给定文档，末尾必须列出 [n] 引用。",\n    messages: convertToCoreMessages([\n      ...messages,\n      { role: "system", content: \`Context:\\n\${buildContext(hits)}\` }\n    ]),\n    onFinish: async ({ text, usage }) => {\n      await analytics.track("chat.finished", {\n        userId,\n        tokens: usage.totalTokens,\n        citations: hits.map((h) => h.id)\n      });\n    }\n  });\n\n  return result.toDataStreamResponse({\n    headers: { "x-citations": JSON.stringify(hits.map((h) => h.id)) }\n  });\n}`,
    prompt: "生产 AI 聊天 UI 为什么强调 streaming + citation 组合？",
    correct: "streaming 降低感知延迟，citation 提供可验证证据，缺一都会掉信任",
    wrong: "streaming 只影响观感，citation 只影响审计，两者互相独立",
    output: "chat.finished tokens=482 citations=[handbook#v3#7, handbook#v3#8]",
    lanes: ["召回上下文", "流式生成", "反馈埋点"],
    laneValues: ["Top-5 命中", "streamText 推送", "analytics 落库"],
    log: ["召回 Top-5", "streamText 边生成边推送", "onFinish 写入 analytics"],
    summary: ["streaming 优化 TTFB", "citation 提供可信度", "onFinish 是反馈信号入口"],
    sourceTitle: "Vercel Generative UI",
    sourceUrl: "https://vercel.com/docs/ai/generative-ui"
  }),
  createAiAppLesson({
    id: "ai-app-production-platform-analytics-feedback",
    stageId: "ai-app-production-platform",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Analytics 层：反馈聚合",
    concept: "用户 `thumbs down` + 编辑重跑 + 会话放弃 = 隐性质量信号。聚合到数仓，join trace 与 citation，找出问题 prompt / 召回文档，作为下一轮 fine-tune 或 prompt 优化的输入。",
    points: ["显式 + 隐式反馈都要收", "join trace 定位根因", "输出成 retrain sample"],
    memoryHook: "反馈聚合出短板，短板反哺下一轮",
    fileName: "analytics.ts",
    code: `type FeedbackRow = {\n  sessionId: string;\n  traceId: string;\n  rating: -1 | 0 | 1;\n  edited: boolean;\n  abandonedAtStep?: string;\n  citations: string[];\n};\n\nexport async function buildRetrainSet(sinceDays = 7) {\n  const rows: FeedbackRow[] = await warehouse.query(\`\n    select session_id, trace_id, rating, edited, abandoned_step, citations\n    from chat_feedback\n    where created_at > now() - interval '\${sinceDays} days'\n      and (rating = -1 or edited or abandoned_step is not null)\n  \`);\n\n  const samples = await Promise.all(\n    rows.map(async (r) => {\n      const trace = await tracer.load(r.traceId);\n      return {\n        query: trace.input.query,\n        badAnswer: trace.output.answer,\n        goodAnswer: r.edited ? await warehouse.getEditedAnswer(r.sessionId) : null,\n        weakCitations: r.citations,\n        reason: r.rating === -1 ? "thumbs_down" : r.edited ? "user_edit" : "abandoned"\n      };\n    })\n  );\n\n  return samples;\n}\n\nconst dataset = await buildRetrainSet();\nconsole.log(\`collected \${dataset.length} retrain samples\`);`,
    prompt: "为什么要把用户编辑与放弃也算作反馈信号？",
    correct: "显式 thumbs 稀疏，编辑与放弃是高信号的隐式反馈，覆盖真实痛点",
    wrong: "只统计 thumbs down 就够了，编辑和放弃有太多噪声不可用",
    output: "collected 137 retrain samples",
    lanes: ["拉反馈日志", "join trace", "生成 retrain"],
    laneValues: ["近 7 日反馈", "关联 trace", "137 条样本"],
    log: ["拉取 7 日反馈", "关联 trace 与 citation", "生成 137 条 retrain 样本"],
    summary: ["隐式反馈是补稀疏 thumbs 的关键", "join trace 才有根因", "样本是下一轮优化的燃料"],
    sourceTitle: "LangSmith Agent Evaluation",
    sourceUrl: "https://docs.smith.langchain.com/evaluation/tutorials/agents"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-production-platform-project",
  stageId: "ai-app-production-platform",
  eyebrowStage: eyebrow,
  title: "端到端 AI 应用平台骨架",
  brief: "把 Ingest → RAG → Chain → Eval → Safety → Ops → UI → Analytics 8 层串成一个可交付的 handler：请求进入先过 safety 与限流，命中灰度版本后跑 LangGraph 链路，流式返回带 citation 的答案，反馈异步落 analytics，评测集在 CI 中守住 baseline。",
  concept: "生产 AI 应用不是单点 LLM 调用，而是数据（Ingest）、检索（RAG）、编排（Chain）、质量（Eval）、安全（Safety）、运维（Ops）、体验（UI）、反馈（Analytics）8 层协作的系统。任何一层缺失都会在线上放大成事故。",
  points: ["8 层各司其职，串成闭环", "trace 贯穿所有层便于归因", "评测 + 反馈驱动持续优化"],
  memoryHook: "平台 = 数据 + 检索 + 编排 + 质量 + 安全 + 运维 + 体验 + 反馈",
  fileName: "platform.ts",
  code: `import { streamText, convertToCoreMessages } from "ai";\nimport { openai } from "@ai-sdk/openai";\nimport { guarded } from "./safety";\nimport { serve as opsServe, rollback } from "./ops";\nimport { retrieveWithRerank, buildContext } from "./rag";\nimport { runChain } from "./chain";\n\nexport async function POST(req: Request) {\n  const { messages, userId } = await req.json();\n  const query = messages.at(-1)?.content ?? "";\n\n  return guarded(query, async () => {\n    const { version } = await opsServe(userId, query);\n    const hits = await retrieveWithRerank(query, await vectorSearch(query, 40));\n    const state = await runChain(query);\n\n    const result = streamText({\n      model: openai(version === "v4" ? "gpt-4o" : "gpt-4o-mini"),\n      system: "基于 Context 回答，末尾附 [n] 引用。",\n      messages: convertToCoreMessages([\n        ...messages,\n        { role: "system", content: \`Context:\\n\${buildContext(hits)}\` }\n      ]),\n      onFinish: async ({ text, usage }) => {\n        await analytics.track("chat.finished", {\n          userId,\n          version,\n          traceId: state.traceId,\n          tokens: usage.totalTokens,\n          citations: hits.map((h) => h.id)\n        });\n        if (usage.totalTokens > 8000) await alerts.warn("token_budget_exceeded", { userId, version });\n      }\n    });\n\n    return result.toDataStreamResponse({\n      headers: {\n        "x-version": version,\n        "x-citations": JSON.stringify(hits.map((h) => h.id))\n      }\n    });\n  }).then((r) => (typeof r === "object" && "blocked" in r ? new Response(r.answer, { status: 200 }) : r));\n}\n\n// CI 前置守护\nimport("./eval").catch((err) => {\n  rollback(\`eval failure: \${err.message}\`);\n});`,
  prompt: "端到端 AI 应用平台把 8 层串起来的核心价值是什么？",
  correct: "每层独立可替换、可观测、可回滚，任何异常都能沿 trace 定位并单点修复",
  wrong: "把所有层塞进一个大 prompt 让 LLM 自己处理，架构最简单",
  correctFeedback: "正确：分层架构让 Ingest / RAG / Chain / Eval / Safety / Ops / UI / Analytics 各自演进，trace 贯穿归因。",
  wrongFeedback: "错误：单大 prompt 不可观测、不可回滚，一个环节坏了整个系统黑盒。",
  additionalWrong: {
    label: "只要 LLM 能生成答案就够了，评测和反馈是奢侈品",
    feedback: "错误：没有评测和反馈的 AI 应用会随模型漂移和 prompt 演进悄悄退化，无法持续交付。"
  },
  lanes: ["Safety + Ops", "RAG + Chain", "UI + Analytics"],
  laneValues: ["preCheck 通过 + v4 灰度", "召回 5 条 + 图执行", "流式返回 + 反馈落库"],
  log: ["safety 通过 + 命中 v4 灰度", "召回 Top-5 + LangGraph 链路完成", "流式 200 tokens + analytics 落库"],
  summary: ["8 层协作才叫平台", "trace 是归因底座", "评测 + 反馈驱动闭环"],
  sourceTitle: "LangGraph Introduction",
  sourceUrl: "https://langchain-ai.github.io/langgraph/tutorials/introduction/"
});

export const aiApplicationStageTenProductionPlatformLessons: LessonSpec[] = [...knowledgeLessons, project];
