import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "高级 Prompt 与链式调用";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-prompt-chain-message-roles",
    stageId: "ai-app-prompt-chain",
    order: 1,
    eyebrowStage: eyebrow,
    title: "System / User / Assistant 角色",
    concept: "Chat Completions 的 messages 数组以角色区分职责：system 定义人设与硬约束，user 承载真实请求，assistant 记录历史输出。顺序必须严格 system → 交替的 user / assistant，模型才能沿多轮上下文推理。",
    points: ["system 放置人设与硬约束", "user/assistant 交替表达轮次", "顺序错乱会破坏上下文推理"],
    memoryHook: "system 定人设，user/assistant 轮流走",
    fileName: "message-roles.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst res = await openai.chat.completions.create({\n  model: "gpt-4o-mini",\n  messages: [\n    { role: "system", content: "你是资深 Node.js 讲师，用中文回答且拒绝越权。" },\n    { role: "user", content: "解释一下事件循环" },\n    { role: "assistant", content: "事件循环分为 timers、poll、check 等阶段..." },\n    { role: "user", content: "那 setImmediate 和 setTimeout(0) 有什么差别？" }\n  ]\n});\nconsole.log(res.choices[0].message.content);`,
    prompt: "为什么 system 消息通常只放一条且放在最前面？",
    correct: "system 定义全局人设与约束，放最前才能被模型稳定纳入每一轮推理",
    wrong: "system 可以出现任意多条并散落在对话中间，模型会自动合并",
    output: "setImmediate 在 check 阶段触发，setTimeout(0) 在 timers 阶段触发...",
    lanes: ["写 system", "追加用户消息", "调用模型"],
    laneValues: ["讲师人设", "拼接 4 条消息", "gpt-4o-mini 回复"],
    log: ["system 设定讲师人设", "拼接 user/assistant 历史", "模型返回下一轮回答"],
    summary: ["system 是全局约束的唯一入口", "user/assistant 严格交替保多轮上下文", "顺序错乱等于清空短期记忆"],
    sourceTitle: "OpenAI Text Generation",
    sourceUrl: "https://platform.openai.com/docs/guides/text-generation"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-few-shot",
    stageId: "ai-app-prompt-chain",
    order: 2,
    eyebrowStage: eyebrow,
    title: "Few-shot 示例选择",
    concept: "Few-shot 通过在 prompt 中给出输入-输出示例引导模型对齐格式与风格。示例应覆盖典型正/反样本，并按与真实 query 的相似度动态选择，避免固定示例污染上下文。",
    points: ["示例覆盖典型正反样本", "按相似度动态选取示例", "示例过多会挤占上下文预算"],
    memoryHook: "Few-shot = 演示 + 相似度筛选",
    fileName: "few-shot.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst exemplars = [\n  { input: "iPhone 15", output: "{\\"brand\\":\\"Apple\\",\\"category\\":\\"phone\\"}" },\n  { input: "Model Y", output: "{\\"brand\\":\\"Tesla\\",\\"category\\":\\"car\\"}" }\n];\n\nconst shots = exemplars\n  .map((e) => \`输入: \${e.input}\\n输出: \${e.output}\`)\n  .join("\\n\\n");\n\nconst res = await openai.chat.completions.create({\n  model: "gpt-4o-mini",\n  messages: [\n    { role: "system", content: "只输出 JSON。" },\n    { role: "user", content: \`\${shots}\\n\\n输入: MacBook Pro\\n输出:\` }\n  ]\n});\nconsole.log(res.choices[0].message.content);`,
    prompt: "Few-shot 示例数量应该越多越好吗？",
    correct: "不是，示例越多占用越多 token，应挑覆盖度高且与 query 相似的少量样本",
    wrong: "示例越多模型越准，建议一次性塞入 20+ 条覆盖全部品类",
    output: "{\"brand\":\"Apple\",\"category\":\"laptop\"}",
    lanes: ["整理示例", "拼接 prompt", "获取结构化输出"],
    laneValues: ["2 条示例", "shots + query", "JSON 返回"],
    log: ["装载 2 条示例", "按模板拼接 prompt", "模型返回 JSON"],
    summary: ["示例质量高于数量", "动态选取示例避免上下文膨胀", "格式一致才能稳定引导输出"],
    sourceTitle: "OpenAI Text Generation",
    sourceUrl: "https://platform.openai.com/docs/guides/text-generation"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-chain-of-thought",
    stageId: "ai-app-prompt-chain",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Chain-of-Thought 推理",
    concept: "CoT 通过在 prompt 中要求模型显式列出中间推理步骤，提升复杂逻辑题的准确率。生产环境常用 “思考 → 结论” 结构化输出，再从中提取最终答案，避免思路直接暴露给用户。",
    points: ["先思考步骤再给出结论", "用结构化字段分离思路与答案", "对外只暴露 answer 字段"],
    memoryHook: "CoT = 思考过程 + 最终答案分层",
    fileName: "chain-of-thought.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst res = await openai.chat.completions.create({\n  model: "gpt-4o-mini",\n  messages: [\n    { role: "system", content: "先在 reasoning 字段列出推理步骤，再在 answer 字段给出结论，只输出 JSON。" },\n    { role: "user", content: "一个数除以 3 余 2，除以 5 余 3，最小正整数是多少？" }\n  ],\n  response_format: { type: "json_object" }\n});\nconst parsed = JSON.parse(res.choices[0].message.content ?? "{}");\nconsole.log({ answer: parsed.answer });`,
    prompt: "生产环境为什么不建议直接把 CoT 推理过程展示给用户？",
    correct: "思考过程可能泄露 prompt 或包含错误中间步骤，只回传 answer 更安全",
    wrong: "把 reasoning 字段完整展示给用户能提升信任度，应该一直保留",
    output: "{ answer: 8 }",
    lanes: ["请求 CoT", "解析 JSON", "剥离 reasoning"],
    laneValues: ["response_format=json", "parse 结果", "只留 answer"],
    log: ["模型返回 reasoning+answer", "JSON.parse 成功", "对外只暴露 answer"],
    summary: ["CoT 提升复杂题准确率", "结构化字段隔离推理与答案", "生产环境要过滤中间思路"],
    sourceTitle: "OpenAI Text Generation",
    sourceUrl: "https://platform.openai.com/docs/guides/text-generation"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-structured-outputs",
    stageId: "ai-app-prompt-chain",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Structured Outputs 与 JSON Schema",
    concept: "Structured Outputs 让模型严格遵循 JSON Schema 生成输出，杜绝手写 prompt 时 “模型偶尔漏字段” 的问题。相比 json_object 模式，Schema 模式还会对字段类型与枚举做强校验。",
    points: ["Schema 强约束字段与类型", "additionalProperties: false 避免多余字段", "SDK 直接反序列化为对象"],
    memoryHook: "Structured Outputs = Schema 兜底 JSON",
    fileName: "structured-outputs.ts",
    code: `import OpenAI from "openai";\nimport { z } from "zod";\nimport { zodResponseFormat } from "openai/helpers/zod";\n\nconst openai = new OpenAI();\nconst Ticket = z.object({\n  title: z.string(),\n  priority: z.enum(["low", "medium", "high"]),\n  tags: z.array(z.string())\n});\n\nconst res = await openai.chat.completions.parse({\n  model: "gpt-4o-mini",\n  messages: [\n    { role: "system", content: "把用户反馈转成工单结构。" },\n    { role: "user", content: "登录页在 Safari 上白屏，急！" }\n  ],\n  response_format: zodResponseFormat(Ticket, "ticket")\n});\nconst ticket = res.choices[0].message.parsed!;\nconsole.log(ticket.priority);`,
    prompt: "为什么优先用 Structured Outputs 而不是 json_object + 手工校验？",
    correct: "Schema 模式由模型服务端约束字段与类型，避免应用层反复重试与拼接",
    wrong: "json_object 模式已经能 100% 保证字段齐全，Schema 只是语法糖",
    output: "high",
    lanes: ["定义 Schema", "调用 parse", "使用对象"],
    laneValues: ["Zod Ticket", "chat.parse", "读取 priority"],
    log: ["Zod 编译 Schema", "parse 返回强类型对象", "读取 priority=high"],
    summary: ["Schema 是结构化输出的唯一契约", "SDK 反序列化省去手工校验", "additionalProperties:false 防幻觉字段"],
    sourceTitle: "OpenAI Structured Outputs",
    sourceUrl: "https://platform.openai.com/docs/guides/structured-outputs"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-lcel-pipe",
    stageId: "ai-app-prompt-chain",
    order: 5,
    eyebrowStage: eyebrow,
    title: "LCEL 管道操作符",
    concept: "LangChain LCEL 用 `.pipe()` 把 PromptTemplate、Model、OutputParser 组合成可复用的 Runnable。每个组件都实现 Runnable 协议，天然支持 batch/stream/async 与 trace。",
    points: ["Runnable 协议统一接口", ".pipe() 串联组件", "自带 batch/stream/async"],
    memoryHook: "LCEL = Prompt | Model | Parser",
    fileName: "lcel-pipe.ts",
    code: `import { ChatPromptTemplate } from "@langchain/core/prompts";\nimport { ChatOpenAI } from "@langchain/openai";\nimport { StringOutputParser } from "@langchain/core/output_parsers";\n\nconst prompt = ChatPromptTemplate.fromMessages([\n  ["system", "用一句话总结主题。"],\n  ["user", "{topic}"]\n]);\n\nconst chain = prompt.pipe(new ChatOpenAI({ model: "gpt-4o-mini" })).pipe(new StringOutputParser());\nconst summary = await chain.invoke({ topic: "Node.js 事件循环" });\nconsole.log(summary);`,
    prompt: "为什么用 LCEL 而不是手写 for 循环拼接 prompt / 调模型 / 解析？",
    correct: "LCEL 统一 Runnable 接口，天然获得 batch/stream/trace/重试等能力",
    wrong: "LCEL 只是语法糖，手写 for 循环性能更好、更灵活",
    output: "Node.js 事件循环通过阶段化队列驱动异步回调。",
    lanes: ["组装 Runnable", "调用 invoke", "接收 string"],
    laneValues: ["Prompt|Model|Parser", "invoke({topic})", "输出摘要"],
    log: ["Prompt.pipe(Model)", "再 pipe(Parser)", "invoke 返回摘要"],
    summary: ["LCEL 强调组合优先", "统一接口带来 batch/stream", "trace 自动串到 LangSmith"],
    sourceTitle: "LangChain LCEL 概念",
    sourceUrl: "https://python.langchain.com/docs/concepts/lcel/"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-prompt-template",
    stageId: "ai-app-prompt-chain",
    order: 6,
    eyebrowStage: eyebrow,
    title: "PromptTemplate 与变量注入",
    concept: "PromptTemplate 用命名占位符 `{var}` 把 prompt 结构与运行时变量分离。变量在 `.invoke()` 时统一填充，可避免手工字符串拼接导致的转义与漏参问题。",
    points: ["模板与变量分离", "占位符 {var} 显式声明", "invoke 时统一填充与校验"],
    memoryHook: "模板定结构，invoke 传变量",
    fileName: "prompt-template.ts",
    code: `import { ChatPromptTemplate } from "@langchain/core/prompts";\nimport { ChatOpenAI } from "@langchain/openai";\n\nconst prompt = ChatPromptTemplate.fromMessages([\n  ["system", "你是{role}，回答保持 {tone} 语气。"],\n  ["user", "帮我评估这段方案: {content}"]\n]);\n\nconst chain = prompt.pipe(new ChatOpenAI({ model: "gpt-4o-mini" }));\nconst res = await chain.invoke({\n  role: "资深架构师",\n  tone: "严谨",\n  content: "用 SQLite 承担 1w QPS 的电商主库"\n});\nconsole.log(res.content);`,
    prompt: "为什么模板要用 `{var}` 而不是直接在代码里拼接字符串？",
    correct: "模板与变量分离便于版本管理、A/B 测试和自动校验漏参",
    wrong: "字符串拼接更直观，模板只是团队规范，没有实质好处",
    output: "SQLite 单写模型难以支撑 1w QPS，建议改为 PostgreSQL 主从...",
    lanes: ["定义模板", "填充变量", "生成回答"],
    laneValues: ["role/tone/content", "invoke 变量", "架构评估"],
    log: ["模板声明 3 个变量", "invoke 时全部填充", "模型返回评估"],
    summary: ["模板是可复用的 prompt 单元", "变量声明化便于校验", "支持版本管理与 A/B"],
    sourceTitle: "LangChain LCEL 概念",
    sourceUrl: "https://python.langchain.com/docs/concepts/lcel/"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-runnable-branch",
    stageId: "ai-app-prompt-chain",
    order: 7,
    eyebrowStage: eyebrow,
    title: "RunnableBranch 条件分支",
    concept: "RunnableBranch 让 Chain 按运行时条件路由到不同子链：例如 “技术问题走 RAG，闲聊走通用 Chat”。每个分支仍是 Runnable，天然支持组合与 trace。",
    points: ["按条件路由到不同子链", "默认分支兜底未匹配情况", "每个分支仍是 Runnable"],
    memoryHook: "分支 = 条件 → 子链，末位兜底",
    fileName: "runnable-branch.ts",
    code: `import { RunnableBranch, RunnableLambda } from "@langchain/core/runnables";\n\nconst techChain = RunnableLambda.from(async (q: string) => \`[RAG] \${q} 的技术答案\`);\nconst chitChain = RunnableLambda.from(async (q: string) => \`[Chat] 你好，关于「\${q}」我随便聊聊\`);\nconst defaultChain = RunnableLambda.from(async (q: string) => \`[Fallback] \${q}\`);\n\nconst router = RunnableBranch.from([\n  [(q: string) => /error|bug|异常/.test(q), techChain],\n  [(q: string) => /你好|聊聊/.test(q), chitChain],\n  defaultChain\n]);\n\nconsole.log(await router.invoke("聊聊今天天气"));`,
    prompt: "RunnableBranch 里没有匹配任何条件时会发生什么？",
    correct: "会走最后传入的默认分支，避免运行时抛未处理错误",
    wrong: "会抛出未捕获异常，必须外层 try/catch 兜底",
    output: "[Chat] 你好，关于「聊聊今天天气」我随便聊聊",
    lanes: ["评估条件", "路由分支", "执行子链"],
    laneValues: ["匹配聊天", "选择 chitChain", "返回 [Chat]..."],
    log: ["评估 3 个条件", "命中聊天分支", "执行 chitChain"],
    summary: ["条件路由是复杂 Chain 的关键", "默认分支保证鲁棒性", "分支间可以嵌套 LCEL"],
    sourceTitle: "LangChain LCEL 概念",
    sourceUrl: "https://python.langchain.com/docs/concepts/lcel/"
  }),
  createAiAppLesson({
    id: "ai-app-prompt-chain-streaming",
    stageId: "ai-app-prompt-chain",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Streaming 输出与增量解析",
    concept: "流式输出通过 SSE 增量返回 token，显著降低首字节延迟。前端边收边渲染，同时后端可以在流上做增量 JSON 解析或提前终止不合规输出。",
    points: ["stream=true 触发 SSE", "边收边渲染降低 TTFB", "可增量解析或提前终止"],
    memoryHook: "Streaming = SSE 增量 + 边收边处理",
    fileName: "streaming.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst stream = await openai.chat.completions.create({\n  model: "gpt-4o-mini",\n  stream: true,\n  messages: [{ role: "user", content: "写一首关于事件循环的短诗" }]\n});\n\nlet buffer = "";\nfor await (const chunk of stream) {\n  const delta = chunk.choices[0]?.delta?.content ?? "";\n  buffer += delta;\n  process.stdout.write(delta);\n  if (buffer.length > 800) break;\n}`,
    prompt: "流式输出相比一次性等待完整响应的核心收益是什么？",
    correct: "显著降低首字节延迟，用户能立即看到增量内容并可提前终止",
    wrong: "流式仅节省服务器带宽，用户感知延迟没有区别",
    output: "事件循环转呀转 / timers 起舞 poll 忙...",
    lanes: ["开启 stream", "接收 delta", "边收边处理"],
    laneValues: ["stream=true", "for-await chunk", "增量写终端"],
    log: ["stream=true 建立 SSE", "chunk 持续到达", "buffer 超阈值时终止"],
    summary: ["流式让 TTFB 快到可感知", "增量渲染改善体验", "边收边判断可提前止损"],
    sourceTitle: "LangChain Streaming",
    sourceUrl: "https://python.langchain.com/docs/how_to/streaming/"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-prompt-chain-project",
  stageId: "ai-app-prompt-chain",
  eyebrowStage: eyebrow,
  title: "多步 Chain：RAG → 摘要 → 结构化输出",
  brief: "把本阶段的 Prompt 模板、LCEL、Structured Outputs、Streaming 拼成一条多步 Chain：检索资料 → 摘要压缩 → 输出结构化 JSON，供下游系统消费。",
  concept: "多步 Chain 需要每步显式声明输入输出契约：RAG 段落传给摘要，摘要传给结构化输出，最后一步用 Schema 兜底。任意一环失败都能沿 trace 定位。",
  points: ["三段 Chain 显式契约", "末段用 Schema 保结构", "全链路可 stream 与 trace"],
  memoryHook: "Chain = RAG | Summary | Structured",
  fileName: "multi-step-chain.ts",
  code: `import { ChatPromptTemplate } from "@langchain/core/prompts";\nimport { ChatOpenAI } from "@langchain/openai";\nimport { RunnableSequence, RunnableLambda } from "@langchain/core/runnables";\nimport { z } from "zod";\n\nconst Report = z.object({\n  title: z.string(),\n  bullets: z.array(z.string()),\n  risk: z.enum(["low", "medium", "high"])\n});\n\nconst retriever = RunnableLambda.from(async (query: string) => {\n  const docs = await vectorStore.similaritySearch(query, 4);\n  return { query, context: docs.map((d) => d.pageContent).join("\\n\\n") };\n});\n\nconst summarize = ChatPromptTemplate.fromMessages([\n  ["system", "根据 context 用 3 条要点回答 query，保留数字与结论。"],\n  ["user", "query: {query}\\ncontext: {context}"]\n]).pipe(new ChatOpenAI({ model: "gpt-4o-mini" }));\n\nconst structure = new ChatOpenAI({ model: "gpt-4o-mini" }).withStructuredOutput(Report);\n\nconst chain = RunnableSequence.from([\n  retriever,\n  summarize,\n  RunnableLambda.from(async (msg: { content: string }) => msg.content),\n  structure\n]);\n\nconst report = await chain.invoke("上季度支付失败率的主要原因？");\nconsole.log(report.risk, report.bullets);`,
  prompt: "多步 Chain 为什么要在末段用 Schema 而不是让第一段就产出 JSON？",
  correct: "分层职责让每步只做一件事，末段 Schema 兜底避免早期步骤格式漂移影响后续",
  wrong: "在第一步 RAG 输出时就要求 JSON，可以省一次模型调用，性能更好",
  correctFeedback: "正确：Chain 的核心是分层契约，Schema 兜底是防止漂移的最后一道防线。",
  wrongFeedback: "错误：RAG 阶段过早要求 JSON 会牺牲召回质量，也让 Schema 兜底失去意义。",
  additionalWrong: {
    label: "只要最终输出是 JSON，就不需要 trace 与中间摘要，直接问模型即可",
    feedback: "错误：没有中间摘要与 trace，Chain 一旦回归就无法定位是检索、摘要还是结构化环节出错。"
  },
  lanes: ["检索资料", "摘要压缩", "结构化输出"],
  laneValues: ["Top-4 docs", "3 条要点", "Report JSON"],
  log: ["retriever 召回 4 篇文档", "summarize 生成 3 条要点", "structure 输出 Report JSON"],
  summary: ["多步 Chain 要显式契约", "末段 Schema 是漂移防线", "全链路可 stream 与 trace"],
  sourceTitle: "OpenAI Cookbook: Streaming",
  sourceUrl: "https://cookbook.openai.com/examples/how_to_stream_completions"
});

export const aiApplicationStageFivePromptChainLessons: LessonSpec[] = [...knowledgeLessons, project];
