import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "可观测与 Tracing";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-observability-tracing-otel-genai-semconv",
    stageId: "ai-app-observability-tracing",
    order: 1,
    eyebrowStage: eyebrow,
    title: "OpenTelemetry GenAI 语义约定",
    concept: "OpenTelemetry 的 GenAI semantic conventions 规定了 LLM 调用 span 的标准属性：`gen_ai.system`、`gen_ai.request.model`、`gen_ai.usage.input_tokens` 等。使用标准属性名后，任意后端（Jaeger/Tempo/Langfuse）都能自动识别与聚合。",
    points: ["gen_ai.* 命名空间统一属性", "input_tokens/output_tokens 是标准键", "跨后端复用同一份埋点"],
    memoryHook: "标准属性 = 跨后端可移植",
    fileName: "otel-genai-semconv.ts",
    code: `import { trace, SpanKind } from "@opentelemetry/api";\n\nconst tracer = trace.getTracer("ai-app");\n\nexport async function chatWithOtel(model: string, prompt: string) {\n  return tracer.startActiveSpan(\n    "chat gpt-4o-mini",\n    { kind: SpanKind.CLIENT },\n    async (span) => {\n      span.setAttribute("gen_ai.system", "openai");\n      span.setAttribute("gen_ai.operation.name", "chat");\n      span.setAttribute("gen_ai.request.model", model);\n      const res = await callLLM(model, prompt);\n      span.setAttribute("gen_ai.response.model", res.model);\n      span.setAttribute("gen_ai.usage.input_tokens", res.usage.input);\n      span.setAttribute("gen_ai.usage.output_tokens", res.usage.output);\n      span.end();\n      return res;\n    }\n  );\n}`,
    prompt: "为什么要用 `gen_ai.usage.input_tokens` 这类标准属性而不是自己起名？",
    correct: "标准属性名让 Jaeger/Tempo/Langfuse 等后端自动识别、聚合和绘图",
    wrong: "只是命名习惯而已，用 `tokens_in` 也能取到相同效果",
    output: "span attributes: gen_ai.system=openai, gen_ai.usage.input_tokens=128",
    lanes: ["起 span", "写标准属性", "结束上报"],
    laneValues: ["startActiveSpan", "gen_ai.* 属性", "span.end()"],
    log: ["开启 chat span", "写入 gen_ai.request.model", "上报 usage.input_tokens=128"],
    summary: ["GenAI semconv 定义了标准属性名", "标准属性让后端自动识别聚合", "自定义属性放业务命名空间"],
    sourceTitle: "OpenTelemetry Semantic Conventions for GenAI",
    sourceUrl: "https://opentelemetry.io/docs/specs/semconv/gen-ai/"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-span-structure",
    stageId: "ai-app-observability-tracing",
    order: 2,
    eyebrowStage: eyebrow,
    title: "LLM / Retrieval / Tool span 结构",
    concept: "一次 RAG 调用应拆成三类 span：`retrieval` span 记录 query 与命中 chunk，`llm` span 记录 prompt/response 与 token，`tool` span 记录函数调用。三类 span 通过同一个 trace_id 串成树，才能定位到底是召回错还是生成错。",
    points: ["retrieval / llm / tool 三类 span", "共享 trace_id 组成调用树", "每类 span 有专属属性"],
    memoryHook: "分类 span 才能分类归因",
    fileName: "span-structure.ts",
    code: `import { trace } from "@opentelemetry/api";\n\nconst tracer = trace.getTracer("rag-app");\n\nexport async function ragAnswer(question: string) {\n  return tracer.startActiveSpan("rag.answer", async (root) => {\n    const chunks = await tracer.startActiveSpan("retrieval.search", async (s) => {\n      s.setAttribute("retrieval.query", question);\n      const hits = await vectorSearch(question, 4);\n      s.setAttribute("retrieval.hit_count", hits.length);\n      s.end();\n      return hits;\n    });\n    const answer = await tracer.startActiveSpan("llm.generate", async (s) => {\n      s.setAttribute("gen_ai.request.model", "gpt-4o-mini");\n      const res = await generate(question, chunks);\n      s.setAttribute("gen_ai.usage.output_tokens", res.usage.output);\n      s.end();\n      return res.text;\n    });\n    root.end();\n    return answer;\n  });\n}`,
    prompt: "RAG 应用为什么要把 retrieval 与 llm 拆成独立 span？",
    correct: "拆开后能分别归因召回质量与生成质量，而不是把两个问题混成一次失败",
    wrong: "拆开只是让 UI 好看，不拆也能通过 log 定位",
    output: "trace: rag.answer → [retrieval.search hit=4, llm.generate output=256]",
    lanes: ["retrieval span", "llm span", "trace 汇总"],
    laneValues: ["hit_count=4", "output_tokens=256", "trace_id 一致"],
    log: ["retrieval.search 命中 4 条", "llm.generate 输出 256 tokens", "root span 关闭"],
    summary: ["三类 span 对应 RAG 三个失败面", "共享 trace_id 保持链路完整", "每类 span 有专属属性"],
    sourceTitle: "OpenTelemetry JavaScript Instrumentation",
    sourceUrl: "https://opentelemetry.io/docs/languages/js/instrumentation/"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-langsmith-integration",
    stageId: "ai-app-observability-tracing",
    order: 3,
    eyebrowStage: eyebrow,
    title: "LangSmith trace 集成",
    concept: "LangSmith 只需配置 `LANGSMITH_TRACING=true` 与 `LANGSMITH_API_KEY`，配合 `traceable` 装饰任意函数即可自动上报 run。LangChain / LangGraph 无需改代码，因为内置埋点会读取同一份环境变量。",
    points: ["LANGSMITH_TRACING=true 开总开关", "traceable 包裹自定义函数", "LangChain 内置埋点零改动"],
    memoryHook: "两个环境变量 + 一个 traceable",
    fileName: "langsmith-integration.ts",
    code: `import { traceable } from "langsmith/traceable";\nimport OpenAI from "openai";\n\nprocess.env.LANGSMITH_TRACING = "true";\nprocess.env.LANGSMITH_API_KEY = process.env.LANGSMITH_API_KEY ?? "";\nprocess.env.LANGSMITH_PROJECT = "rag-prod";\n\nconst openai = new OpenAI();\n\nexport const answer = traceable(\n  async (question: string) => {\n    const res = await openai.chat.completions.create({\n      model: "gpt-4o-mini",\n      messages: [{ role: "user", content: question }]\n    });\n    return res.choices[0].message.content;\n  },\n  { name: "rag.answer", run_type: "chain" }\n);\n\nawait answer("LangSmith 支持哪些 SDK？");`,
    prompt: "LangSmith 集成后为什么无需修改 LangChain 组件代码就能上报？",
    correct: "LangChain / LangGraph 内置埋点会读取 LANGSMITH_TRACING 等环境变量自动开启上报",
    wrong: "必须在每个 chain 上手动调用 langsmith.log 才会出现在 UI",
    output: "LangSmith run: rag.answer / status=success / project=rag-prod",
    lanes: ["读环境变量", "traceable 包裹", "上报 run"],
    laneValues: ["TRACING=true", "name=rag.answer", "project=rag-prod"],
    log: ["读取 LANGSMITH_API_KEY", "traceable 注册 rag.answer", "上报 run 至 rag-prod"],
    summary: ["环境变量控制全局开关", "traceable 是最小侵入方式", "LangChain 组件天然被埋点"],
    sourceTitle: "LangSmith Observability",
    sourceUrl: "https://docs.smith.langchain.com/observability"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-langfuse-selfhosted",
    stageId: "ai-app-observability-tracing",
    order: 4,
    eyebrowStage: eyebrow,
    title: "Langfuse 自托管 tracing",
    concept: "Langfuse 通过 Docker Compose 可完全自托管，数据留在自己的 Postgres/ClickHouse 中。SDK 用 `trace/span/generation` 三层结构：`generation` 专门表示 LLM 调用，会自动展示 prompt、completion、tokens、cost。",
    points: ["Docker Compose 一键自托管", "trace/span/generation 三层结构", "generation 自动展示 prompt/cost"],
    memoryHook: "自托管 = 数据留内网 + 一键部署",
    fileName: "langfuse-selfhosted.ts",
    code: `import { Langfuse } from "langfuse";\n\nconst langfuse = new Langfuse({\n  publicKey: process.env.LANGFUSE_PUBLIC_KEY!,\n  secretKey: process.env.LANGFUSE_SECRET_KEY!,\n  baseUrl: "https://langfuse.internal.corp"\n});\n\nexport async function answerWithLangfuse(userId: string, question: string) {\n  const trace = langfuse.trace({ name: "rag.answer", userId });\n  const gen = trace.generation({\n    name: "llm.generate",\n    model: "gpt-4o-mini",\n    input: [{ role: "user", content: question }]\n  });\n  const res = await callLLM(question);\n  gen.end({\n    output: res.text,\n    usage: { input: res.usage.input, output: res.usage.output }\n  });\n  await langfuse.flushAsync();\n  return res.text;\n}`,
    prompt: "什么场景下应该优先选 Langfuse 自托管而不是云版？",
    correct: "对数据合规敏感的场景：prompt/completion 不能出企业网，同时又要完整 trace UI",
    wrong: "所有场景都应该自托管，云版不安全不应使用",
    output: "trace: rag.answer / generation llm.generate tokens 128→256",
    lanes: ["建 trace", "开 generation", "flush 上报"],
    laneValues: ["userId 绑定", "model=gpt-4o-mini", "usage 128/256"],
    log: ["trace rag.answer 创建", "generation 记录 prompt", "flushAsync 上报 Langfuse"],
    summary: ["自托管解决数据合规诉求", "generation 是 LLM 专属 span", "flush 决定上报时机"],
    sourceTitle: "Langfuse Tracing",
    sourceUrl: "https://langfuse.com/docs/tracing"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-token-latency-cost",
    stageId: "ai-app-observability-tracing",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Token / 延迟 / 成本指标",
    concept: "每次 LLM 调用都要记录三类核心指标：input/output tokens、端到端 latency、按模型价格算出的 USD cost。这三项拼在同一条 log 上，才能同时回答“慢在哪”“花在哪”“为什么花”。",
    points: ["tokens 拆 input/output 分别记", "latency 覆盖首字节与总时长", "cost 用模型单价换算"],
    memoryHook: "Tokens + Latency + Cost 一条 log",
    fileName: "token-latency-cost.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\nconst PRICE_PER_1K = { input: 0.00015, output: 0.0006 };\n\nexport async function loggedChat(prompt: string) {\n  const started = performance.now();\n  const res = await openai.chat.completions.create({\n    model: "gpt-4o-mini",\n    messages: [{ role: "user", content: prompt }]\n  });\n  const latencyMs = performance.now() - started;\n  const inTok = res.usage!.prompt_tokens;\n  const outTok = res.usage!.completion_tokens;\n  const costUsd = (inTok / 1000) * PRICE_PER_1K.input + (outTok / 1000) * PRICE_PER_1K.output;\n  console.log(JSON.stringify({\n    event: "llm.call",\n    model: "gpt-4o-mini",\n    latency_ms: Math.round(latencyMs),\n    input_tokens: inTok,\n    output_tokens: outTok,\n    cost_usd: Number(costUsd.toFixed(6))\n  }));\n  return res.choices[0].message.content;\n}`,
    prompt: "只记录总 tokens 而不拆 input/output 会带来什么问题？",
    correct: "无法算出准确成本，也无法区分是 prompt 过长还是生成过长导致的开销",
    wrong: "没影响，总 tokens 就够回答成本问题",
    output: `{"event":"llm.call","model":"gpt-4o-mini","latency_ms":812,"input_tokens":128,"output_tokens":256,"cost_usd":0.000173}`,
    lanes: ["计时开始", "调用 LLM", "写指标 log"],
    laneValues: ["performance.now", "usage 拿到", "cost_usd 计算"],
    log: ["开始计时", "调用返回 usage", "写 llm.call JSON log"],
    summary: ["input/output 单独记才能算成本", "latency 是用户体验直接指标", "结构化 JSON 便于聚合"],
    sourceTitle: "OpenAI Cookbook: How to log LLM calls",
    sourceUrl: "https://cookbook.openai.com/examples/how_to_log_llm_calls/"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-error-retry-trace",
    stageId: "ai-app-observability-tracing",
    order: 6,
    eyebrowStage: eyebrow,
    title: "错误 trace 与重试标记",
    concept: "OpenTelemetry 用 `span.recordException(err)` 记录异常，`span.setStatus({ code: SpanStatusCode.ERROR })` 标记失败。重试链路应把每次尝试作为独立 span，并在属性中写 `retry.attempt` 与 `retry.reason`，才能区分“单次错”与“重试后仍错”。",
    points: ["recordException + setStatus 双写", "每次 retry 用独立 span", "retry.attempt 属性做归因"],
    memoryHook: "异常记详情，重试建 span",
    fileName: "error-retry-trace.ts",
    code: `import { trace, SpanStatusCode } from "@opentelemetry/api";\n\nconst tracer = trace.getTracer("ai-app");\n\nexport async function callWithRetry(prompt: string, max = 3) {\n  return tracer.startActiveSpan("llm.call.with_retry", async (root) => {\n    let lastErr: unknown;\n    for (let attempt = 1; attempt <= max; attempt++) {\n      const s = tracer.startSpan("llm.attempt");\n      s.setAttribute("retry.attempt", attempt);\n      try {\n        const res = await callLLM(prompt);\n        s.end();\n        root.setAttribute("retry.total", attempt);\n        root.end();\n        return res;\n      } catch (err) {\n        lastErr = err;\n        s.recordException(err as Error);\n        s.setStatus({ code: SpanStatusCode.ERROR, message: (err as Error).message });\n        s.setAttribute("retry.reason", "upstream_timeout");\n        s.end();\n      }\n    }\n    root.setStatus({ code: SpanStatusCode.ERROR });\n    root.end();\n    throw lastErr;\n  });\n}`,
    prompt: "为什么要给每次重试建立独立 span，而不是复用一个？",
    correct: "独立 span 才能精确区分“第几次失败”“每次错误原因”“总耗时”这些独立维度",
    wrong: "复用一个 span 更省资源，反正最终成功就够了",
    output: "trace: llm.call.with_retry(status=OK, retry.total=2) → llm.attempt[1]=ERROR, llm.attempt[2]=OK",
    lanes: ["第 1 次尝试", "记录异常", "第 2 次尝试"],
    laneValues: ["attempt=1 失败", "recordException", "attempt=2 成功"],
    log: ["attempt=1 超时", "span 记录 ERROR", "attempt=2 返回成功"],
    summary: ["recordException 保留异常堆栈", "每次 retry 独立 span 便于聚合", "retry.attempt 是重要维度"],
    sourceTitle: "OpenTelemetry Semantic Conventions for GenAI",
    sourceUrl: "https://opentelemetry.io/docs/specs/semconv/gen-ai/"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-user-feedback",
    stageId: "ai-app-observability-tracing",
    order: 7,
    eyebrowStage: eyebrow,
    title: "用户反馈信号采集",
    concept: "thumbs up/down、评分、二次追问都是宝贵的在线信号。LangSmith 用 `client.createFeedback(runId, { key, score, comment })` 把用户反馈挂到 run 上，后续可以按分数聚合定位低分 prompt 与低召回率场景。",
    points: ["用 run_id 关联反馈到 trace", "key 区分维度（quality/helpful）", "低分聚合定位薄弱链路"],
    memoryHook: "反馈挂 run_id，聚合看趋势",
    fileName: "user-feedback.ts",
    code: `import { Client } from "langsmith";\n\nconst client = new Client();\n\nexport async function submitThumb(runId: string, thumb: "up" | "down", comment?: string) {\n  await client.createFeedback(runId, "user_thumb", {\n    score: thumb === "up" ? 1 : 0,\n    comment,\n    feedbackSourceType: "app"\n  });\n}\n\nexport async function submitRating(runId: string, stars: number) {\n  await client.createFeedback(runId, "quality", {\n    score: stars / 5,\n    value: stars,\n    feedbackSourceType: "app"\n  });\n}\n\nawait submitThumb("run_abc123", "down", "答案没提到 2024 数据");`,
    prompt: "用户点了 thumb down，最有价值的追踪动作是什么？",
    correct: "把 thumb down 通过 run_id 挂到该次 trace 上，按低分聚合定位薄弱 prompt/召回",
    wrong: "只在业务库里记一行 log，与 trace 无关联",
    output: "feedback: runId=run_abc123 key=user_thumb score=0 comment=\"答案没提到 2024 数据\"",
    lanes: ["用户点击", "写 feedback", "关联 run"],
    laneValues: ["thumb=down", "createFeedback", "run_id 绑定"],
    log: ["用户点 thumb down", "createFeedback score=0", "关联 run_abc123"],
    summary: ["反馈必须绑定 run_id", "key 支持多维度", "低分是最好的迭代信号"],
    sourceTitle: "LangSmith: Collect User Feedback",
    sourceUrl: "https://docs.smith.langchain.com/observability/how_to_guides/monitoring/user_feedback"
  }),
  createAiAppLesson({
    id: "ai-app-observability-tracing-sampling-storage",
    stageId: "ai-app-observability-tracing",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Trace 采样与存储策略",
    concept: "生产环境全量存 trace 成本极高。常见做法：正常请求按 10% `TraceIdRatioBased` 采样，错误/高延迟/低反馈请求 100% 采样（tail-based sampling）。历史 trace 冷存到对象存储，热数据保留 7-30 天。",
    points: ["head sampling 用比例控制成本", "tail sampling 保留错误全量", "冷热分层控制存储成本"],
    memoryHook: "错误全采，正常抽样，历史冷存",
    fileName: "sampling-storage.ts",
    code: `import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node";\nimport {\n  ParentBasedSampler,\n  TraceIdRatioBasedSampler\n} from "@opentelemetry/sdk-trace-base";\n\nconst provider = new NodeTracerProvider({\n  sampler: new ParentBasedSampler({\n    root: new TraceIdRatioBasedSampler(0.1)\n  })\n});\n\nprovider.register();\n\nexport function shouldForceKeep(ctx: { error?: boolean; latencyMs?: number; thumb?: "up" | "down" }) {\n  if (ctx.error) return true;\n  if ((ctx.latencyMs ?? 0) > 3000) return true;\n  if (ctx.thumb === "down") return true;\n  return false;\n}`,
    prompt: "生产 QPS 很高时为什么不能全量存 trace？",
    correct: "存储和查询成本会指数上升，用比例采样 + 关键路径全采能保留证据同时可控成本",
    wrong: "现代存储很便宜，全量存永远都是最优解",
    output: "sampler: ParentBased(root=TraceIdRatio(0.1)) → 正常 10% + 错误/慢/低分强制 100%",
    lanes: ["配置采样器", "计算命中", "强制关键 trace"],
    laneValues: ["ratio=0.1", "10% 通过", "error/high-latency 强制"],
    log: ["设置 TraceIdRatioBased 0.1", "普通请求 10% 命中", "error/慢请求强制保留"],
    summary: ["采样是成本与证据的平衡", "错误/慢/低分要 100% 保留", "冷热分层控制长期成本"],
    sourceTitle: "OpenTelemetry JavaScript Instrumentation",
    sourceUrl: "https://opentelemetry.io/docs/languages/js/instrumentation/"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-observability-tracing-project",
  stageId: "ai-app-observability-tracing",
  eyebrowStage: eyebrow,
  title: "RAG 应用端到端 Tracing",
  brief: "给一个 RAG 问答系统接入完整可观测链路：retrieval span 记录召回、llm span 记录 token/cost、错误自动打标、用户反馈挂到 run，采样策略保证错误 100% 保留。",
  concept: "串联本阶段：OTel GenAI semconv、三类 span 结构、LangSmith/Langfuse 上报、token/latency/cost 指标、错误与反馈信号、采样策略，形成一条可回溯、可归因、可迭代的 RAG trace 链路。",
  points: ["三类 span 拆开归因", "指标 + 反馈联合驱动迭代", "错误/低分强制保留 trace"],
  memoryHook: "端到端 = span + 指标 + 反馈 + 采样",
  fileName: "rag-tracing.ts",
  code: `import { trace, SpanStatusCode } from "@opentelemetry/api";\nimport { Client } from "langsmith";\n\nconst tracer = trace.getTracer("rag-app");\nconst ls = new Client();\n\nexport async function ragAnswer(userId: string, question: string) {\n  return tracer.startActiveSpan("rag.answer", async (root) => {\n    root.setAttribute("user.id", userId);\n    try {\n      const chunks = await tracer.startActiveSpan("retrieval.search", async (s) => {\n        s.setAttribute("retrieval.query", question);\n        const hits = await vectorSearch(question, 4);\n        s.setAttribute("retrieval.hit_count", hits.length);\n        s.end();\n        return hits;\n      });\n\n      const res = await tracer.startActiveSpan("llm.generate", async (s) => {\n        s.setAttribute("gen_ai.system", "openai");\n        s.setAttribute("gen_ai.request.model", "gpt-4o-mini");\n        const started = performance.now();\n        const out = await generate(question, chunks);\n        s.setAttribute("gen_ai.usage.input_tokens", out.usage.input);\n        s.setAttribute("gen_ai.usage.output_tokens", out.usage.output);\n        s.setAttribute("gen_ai.latency_ms", Math.round(performance.now() - started));\n        s.end();\n        return out;\n      });\n\n      root.setAttribute("rag.answer_chars", res.text.length);\n      root.end();\n      return { runId: root.spanContext().traceId, text: res.text };\n    } catch (err) {\n      root.recordException(err as Error);\n      root.setStatus({ code: SpanStatusCode.ERROR });\n      root.end();\n      throw err;\n    }\n  });\n}\n\nexport async function onUserThumb(runId: string, thumb: "up" | "down") {\n  await ls.createFeedback(runId, "user_thumb", {\n    score: thumb === "up" ? 1 : 0,\n    feedbackSourceType: "app"\n  });\n}`,
  prompt: "RAG 用户反馈“答案不准”时，最先要沿 trace 看什么？",
  correct: "先看 retrieval span 的 hit_count 与召回 chunk，再看 llm span 的 prompt/completion，定位是召回错还是生成错",
  wrong: "直接重跑一次 prompt，看能不能复现错误答案",
  correctFeedback: "正确：分层归因是 RAG debug 的第一原则——先看召回再看生成。",
  wrongFeedback: "错误：不看 trace 直接重跑会掩盖真正的失败面，且 LLM 不确定性会误导判断。",
  additionalWrong: {
    label: "只把 thumb down 写进业务库，与 trace 不做关联",
    feedback: "错误：反馈脱离 trace 后无法按低分聚合定位薄弱 prompt/召回，迭代失去证据链。"
  },
  lanes: ["retrieval span", "llm span", "反馈+采样"],
  laneValues: ["hit_count=4", "usage 128/256", "thumb 挂 runId"],
  log: ["retrieval.search 命中 4 条", "llm.generate 输出 256 tokens", "user_thumb 挂到 runId"],
  summary: ["三类 span 分层归因", "指标与反馈用 runId 串联", "错误/低分 100% 采样保证证据"],
  sourceTitle: "LangSmith Observability",
  sourceUrl: "https://docs.smith.langchain.com/observability"
});

export const aiApplicationStageNineObservabilityTracingLessons: LessonSpec[] = [...knowledgeLessons, project];
