import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "向量检索与混合搜索";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-vector-retrieval-embedding-basics",
    stageId: "ai-app-vector-retrieval",
    order: 1,
    eyebrowStage: eyebrow,
    title: "Embedding 生成基础",
    concept: "Embedding 把文本映射为固定维度向量，语义相近的文本在余弦空间中距离更小。`text-embedding-3-small` 输出 1536 维，成本比 3-large 更低，是 RAG 场景默认起点。",
    points: ["选定模型即锁定维度与相似度语义", "批量 embed 摊平网络开销", "维度决定后续存储与检索成本"],
    memoryHook: "同一个模型，同一个坐标系",
    fileName: "embedding-basics.ts",
    code: `import OpenAI from "openai";\n\nconst openai = new OpenAI();\n\nconst docs = [\n  "Node.js 是基于 V8 的服务端运行时",\n  "Deno 也基于 V8，但默认更安全",\n  "React 是前端 UI 库"\n];\n\nconst res = await openai.embeddings.create({\n  model: "text-embedding-3-small",\n  input: docs\n});\n\nconst vectors = res.data.map((d) => d.embedding);\nconsole.log(vectors.length, vectors[0].length);`,
    prompt: "为什么同一个知识库的所有 chunk 必须使用同一个 embedding 模型？",
    correct: "不同模型的向量空间不可比，混用会让相似度分数完全失去意义",
    wrong: "只要维度一样就可以随意混用不同模型的向量",
    output: "3 1536",
    lanes: ["准备文档", "调用 embed", "得到向量"],
    laneValues: ["3 段文本", "text-embedding-3-small", "3 × 1536"],
    log: ["准备 3 段文本", "调用 text-embedding-3-small", "返回 3 × 1536 向量"],
    summary: ["模型决定向量空间", "批量调用降低延迟", "维度直接影响后续存储成本"],
    sourceTitle: "OpenAI Embeddings",
    sourceUrl: "https://platform.openai.com/docs/guides/embeddings"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-pgvector-upsert",
    stageId: "ai-app-vector-retrieval",
    order: 2,
    eyebrowStage: eyebrow,
    title: "向量数据库写入",
    concept: "pgvector 用 `vector(dim)` 列存储 embedding，配合 HNSW 索引支持 ANN。写入时把文档、元数据、向量一并入库，检索时才能同时做过滤与相似度排序。",
    points: ["向量列维度必须与模型输出一致", "HNSW 是通用 ANN 首选索引", "元数据字段用于检索前过滤"],
    memoryHook: "存向量要连身份证一起存",
    fileName: "pgvector-upsert.ts",
    code: `import postgres from "postgres";\nimport OpenAI from "openai";\n\nconst sql = postgres(process.env.DATABASE_URL!);\nconst openai = new OpenAI();\n\nasync function upsert(docs: { id: string; text: string; tag: string }[]) {\n  const res = await openai.embeddings.create({\n    model: "text-embedding-3-small",\n    input: docs.map((d) => d.text)\n  });\n  for (let i = 0; i < docs.length; i++) {\n    const vec = \`[\${res.data[i].embedding.join(",")}]\`;\n    await sql\`insert into kb(id, text, tag, embedding)\n              values (\${docs[i].id}, \${docs[i].text}, \${docs[i].tag}, \${vec}::vector)\n              on conflict (id) do update set text=excluded.text, embedding=excluded.embedding\`;\n  }\n}\n\nawait upsert([{ id: "d1", text: "Node.js 事件循环", tag: "runtime" }]);`,
    prompt: "向量入库时同时保存 tag/source 等元数据的主要目的是什么？",
    correct: "检索时可以先按元数据过滤子集，再做相似度排序，兼顾精度与性能",
    wrong: "只是方便调试，实际检索完全靠向量距离即可",
    output: "INSERT 0 1",
    lanes: ["生成向量", "写入行", "建立索引"],
    laneValues: ["1 × 1536", "kb 表 upsert", "HNSW 就绪"],
    log: ["调用 embedding 得到 1 × 1536", "upsert 到 kb 表", "HNSW 索引可用"],
    summary: ["维度与模型必须匹配", "元数据过滤+向量排序是标准姿势", "HNSW 索引是 pgvector 默认选择"],
    sourceTitle: "pgvector",
    sourceUrl: "https://github.com/pgvector/pgvector"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-ann-topk",
    stageId: "ai-app-vector-retrieval",
    order: 3,
    eyebrowStage: eyebrow,
    title: "ANN 检索与 top_k",
    concept: "ANN 用近邻图或倒排量化在牺牲极少召回率的前提下大幅提速。`top_k` 决定返回候选数，距离度量要与 embedding 训练时一致，OpenAI embedding 通常用余弦相似度。",
    points: ["top_k 太小会漏召回，太大会污染上下文", "距离度量必须与模型训练一致", "HNSW 的 efSearch 控制精度/延迟"],
    memoryHook: "top_k 调召回，度量决语义",
    fileName: "ann-topk.ts",
    code: `import postgres from "postgres";\nimport OpenAI from "openai";\n\nconst sql = postgres(process.env.DATABASE_URL!);\nconst openai = new OpenAI();\n\nasync function search(query: string, topK = 5) {\n  const [{ embedding }] = (\n    await openai.embeddings.create({\n      model: "text-embedding-3-small",\n      input: [query]\n    })\n  ).data;\n  const vec = \`[\${embedding.join(",")}]\`;\n  return sql\`select id, text, 1 - (embedding <=> \${vec}::vector) as score\n              from kb\n              order by embedding <=> \${vec}::vector\n              limit \${topK}\`;\n}\n\nconst rows = await search("Node 的事件循环怎么调度", 5);\nconsole.log(rows.map((r) => r.id));`,
    prompt: "线上召回率偏低但延迟很好，最先该调整哪个参数？",
    correct: "提高 top_k 或 HNSW 的 efSearch 换取召回率，再评估延迟能否接受",
    wrong: "直接换成更大的 embedding 模型重建索引",
    output: "[ 'd1', 'd7', 'd3', 'd12', 'd5' ]",
    lanes: ["query embed", "ANN 检索", "返回 top_k"],
    laneValues: ["1 × 1536", "HNSW 搜索", "5 条候选"],
    log: ["query 转向量", "ANN 遍历 HNSW", "返回 5 条结果"],
    summary: ["top_k 影响召回与上下文噪声", "距离度量必须与模型对齐", "efSearch 调节精度延迟平衡"],
    sourceTitle: "pgvector",
    sourceUrl: "https://github.com/pgvector/pgvector"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-hybrid-search",
    stageId: "ai-app-vector-retrieval",
    order: 4,
    eyebrowStage: eyebrow,
    title: "向量 + BM25 混合检索",
    concept: "向量擅长语义相近，BM25 擅长关键词与实体命中，两者互补。常用做法是并行召回 → RRF (Reciprocal Rank Fusion) 融合排名，再交给 rerank 精排。",
    points: ["向量补语义，BM25 补关键词", "RRF 融合不依赖分数绝对值", "融合后再 rerank 精度更高"],
    memoryHook: "语义配关键词，融合靠 RRF",
    fileName: "hybrid-search.ts",
    code: `type Hit = { id: string; rank: number };\n\nfunction rrf(lists: Hit[][], k = 60) {\n  const scores = new Map<string, number>();\n  for (const list of lists) {\n    for (const hit of list) {\n      scores.set(hit.id, (scores.get(hit.id) ?? 0) + 1 / (k + hit.rank));\n    }\n  }\n  return [...scores.entries()]\n    .sort((a, b) => b[1] - a[1])\n    .map(([id, score]) => ({ id, score }));\n}\n\nconst vectorHits: Hit[] = [{ id: "d1", rank: 1 }, { id: "d2", rank: 2 }];\nconst bm25Hits: Hit[] = [{ id: "d2", rank: 1 }, { id: "d3", rank: 2 }];\n\nconst fused = rrf([vectorHits, bm25Hits]);\nconsole.log(fused.slice(0, 3));`,
    prompt: "已经有向量检索，为什么还要引入 BM25 关键词检索？",
    correct: "BM25 对专有名词、错别字、稀有词命中更稳，与向量语义召回互补",
    wrong: "BM25 更快，可以直接替代向量检索节省成本",
    output: "[ { id: 'd2', score: 0.0328 }, { id: 'd1', score: 0.0164 }, { id: 'd3', score: 0.0161 } ]",
    lanes: ["向量召回", "BM25 召回", "RRF 融合"],
    laneValues: ["2 条向量结果", "2 条 BM25 结果", "3 条融合结果"],
    log: ["向量返回 d1,d2", "BM25 返回 d2,d3", "RRF 融合排序"],
    summary: ["向量与 BM25 语义互补", "RRF 免调分数量纲", "融合后仍需 rerank 精排"],
    sourceTitle: "LangChain Retrievers",
    sourceUrl: "https://python.langchain.com/docs/how_to/retrievers/"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-rerank-model",
    stageId: "ai-app-vector-retrieval",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Rerank 精排",
    concept: "Rerank 用 cross-encoder 对 (query, passage) 打分，比单塔 embedding 更准。生产上先用向量/BM25 召回 Top-50，再用 Cohere Rerank 或 bge-reranker 精排到 Top-5。",
    points: ["cross-encoder 精度高但只能做精排", "召回宽 + 精排窄是常规组合", "top_n 由上下文预算决定"],
    memoryHook: "召回抓宽，rerank 收窄",
    fileName: "rerank-model.ts",
    code: `import { CohereClient } from "cohere-ai";\n\nconst cohere = new CohereClient({ token: process.env.COHERE_API_KEY });\n\nasync function rerank(query: string, candidates: { id: string; text: string }[], topN = 5) {\n  const res = await cohere.rerank({\n    model: "rerank-english-v3.0",\n    query,\n    documents: candidates.map((c) => c.text),\n    topN\n  });\n  return res.results.map((r) => ({\n    id: candidates[r.index].id,\n    score: r.relevanceScore\n  }));\n}\n\nconst reranked = await rerank("event loop", [\n  { id: "d1", text: "Node.js 事件循环调度阶段" },\n  { id: "d2", text: "React 组件生命周期" }\n]);\nconsole.log(reranked);`,
    prompt: "Top-50 召回 + Top-5 rerank 的两段式为什么优于只用向量取 Top-5？",
    correct: "召回段追求 recall，精排段用 cross-encoder 换取精度，整体优于单一模型",
    wrong: "只是为了让链路看起来更复杂，效果和单段向量检索一致",
    output: "[ { id: 'd1', score: 0.92 }, { id: 'd2', score: 0.08 } ]",
    lanes: ["候选集", "cross-encoder", "Top-N 输出"],
    laneValues: ["2 条候选", "rerank-english-v3", "Top-5"],
    log: ["候选 2 条", "调用 rerank 模型", "输出精排分数"],
    summary: ["召回宽 + 精排窄", "cross-encoder 精度换速度", "top_n 结合上下文预算"],
    sourceTitle: "Cohere Rerank",
    sourceUrl: "https://docs.cohere.com/docs/rerank-2"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-chunking-strategy",
    stageId: "ai-app-vector-retrieval",
    order: 6,
    eyebrowStage: eyebrow,
    title: "文档切分策略",
    concept: "chunk 过大导致向量语义稀释，过小又切碎上下文。常见做法是 500-800 tokens、10-15% overlap，或按 heading/句子边界做 semantic split，保留结构信号。",
    points: ["chunk_size 决定语义密度", "overlap 缓解边界丢失", "语义/结构切分优于纯字符切"],
    memoryHook: "块要合身，边界要有余",
    fileName: "chunking-strategy.ts",
    code: `type Chunk = { id: string; text: string; sourceId: string };\n\nfunction chunkByParagraph(text: string, size = 600, overlap = 80): string[] {\n  const paragraphs = text.split(/\\n{2,}/);\n  const chunks: string[] = [];\n  let buf = "";\n  for (const p of paragraphs) {\n    if ((buf + p).length > size) {\n      chunks.push(buf.trim());\n      buf = buf.slice(-overlap) + p;\n    } else {\n      buf += "\\n\\n" + p;\n    }\n  }\n  if (buf.trim()) chunks.push(buf.trim());\n  return chunks;\n}\n\nconst chunks: Chunk[] = chunkByParagraph(longDoc).map((text, i) => ({\n  id: \`doc-42#\${i}\`,\n  text,\n  sourceId: "doc-42"\n}));\nconsole.log(chunks.length);`,
    prompt: "PDF 手册按每 500 字硬切召回效果差，最该先调什么？",
    correct: "改成按段落/heading 切分，并保留 10% overlap 让边界信息不丢",
    wrong: "把 chunk 缩到 100 字提高召回粒度",
    output: "18",
    lanes: ["原始文档", "语义切分", "生成 chunks"],
    laneValues: ["1 份长文", "段落 + overlap", "18 个 chunk"],
    log: ["读取原始文档", "按段落切分", "生成 18 个 chunk"],
    summary: ["chunk_size 影响语义密度", "overlap 补边界信息", "按结构切分优于纯字符切"],
    sourceTitle: "LangChain Retrievers",
    sourceUrl: "https://python.langchain.com/docs/how_to/retrievers/"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-cache-and-updates",
    stageId: "ai-app-vector-retrieval",
    order: 7,
    eyebrowStage: eyebrow,
    title: "检索缓存与增量更新",
    concept: "热点 query 的召回结果可 KV 缓存降低延迟与成本；知识库更新时按 sourceId 增量 upsert，删除旧 chunk 并重建 embedding，避免全量重跑。",
    points: ["query→results 缓存吃热点", "按 sourceId 做增量替换", "版本号或 hash 判断是否需要重 embed"],
    memoryHook: "热点走缓存，更新走增量",
    fileName: "cache-and-updates.ts",
    code: `import { createHash } from "node:crypto";\nimport { redis } from "./redis";\nimport { sql } from "./db";\nimport { embed } from "./embed";\n\nfunction hash(text: string) {\n  return createHash("sha1").update(text).digest("hex");\n}\n\nexport async function cachedSearch(query: string, run: () => Promise<unknown>) {\n  const key = \`ret:\${hash(query)}\`;\n  const cached = await redis.get(key);\n  if (cached) return JSON.parse(cached);\n  const fresh = await run();\n  await redis.set(key, JSON.stringify(fresh), "EX", 300);\n  return fresh;\n}\n\nexport async function upsertDoc(sourceId: string, chunks: { id: string; text: string }[]) {\n  await sql\`delete from kb where source_id = \${sourceId}\`;\n  for (const c of chunks) {\n    const vec = await embed(c.text);\n    await sql\`insert into kb(id, source_id, text, embedding) values (\${c.id}, \${sourceId}, \${c.text}, \${vec})\`;\n  }\n}`,
    prompt: "知识库中某一份文档更新了，最稳的做法是？",
    correct: "按 sourceId 先删除旧 chunk，再重建向量并写回，避免残留过期条目",
    wrong: "只在旧向量后追加新 chunk，让检索按分数自然覆盖旧内容",
    output: "cache miss → embed → cache set",
    lanes: ["查缓存", "回源检索", "写回缓存"],
    laneValues: ["ret:sha1", "run() 执行", "EX 300"],
    log: ["cache miss", "回源执行召回", "写回 300s 缓存"],
    summary: ["热点缓存显著降延迟", "sourceId 是增量替换单元", "hash/version 决定是否重 embed"],
    sourceTitle: "OpenAI Cookbook: Vector DB",
    sourceUrl: "https://cookbook.openai.com/examples/vector_databases/"
  }),
  createAiAppLesson({
    id: "ai-app-vector-retrieval-retrieval-eval",
    stageId: "ai-app-vector-retrieval",
    order: 8,
    eyebrowStage: eyebrow,
    title: "检索质量评测",
    concept: "线上迭代必须有可复现的检索评测集：给定 query 与标注 relevant doc_id，计算 Recall@k 和 MRR。任何参数调整都要跑评测再上线，避免主观判断。",
    points: ["Recall@k 衡量召回覆盖率", "MRR 衡量首命中位置", "评测集要覆盖长尾 query"],
    memoryHook: "无评测不上线，无标注不迭代",
    fileName: "retrieval-eval.ts",
    code: `type EvalCase = { query: string; relevant: Set<string> };\n\nasync function evaluate(cases: EvalCase[], search: (q: string) => Promise<string[]>, k = 5) {\n  let recallHits = 0;\n  let mrrSum = 0;\n  for (const c of cases) {\n    const ids = await search(c.query);\n    const topK = ids.slice(0, k);\n    if (topK.some((id) => c.relevant.has(id))) recallHits += 1;\n    const firstRank = topK.findIndex((id) => c.relevant.has(id));\n    if (firstRank >= 0) mrrSum += 1 / (firstRank + 1);\n  }\n  return {\n    recallAtK: recallHits / cases.length,\n    mrr: mrrSum / cases.length\n  };\n}\n\nconst metrics = await evaluate(cases, hybridSearch, 5);\nconsole.log(metrics);`,
    prompt: "把 top_k 从 5 调到 10 后 Recall@5 反而下降，该怎么解读？",
    correct: "评测未通过就不该上线，回滚参数并检查是否引入了噪声候选压低 rerank 排序",
    wrong: "召回数变多总是更好，直接上线让线上数据说话",
    output: "{ recallAtK: 0.82, mrr: 0.61 }",
    lanes: ["加载评测集", "跑检索", "计算指标"],
    laneValues: ["100 条 case", "hybridSearch", "Recall/MRR"],
    log: ["加载 100 条 case", "跑一遍 hybridSearch", "输出 Recall/MRR"],
    summary: ["评测集是参数调整的裁判", "Recall@k 与 MRR 互补", "上线前必须先跑评测"],
    sourceTitle: "OpenAI Cookbook: Vector DB",
    sourceUrl: "https://cookbook.openai.com/examples/vector_databases/"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-vector-retrieval-project",
  stageId: "ai-app-vector-retrieval",
  eyebrowStage: eyebrow,
  title: "端到端向量检索管线",
  brief: "构建一条完整检索管线：文档切分 → embedding 入库 (pgvector) → 向量 + BM25 混合召回 → Cohere Rerank 精排 → 输出 Top-K 供 LLM 使用，并在评测集上验证 Recall@5 与 MRR。",
  concept: "串联本阶段知识点：切分策略、embedding、pgvector 写入、ANN 检索、混合召回、rerank 精排、评测，形成一个可交付的 RAG 检索层。",
  points: ["宽召回窄精排是主流架构", "缓存 + 增量更新兼顾成本与新鲜度", "评测集是迭代的唯一裁判"],
  memoryHook: "召回宽、rerank 窄、评测把关",
  fileName: "pipeline.ts",
  code: `import { chunkByParagraph } from "./chunking-strategy";\nimport { upsertDoc } from "./cache-and-updates";\nimport { vectorSearch } from "./ann-topk";\nimport { bm25Search } from "./bm25";\nimport { rrf } from "./hybrid-search";\nimport { rerank } from "./rerank-model";\nimport { evaluate } from "./retrieval-eval";\n\nexport async function ingest(sourceId: string, raw: string) {\n  const chunks = chunkByParagraph(raw).map((text, i) => ({\n    id: \`\${sourceId}#\${i}\`,\n    text\n  }));\n  await upsertDoc(sourceId, chunks);\n}\n\nexport async function retrieve(query: string, topK = 5) {\n  const [vec, bm25] = await Promise.all([\n    vectorSearch(query, 50),\n    bm25Search(query, 50)\n  ]);\n  const fused = rrf([vec, bm25]).slice(0, 20);\n  const candidates = await loadTexts(fused.map((h) => h.id));\n  const reranked = await rerank(query, candidates, topK);\n  return reranked;\n}\n\nconst metrics = await evaluate(cases, retrieve, 5);\nconsole.log("release gate", metrics);`,
  prompt: "该管线上线前最应该守住哪一道闸门？",
  correct: "在评测集上确认 Recall@5 与 MRR 不劣于基线，再放量上线",
  wrong: "只要人工抽查几个 query 看起来合理就可以上线",
  correctFeedback: "正确：评测集是唯一可复现的裁判，能防止 chunk/topK/rerank 参数调整引入回归。",
  wrongFeedback: "错误：人工抽查覆盖不到长尾 query，检索回归上线后才能被用户感知就已经晚了。",
  additionalWrong: {
    label: "只跑单元测试验证代码路径，不需要跑检索评测",
    feedback: "错误：单元测试无法度量召回率和排序质量，必须用带标注的评测集。"
  },
  lanes: ["召回", "融合精排", "评测放行"],
  laneValues: ["向量 + BM25", "RRF + rerank", "Recall/MRR"],
  log: ["并行召回向量与 BM25", "RRF 融合并 rerank", "评测集验证放行"],
  summary: ["召回宽 + 精排窄是主流结构", "评测集把关每次参数调整", "缓存与增量更新是运行时基础"],
  sourceTitle: "OpenAI Cookbook: Vector DB",
  sourceUrl: "https://cookbook.openai.com/examples/vector_databases/"
});

export const aiApplicationStageFourVectorRetrievalLessons: LessonSpec[] = [...knowledgeLessons, project];
