import type { LessonSpec } from "../../../lib/curriculum/types";
import { createAiAppLesson, createAiAppStageProject } from "./ai-application-lesson-factory";

const eyebrow = "模型选型与路由";

const knowledgeLessons: LessonSpec[] = [
  createAiAppLesson({
    id: "ai-app-model-selection-capability-matrix",
    stageId: "ai-app-model-selection",
    order: 1,
    eyebrowStage: eyebrow,
    title: "模型能力矩阵",
    concept: "GPT-4o、Claude 3.5 Sonnet、Gemini 1.5 Pro、开源 Llama/Qwen 在推理深度、上下文长度、多模态、成本与部署方式上各有权衡。选型第一步是把候选模型按能力维度做成矩阵，而不是只看一个综合分。",
    points: ["按维度矩阵化：推理/上下文/多模态/成本/部署", "闭源综合稳定，开源可私有部署与微调", "官方模型页是能力和限制的第一来源"],
    memoryHook: "选模型 = 看矩阵，不看总分",
    fileName: "capability-matrix.ts",
    code: `type Capability = {\n  id: string;\n  vendor: \"openai\" | \"anthropic\" | \"google\" | \"oss\";\n  contextTokens: number;\n  multimodal: (\"text\" | \"vision\" | \"audio\")[];\n  toolUse: boolean;\n  inputPricePerMTok: number;\n};\n\nexport const matrix: Capability[] = [\n  { id: \"gpt-4o\", vendor: \"openai\", contextTokens: 128_000, multimodal: [\"text\", \"vision\", \"audio\"], toolUse: true, inputPricePerMTok: 2.5 },\n  { id: \"claude-3-5-sonnet\", vendor: \"anthropic\", contextTokens: 200_000, multimodal: [\"text\", \"vision\"], toolUse: true, inputPricePerMTok: 3 },\n  { id: \"gemini-1.5-pro\", vendor: \"google\", contextTokens: 2_000_000, multimodal: [\"text\", \"vision\", \"audio\"], toolUse: true, inputPricePerMTok: 1.25 },\n  { id: \"llama-3.1-70b\", vendor: \"oss\", contextTokens: 128_000, multimodal: [\"text\"], toolUse: true, inputPricePerMTok: 0.6 }\n];\n\nconsole.log(matrix.filter((m) => m.contextTokens >= 200_000).map((m) => m.id));`,
    prompt: "为一个需要处理 30 万 token 长合同的任务选模型，最合理的判断依据是？",
    correct: "查能力矩阵中 contextTokens ≥ 300k 的候选，再叠加成本和质量约束",
    wrong: "直接选行业热度最高的 GPT-4o，长文档截断即可",
    output: "['claude-3-5-sonnet', 'gemini-1.5-pro']",
    lanes: ["加载矩阵", "按维度过滤", "输出候选"],
    laneValues: ["4 个模型", "context≥200k", "2 个候选"],
    log: ["加载 4 个模型能力", "筛选 contextTokens≥200k", "输出 2 个候选"],
    summary: ["能力矩阵是选型的第一手证据", "维度化避免被单一榜单误导", "开源模型的价值在部署与微调"],
    sourceTitle: "OpenAI Models",
    sourceUrl: "https://platform.openai.com/docs/models"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-complexity-routing",
    stageId: "ai-app-model-selection",
    order: 2,
    eyebrowStage: eyebrow,
    title: "任务复杂度分级路由",
    concept: "把任务分成简单（FAQ、分类）、中等（摘要、结构化抽取）、复杂（多步推理、代码生成）三档，分别路由到便宜/中档/旗舰模型。分级路由可在不牺牲效果的前提下显著降成本。",
    points: ["按任务复杂度分 3 档路由", "先分类器判档，再选模型", "旗舰模型只留给真复杂任务"],
    memoryHook: "先分档，再选型",
    fileName: "complexity-routing.ts",
    code: `type Tier = \"simple\" | \"medium\" | \"complex\";\n\nconst modelByTier: Record<Tier, string> = {\n  simple: \"gpt-4o-mini\",\n  medium: \"claude-3-5-haiku\",\n  complex: \"gpt-4o\"\n};\n\nfunction classify(task: { intent: string; steps: number }): Tier {\n  if (task.intent === \"faq\" || task.intent === \"classify\") return \"simple\";\n  if (task.steps <= 2) return \"medium\";\n  return \"complex\";\n}\n\nexport function route(task: { intent: string; steps: number }) {\n  const tier = classify(task);\n  return { tier, model: modelByTier[tier] };\n}\n\nconsole.log(route({ intent: \"multi-hop-reasoning\", steps: 5 }));`,
    prompt: "线上 80% 请求是 FAQ 问答，最合理的路由策略是？",
    correct: "用便宜模型服务 FAQ，把旗舰模型留给少量真正复杂的推理请求",
    wrong: "为了体验一致，所有请求都走 GPT-4o 保证质量",
    output: "{ tier: 'complex', model: 'gpt-4o' }",
    lanes: ["接收任务", "复杂度分类", "选定模型"],
    laneValues: ["intent=multi-hop", "tier=complex", "gpt-4o"],
    log: ["收到任务 steps=5", "分类为 complex", "路由到 gpt-4o"],
    summary: ["分级路由是成本优化的核心杠杆", "分类器可以是规则或小模型", "旗舰模型是稀缺资源"],
    sourceTitle: "LangChain Routing",
    sourceUrl: "https://python.langchain.com/docs/how_to/routing/"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-fallback-strategy",
    stageId: "ai-app-model-selection",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Fallback 与降级策略",
    concept: "primary 模型出现 429/5xx/超时时应自动降级到 backup 模型，而不是把错误抛给用户。fallback 链要按能力接近程度排序，并记录降级事件用于观测。",
    points: ["primary → backup 有序降级", "只对可恢复错误触发 fallback", "降级事件必须打点观测"],
    memoryHook: "主备切换 = 可恢复 + 打点",
    fileName: "fallback.ts",
    code: `import OpenAI from \"openai\";\n\nconst openai = new OpenAI();\nconst chain = [\"gpt-4o\", \"claude-3-5-sonnet\", \"gpt-4o-mini\"];\n\nasync function complete(messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[]) {\n  for (const model of chain) {\n    try {\n      return await openai.chat.completions.create({ model, messages });\n    } catch (err: any) {\n      const status = err?.status ?? 0;\n      if (status !== 429 && status < 500) throw err;\n      await metrics.increment(\"llm.fallback\", { from: model });\n    }\n  }\n  throw new Error(\"所有备用模型均失败\");\n}\n\nconst res = await complete([{ role: \"user\", content: \"总结这份合同\" }]);\nconsole.log(res.model);`,
    prompt: "primary 模型返回 400 参数错误时是否应该触发 fallback？",
    correct: "不应该，400 是不可恢复错误，fallback 只处理限流和 5xx 等瞬时故障",
    wrong: "任何错误都切到 backup 模型，尽量保证不打断用户",
    output: "llm.fallback from=gpt-4o",
    lanes: ["调用 primary", "捕获错误", "切换 backup"],
    laneValues: ["gpt-4o 请求", "status=429", "claude-3-5-sonnet"],
    log: ["gpt-4o 请求 429", "打点 llm.fallback", "claude-3-5-sonnet 成功"],
    summary: ["fallback 只兜可恢复错误", "降级链按能力接近排序", "每次降级都必须打点"],
    sourceTitle: "LiteLLM Routing",
    sourceUrl: "https://docs.litellm.ai/docs/routing"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-latency-quality-cost",
    stageId: "ai-app-model-selection",
    order: 4,
    eyebrowStage: eyebrow,
    title: "延迟质量成本三角",
    concept: "延迟、质量、成本三者不能同时最优，需要按场景牺牲一项。实时对话优先延迟，离线报告优先质量，批量分类优先成本。选型时先明确本次牺牲的是哪一角。",
    points: ["三角权衡：延迟/质量/成本", "按场景锁定牺牲项", "同一产品可为不同场景配不同模型"],
    memoryHook: "三角只能选两角",
    fileName: "tradeoff.ts",
    code: `type Priority = \"latency\" | \"quality\" | \"cost\";\n\nconst byPriority: Record<Priority, { model: string; reason: string }> = {\n  latency: { model: \"gpt-4o-mini\", reason: \"首 token 快，适合实时对话\" },\n  quality: { model: \"gpt-4o\", reason: \"复杂推理与结构化输出最稳\" },\n  cost: { model: \"llama-3.1-70b\", reason: \"自建推理成本最低\" }\n};\n\nexport function pick(priority: Priority) {\n  return byPriority[priority];\n}\n\nconsole.log(pick(\"latency\"));`,
    prompt: "实时语音客服助手对模型选型最应该优先的是什么？",
    correct: "优先延迟，选首 token 快的模型，用小模型 + 缓存兜住成本",
    wrong: "优先质量，选 GPT-4o 保证每次回答准确即可，延迟可接受",
    output: "{ model: 'gpt-4o-mini', reason: '首 token 快，适合实时对话' }",
    lanes: ["定义优先级", "查权衡表", "输出模型"],
    laneValues: ["priority=latency", "gpt-4o-mini", "reason=首 token 快"],
    log: ["priority=latency", "查表命中 gpt-4o-mini", "输出理由"],
    summary: ["三角权衡是选型的隐含契约", "同一产品可按场景切模型", "锁定牺牲项后决策才收敛"],
    sourceTitle: "OpenRouter Models",
    sourceUrl: "https://openrouter.ai/docs/models"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-context-window-chunking",
    stageId: "ai-app-model-selection",
    order: 5,
    eyebrowStage: eyebrow,
    title: "上下文窗口与 chunking",
    concept: "输入 token 数远小于模型 context 时，直接选便宜模型；接近或超过时，要么切换到长 context 模型（Gemini 1.5、Claude 200k），要么走 chunking + RAG。窗口选择直接决定架构。",
    points: ["input tokens ≪ context 用便宜模型", "input tokens 接近 context 换长窗口模型", "input tokens ≫ context 走 chunking + RAG"],
    memoryHook: "先算 token，再定架构",
    fileName: "context-window.ts",
    code: `type Choice =\n  | { strategy: \"direct\"; model: string }\n  | { strategy: \"long-context\"; model: string }\n  | { strategy: \"chunk-rag\"; model: string; chunkTokens: number };\n\nexport function chooseByTokens(inputTokens: number): Choice {\n  if (inputTokens <= 32_000) return { strategy: \"direct\", model: \"gpt-4o-mini\" };\n  if (inputTokens <= 200_000) return { strategy: \"long-context\", model: \"claude-3-5-sonnet\" };\n  return { strategy: \"chunk-rag\", model: \"gpt-4o\", chunkTokens: 2_000 };\n}\n\nconsole.log(chooseByTokens(500_000));`,
    prompt: "输入 50 万 token 的文档最合适的策略是？",
    correct: "chunking + RAG，把长文档切片后按相关性召回，再喂给模型",
    wrong: "无脑塞进 Gemini 1.5 Pro 的 2M 窗口，一次性让模型消化",
    output: "{ strategy: 'chunk-rag', model: 'gpt-4o', chunkTokens: 2000 }",
    lanes: ["估算 tokens", "匹配策略", "输出模型"],
    laneValues: ["500k tokens", "chunk-rag", "gpt-4o + 2k chunk"],
    log: ["估算 500k tokens", "匹配 chunk-rag 策略", "输出模型与切片大小"],
    summary: ["context 窗口决定架构走向", "长窗口模型不是万能钥匙", "chunking + RAG 更利于成本与召回控制"],
    sourceTitle: "Anthropic Claude Models",
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-structured-output",
    stageId: "ai-app-model-selection",
    order: 6,
    eyebrowStage: eyebrow,
    title: "结构化输出能力对比",
    concept: "OpenAI 的 Structured Outputs 支持严格 JSON Schema、100% 语法保证；Anthropic 通过 tool_use 间接输出结构；Gemini 用 responseSchema；开源模型需要 grammar/outlines 等采样约束。要按“是否严格”选模型。",
    points: ["OpenAI Structured Outputs 语法级保证", "Claude 借 tool_use 输出结构", "OSS 需 grammar/outlines 约束采样"],
    memoryHook: "结构化 = 语法级 or 采样级",
    fileName: "structured-output.ts",
    code: `import OpenAI from \"openai\";\n\nconst openai = new OpenAI();\n\nconst schema = {\n  type: \"object\",\n  properties: {\n    intent: { type: \"string\", enum: [\"refund\", \"query\", \"other\"] },\n    orderId: { type: \"string\" }\n  },\n  required: [\"intent\", \"orderId\"],\n  additionalProperties: false\n};\n\nconst res = await openai.chat.completions.create({\n  model: \"gpt-4o-2024-08-06\",\n  messages: [{ role: \"user\", content: \"我要退订单 10086\" }],\n  response_format: {\n    type: \"json_schema\",\n    json_schema: { name: \"intent\", schema, strict: true }\n  }\n});\nconsole.log(JSON.parse(res.choices[0].message.content!));`,
    prompt: "需要 100% 保证输出符合 JSON Schema，最合适的选择是？",
    correct: "选支持 Structured Outputs strict 模式的模型，如 GPT-4o 2024-08-06",
    wrong: "任何模型都可以，只要在 prompt 里反复强调“请输出 JSON”",
    output: "{ intent: 'refund', orderId: '10086' }",
    lanes: ["定义 schema", "发起 strict 请求", "解析结构化输出"],
    laneValues: ["schema=intent", "gpt-4o strict", "JSON parse 成功"],
    log: ["定义 JSON schema", "调用 strict 模式", "解析得到结构化对象"],
    summary: ["结构化能力是选型硬指标", "strict 模式免去二次校验", "OSS 走 grammar 约束采样"],
    sourceTitle: "OpenAI Models",
    sourceUrl: "https://platform.openai.com/docs/models"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-tool-use-differences",
    stageId: "ai-app-model-selection",
    order: 7,
    eyebrowStage: eyebrow,
    title: "Tool use 支持差异",
    concept: "OpenAI 用 `tools` + `tool_calls[]` 天然支持并行；Anthropic 用 `tools` + `tool_use` block；Gemini 用 `function_declarations`；OSS 需 fine-tune 或 prompt hack。跨厂商切换必须抽象 tool 适配层。",
    points: ["三家 API 结构与字段不一致", "并行调用支持度不同", "抽象适配层隔离差异"],
    memoryHook: "工具协议不通，靠 adapter 兜",
    fileName: "tool-adapter.ts",
    code: `type NormalizedToolCall = { id: string; name: string; args: Record<string, unknown> };\n\nexport function extractToolCalls(vendor: \"openai\" | \"anthropic\" | \"google\", raw: any): NormalizedToolCall[] {\n  if (vendor === \"openai\") {\n    return (raw.choices[0].message.tool_calls ?? []).map((c: any) => ({\n      id: c.id,\n      name: c.function.name,\n      args: JSON.parse(c.function.arguments)\n    }));\n  }\n  if (vendor === \"anthropic\") {\n    return raw.content.filter((b: any) => b.type === \"tool_use\").map((b: any) => ({\n      id: b.id,\n      name: b.name,\n      args: b.input\n    }));\n  }\n  return raw.candidates[0].content.parts.filter((p: any) => p.functionCall).map((p: any) => ({\n    id: p.functionCall.name,\n    name: p.functionCall.name,\n    args: p.functionCall.args\n  }));\n}`,
    prompt: "产品要同时支持 GPT-4o 和 Claude 3.5，工程上最稳的做法是？",
    correct: "定义统一的 NormalizedToolCall，在 adapter 层归一化两家协议差异",
    wrong: "让业务代码分别写两条 if 分支，直接消费厂商原始返回",
    output: "[{ id: 'call_1', name: 'get_weather', args: { city: 'Beijing' } }]",
    lanes: ["接收响应", "识别厂商", "归一化 tool_calls"],
    laneValues: ["openai response", "vendor=openai", "1 个 tool_call"],
    log: ["收到 openai response", "识别 vendor", "归一化 1 个 tool_call"],
    summary: ["跨厂商工具协议差异必须抽象", "并行度差异影响调度模型", "adapter 层是切模型的护城河"],
    sourceTitle: "Anthropic Models",
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models"
  }),
  createAiAppLesson({
    id: "ai-app-model-selection-multimodal-compare",
    stageId: "ai-app-model-selection",
    order: 8,
    eyebrowStage: eyebrow,
    title: "多模态能力对比",
    concept: "GPT-4o 原生支持文本/图像/音频输入输出；Claude 3.5 支持文本+图像；Gemini 1.5 支持文本/图像/音频/视频。选型时要看：模态覆盖、输入尺寸限制、是否原生 vs 拼接两阶段。",
    points: ["按模态覆盖过滤候选", "关注单次输入尺寸/时长限制", "原生多模态 > 两阶段拼接"],
    memoryHook: "多模态 = 覆盖 + 限制 + 原生度",
    fileName: "multimodal.ts",
    code: `type Modality = \"text\" | \"image\" | \"audio\" | \"video\";\n\ntype Model = { id: string; supports: Modality[]; maxImagePerCall?: number; maxVideoMinutes?: number };\n\nconst models: Model[] = [\n  { id: \"gpt-4o\", supports: [\"text\", \"image\", \"audio\"], maxImagePerCall: 10 },\n  { id: \"claude-3-5-sonnet\", supports: [\"text\", \"image\"], maxImagePerCall: 20 },\n  { id: \"gemini-1.5-pro\", supports: [\"text\", \"image\", \"audio\", \"video\"], maxImagePerCall: 3000, maxVideoMinutes: 60 }\n];\n\nexport function pickForModalities(required: Modality[]) {\n  return models.filter((m) => required.every((r) => m.supports.includes(r)));\n}\n\nconsole.log(pickForModalities([\"text\", \"video\"]).map((m) => m.id));`,
    prompt: "任务需要分析一段 30 分钟视频并给出摘要，最合理的模型是？",
    correct: "选原生支持 video 的 Gemini 1.5 Pro，避免抽帧+图像模型的两阶段拼接",
    wrong: "用 GPT-4o 逐帧抽图作为图像输入，让模型自己拼上下文",
    output: "['gemini-1.5-pro']",
    lanes: ["解析所需模态", "过滤候选", "输出模型"],
    laneValues: ["required=text,video", "只剩 gemini", "1 个候选"],
    log: ["解析 required=text,video", "过滤支持列表", "输出 1 个候选"],
    summary: ["模态覆盖是硬门槛", "尺寸/时长限制常被忽略", "原生多模态减少拼接误差"],
    sourceTitle: "Google Gemini Models",
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models/gemini"
  })
];

const project = createAiAppStageProject({
  id: "ai-app-model-selection-project",
  stageId: "ai-app-model-selection",
  eyebrowStage: eyebrow,
  title: "智能模型路由系统",
  brief: "构建一个模型路由系统：接收任务 → 判定复杂度与模态 → 按三角权衡选主模型 → 挂 fallback 链 → 记录选型与降级事件，最终输出结构化响应。",
  concept: "串联本阶段的能力矩阵、复杂度分级、fallback、三角权衡、上下文窗口、结构化输出与多模态判断，形成一个可交付的智能路由骨架。",
  points: ["按能力矩阵和任务特征选型", "primary + fallback 链兜住可恢复错误", "每次路由与降级都要打点"],
  memoryHook: "路由 = 选型 + 兜底 + 观测",
  fileName: "model-router.ts",
  code: `import OpenAI from \"openai\";\n\ntype Task = { intent: string; tokens: number; modalities: (\"text\" | \"image\" | \"audio\" | \"video\")[]; priority: \"latency\" | \"quality\" | \"cost\" };\n\nconst openai = new OpenAI();\n\nfunction pickPrimary(task: Task): string {\n  if (task.modalities.includes(\"video\")) return \"gemini-1.5-pro\";\n  if (task.tokens > 200_000) return \"gemini-1.5-pro\";\n  if (task.priority === \"latency\") return \"gpt-4o-mini\";\n  if (task.priority === \"cost\") return \"llama-3.1-70b\";\n  return \"gpt-4o\";\n}\n\nfunction fallbackChain(primary: string): string[] {\n  const chain = [primary, \"claude-3-5-sonnet\", \"gpt-4o-mini\"];\n  return Array.from(new Set(chain));\n}\n\nexport async function route(task: Task, messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[]) {\n  const chain = fallbackChain(pickPrimary(task));\n  await metrics.increment(\"router.decision\", { primary: chain[0] });\n  for (const model of chain) {\n    try {\n      return await openai.chat.completions.create({ model, messages });\n    } catch (err: any) {\n      if (err?.status !== 429 && (err?.status ?? 0) < 500) throw err;\n      await metrics.increment(\"router.fallback\", { from: model });\n    }\n  }\n  throw new Error(\"路由链全部失败\");\n}\n\nconst res = await route(\n  { intent: \"summary\", tokens: 12_000, modalities: [\"text\"], priority: \"quality\" },\n  [{ role: \"user\", content: \"请总结这份季度财报\" }]\n);\nconsole.log(res.model);`,
  prompt: "路由系统为什么要把选型决策和降级事件都打点？",
  correct: "选型和降级是产品体验和成本的因果链，无打点就无法归因效果差异与失败模式",
  wrong: "只要最终响应正确即可，打点会增加系统复杂度，可以省略",
  correctFeedback: "正确：只有决策和降级事件都可观测，才能回答“为什么这次质量下降”或“为什么这次变贵”。",
  wrongFeedback: "错误：没有决策打点的路由 = 黑盒，出问题时既不能归因质量也不能归因成本。",
  additionalWrong: {
    label: "只要 primary 模型足够强，就不需要 fallback 链",
    feedback: "错误：任何单一模型都会遇到限流和 5xx，fallback 是 SLA 的基础设施。"
  },
  lanes: ["解析任务", "选主 + 挂 fallback", "执行 + 打点"],
  laneValues: ["intent=summary", "primary=gpt-4o", "调用 + emit"],
  log: ["解析任务特征", "选定 primary=gpt-4o", "调用成功并打点 router.decision"],
  summary: ["路由决策要按任务特征多维判定", "fallback 链是 SLA 的底座", "决策与降级必须可观测"],
  sourceTitle: "LiteLLM Routing",
  sourceUrl: "https://docs.litellm.ai/docs/routing"
});

export const aiApplicationStageSixModelSelectionLessons: LessonSpec[] = [...knowledgeLessons, project];
