import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "文件批处理与文本自动化";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-file-batch-pathlib-traverse",
    stageId: "python-file-batch",
    order: 1,
    eyebrowStage: eyebrow,
    title: "pathlib 递归遍历模式",
    concept: "`pathlib.Path.rglob` 按通配符递归收集路径，返回惰性迭代器。适合按扩展名或目录规则筛选，避免手写 `os.walk` 循环拼接。",
    points: ["rglob 惰性迭代不加载全部", "Path.suffix / stem 拆解命名", "is_file / is_dir 判定节点类型"],
    memoryHook: "rglob 是文件雷达，边扫描边处理",
    fileName: "traverse.py",
    code: `from pathlib import Path\n\nroot = Path("./logs")\ncount = sum(1 for p in root.rglob("*.log") if p.is_file())\nprint(count)`,
    prompt: "这段代码最能说明什么？",
    correct: "rglob 按模式惰性递归遍历，并结合 is_file 过滤真实文件",
    wrong: "rglob 会立即把所有匹配路径读入内存",
    output: "3",
    lanes: ["解释器加载", "递归遍历", "统计输出"],
    laneValues: ["载入 pathlib", "rglob 遍历 3 个 .log", "打印计数 3"],
    log: ["扫描 ./logs 目录", "命中 3 个 *.log 文件", "3"],
    summary: ["rglob 提供惰性迭代", "combine is_file 排除目录", "路径遍历避免手写字符串拼接"],
    sourceTitle: "Python pathlib",
    sourceUrl: "https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob"
  }),
  createPythonLesson({
    id: "python-file-batch-encoding-detect",
    stageId: "python-file-batch",
    order: 2,
    eyebrowStage: eyebrow,
    title: "编码探测与安全读取",
    concept: "读取未知来源的文本时，先用二进制模式取样再交给 `chardet` 或 `charset-normalizer` 猜测编码，最后用 `errors='replace'` 兜底避免脚本崩溃。",
    points: ["先二进制读取采样字节", "errors='replace' 保护流水线", "记录被替换字符便于回查"],
    memoryHook: "先探测再解码，别赌 UTF-8",
    fileName: "encoding.py",
    code: `from pathlib import Path\n\nsample = Path("data.csv").read_bytes()[:2048]\nencoding = "utf-8" if sample.startswith(b"\\xef\\xbb\\xbf") else "gbk"\ntext = Path("data.csv").read_text(encoding=encoding, errors="replace")\nprint(len(text), encoding)`,
    prompt: "为什么读文本前建议先取样字节？",
    correct: "避免误判编码导致乱码，并可以决定用什么解码策略",
    wrong: "Python 会自动识别所有编码，不需要额外判断",
    output: "1024 gbk",
    lanes: ["读取字节", "选择编码", "解码文本"],
    laneValues: ["读入前 2KB", "识别 BOM 或 GBK", "得到 str 长度 1024"],
    log: ["read_bytes 2048", "选择 gbk", "1024 gbk"],
    summary: ["先探测再解码", "errors='replace' 防崩溃", "记录乱码用于回查"],
    sourceTitle: "Python codecs",
    sourceUrl: "https://docs.python.org/3/library/codecs.html"
  }),
  createPythonLesson({
    id: "python-file-batch-rename-rules",
    stageId: "python-file-batch",
    order: 3,
    eyebrowStage: eyebrow,
    title: "批量重命名与冲突处理",
    concept: "使用 `Path.rename` 需要保证目标不存在或使用 `Path.replace` 强制覆盖。批量任务应先建立目标名映射表，再在冲突时追加序号或跳过。",
    points: ["先规划命名映射再执行", "冲突用序号或跳过", "干跑模式先打印再执行"],
    memoryHook: "重命名前先干跑，避免不可逆覆盖",
    fileName: "rename.py",
    code: `from pathlib import Path\n\nplan = [(p, p.with_name(p.stem.lower() + p.suffix)) for p in Path(".").glob("*.LOG")]\nfor src, dst in plan:\n    if dst.exists():\n        print("skip", dst)\n        continue\n    src.rename(dst)\nprint("done", len(plan))`,
    prompt: "为什么先构建 plan 再执行 rename 更安全？",
    correct: "可以先查看冲突并干跑，避免不可逆的批量覆盖",
    wrong: "rename 支持自动回滚，不需要提前规划",
    output: "done 5",
    lanes: ["扫描候选", "生成映射", "执行重命名"],
    laneValues: ["5 个 .LOG", "映射到小写命名", "打印 done 5"],
    log: ["glob 命中 5", "生成 5 条 plan", "done 5"],
    summary: ["Path.rename 遇冲突会抛错", "干跑先打印映射", "with_name/with_suffix 组合命名"],
    sourceTitle: "Python pathlib.Path.rename",
    sourceUrl: "https://docs.python.org/3/library/pathlib.html#pathlib.Path.rename"
  }),
  createPythonLesson({
    id: "python-file-batch-text-cleanup",
    stageId: "python-file-batch",
    order: 4,
    eyebrowStage: eyebrow,
    title: "结构化文本清洗",
    concept: "文本清洗常按行处理：`strip` 去空白、`splitlines` 保留结构、`filter` + 生成器组合过滤。用 `NamedTemporaryFile` 写入再原子替换，保证异常时不会破坏原文件。",
    points: ["生成器保持恒定内存", "先写临时文件再原子替换", "空行/注释按规则统一处理"],
    memoryHook: "清洗流水线：读→过滤→原子写",
    fileName: "cleanup.py",
    code: `from pathlib import Path\nimport tempfile\nimport os\n\nsrc = Path("input.txt")\ntmp = tempfile.NamedTemporaryFile("w", delete=False, encoding="utf-8")\nwith src.open(encoding="utf-8") as f:\n    for line in f:\n        line = line.rstrip()\n        if line and not line.startswith("#"):\n            tmp.write(line + "\\n")\ntmp.close()\nos.replace(tmp.name, src)\nprint("cleaned")`,
    prompt: "为什么用临时文件 + os.replace 而不是直接覆盖？",
    correct: "任何异常都不会破坏原文件，替换是原子操作",
    wrong: "临时文件只是为了速度更快，功能上和直接写等价",
    output: "cleaned",
    lanes: ["读取行", "过滤清洗", "原子写回"],
    laneValues: ["逐行读", "去掉空行与注释", "os.replace 覆盖"],
    log: ["打开 input.txt", "过滤 12 行", "cleaned"],
    summary: ["生成器保持恒定内存", "tempfile + os.replace 原子替换", "空行和注释按需过滤"],
    sourceTitle: "Python tempfile.NamedTemporaryFile",
    sourceUrl: "https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile"
  }),
  createPythonLesson({
    id: "python-file-batch-fast-hash",
    stageId: "python-file-batch",
    order: 5,
    eyebrowStage: eyebrow,
    title: "增量识别与文件指纹",
    concept: "批量任务需要跳过未变更文件。用 `hashlib.blake2b` 分块读取生成指纹，与上次记录对比只处理变化的文件，避免重复计算。",
    points: ["blake2b 比 md5 更快更安全", "分块读取控制内存", "指纹缓存放旁路 json 文件"],
    memoryHook: "指纹缓存 = 增量流水线的钥匙",
    fileName: "hash.py",
    code: `from pathlib import Path\nimport hashlib\n\ndef fingerprint(path: Path) -> str:\n    h = hashlib.blake2b(digest_size=16)\n    with path.open("rb") as f:\n        for chunk in iter(lambda: f.read(64 * 1024), b""):\n            h.update(chunk)\n    return h.hexdigest()\n\nprint(fingerprint(Path("input.txt"))[:8])`,
    prompt: "为什么分块读取而不是一次 read()？",
    correct: "避免大文件占满内存，同时利用 CPU 缓存",
    wrong: "分块读取只是为了兼容旧 Python 版本",
    output: "1f9a3c7d",
    lanes: ["打开文件", "分块散列", "输出指纹"],
    laneValues: ["input.txt", "循环 read(64KB)", "hexdigest 前 8 位"],
    log: ["open input.txt", "散列完成", "1f9a3c7d"],
    summary: ["blake2b 是现代默认", "iter + sentinel 是分块惯用法", "只对变化文件继续下游处理"],
    sourceTitle: "Python hashlib",
    sourceUrl: "https://docs.python.org/3/library/hashlib.html"
  }),
  createPythonLesson({
    id: "python-file-batch-parallel-io",
    stageId: "python-file-batch",
    order: 6,
    eyebrowStage: eyebrow,
    title: "并行 IO 与线程池",
    concept: "文件 IO 是典型的 IO-bound 任务。用 `concurrent.futures.ThreadPoolExecutor` 并发处理多个文件，比进程池更轻，比协程更贴近同步文件 API。",
    points: ["IO-bound 用线程池", "as_completed 拿到最先结束的任务", "并发数由磁盘和目标服务决定"],
    memoryHook: "IO-bound 用线程，CPU-bound 用进程",
    fileName: "parallel.py",
    code: `from concurrent.futures import ThreadPoolExecutor, as_completed\nfrom pathlib import Path\n\nfiles = list(Path("./data").glob("*.csv"))\nwith ThreadPoolExecutor(max_workers=8) as pool:\n    futures = {pool.submit(lambda p: p.read_text(), f): f for f in files}\n    for fut in as_completed(futures):\n        print(len(fut.result()), futures[fut].name)`,
    prompt: "为什么这里选线程池而不是进程池？",
    correct: "文件读取是 IO-bound，线程池开销更小",
    wrong: "线程池比进程池并发数更多，所以永远更快",
    output: "8192 orders.csv",
    lanes: ["构建任务", "并发执行", "收集结果"],
    laneValues: ["扫描 5 个 CSV", "8 线程并发读", "as_completed 输出"],
    log: ["扫描 5", "并发读取", "8192 orders.csv"],
    summary: ["IO-bound 首选 ThreadPoolExecutor", "as_completed 处理先完成的任务", "并发数上限受磁盘影响"],
    sourceTitle: "Python concurrent.futures",
    sourceUrl: "https://docs.python.org/3/library/concurrent.futures.html"
  }),
  createPythonLesson({
    id: "python-file-batch-safe-write",
    stageId: "python-file-batch",
    order: 7,
    eyebrowStage: eyebrow,
    title: "崩溃安全的写入策略",
    concept: "写文件时应使用 `write → fsync → os.replace` 三步保证崩溃安全。直接 `open('w')` 在断电或异常时会留下半截文件，破坏后续增量流程。",
    points: ["fsync 强制落盘", "os.replace 原子替换", "记录写入前后 checksum"],
    memoryHook: "写→sync→replace，才是断电安全",
    fileName: "safe_write.py",
    code: `from pathlib import Path\nimport os\nimport tempfile\n\ndata = "generated"\ndst = Path("out.txt")\nwith tempfile.NamedTemporaryFile("w", dir=dst.parent, delete=False, encoding="utf-8") as tmp:\n    tmp.write(data)\n    tmp.flush()\n    os.fsync(tmp.fileno())\nos.replace(tmp.name, dst)\nprint(dst.read_text())`,
    prompt: "为什么 flush 之后还要 os.fsync？",
    correct: "flush 只是 Python 缓冲落到内核，fsync 才把内核缓存落到磁盘",
    wrong: "flush 和 fsync 是同一个操作的两种写法",
    output: "generated",
    lanes: ["写临时文件", "fsync 落盘", "原子替换"],
    laneValues: ["tempfile", "os.fsync", "os.replace"],
    log: ["写入 generated", "fsync 完成", "generated"],
    summary: ["fsync 保证真正落盘", "os.replace 是原子替换", "崩溃安全需要三步组合"],
    sourceTitle: "Python os.fsync",
    sourceUrl: "https://docs.python.org/3/library/os.html#os.fsync"
  }),
  createPythonLesson({
    id: "python-file-batch-log-rotation",
    stageId: "python-file-batch",
    order: 8,
    eyebrowStage: eyebrow,
    title: "轮转日志与归档策略",
    concept: "`logging.handlers.TimedRotatingFileHandler` 按时间切分日志，归档旧文件避免单文件膨胀。批处理任务落地日志时应结合结构化字段，方便下游查询。",
    points: ["按时间/大小轮转", "结构化字段用 JSON logger", "归档过期文件配合备份"],
    memoryHook: "轮转日志是批处理的黑匣子",
    fileName: "rotating.py",
    code: `import logging\nfrom logging.handlers import TimedRotatingFileHandler\n\nhandler = TimedRotatingFileHandler("job.log", when="midnight", backupCount=7)\nhandler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))\nlogger = logging.getLogger("job")\nlogger.setLevel(logging.INFO)\nlogger.addHandler(handler)\nlogger.info("start batch")\nprint("logged")`,
    prompt: "为什么批处理任务倾向使用轮转日志？",
    correct: "避免单文件膨胀，保留固定期限归档便于回查",
    wrong: "轮转日志是为了让日志格式更加美观",
    output: "logged",
    lanes: ["注册 handler", "写入日志", "自动归档"],
    laneValues: ["Timed handler", "logger.info", "backup 7 份"],
    log: ["注册 job handler", "写入 start batch", "logged"],
    summary: ["按时间轮转控制单文件大小", "backupCount 保留固定份数", "结构化日志便于下游查询"],
    sourceTitle: "Python logging.handlers",
    sourceUrl: "https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler"
  })
];

const project = createPythonStageProject({
  id: "python-file-batch-project",
  stageId: "python-file-batch",
  eyebrowStage: eyebrow,
  title: "批量文档标准化工具",
  brief: "构建一个 CLI 工具，把混合编码、命名不规范的历史文档统一为 UTF-8 + 小写命名，并输出处理报告。",
  concept: "串联阶段知识点：遍历目录、探测编码、按规则重命名、清洗文本内容、原子写入并生成结构化日志。",
  points: ["组合 pathlib / chardet / tempfile", "干跑模式与真正执行分离", "写入结构化处理报告"],
  memoryHook: "自动化脚本 = 干跑 + 原子 + 报告",
  fileName: "standardize.py",
  code: `from pathlib import Path\nimport json\nimport os\nimport tempfile\n\ndef standardize(root: Path, dry_run: bool = True) -> dict:\n    report = {"renamed": [], "cleaned": [], "skipped": []}\n    for path in root.rglob("*"):\n        if not path.is_file():\n            continue\n        target = path.with_name(path.stem.lower() + path.suffix)\n        if target != path:\n            if dry_run:\n                report["renamed"].append((str(path), str(target)))\n            else:\n                path.rename(target)\n                path = target\n        text = path.read_text(encoding="utf-8", errors="replace")\n        cleaned = "\\n".join(line.rstrip() for line in text.splitlines() if line.strip())\n        if cleaned != text:\n            if dry_run:\n                report["cleaned"].append(str(path))\n            else:\n                tmp = tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False, encoding="utf-8")\n                tmp.write(cleaned)\n                tmp.close()\n                os.replace(tmp.name, path)\n    return report\n\nresult = standardize(Path("./docs"))\nprint(json.dumps(result, ensure_ascii=False, indent=2))`,
  prompt: "为什么标准化脚本默认应该是 dry_run？",
  correct: "先展示影响范围，避免不可逆的批量改动",
  wrong: "dry_run 只是性能调优选项，可以直接跳过",
  correctFeedback: "正确：批量脚本默认 dry_run，可以给用户机会检查影响面。",
  wrongFeedback: "错误：dry_run 是安全默认值，不是性能优化。",
  additionalWrong: {
    label: "只要备份原目录就可以关闭 dry_run",
    feedback: "备份不能替代干跑：dry_run 让脚本先给出可读的变更清单。"
  },
  lanes: ["扫描输入", "生成变更计划", "落地或干跑"],
  laneValues: ["rglob docs/", "生成 rename+clean 计划", "输出 JSON 报告"],
  log: ["扫描 12 个文件", "生成计划", "报告写入 stdout"],
  summary: ["干跑先给出计划", "遇冲突记录到 skipped", "结构化报告便于人工复核"],
  sourceTitle: "Python pathlib 与 tempfile 组合",
  sourceUrl: "https://docs.python.org/3/library/pathlib.html"
});

export const pythonStageFourFileBatchLessons: LessonSpec[] = [...knowledgeLessons, project];
