import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "子进程与运维编排";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-subprocess-run-basics",
    stageId: "python-ops-process",
    order: 1,
    eyebrowStage: eyebrow,
    title: "subprocess.run 与 check=True",
    concept: "`subprocess.run` 是同步执行外部命令的推荐入口。使用 `check=True` 让非零退出直接抛出 `CalledProcessError`，配合 `capture_output=True` 收集 stdout/stderr，避免脚本继续跑在错误结果上。",
    points: ["check=True 让失败立刻抛异常", "capture_output 收集输出而不是打屏", "returncode 是编排链路的第一手证据"],
    memoryHook: "run(check=True)：失败必抛，不再侥幸继续",
    fileName: "run_basics.py",
    code: `import subprocess\n\nresult = subprocess.run(\n    ["uname", "-a"],\n    check=True,\n    capture_output=True,\n    text=True,\n)\nprint(result.stdout.strip())`,
    prompt: "为什么运维脚本更推荐显式设置 `check=True`？",
    correct: "非零退出会立即抛出异常，避免后续步骤基于失败结果继续执行",
    wrong: "check=True 只是把日志级别提高，不影响后续流程",
    output: "Linux runner 6.1.0 #1 SMP x86_64 GNU/Linux",
    lanes: ["构造参数", "fork/exec", "回收结果"],
    laneValues: ["列表参数 uname -a", "子进程执行", "returncode=0"],
    log: ["subprocess.run 启动", "uname 输出捕获", "returncode=0"],
    summary: ["run 是同步执行首选", "check=True 显式失败", "capture_output 便于结构化处理"],
    sourceTitle: "Python subprocess.run",
    sourceUrl: "https://docs.python.org/3/library/subprocess.html#subprocess.run"
  }),
  createPythonLesson({
    id: "python-subprocess-pipe-io",
    stageId: "python-ops-process",
    order: 2,
    eyebrowStage: eyebrow,
    title: "stdin/stdout 管道传输",
    concept: "把上一个命令的输出接到下一个命令的输入，应使用 `Popen` 的 `stdin=` / `stdout=subprocess.PIPE`。避免在 shell 里手写管道以获得更好的错误处理和可测试性。",
    points: ["PIPE 让父子进程按流交换数据", "communicate 一次性收尾并回收资源", "长管道要处理反压避免死锁"],
    memoryHook: "PIPE 是接线柱，communicate 是收线人",
    fileName: "pipe_io.py",
    code: `import subprocess\n\nps = subprocess.Popen(["ps", "-ef"], stdout=subprocess.PIPE)\ngrep = subprocess.Popen(\n    ["grep", "python"],\n    stdin=ps.stdout,\n    stdout=subprocess.PIPE,\n    text=True,\n)\nps.stdout.close()\nout, _ = grep.communicate()\nprint(out.splitlines()[0])`,
    prompt: "为什么要在 grep 之前 `ps.stdout.close()`？",
    correct: "关闭父进程持有的写端，让 grep 能感知 EOF 正常退出",
    wrong: "close 只是节省一个文件描述符，不影响子进程结束",
    output: "root      1234  1000  0 09:12 ?        00:00:00 python worker.py",
    lanes: ["启动上游", "串联管道", "收集输出"],
    laneValues: ["Popen ps", "stdin=ps.stdout", "communicate"],
    log: ["ps 启动", "grep 接管管道", "输出首行"],
    summary: ["Popen + PIPE 组合命令", "关闭上游写端触发 EOF", "communicate 阻塞收尾"],
    sourceTitle: "Python subprocess.Popen",
    sourceUrl: "https://docs.python.org/3/library/subprocess.html#subprocess.Popen"
  }),
  createPythonLesson({
    id: "python-subprocess-timeout",
    stageId: "python-ops-process",
    order: 3,
    eyebrowStage: eyebrow,
    title: "timeout 与超时后的 kill",
    concept: "`subprocess.run(..., timeout=T)` 超时会抛 `TimeoutExpired`，此时子进程仍在运行需要显式 `kill`。工程实践里应用 `try/except` 捕获并保证进程被回收，避免僵尸和资源泄漏。",
    points: ["TimeoutExpired 不代表进程已死", "except 中调用 kill+wait 回收", "超时时长要覆盖正常抖动"],
    memoryHook: "超时会抛，但不会自己收尸",
    fileName: "timeout.py",
    code: `import subprocess\n\ntry:\n    subprocess.run(["sleep", "30"], timeout=1, check=True)\nexcept subprocess.TimeoutExpired as exc:\n    print("timeout after", exc.timeout, "seconds")\n    if exc.stderr:\n        print(exc.stderr)`,
    prompt: "捕获 TimeoutExpired 之后运维脚本应该做什么？",
    correct: "确认子进程已经被 kill 并 wait，避免残留进程占用资源",
    wrong: "只需记录日志即可，Python 会自动回收子进程",
    output: "timeout after 1 seconds",
    lanes: ["设定超时", "触发 kill", "回收资源"],
    laneValues: ["timeout=1", "TimeoutExpired", "wait 回收"],
    log: ["subprocess.run 启动", "1s 触发超时", "记录并回收"],
    summary: ["timeout 只是打断，不是回收", "捕获异常必须 wait", "超时时长要贴合真实抖动"],
    sourceTitle: "Python subprocess.TimeoutExpired",
    sourceUrl: "https://docs.python.org/3/library/subprocess.html#subprocess.TimeoutExpired"
  }),
  createPythonLesson({
    id: "python-subprocess-shell-safety",
    stageId: "python-ops-process",
    order: 4,
    eyebrowStage: eyebrow,
    title: "shell=True 与命令注入风险",
    concept: "`shell=True` 会把字符串交给 `/bin/sh` 解析，一旦拼接用户输入就存在命令注入。默认应使用列表参数 + `shell=False`，需要 shell 特性时用 `shlex.quote` 或 `shlex.split` 显式管控。",
    points: ["列表参数天然规避注入", "shlex.quote 转义单个片段", "shell=True 时禁止直接拼字符串"],
    memoryHook: "能用列表就别用 shell=True",
    fileName: "shell_safety.py",
    code: `import shlex\nimport subprocess\n\nuser_input = "log; rm -rf /"\nsafe = ["grep", user_input, "/var/log/app.log"]\nresult = subprocess.run(safe, capture_output=True, text=True)\nprint("returncode", result.returncode)\nprint("quoted", shlex.quote(user_input))`,
    prompt: "为什么把用户输入放进列表参数更安全？",
    correct: "参数作为独立 argv 项传递，不会被 shell 解释成额外命令",
    wrong: "列表和字符串在 shell=True 下没有区别",
    output: "returncode 1\nquoted 'log; rm -rf /'",
    lanes: ["接收输入", "参数化调用", "安全执行"],
    laneValues: ["用户输入", "list argv", "shell=False"],
    log: ["读取用户输入", "构造 argv 列表", "子进程执行 returncode=1"],
    summary: ["shell=True 是注入温床", "列表参数天然安全", "shlex.quote 用于必要转义"],
    sourceTitle: "Python subprocess 安全建议",
    sourceUrl: "https://docs.python.org/3/library/subprocess.html#security-considerations"
  }),
  createPythonLesson({
    id: "python-ops-signal-handler",
    stageId: "python-ops-process",
    order: 5,
    eyebrowStage: eyebrow,
    title: "signal.signal 处理 SIGTERM",
    concept: "长跑运维脚本收到 `SIGTERM` 应完成当前批次再退出。用 `signal.signal(SIGTERM, handler)` 注册回调，把中断标志写入共享变量，主循环在下一轮检查后 graceful 退出。",
    points: ["主线程注册 handler 才生效", "handler 只做标记，不做重活", "配合 finally 清理临时文件"],
    memoryHook: "SIGTERM 打旗子，主循环再收尾",
    fileName: "signal_handler.py",
    code: `import signal\nimport time\n\nstop = False\n\ndef handle(signum, frame):\n    global stop\n    stop = True\n\nsignal.signal(signal.SIGTERM, handle)\nfor i in range(3):\n    if stop:\n        print("graceful stop at", i)\n        break\n    time.sleep(0.1)\nelse:\n    print("finished 3 iterations")`,
    prompt: "为什么信号 handler 里只设置标志位，不直接退出？",
    correct: "handler 是异步的，只应打标记，让主循环在安全点执行清理",
    wrong: "handler 里应该立刻 sys.exit，越快越好",
    output: "finished 3 iterations",
    lanes: ["注册 handler", "捕获信号", "主循环收尾"],
    laneValues: ["SIGTERM", "stop=True", "graceful exit"],
    log: ["注册 handler", "循环运行 3 次", "输出结束状态"],
    summary: ["handler 应该只打标记", "主循环在安全点检查", "配合 finally 清理资源"],
    sourceTitle: "Python signal",
    sourceUrl: "https://docs.python.org/3/library/signal.html"
  }),
  createPythonLesson({
    id: "python-ops-parallel-hosts",
    stageId: "python-ops-process",
    order: 6,
    eyebrowStage: eyebrow,
    title: "并发编排多主机",
    concept: "运维脚本要对 N 台主机并发下发命令时，`concurrent.futures.ThreadPoolExecutor` 组合 `paramiko` 或 `fabric` 是常见组合。线程池吃住 IO 等待，`as_completed` 收集先返回的结果并支持逐台失败重试。",
    points: ["IO-bound 用线程池", "as_completed 允许最先完成先返回", "对失败主机独立重试而非整体重跑"],
    memoryHook: "并发下发 = 线程池 + 独立重试",
    fileName: "parallel_hosts.py",
    code: `from concurrent.futures import ThreadPoolExecutor, as_completed\n\ndef ssh_exec(host: str) -> str:\n    # 真实项目里替换成 paramiko SSHClient.exec_command\n    return f"{host}:uptime 10:12,load 0.3"\n\nhosts = ["web-1", "web-2", "web-3"]\nwith ThreadPoolExecutor(max_workers=8) as pool:\n    futures = {pool.submit(ssh_exec, h): h for h in hosts}\n    for fut in as_completed(futures):\n        host = futures[fut]\n        try:\n            print(fut.result())\n        except Exception as exc:\n            print(host, "failed:", exc)`,
    prompt: "为什么并发下发命令倾向按主机独立捕获异常？",
    correct: "单台主机失败不应中断其他主机，可以独立记录并进入重试队列",
    wrong: "只要有一台失败就 raise，让整批任务立即停下最省心",
    output: "web-1:uptime 10:12,load 0.3\nweb-2:uptime 10:12,load 0.3\nweb-3:uptime 10:12,load 0.3",
    lanes: ["下发命令", "并发执行", "收集结果"],
    laneValues: ["3 台主机", "8 线程并发", "as_completed 汇总"],
    log: ["提交 3 个任务", "并发执行完成", "3 条结果输出"],
    summary: ["线程池匹配 IO-bound", "as_completed 尽早处理返回", "错误按主机隔离"],
    sourceTitle: "paramiko SSHClient",
    sourceUrl: "https://docs.paramiko.org/en/latest/api/client.html"
  }),
  createPythonLesson({
    id: "python-ops-credential-vault",
    stageId: "python-ops-process",
    order: 7,
    eyebrowStage: eyebrow,
    title: "凭据隔离与最小权限",
    concept: "运维脚本禁止把密钥硬编码或写入 `argv`。密钥应从环境变量或 vault 拉取，`os.environ.get` 校验存在，日志脱敏，进程结束前清空敏感变量。",
    points: ["密钥不进入 argv 避免 ps 泄露", "读取失败时 fail-fast", "只授予运行所需的最小权限"],
    memoryHook: "密钥走环境变量，不走命令行",
    fileName: "credential_vault.py",
    code: `import os\nimport sys\n\ntoken = os.environ.get("DEPLOY_TOKEN")\nif not token:\n    print("missing DEPLOY_TOKEN", file=sys.stderr)\n    sys.exit(2)\n\nmasked = token[:2] + "***" + token[-2:]\nprint("using token", masked)\n# 使用完立即清理，防止子进程继承\nos.environ.pop("DEPLOY_TOKEN", None)`,
    prompt: "为什么密钥不应作为 argv 参数传给子进程？",
    correct: "argv 会出现在 ps/审计日志里，容易被同机用户看到",
    wrong: "argv 传参是加密的，比环境变量更安全",
    output: "using token gh***xt",
    lanes: ["读取凭据", "校验存在", "使用后清理"],
    laneValues: ["env DEPLOY_TOKEN", "非空校验", "os.environ.pop"],
    log: ["读取环境变量", "掩码打印", "清理凭据"],
    summary: ["密钥来自 vault/env", "日志一律脱敏", "使用完立刻清理"],
    sourceTitle: "Python os.environ",
    sourceUrl: "https://docs.python.org/3/library/os.html#os.environ"
  }),
  createPythonLesson({
    id: "python-ops-atomic-ops",
    stageId: "python-ops-process",
    order: 8,
    eyebrowStage: eyebrow,
    title: "幂等运维操作模式",
    concept: "幂等意味着重跑同一脚本不会破坏系统状态。做法是先探测（是否已存在、版本是否一致），再决定跳过或执行，最后写入状态文件，保证下一次重试有据可依。",
    points: ["探测-决策-执行三段式", "状态写入原子文件", "失败保留现场便于人工介入"],
    memoryHook: "重跑无副作用 = 探测在前，写状态收尾",
    fileName: "atomic_ops.py",
    code: `import json\nimport os\nimport tempfile\nfrom pathlib import Path\n\nstate_path = Path("deploy.state.json")\ncurrent = json.loads(state_path.read_text()) if state_path.exists() else {}\n\ntarget_version = "1.4.2"\nif current.get("version") == target_version:\n    print("already at", target_version)\nelse:\n    # 真实项目：这里替换成实际部署动作\n    current = {"version": target_version, "status": "ok"}\n    tmp = tempfile.NamedTemporaryFile("w", dir=state_path.parent, delete=False, encoding="utf-8")\n    json.dump(current, tmp)\n    tmp.close()\n    os.replace(tmp.name, state_path)\n    print("deployed", target_version)`,
    prompt: "为什么幂等脚本要先读状态再决定动作？",
    correct: "避免重复执行破坏系统状态，重跑时可以安全跳过",
    wrong: "先执行再检查状态更保险，反正状态文件会被覆盖",
    output: "deployed 1.4.2",
    lanes: ["读取状态", "决策动作", "写回状态"],
    laneValues: ["deploy.state.json", "版本对比", "os.replace 落地"],
    log: ["读取现状", "决定部署 1.4.2", "写入状态文件"],
    summary: ["幂等来自探测与状态", "写状态用原子替换", "失败保留现场便于回滚"],
    sourceTitle: "Python os.replace",
    sourceUrl: "https://docs.python.org/3/library/os.html#os.replace"
  })
];

const project = createPythonStageProject({
  id: "python-ops-process-project",
  stageId: "python-ops-process",
  eyebrowStage: eyebrow,
  title: "远程主机批量运维脚本",
  brief: "用 concurrent.futures 组合 paramiko，对 N 台主机并发执行 uptime/df 采样，失败主机独立重试，最后汇总为结构化报告。",
  concept: "串联阶段核心：安全构造子进程 / SSH 命令、超时与信号处理、并发编排、凭据隔离、状态与重试写回。",
  points: ["线程池处理 IO-bound", "失败主机独立重试且限次", "结构化报告便于交付审计"],
  memoryHook: "并发下发 → 独立重试 → 汇总报告",
  fileName: "bulk_ops.py",
  code: `from concurrent.futures import ThreadPoolExecutor, as_completed\nfrom dataclasses import dataclass, field\nimport json\nimport os\nimport sys\nfrom typing import Callable\n\n@dataclass\nclass HostResult:\n    host: str\n    ok: bool = False\n    output: str = ""\n    error: str = ""\n    attempts: int = 0\n\ndef ssh_command(host: str, command: str) -> str:\n    # 真实项目替换为 paramiko.SSHClient.exec_command\n    if host == "web-2":\n        raise TimeoutError("connect timeout")\n    return f"{host} => {command}: ok"\n\ndef run_with_retry(host: str, command: str, max_attempts: int = 3) -> HostResult:\n    result = HostResult(host=host)\n    for attempt in range(1, max_attempts + 1):\n        result.attempts = attempt\n        try:\n            result.output = ssh_command(host, command)\n            result.ok = True\n            return result\n        except Exception as exc:\n            result.error = str(exc)\n    return result\n\ndef bulk_run(hosts: list[str], command: str) -> list[HostResult]:\n    results: list[HostResult] = []\n    with ThreadPoolExecutor(max_workers=8) as pool:\n        futures = {pool.submit(run_with_retry, h, command): h for h in hosts}\n        for fut in as_completed(futures):\n            results.append(fut.result())\n    return results\n\nif __name__ == "__main__":\n    if not os.environ.get("OPS_TOKEN"):\n        print("missing OPS_TOKEN", file=sys.stderr)\n        sys.exit(2)\n    hosts = ["web-1", "web-2", "web-3"]\n    report = [r.__dict__ for r in bulk_run(hosts, "uptime && df -h /")]\n    print(json.dumps({"total": len(report), "results": report}, ensure_ascii=False, indent=2))`,
  prompt: "为什么批量运维脚本应把重试放在“单主机”粒度而不是“整批”粒度？",
  correct: "只有失败主机重试，成功的不再重复动作，既省时间又保持幂等",
  wrong: "整批重试更省事，一次全部重跑最安全",
  correctFeedback: "正确：单主机重试才能保持幂等并显著缩短恢复窗口。",
  wrongFeedback: "错误：整批重试会对成功主机重复动作，破坏幂等假设。",
  additionalWrong: {
    label: "只要 SSH 命令不会失败，就不需要重试逻辑",
    feedback: "网络抖动、主机负载、认证抖动都会失败，重试是运维脚本的默认能力。"
  },
  lanes: ["加载凭据", "并发下发", "汇总报告"],
  laneValues: ["读取 OPS_TOKEN", "线程池执行 SSH", "JSON 结果输出"],
  log: ["凭据加载完成", "3 台主机并发", "输出结构化报告"],
  summary: ["凭据来自环境变量", "并发+独立重试是核心", "结构化报告便于审计"],
  sourceTitle: "paramiko 官方文档",
  sourceUrl: "https://docs.paramiko.org/en/latest/"
});

export const pythonStageNineOpsProcessLessons: LessonSpec[] = [...knowledgeLessons, project];
