import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "任务调度与后台运行";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-schedule-cron-basics",
    stageId: "python-scheduling",
    order: 1,
    eyebrowStage: eyebrow,
    title: "cron 表达式语义解析",
    concept: "cron 五段字段依次为分/时/日/月/周，`*` 表示任意，`*/n` 表示每 n 步，逗号列举、连字符表示范围。读懂表达式比死记硬背更重要。",
    points: ["五段字段位置固定", "*/n 表示步长", "逗号/连字符组合表达"],
    memoryHook: "分时日月周，从左到右",
    fileName: "cron_read.py",
    code: `EXPR = "*/5 9-18 * * 1-5"\n\nfields = EXPR.split()\nlabels = ["minute", "hour", "day", "month", "weekday"]\nfor label, value in zip(labels, fields):\n    print(label, value)`,
    prompt: "`*/5 9-18 * * 1-5` 代表什么调度？",
    correct: "工作日 9 到 18 点之间，每 5 分钟触发一次",
    wrong: "每天固定 5 点、9 点、18 点各触发一次",
    output: "minute */5\nhour 9-18\nday *\nmonth *\nweekday 1-5",
    lanes: ["拆分表达式", "映射字段", "解释语义"],
    laneValues: ["split()", "labels 对齐", "输出解释"],
    log: ["拆分 5 段", "对齐字段", "输出映射"],
    summary: ["cron 是五段结构", "步长/范围/枚举可以组合", "先读懂再写调度"],
    sourceTitle: "crontab(5) 手册",
    sourceUrl: "https://man7.org/linux/man-pages/man5/crontab.5.html"
  }),
  createPythonLesson({
    id: "python-schedule-apscheduler-blocking",
    stageId: "python-scheduling",
    order: 2,
    eyebrowStage: eyebrow,
    title: "APScheduler BlockingScheduler",
    concept: "`BlockingScheduler` 独占当前进程主线程，适合作为脚本入口或 systemd 单元。适配 daemon 场景时可以搭配 `atexit` 优雅关闭，防止任务被强制中断。",
    points: ["BlockingScheduler 占用主线程", "add_job 注册可调用对象", "start 之后阻塞直到关闭"],
    memoryHook: "Blocking 是常驻脚本的心脏",
    fileName: "aps_blocking.py",
    code: `from apscheduler.schedulers.blocking import BlockingScheduler\n\ndef beat():\n    print("tick")\n\nscheduler = BlockingScheduler()\nscheduler.add_job(beat, "interval", seconds=5)\ntry:\n    scheduler.start()\nexcept (KeyboardInterrupt, SystemExit):\n    scheduler.shutdown()`,
    prompt: "为什么脚本入口常用 BlockingScheduler？",
    correct: "它会阻塞主线程，适合作为长期常驻的守护进程",
    wrong: "BlockingScheduler 会自动并发运行任务，比其他调度器更快",
    output: "tick",
    lanes: ["创建调度器", "注册任务", "启动阻塞"],
    laneValues: ["BlockingScheduler()", "add_job(beat)", "start()"],
    log: ["注册 interval=5", "开始阻塞", "tick"],
    summary: ["Blocking 适合脚本级常驻", "shutdown 用于优雅退出", "add_job 是主要注册入口"],
    sourceTitle: "APScheduler BlockingScheduler",
    sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/modules/schedulers/blocking.html"
  }),
  createPythonLesson({
    id: "python-schedule-apscheduler-triggers",
    stageId: "python-scheduling",
    order: 3,
    eyebrowStage: eyebrow,
    title: "Interval / Cron / Date 触发器",
    concept: "APScheduler 三种触发器：`interval` 按固定间隔、`cron` 用类 crontab 表达式、`date` 只跑一次。按业务节奏选择，别把一次性补数任务写成 interval。",
    points: ["interval 适合心跳", "cron 适合业务时段", "date 适合一次性回填"],
    memoryHook: "间隔、时段、一次性，选对触发器",
    fileName: "aps_triggers.py",
    code: `from apscheduler.schedulers.blocking import BlockingScheduler\nfrom datetime import datetime, timedelta\n\ndef pull_fx():\n    print("pull")\n\nscheduler = BlockingScheduler()\nscheduler.add_job(pull_fx, "interval", minutes=5, id="fx-interval")\nscheduler.add_job(pull_fx, "cron", day_of_week="mon-fri", hour="9-18", id="fx-cron")\nscheduler.add_job(pull_fx, "date", run_date=datetime.now() + timedelta(hours=1), id="fx-once")\nprint(len(scheduler.get_jobs()))`,
    prompt: "补数一次性任务应该选哪种触发器？",
    correct: "date 触发器，指定 run_date 后执行一次",
    wrong: "interval 触发器，把 seconds 设置得很大即可",
    output: "3",
    lanes: ["注册 interval", "注册 cron", "注册 date"],
    laneValues: ["fx-interval", "fx-cron", "fx-once"],
    log: ["add_job interval", "add_job cron", "add_job date"],
    summary: ["三种触发器语义不同", "id 便于事后管理", "触发器不能相互替代"],
    sourceTitle: "APScheduler triggers",
    sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/modules/triggers/interval.html"
  }),
  createPythonLesson({
    id: "python-schedule-idempotency",
    stageId: "python-scheduling",
    order: 4,
    eyebrowStage: eyebrow,
    title: "幂等设计与重复执行防护",
    concept: "调度容易出现漏跑或重跑，任务函数应当幂等：同一批次（例如 `YYYY-MM-DDTHH`）多次执行结果一致。可以用数据库唯一键或分布式锁去重。",
    points: ["用业务批次 ID 去重", "写入前先查是否存在", "副作用要有回滚或补偿"],
    memoryHook: "调度任务必须能重跑不出错",
    fileName: "idempotent.py",
    code: `PROCESSED = set()\n\ndef process(batch_id: str) -> str:\n    if batch_id in PROCESSED:\n        return "skip"\n    PROCESSED.add(batch_id)\n    return "done"\n\nprint(process("2026-07-24T10"))\nprint(process("2026-07-24T10"))`,
    prompt: "幂等设计的关键是？",
    correct: "同一批次的重复执行不会产生额外副作用",
    wrong: "确保任务运行时间尽可能短，减少重叠",
    output: "done\nskip",
    lanes: ["生成批次", "去重检查", "执行或跳过"],
    laneValues: ["batch_id", "查缓存", "done/skip"],
    log: ["首次执行", "第二次命中缓存", "skip"],
    summary: ["幂等靠业务批次 ID", "去重前置校验", "副作用需可回滚"],
    sourceTitle: "APScheduler misfire 手册",
    sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/userguide.html#missed-job-executions-and-coalescing"
  }),
  createPythonLesson({
    id: "python-schedule-retry-jitter",
    stageId: "python-scheduling",
    order: 5,
    eyebrowStage: eyebrow,
    title: "重试 + 抖动避免惊群",
    concept: "外部依赖抖动时，同一时刻的批量重试会形成惊群。采用指数退避 + 随机抖动，让重试时间点错开，缓解目标服务压力。",
    points: ["指数退避扩大间隔", "抖动避免同步重试", "限制最大次数防止死循环"],
    memoryHook: "退避 + 抖动 = 温柔的重试",
    fileName: "retry.py",
    code: `import random\nimport time\n\ndef backoff(attempt: int) -> float:\n    base = min(2 ** attempt, 30)\n    return base + random.uniform(0, base * 0.2)\n\nfor attempt in range(4):\n    delay = backoff(attempt)\n    print(f"attempt {attempt} wait {delay:.2f}s")\n    time.sleep(0)`,
    prompt: "为什么退避之外还要加抖动？",
    correct: "避免所有客户端在同一时间点集体重试形成惊群",
    wrong: "抖动只是为了让日志看起来更真实",
    output: "attempt 0 wait 1.14s\nattempt 1 wait 2.31s\nattempt 2 wait 4.62s\nattempt 3 wait 8.90s",
    lanes: ["计算 base", "叠加抖动", "触发重试"],
    laneValues: ["2**attempt", "random.uniform", "sleep 后重试"],
    log: ["attempt 0", "attempt 1", "attempt 3"],
    summary: ["指数退避避免打死目标", "抖动打散集群", "最大次数是安全带"],
    sourceTitle: "AWS 架构博客：Exponential Backoff And Jitter",
    sourceUrl: "https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/"
  }),
  createPythonLesson({
    id: "python-schedule-persistence",
    stageId: "python-scheduling",
    order: 6,
    eyebrowStage: eyebrow,
    title: "jobstore 持久化",
    concept: "默认 `MemoryJobStore` 重启即丢任务。生产环境应挂载 `SQLAlchemyJobStore` 或 Redis，把任务与下次触发时间落库，重启后仍能续跑。",
    points: ["MemoryJobStore 会丢任务", "SQLAlchemyJobStore 挂 SQLite/Postgres", "多实例需要防止重复调度"],
    memoryHook: "任务要落库，重启不丢活",
    fileName: "jobstore.py",
    code: `from apscheduler.schedulers.blocking import BlockingScheduler\nfrom apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore\n\njobstores = {"default": SQLAlchemyJobStore(url="sqlite:///jobs.sqlite")}\nscheduler = BlockingScheduler(jobstores=jobstores)\n\ndef sync():\n    print("sync")\n\nscheduler.add_job(sync, "interval", minutes=5, id="fx-sync", replace_existing=True)\nprint(scheduler.get_job("fx-sync").id)`,
    prompt: "为什么加 `replace_existing=True`？",
    correct: "任务落库后重启会重新注册，允许覆盖旧记录避免报错",
    wrong: "replace_existing 会让任务并发执行，提高性能",
    output: "fx-sync",
    lanes: ["配置 jobstore", "注册任务", "读取现存任务"],
    laneValues: ["SQLAlchemyJobStore", "add_job", "get_job"],
    log: ["连接 jobs.sqlite", "写入 fx-sync", "fx-sync"],
    summary: ["MemoryJobStore 不能生产", "SQLAlchemy 是常见选择", "replace_existing 处理重启"],
    sourceTitle: "APScheduler job stores",
    sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/modules/jobstores/sqlalchemy.html"
  }),
  createPythonLesson({
    id: "python-schedule-systemd-timer",
    stageId: "python-scheduling",
    order: 7,
    eyebrowStage: eyebrow,
    title: "systemd timer 与 OnCalendar",
    concept: "Linux 服务器上更稳的做法是把脚本封装成 `systemd` 单元，配 `.timer` 单元用 `OnCalendar` 触发，日志自动接入 journald，重启机器后由 systemd 恢复。",
    points: ["OnCalendar 语法比 cron 表达力更强", "Persistent=true 追赶漏跑", ".timer 与 .service 配对"],
    memoryHook: "systemd timer 是运维版 cron",
    fileName: "fx-sync.timer",
    code: `[Unit]\nDescription=Run fx sync every 5 minutes\n\n[Timer]\nOnCalendar=*:0/5\nPersistent=true\nAccuracySec=10s\nUnit=fx-sync.service\n\n[Install]\nWantedBy=timers.target`,
    prompt: "`Persistent=true` 的作用是？",
    correct: "机器关机错过的触发点在启动后立即补跑一次",
    wrong: "让 timer 单元一直存在，不会被 systemctl stop 停止",
    output: "timer 已装载",
    lanes: ["编写 timer", "关联 service", "启用调度"],
    laneValues: [".timer 单元", "Unit=fx-sync.service", "systemctl enable"],
    log: ["解析 OnCalendar", "关联 service", "启用 timer"],
    summary: ["OnCalendar 语法直观", "Persistent 处理漏跑", "配对 .service 单元执行"],
    sourceTitle: "systemd.timer",
    sourceUrl: "https://www.freedesktop.org/software/systemd/man/systemd.timer.html"
  }),
  createPythonLesson({
    id: "python-schedule-alerting",
    stageId: "python-scheduling",
    order: 8,
    eyebrowStage: eyebrow,
    title: "失败告警回调",
    concept: "监听 APScheduler 的 `EVENT_JOB_ERROR`，捕获异常后调用 Webhook（如飞书自定义机器人）推送告警。告警内容要包含任务 ID、批次和堆栈摘要，方便直接定位。",
    points: ["监听 JOB_ERROR 事件", "Webhook 附上 job_id 与批次", "告警要可关闭防止骚扰"],
    memoryHook: "任务失败要主动喊人",
    fileName: "alert.py",
    code: `import json\nimport urllib.request\nfrom apscheduler.events import EVENT_JOB_ERROR\nfrom apscheduler.schedulers.blocking import BlockingScheduler\n\nWEBHOOK = "https://open.feishu.cn/open-apis/bot/v2/hook/demo"\n\ndef notify(event):\n    payload = {\n        "msg_type": "text",\n        "content": {"text": f"job {event.job_id} failed: {event.exception!r}"},\n    }\n    req = urllib.request.Request(WEBHOOK, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json"})\n    urllib.request.urlopen(req, timeout=3)\n\nscheduler = BlockingScheduler()\nscheduler.add_listener(notify, EVENT_JOB_ERROR)\nprint("listener registered")`,
    prompt: "监听 EVENT_JOB_ERROR 的好处是？",
    correct: "任务抛异常时自动收到通知，不用等下一次巡检",
    wrong: "会自动阻止任务再次触发，避免连锁失败",
    output: "listener registered",
    lanes: ["注册监听", "捕获异常", "推送告警"],
    laneValues: ["add_listener", "EVENT_JOB_ERROR", "webhook 请求"],
    log: ["注册 listener", "触发异常事件", "发送 webhook"],
    summary: ["JOB_ERROR 事件适合告警", "Webhook 含 job_id 与堆栈", "告警需要开关避免骚扰"],
    sourceTitle: "APScheduler events",
    sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/modules/events.html"
  })
];

const project = createPythonStageProject({
  id: "python-scheduling-project",
  stageId: "python-scheduling",
  eyebrowStage: eyebrow,
  title: "跨机任务调度器",
  brief: "构建一个 APScheduler 调度器：SQLite jobstore 持久化任务、5 分钟拉取汇率、失败自动重试并推送告警。示例场景为每 5 分钟同步一次外币汇率。",
  concept: "串联本阶段：cron 表达式、BlockingScheduler、SQLAlchemyJobStore、指数退避重试、EVENT_JOB_ERROR 告警。目标是重启不丢任务，失败可自愈，异常有告警。",
  points: ["jobstore 保证重启不丢任务", "重试 + 抖动缓解外部抖动", "告警回调闭环失败情况"],
  memoryHook: "调度器 = 持久化 + 幂等 + 告警",
  fileName: "fx_scheduler.py",
  code: `import json\nimport logging\nimport random\nimport time\nimport urllib.request\nfrom datetime import datetime\n\nfrom apscheduler.events import EVENT_JOB_ERROR\nfrom apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore\nfrom apscheduler.schedulers.blocking import BlockingScheduler\n\nlogger = logging.getLogger("fx")\nWEBHOOK = "https://open.feishu.cn/open-apis/bot/v2/hook/demo"\nMAX_RETRY = 3\n\ndef fetch_rate(pair: str) -> float:\n    # 假设的外部调用，可能抛错\n    if random.random() < 0.2:\n        raise RuntimeError("upstream flaky")\n    return round(random.uniform(6.9, 7.3), 4)\n\ndef pull_fx(pair: str = "USD/CNY") -> None:\n    batch = datetime.utcnow().strftime("%Y-%m-%dT%H:%M")\n    for attempt in range(MAX_RETRY):\n        try:\n            rate = fetch_rate(pair)\n            logger.info(json.dumps({"batch": batch, "pair": pair, "rate": rate}))\n            return\n        except Exception:\n            wait = min(2 ** attempt, 30) + random.uniform(0, 1)\n            time.sleep(wait)\n    raise RuntimeError(f"{pair} still failing after {MAX_RETRY} attempts")\n\ndef notify(event) -> None:\n    payload = {\n        "msg_type": "text",\n        "content": {"text": f"job {event.job_id} failed: {event.exception!r}"},\n    }\n    req = urllib.request.Request(WEBHOOK, data=json.dumps(payload).encode("utf-8"), headers={"Content-Type": "application/json"})\n    try:\n        urllib.request.urlopen(req, timeout=3)\n    except Exception:\n        logger.exception("notify failed")\n\ndef build_scheduler() -> BlockingScheduler:\n    jobstores = {"default": SQLAlchemyJobStore(url="sqlite:///fx-jobs.sqlite")}\n    scheduler = BlockingScheduler(jobstores=jobstores, timezone="Asia/Shanghai")\n    scheduler.add_job(pull_fx, "cron", minute="*/5", id="fx-usd-cny", replace_existing=True, kwargs={"pair": "USD/CNY"})\n    scheduler.add_listener(notify, EVENT_JOB_ERROR)\n    return scheduler\n\nif __name__ == "__main__":\n    logging.basicConfig(level=logging.INFO)\n    build_scheduler().start()`,
  prompt: "这个调度器为什么把任务放进 SQLite jobstore？",
  correct: "机器重启或部署后任务仍然存在，避免手动重新注册",
  wrong: "SQLite 让调度更快，减少 GIL 竞争",
  correctFeedback: "正确：持久化 jobstore 是常驻调度器的基础，配合告警形成闭环。",
  wrongFeedback: "错误：jobstore 是为持久化而非性能，别把两件事混在一起。",
  additionalWrong: {
    label: "任务只要在容器里运行，就不需要持久化",
    feedback: "容器重启同样会丢内存里的任务，jobstore 依然必要。"
  },
  lanes: ["注册任务", "执行与重试", "失败告警"],
  laneValues: ["cron */5", "指数退避", "webhook 通知"],
  log: ["加载 SQLite jobstore", "每 5 分钟拉取", "失败推送告警"],
  summary: ["jobstore 落库保重启", "重试 + 抖动更抗抖", "JOB_ERROR 触发告警"],
  sourceTitle: "APScheduler 官方文档",
  sourceUrl: "https://apscheduler.readthedocs.io/en/3.x/"
});

export const pythonStageEightSchedulingLessons: LessonSpec[] = [...knowledgeLessons, project];
