import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "模块、包与测试";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-modules-testing-import-system",
    stageId: "python-modules-testing",
    order: 1,
    eyebrowStage: eyebrow,
    title: "import 系统：绝对与相对导入",
    concept: "Python 通过 `sys.path` 列表查找模块，第一个匹配的位置胜出。包内推荐使用绝对导入（`from mypkg.utils import x`），相对导入（`from .utils import x`）只在包内部使用，且不能在顶层脚本中运行。`__init__.py` 存在与否决定是常规包还是命名空间包。",
    points: ["sys.path 决定模块搜索顺序", "绝对导入是包内推荐写法", "相对导入不能在顶层脚本运行"],
    memoryHook: "sys.path 是清单，相对导入只在包里跑",
    fileName: "import_demo.py",
    code: `import sys\nfrom pathlib import Path\n\nprint(sys.path[0])\n\n# 绝对导入：从项目根开始定位\nfrom mypkg.services import loader\n\n# 相对导入：仅在被作为包的一部分导入时可用\n# from .services import loader  # 顶层 python import_demo.py 会报错\n\nresult = loader.load(Path("config.yaml"))\nprint(result)`,
    prompt: "关于绝对导入与相对导入，哪一项描述最准确？",
    correct: "相对导入依赖 __package__ 上下文，只在被作为包的一部分导入时生效；顶层脚本直接运行会报 ImportError",
    wrong: "相对导入与绝对导入完全等价，可以在任何脚本里互换使用",
    output: "/home/user/project\n{'db': 'sqlite:///data.db'}",
    lanes: ["解释器", "sys.path", "模块加载"],
    laneValues: ["解析 import 语句", "按路径搜索", "绑定模块对象"],
    log: ["Python 启动，构造 sys.path", "匹配 mypkg 目录", "loader 模块加载并执行"],
    summary: ["sys.path 首元素通常是脚本目录", "包内优先用绝对导入", "相对导入需要 __package__ 上下文"],
    sourceTitle: "The import system",
    sourceUrl: "https://docs.python.org/3/reference/import.html",
    correctFeedback: "对：相对导入依赖包上下文，直接执行会得到 ImportError: attempted relative import with no known parent package。",
    wrongFeedback: "错：相对导入不能在没有包上下文的顶层脚本中使用。",
    additionalWrong: {
      label: "sys.path 是只读的，运行时不能修改",
      feedback: "错：sys.path 是普通 list，可以在运行时 append/insert，但改动会影响后续 import 行为。"
    }
  }),
  createPythonLesson({
    id: "python-modules-testing-package-init",
    stageId: "python-modules-testing",
    order: 2,
    eyebrowStage: eyebrow,
    title: "常规包、命名空间包与 __all__",
    concept: "含 `__init__.py` 的目录是常规包（regular package），可以在初始化时执行代码、暴露公共 API。不含 `__init__.py` 的目录是命名空间包（PEP 420），允许跨多个路径拼接同一包。`__all__` 定义 `from pkg import *` 时导出的名字列表，也是包公开 API 的自文档。",
    points: ["常规包在 __init__ 中执行初始化", "命名空间包可跨目录合并", "__all__ 控制通配导入范围"],
    memoryHook: "有 __init__ 是常规包，__all__ 是门牌",
    fileName: "mypkg_init.py",
    code: `# mypkg/__init__.py\nfrom .loader import load_config\nfrom .writer import write_report\n\n__all__ = ["load_config", "write_report"]\n__version__ = "1.2.0"\n\nprint(f"mypkg {__version__} initialized")\n\n# 使用方：\n# from mypkg import *  # 只会导入 __all__ 列出的两个名字`,
    prompt: "关于 `__all__` 的作用，哪一项描述正确？",
    correct: "`__all__` 只影响 `from pkg import *` 的行为，同时是包公开 API 的自文档；显式 import 不受它限制",
    wrong: "`__all__` 会阻止其它模块访问未列出的名字，等价于访问控制",
    output: "mypkg 1.2.0 initialized",
    lanes: ["包发现", "__init__ 执行", "API 暴露"],
    laneValues: ["匹配目录", "加载 loader/writer", "填充 __all__"],
    log: ["解析 import mypkg", "运行 __init__.py", "对外暴露 load_config / write_report"],
    summary: ["__init__.py 是包入口", "命名空间包适合插件式拆分", "__all__ 记录公开 API"],
    sourceTitle: "Packages",
    sourceUrl: "https://docs.python.org/3/tutorial/modules.html#packages",
    correctFeedback: "对：Python 不提供真正的访问控制，__all__ 仅规范通配导入。",
    wrongFeedback: "错：Python 不阻止访问“私有”名字，_ 前缀与 __all__ 只是约定。"
  }),
  createPythonLesson({
    id: "python-modules-testing-venv-pip",
    stageId: "python-modules-testing",
    order: 3,
    eyebrowStage: eyebrow,
    title: "虚拟环境与 pip 安装模式",
    concept: "`python -m venv .venv` 创建隔离环境，激活后 `pip install` 只影响该环境。`pip install -e .` 以“可编辑”方式安装本地项目，源码改动实时生效。`requirements.txt` 用于锁定版本，生产部署时配合 `pip install -r requirements.txt --no-deps` 或 pip-tools/uv 生成的锁文件。",
    points: ["venv 隔离依赖不污染系统", "-e . 可编辑安装本地代码", "requirements.txt 锁定复现版本"],
    memoryHook: "venv 是沙盒，-e 让本地代码可改可用",
    fileName: "setup_env.sh",
    code: `# 创建虚拟环境\npython -m venv .venv\nsource .venv/bin/activate\n\n# 升级 pip 并安装依赖\npython -m pip install --upgrade pip\npip install -r requirements.txt\n\n# 以可编辑方式安装当前项目（读取 pyproject.toml）\npip install -e .\n\n# 验证\npython -c "import mypkg; print(mypkg.__version__)"`,
    prompt: "为什么推荐用 `pip install -e .` 而不是 `pip install .`？",
    correct: "-e 会安装成指向源码的链接，修改本地代码立即生效，无需反复重装，适合开发阶段",
    wrong: "-e 只是别名，与不带 -e 完全等价，只影响下载速度",
    output: "mypkg 1.2.0",
    lanes: ["venv 创建", "pip 安装", "验证导入"],
    laneValues: ["生成 .venv 目录", "解析 requirements", "打印版本号"],
    log: ["python -m venv .venv", "pip install -r requirements.txt 完成", "import mypkg 成功"],
    summary: ["venv 是官方推荐隔离方案", "可编辑安装适合开发调试", "锁文件保证部署可复现"],
    sourceTitle: "venv — Creation of virtual environments",
    sourceUrl: "https://docs.python.org/3/library/venv.html"
  }),
  createPythonLesson({
    id: "python-modules-testing-src-layout",
    stageId: "python-modules-testing",
    order: 4,
    eyebrowStage: eyebrow,
    title: "src 布局与 pyproject.toml",
    concept: "src 布局把包源码放在 `src/mypkg/` 下，测试放在 `tests/`，两者分离后运行测试必须先安装包（`pip install -e .`），避免“测试到未安装的临时目录版本”的假象。`pyproject.toml` 是 PEP 621 标准的项目元数据，取代旧的 setup.py。",
    points: ["src/ 与 tests/ 分离避免误导入", "pyproject.toml 是 PEP 621 标准", "测试前必须先安装包"],
    memoryHook: "src 布局强制走真实安装路径",
    fileName: "pyproject.toml",
    code: `[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n\n[project]\nname = "mypkg"\nversion = "1.2.0"\nrequires-python = ">=3.11"\ndependencies = ["pyyaml>=6.0"]\n\n[project.optional-dependencies]\ndev = ["pytest>=8.0", "pytest-cov", "mypy"]\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\npythonpath = ["src"]`,
    prompt: "为什么推荐 src 布局而不是把包直接放在项目根目录？",
    correct: "src 布局强制通过安装后的路径导入，避免测试意外命中源码目录，暴露打包时缺失的资源",
    wrong: "src 布局纯粹是审美偏好，对测试和打包没有任何区别",
    output: "配置文件本身不产生运行时输出",
    lanes: ["读取配置", "解析元数据", "配置测试路径"],
    laneValues: ["加载 pyproject.toml", "识别依赖与可选组", "pytest 使用 src 路径"],
    log: ["hatchling 读取 [project] 段", "pip 解析依赖", "pytest 从 tests 加载用例"],
    summary: ["pyproject.toml 是现代 Python 项目标准", "src 布局强化测试真实性", "可选依赖用于分离开发工具链"],
    sourceTitle: "Writing your pyproject.toml",
    sourceUrl: "https://packaging.python.org/en/latest/guides/writing-pyproject-toml/",
    correctFeedback: "对：src 布局的核心价值是避免“误用未安装的源码”，让测试贴近真实分发形态。",
    wrongFeedback: "错：src 布局有明确的工程意义，能暴露打包资源缺失等问题。"
  }),
  createPythonLesson({
    id: "python-modules-testing-pytest-basics",
    stageId: "python-modules-testing",
    order: 5,
    eyebrowStage: eyebrow,
    title: "pytest 基础：断言与参数化",
    concept: "pytest 直接使用 `assert` 断言并做智能重写，失败时显示两侧变量的实际值。`pytest.raises` 用于断言异常，`@pytest.mark.parametrize` 用一份测试覆盖多组输入，让边界用例集中管理。",
    points: ["assert 由 pytest 重写显示细节", "pytest.raises 断言异常类型", "parametrize 展开为多个用例"],
    memoryHook: "assert 直写，parametrize 展开表格",
    fileName: "test_parser.py",
    code: `import pytest\nfrom mypkg.parser import parse_port\n\n@pytest.mark.parametrize("raw,expected", [\n    ("80", 80),\n    ("8080", 8080),\n    ("65535", 65535),\n])\ndef test_parse_port_ok(raw, expected):\n    assert parse_port(raw) == expected\n\ndef test_parse_port_out_of_range():\n    with pytest.raises(ValueError, match="out of range"):\n        parse_port("70000")`,
    prompt: "关于 `parametrize` 与 `pytest.raises`，哪一项描述准确？",
    correct: "parametrize 会为每组入参生成独立用例并单独报告；pytest.raises 通过上下文管理器捕获期望异常并可校验消息",
    wrong: "parametrize 会把所有入参合并为一个用例，任意一组失败就全部失败但看不到具体哪组",
    output: "4 passed in 0.03s",
    lanes: ["测试收集", "参数展开", "断言执行"],
    laneValues: ["扫描 tests/", "生成 4 个用例", "全部通过"],
    log: ["pytest 收集 test_parser.py", "parametrize 展开为 3 个 test_parse_port_ok", "raises 匹配 ValueError"],
    summary: ["assert 有智能失败输出", "parametrize 减少重复代码", "raises 支持 match 校验消息"],
    sourceTitle: "pytest documentation",
    sourceUrl: "https://docs.pytest.org/en/stable/how-to/parametrize.html"
  }),
  createPythonLesson({
    id: "python-modules-testing-fixture",
    stageId: "python-modules-testing",
    order: 6,
    eyebrowStage: eyebrow,
    title: "fixture：作用域、autouse 与依赖",
    concept: "`@pytest.fixture` 声明可复用的准备/清理逻辑。scope 控制生命周期（function/class/module/session），function 是默认值。`autouse=True` 让 fixture 自动应用到范围内所有用例；fixture 可以依赖其它 fixture，pytest 会自动解析依赖图。",
    points: ["scope 决定共享粒度", "autouse 自动生效免声明", "fixture 可以链式依赖"],
    memoryHook: "scope 决定复用范围，autouse 是背景板",
    fileName: "conftest.py",
    code: `import pytest\nfrom pathlib import Path\n\n@pytest.fixture(scope="session")\ndef workspace(tmp_path_factory):\n    root = tmp_path_factory.mktemp("ws")\n    (root / "config.yaml").write_text("db: sqlite:///:memory:\\n")\n    return root\n\n@pytest.fixture\ndef config_path(workspace: Path) -> Path:\n    return workspace / "config.yaml"\n\n@pytest.fixture(autouse=True)\ndef _reset_env(monkeypatch):\n    monkeypatch.delenv("APP_ENV", raising=False)`,
    prompt: "关于 fixture 的 scope 与 autouse，哪一项描述最准确？",
    correct: "scope=session 时 workspace 在整个测试会话中只创建一次并被多个用例共享；autouse fixture 无需在参数列表中声明就会执行",
    wrong: "所有 fixture 无论 scope 都会在每个用例前后重新执行一次",
    output: "1 passed in 0.02s",
    lanes: ["fixture 注册", "依赖解析", "清理"],
    laneValues: ["加载 conftest", "构造 workspace → config_path", "session 结束回收"],
    log: ["session fixture workspace 创建一次", "config_path 依赖 workspace", "autouse _reset_env 每用例自动生效"],
    summary: ["scope 越大生命周期越长", "autouse 适合环境重置", "fixture 依赖图由 pytest 解析"],
    sourceTitle: "pytest fixtures",
    sourceUrl: "https://docs.pytest.org/en/stable/how-to/fixtures.html",
    correctFeedback: "对：scope 让准备工作成本可控，autouse 适合把“每个用例都要做”的重置内建成默认。",
    wrongFeedback: "错：不同 scope 生命周期不同，session 级别只创建一次。",
    additionalWrong: {
      label: "fixture 不能依赖其它 fixture，必须自包含",
      feedback: "错：fixture 可以在参数中声明依赖，pytest 会自动按拓扑顺序构造。"
    }
  }),
  createPythonLesson({
    id: "python-modules-testing-mock-patch",
    stageId: "python-modules-testing",
    order: 7,
    eyebrowStage: eyebrow,
    title: "unittest.mock：patch 位置与 MagicMock",
    concept: "`unittest.mock.patch` 的关键原则是“在使用处 patch，而不是在定义处 patch”。例如 `mypkg.service` 里 `from mypkg.io import fetch`，测试时要 patch `mypkg.service.fetch` 而不是 `mypkg.io.fetch`。`MagicMock` 支持任意属性/调用链，`return_value` 与 `side_effect` 组合可以模拟正常与异常路径。",
    points: ["patch 目标是使用位置", "side_effect 模拟异常路径", "MagicMock 自动生成属性链"],
    memoryHook: "patch 使用处，不 patch 定义处",
    fileName: "test_service.py",
    code: `from unittest.mock import patch, MagicMock\nfrom mypkg.service import summarize\n\n@patch("mypkg.service.fetch")  # 在 service 模块里 patch，而非 mypkg.io\ndef test_summarize_uses_cached_response(mock_fetch: MagicMock):\n    mock_fetch.return_value = {"items": [1, 2, 3]}\n    result = summarize(user_id=42)\n    mock_fetch.assert_called_once_with(user_id=42)\n    assert result == 6\n\n@patch("mypkg.service.fetch", side_effect=TimeoutError("upstream slow"))\ndef test_summarize_propagates_timeout(_mock_fetch):\n    import pytest\n    with pytest.raises(TimeoutError):\n        summarize(user_id=1)`,
    prompt: "为什么要 patch `mypkg.service.fetch` 而不是 `mypkg.io.fetch`？",
    correct: "`from mypkg.io import fetch` 会在 mypkg.service 命名空间中绑定一个引用，patch 定义处对这个已绑定的引用无效",
    wrong: "两者完全等价，patch 任何一处都能拦截到调用",
    output: "2 passed in 0.04s",
    lanes: ["定位使用处", "替换为 Mock", "断言调用"],
    laneValues: ["mypkg.service.fetch", "MagicMock 返回预设值", "assert_called_once_with"],
    log: ["patch 生效于 mypkg.service", "summarize 调用 fetch 命中 Mock", "断言调用参数与返回"],
    summary: ["Mock 目标要看导入语义", "side_effect 支持异常与序列", "assert_called_* 校验交互"],
    sourceTitle: "unittest.mock — where to patch",
    sourceUrl: "https://docs.python.org/3/library/unittest.mock.html#where-to-patch"
  }),
  createPythonLesson({
    id: "python-modules-testing-coverage-mypy",
    stageId: "python-modules-testing",
    order: 8,
    eyebrowStage: eyebrow,
    title: "覆盖率与 mypy 类型检查",
    concept: "`coverage.py`（通常通过 `pytest --cov`）度量“测试执行了哪些行”，但高覆盖率不等价于用例质量，还需关注分支覆盖与断言强度。`mypy --strict` 强制注解完整、拒绝隐式 Any，能在运行前捕获大量类型不一致的问题；测试代码也建议加类型注解，让 mock 参数、返回值有静态保障。",
    points: ["--cov 提供行/分支覆盖", "mypy --strict 拒绝隐式 Any", "测试也应带类型注解"],
    memoryHook: "覆盖率看广度，mypy 看正确性",
    fileName: "ci_check.sh",
    code: `# 类型检查：strict 模式暴露隐式 Any\nmypy --strict src/mypkg\n\n# 单测 + 覆盖率：低于 85% 直接失败\npytest \\\n  --cov=mypkg \\\n  --cov-branch \\\n  --cov-report=term-missing \\\n  --cov-fail-under=85\n\n# 输出示例：\n# TOTAL   412   38   91%\n# Required test coverage of 85% reached.`,
    prompt: "关于覆盖率与类型检查，哪一项理解最准确？",
    correct: "覆盖率只保证代码被执行过，需要配合分支覆盖与断言强度评估；mypy --strict 在运行前捕获类型不一致，两者互补",
    wrong: "覆盖率 100% 就意味着代码无缺陷，无需再运行 mypy",
    output: "TOTAL 412 38 91%\nRequired test coverage of 85% reached.",
    lanes: ["静态检查", "测试执行", "覆盖率报告"],
    laneValues: ["mypy --strict", "pytest --cov", "生成 term-missing"],
    log: ["mypy 扫描 src/mypkg 通过", "pytest 收集并运行用例", "分支覆盖率 91% 满足门槛"],
    summary: ["行覆盖 ≠ 断言完整", "--cov-branch 揭示未走的分支", "mypy 与 pytest 是互补而非替代"],
    sourceTitle: "mypy documentation",
    sourceUrl: "https://mypy.readthedocs.io/en/stable/command_line.html",
    correctFeedback: "对：覆盖率反映“行是否被执行”，正确性还要靠断言与类型检查双保险。",
    wrongFeedback: "错：即使 100% 覆盖，弱断言也可能漏掉逻辑错误；mypy 关注的问题维度不同。",
    additionalWrong: {
      label: "mypy 只对新写的类型注解生效，对没写注解的函数完全跳过检查",
      feedback: "错：--strict 会把缺失注解视为错误；即使非 strict，未注解函数也会按推断规则参与检查。"
    }
  })
];

const project = createPythonStageProject({
  id: "python-modules-testing-project",
  stageId: "python-modules-testing",
  eyebrowStage: eyebrow,
  title: "可测试配置解析器",
  brief: "用 dataclass 建模配置，支持 YAML 与环境变量覆盖；抽出可注入的读取器便于替换；用 pytest + parametrize + monkeypatch 覆盖成功与异常路径，并输出分支覆盖率报告。",
  concept: "配置解析是典型的“IO + 纯逻辑”混合问题：用 dataclass 表达目标模型，用协议/回调抽出读取器（Reader）以便注入 Mock；解析逻辑保持纯函数，接受字典输入返回 dataclass；测试时通过 monkeypatch 覆盖环境变量、通过参数化列表覆盖边界值，最后用 coverage 检查分支覆盖率。",
  points: ["dataclass 表达配置模型", "IO 与纯逻辑分离便于注入", "参数化 + monkeypatch 覆盖分支"],
  memoryHook: "先建模，再解耦 IO，最后覆盖分支",
  fileName: "config_loader.py",
  code: `# src/mypkg/config.py\nimport os\nimport yaml\nfrom dataclasses import dataclass\nfrom pathlib import Path\nfrom typing import Callable, Mapping\n\n@dataclass(frozen=True)\nclass AppConfig:\n    database_url: str\n    debug: bool = False\n\nReader = Callable[[Path], Mapping[str, object]]\n\ndef _yaml_reader(path: Path) -> Mapping[str, object]:\n    return yaml.safe_load(path.read_text()) or {}\n\ndef load(path: Path, reader: Reader = _yaml_reader) -> AppConfig:\n    raw = dict(reader(path))\n    if url := os.getenv("DATABASE_URL"):\n        raw["database_url"] = url\n    if "database_url" not in raw:\n        raise ValueError("database_url is required")\n    return AppConfig(database_url=str(raw["database_url"]),\n                     debug=bool(raw.get("debug", False)))\n\n# tests/test_config.py\nimport pytest\nfrom mypkg.config import AppConfig, load\n\ndef test_env_overrides_file(tmp_path, monkeypatch):\n    (tmp_path / "c.yaml").write_text("database_url: sqlite:///file.db\\n")\n    monkeypatch.setenv("DATABASE_URL", "postgres://env")\n    cfg = load(tmp_path / "c.yaml")\n    assert cfg == AppConfig(database_url="postgres://env", debug=False)\n\ndef test_missing_url_raises(tmp_path, monkeypatch):\n    (tmp_path / "c.yaml").write_text("debug: true\\n")\n    monkeypatch.delenv("DATABASE_URL", raising=False)\n    with pytest.raises(ValueError, match="database_url"):\n        load(tmp_path / "c.yaml")`,
  prompt: "在这个可测试配置解析器中，哪种设计最有利于用例覆盖？",
  correct: "把 IO 抽成 Reader 回调注入 `load`，解析逻辑保持纯函数；测试用 monkeypatch 控制环境变量、用 tmp_path 提供文件、用参数化覆盖边界",
  wrong: "把 YAML 读取、环境变量读取、字段校验都写在同一个函数里，靠真实文件系统跑测试",
  additionalWrong: {
    label: "只对成功路径写一条冒烟测试，异常与优先级不必显式覆盖",
    feedback: "错：配置解析的价值往往在异常路径（缺字段、类型错误、优先级），必须显式覆盖。"
  },
  correctFeedback: "对：可注入的 Reader + 纯解析函数让分支易于覆盖，monkeypatch/tmp_path 消除对真实环境的依赖。",
  wrongFeedback: "错：耦合 IO 与解析会让测试脆弱、慢，且很难覆盖异常分支。",
  lanes: ["模型建立", "解析执行", "测试验证"],
  laneValues: ["定义 AppConfig", "load 合并环境变量", "pytest 覆盖成功与异常"],
  log: ["加载 YAML 得到原始字典", "环境变量 DATABASE_URL 覆盖 file 值", "AppConfig 构造完成并通过测试"],
  summary: ["dataclass 让配置有明确形状", "依赖注入让测试无需真实 IO", "分支覆盖率是评估用例完整性的最低门槛"],
  sourceTitle: "pytest How-to guides",
  sourceUrl: "https://docs.pytest.org/en/stable/how-to/index.html"
});

export const pythonStageTwoModulesTestingLessons: LessonSpec[] = [
  ...knowledgeLessons,
  project
];
