import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "HTTP 抓取与数据管道";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-http-requests-basics",
    stageId: "python-http-scraping",
    order: 1,
    eyebrowStage: eyebrow,
    title: "requests.get 与响应对象",
    concept: "`requests.get` 返回 `Response` 对象，`raise_for_status` 把 4xx/5xx 转换为异常，`response.json()` 只在 `Content-Type` 是 JSON 时才安全调用。默认没有超时，工程代码必须显式指定。",
    points: ["永远显式传 timeout", "raise_for_status 转异常", "response.json 前先看类型"],
    memoryHook: "requests 不设超时，就是给自己埋雷",
    fileName: "requests_basics.py",
    code: `import requests\n\nresp = requests.get("https://httpbin.org/json", timeout=5)\nresp.raise_for_status()\nprint(resp.status_code, resp.headers["Content-Type"])\nprint(resp.json()["slideshow"]["title"])`,
    prompt: "为什么工程代码必须给 requests.get 传 timeout？",
    correct: "requests 默认无超时，网络卡住会让线程永久挂起",
    wrong: "timeout 只是提示服务器，客户端不会真正生效",
    output: "200 application/json\nSample Slide Show",
    lanes: ["发起请求", "校验状态", "解析响应"],
    laneValues: ["GET /json timeout=5", "raise_for_status", "取 slideshow.title"],
    log: ["请求 httpbin", "200 OK", "打印标题"],
    summary: ["timeout 是硬要求", "raise_for_status 提早失败", "response.json 依赖 Content-Type"],
    sourceTitle: "Requests: HTTP for Humans",
    sourceUrl: "https://requests.readthedocs.io/en/latest/"
  }),
  createPythonLesson({
    id: "python-http-httpx-async",
    stageId: "python-http-scraping",
    order: 2,
    eyebrowStage: eyebrow,
    title: "httpx.AsyncClient 并发请求",
    concept: "`httpx.AsyncClient` 在同一 event loop 内复用连接池，配合 `asyncio.gather` 可以并发发起数十个请求。相比开 N 个线程，协程内存和上下文切换代价更低。",
    points: ["AsyncClient 复用连接池", "gather 并发多个协程", "同步/异步 API 保持一致"],
    memoryHook: "httpx = requests 同款 API，多送一个 async",
    fileName: "httpx_async.py",
    code: `import asyncio\nimport httpx\n\nasync def fetch(client: httpx.AsyncClient, path: str) -> int:\n    resp = await client.get(path, timeout=5)\n    return resp.status_code\n\nasync def main() -> None:\n    async with httpx.AsyncClient(base_url="https://httpbin.org") as client:\n        codes = await asyncio.gather(*[fetch(client, "/status/200") for _ in range(3)])\n    print(codes)\n\nasyncio.run(main())`,
    prompt: "为什么使用 AsyncClient 而不是每次都 httpx.get？",
    correct: "共享连接池减少 TLS 握手开销，并适合与 asyncio.gather 组合",
    wrong: "AsyncClient 是老 API，httpx.get 更快因为无状态",
    output: "[200, 200, 200]",
    lanes: ["建立客户端", "并发请求", "汇总状态"],
    laneValues: ["AsyncClient", "gather 3 个 fetch", "[200, 200, 200]"],
    log: ["初始化连接池", "并发 3 个请求", "打印状态列表"],
    summary: ["AsyncClient 复用连接", "gather 组合协程", "同步 Client 语义一致"],
    sourceTitle: "HTTPX",
    sourceUrl: "https://www.python-httpx.org/"
  }),
  createPythonLesson({
    id: "python-http-rate-limit",
    stageId: "python-http-scraping",
    order: 3,
    eyebrowStage: eyebrow,
    title: "限流与令牌桶",
    concept: "同步脚本用 `time.sleep` 强制间隔即可，异步场景应使用 `asyncio.Semaphore` 限制并发数，或用令牌桶按 QPS 发放许可。目标是尊重上游速率限制，避免被封禁。",
    points: ["同步用 sleep 或 tenacity", "asyncio.Semaphore 限并发", "令牌桶按 QPS 控制"],
    memoryHook: "限流不是可选项，是抓取合规的护身符",
    fileName: "rate_limit.py",
    code: `import asyncio\n\nsemaphore = asyncio.Semaphore(2)\n\nasync def call(i: int) -> None:\n    async with semaphore:\n        await asyncio.sleep(0.1)\n        print("done", i)\n\nasync def main() -> None:\n    await asyncio.gather(*[call(i) for i in range(4)])\n\nasyncio.run(main())`,
    prompt: "为什么爬虫脚本必须做限流？",
    correct: "尊重上游速率限制，避免被封禁或触发反爬",
    wrong: "限流只在生产环境需要，抓取脚本可以省略",
    output: "done 0\ndone 1\ndone 2\ndone 3",
    lanes: ["申请令牌", "受限执行", "释放令牌"],
    laneValues: ["Semaphore(2)", "并发 2 个 call", "打印 done"],
    log: ["初始化信号量", "两两执行", "输出四行 done"],
    summary: ["同步用 sleep", "asyncio.Semaphore 控并发", "令牌桶适合精确 QPS"],
    sourceTitle: "Python asyncio.Semaphore",
    sourceUrl: "https://docs.python.org/3/library/asyncio-sync.html#asyncio.Semaphore"
  }),
  createPythonLesson({
    id: "python-http-retry-backoff",
    stageId: "python-http-scraping",
    order: 4,
    eyebrowStage: eyebrow,
    title: "指数退避与 Retry 策略",
    concept: "网络请求应对瞬时故障，用 `urllib3.util.retry.Retry` 或 `tenacity` 组合状态码白名单 + 指数退避。只对 429/5xx 重试，避免放大 4xx 的错误。",
    points: ["只对幂等或 5xx 重试", "指数退避 + jitter", "记录最终失败进入死信队列"],
    memoryHook: "重试要幂等，退避要有 jitter",
    fileName: "retry.py",
    code: `import requests\nfrom requests.adapters import HTTPAdapter\nfrom urllib3.util.retry import Retry\n\nretry = Retry(total=3, backoff_factor=0.5, status_forcelist=[429, 500, 502, 503, 504])\nsession = requests.Session()\nsession.mount("https://", HTTPAdapter(max_retries=retry))\nresp = session.get("https://httpbin.org/status/200", timeout=5)\nprint(resp.status_code)`,
    prompt: "为什么不能对所有错误都重试？",
    correct: "非幂等请求或 4xx 客户端错误重试会放大故障和数据不一致",
    wrong: "重试次数越多越好，可以覆盖所有场景",
    output: "200",
    lanes: ["注册 Retry", "发起请求", "命中或退避"],
    laneValues: ["Retry(total=3)", "GET status/200", "打印 200"],
    log: ["挂载适配器", "发起请求", "200"],
    summary: ["幂等请求才能安全重试", "status_forcelist 精确控制", "记录最终失败便于回查"],
    sourceTitle: "urllib3 Retry",
    sourceUrl: "https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry"
  }),
  createPythonLesson({
    id: "python-http-html-extract",
    stageId: "python-http-scraping",
    order: 5,
    eyebrowStage: eyebrow,
    title: "selectolax 抽取 HTML 内容",
    concept: "`selectolax` 使用 C 实现的 modest 引擎，解析速度显著优于 BeautifulSoup。用 CSS selector 定位节点，`text(strip=True)` 拿到清洗后的文本。",
    points: ["selectolax 比 bs4 快数倍", "CSS selector 表达节点", "text(strip=True) 直接去空白"],
    memoryHook: "抓取要吞海量 HTML？先想 selectolax",
    fileName: "extract.py",
    code: `from selectolax.parser import HTMLParser\n\nhtml = "<ul><li class='item'>A</li><li class='item'>B</li></ul>"\ntree = HTMLParser(html)\nitems = [node.text(strip=True) for node in tree.css("li.item")]\nprint(items)`,
    prompt: "为什么大规模抓取偏好 selectolax？",
    correct: "底层是 C 实现，解析速度显著快于纯 Python 的 bs4",
    wrong: "selectolax 支持 JavaScript 渲染，是无头浏览器",
    output: "['A', 'B']",
    lanes: ["加载 HTML", "CSS 选择", "输出文本"],
    laneValues: ["HTMLParser", "css('li.item')", "['A', 'B']"],
    log: ["解析 HTML", "命中两个 li", "输出列表"],
    summary: ["selectolax 走 C 引擎", "CSS selector 表达式清晰", "text(strip=True) 一步到位"],
    sourceTitle: "selectolax documentation",
    sourceUrl: "https://selectolax.readthedocs.io/"
  }),
  createPythonLesson({
    id: "python-http-persist-sqlite",
    stageId: "python-http-scraping",
    order: 6,
    eyebrowStage: eyebrow,
    title: "sqlite3 增量入库",
    concept: "抓取到的记录用 `INSERT OR IGNORE`（配合 UNIQUE 索引）实现增量写入。启用 WAL 模式让读写不互相阻塞，`executemany` 批量提交，事务粒度不要过大。",
    points: ["UNIQUE + INSERT OR IGNORE 去重", "WAL 模式提升并发", "executemany 批量提交"],
    memoryHook: "增量入库 = 唯一键 + INSERT OR IGNORE",
    fileName: "persist.py",
    code: `import sqlite3\n\nconn = sqlite3.connect(":memory:")\nconn.execute("PRAGMA journal_mode=WAL")\nconn.execute("CREATE TABLE items (hash TEXT PRIMARY KEY, name TEXT)")\nrows = [("h1", "A"), ("h2", "B"), ("h1", "A-dup")]\nconn.executemany("INSERT OR IGNORE INTO items VALUES (?, ?)", rows)\nconn.commit()\nprint(conn.execute("SELECT COUNT(*) FROM items").fetchone()[0])`,
    prompt: "为什么用 INSERT OR IGNORE 而不是先 SELECT 再 INSERT？",
    correct: "一次 SQL 由数据库保证幂等，减少往返和竞态窗口",
    wrong: "两次 SQL 更快，因为 IGNORE 会禁用索引",
    output: "2",
    lanes: ["建表", "批量写入", "计数校验"],
    laneValues: ["CREATE TABLE", "INSERT OR IGNORE", "COUNT = 2"],
    log: ["开启 WAL", "写入 3 行 (1 重复)", "结果 2"],
    summary: ["UNIQUE 索引兜底去重", "WAL 让读写并发", "executemany 减少往返"],
    sourceTitle: "Python sqlite3",
    sourceUrl: "https://docs.python.org/3/library/sqlite3.html"
  }),
  createPythonLesson({
    id: "python-http-session-headers",
    stageId: "python-http-scraping",
    order: 7,
    eyebrowStage: eyebrow,
    title: "Session 复用与 UA/Cookie",
    concept: "`requests.Session` 自动管理 Cookie、连接复用和默认 headers。爬虫必须显式设置合规的 User-Agent，说明用途和联系方式，才符合大多数站点的抓取要求。",
    points: ["Session 复用 TCP 连接", "统一注入 UA/Referer", "Cookie 自动跨请求携带"],
    memoryHook: "长任务用 Session，短请求也别忘 UA",
    fileName: "session.py",
    code: `import requests\n\nsession = requests.Session()\nsession.headers.update({"User-Agent": "NodePathBot/1.0 (+contact@example.com)"})\nresp = session.get("https://httpbin.org/headers", timeout=5)\nresp.raise_for_status()\nprint(resp.json()["headers"]["User-Agent"])`,
    prompt: "为什么爬虫应显式设置 User-Agent？",
    correct: "标注身份和联系方式，方便站点管理员沟通并遵守抓取政策",
    wrong: "默认 UA 已经匿名，无需修改",
    output: "NodePathBot/1.0 (+contact@example.com)",
    lanes: ["建立会话", "注入 headers", "发起请求"],
    laneValues: ["Session()", "update UA", "GET /headers"],
    log: ["复用连接", "注入 UA", "回显 UA"],
    summary: ["Session 复用连接池", "统一 headers 管理", "身份透明降低封禁概率"],
    sourceTitle: "Requests — Session Objects",
    sourceUrl: "https://requests.readthedocs.io/en/latest/user/advanced/#session-objects"
  }),
  createPythonLesson({
    id: "python-http-robots-legal",
    stageId: "python-http-scraping",
    order: 8,
    eyebrowStage: eyebrow,
    title: "robots.txt 与合规边界",
    concept: "`urllib.robotparser.RobotFileParser` 加载并解析 robots.txt。在抓取之前应校验 `can_fetch` 与站点条款；robots.txt 只是自律协议，法律和条款仍需人工确认。",
    points: ["robots.txt 是自律协议", "can_fetch 判断路径", "条款和法律需要额外确认"],
    memoryHook: "robots.txt 是最低门槛，不是免责金牌",
    fileName: "robots.py",
    code: `from urllib.robotparser import RobotFileParser\n\nrp = RobotFileParser()\nrp.set_url("https://www.example.com/robots.txt")\nrp.read()\nprint(rp.can_fetch("NodePathBot", "https://www.example.com/"))\nprint(rp.can_fetch("NodePathBot", "https://www.example.com/private"))`,
    prompt: "为什么合规抓取只看 robots.txt 是不够的？",
    correct: "robots.txt 是自律协议，法律和站点条款可能有额外限制",
    wrong: "robots.txt 通过就意味着任何数据都能商用",
    output: "True\nFalse",
    lanes: ["加载 robots", "解析规则", "校验路径"],
    laneValues: ["RobotFileParser", "read()", "can_fetch"],
    log: ["下载 robots.txt", "解析规则", "True/False"],
    summary: ["can_fetch 是入门门槛", "站点条款需要额外阅读", "合规抓取包含限速与身份"],
    sourceTitle: "Python urllib.robotparser",
    sourceUrl: "https://docs.python.org/3/library/urllib.robotparser.html"
  })
];

const project = createPythonStageProject({
  id: "python-http-scraping-project",
  stageId: "python-http-scraping",
  eyebrowStage: eyebrow,
  title: "站点抓取与增量入库脚本",
  brief: "构建一个抓取器：从示例站点拉取商品列表，按 hash 去重，增量入库到 SQLite，并输出运行报告。",
  concept: "整合 Session、限流、Retry、selectolax 抽取与 sqlite3 增量落库，展示一个可长期运行的抓取骨架。",
  points: ["Session + Retry 兜底网络", "hash 作为唯一键", "报告写出运行摘要"],
  memoryHook: "抓取脚本 = 会话 + 限流 + 去重 + 报告",
  fileName: "scrape.py",
  code: `import hashlib\nimport sqlite3\nimport time\nimport requests\nfrom requests.adapters import HTTPAdapter\nfrom selectolax.parser import HTMLParser\nfrom urllib3.util.retry import Retry\n\nSCHEMA = "CREATE TABLE IF NOT EXISTS items (hash TEXT PRIMARY KEY, name TEXT, price TEXT)"\n\ndef build_session() -> requests.Session:\n    retry = Retry(total=3, backoff_factor=0.5, status_forcelist=[429, 500, 502, 503, 504])\n    session = requests.Session()\n    session.headers.update({"User-Agent": "NodePathBot/1.0 (+contact@example.com)"})\n    session.mount("https://", HTTPAdapter(max_retries=retry))\n    return session\n\ndef parse_items(html: str) -> list[dict]:\n    tree = HTMLParser(html)\n    items = []\n    for card in tree.css("li.product"):\n        name = card.css_first("h3").text(strip=True)\n        price = card.css_first("span.price").text(strip=True)\n        items.append({"name": name, "price": price})\n    return items\n\ndef ingest(conn: sqlite3.Connection, items: list[dict]) -> int:\n    rows = [(hashlib.blake2b(f"{i['name']}|{i['price']}".encode(), digest_size=16).hexdigest(), i["name"], i["price"]) for i in items]\n    before = conn.execute("SELECT COUNT(*) FROM items").fetchone()[0]\n    conn.executemany("INSERT OR IGNORE INTO items VALUES (?, ?, ?)", rows)\n    conn.commit()\n    after = conn.execute("SELECT COUNT(*) FROM items").fetchone()[0]\n    return after - before\n\nsession = build_session()\nconn = sqlite3.connect(":memory:")\nconn.execute(SCHEMA)\nnew_count = 0\nfor page in range(1, 3):\n    html = "<ul><li class='product'><h3>Item %d</h3><span class='price'>$10</span></li></ul>" % page\n    new_count += ingest(conn, parse_items(html))\n    time.sleep(0.1)\nprint({"pages": 2, "new": new_count})`,
  prompt: "为什么脚本按 hash 去重而不是按 URL？",
  correct: "商品字段变化时 hash 也会变，可以在同一 URL 下识别更新",
  wrong: "URL 一定唯一，比 hash 去重更可靠",
  correctFeedback: "正确：hash 覆盖字段级变化，URL 只是入口。",
  wrongFeedback: "错误：同一 URL 会因为价格更新变化，仅按 URL 无法识别。",
  additionalWrong: {
    label: "直接 INSERT，让主键冲突报错就好",
    feedback: "冲突报错会打断批处理，应使用 INSERT OR IGNORE 让增量流水线继续。"
  },
  lanes: ["初始化会话", "抓取解析", "增量入库"],
  laneValues: ["Session+Retry", "selectolax 抽取", "INSERT OR IGNORE"],
  log: ["建立会话", "抓取 2 页", "报告写入 stdout"],
  summary: ["会话统一注入 UA", "hash 作为唯一键", "报告便于监控运行结果"],
  sourceTitle: "Python requests + sqlite3 组合",
  sourceUrl: "https://requests.readthedocs.io/en/latest/"
});

export const pythonStageSixHttpScrapingLessons: LessonSpec[] = [...knowledgeLessons, project];
