import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "端到端自动化流水线";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-pipeline-stage-model",
    stageId: "python-automation-pipeline",
    order: 1,
    eyebrowStage: eyebrow,
    title: "流水线阶段拆分与契约",
    concept: "自动化流水线要按“采集 → 清洗 → 发布”等阶段拆分，每个阶段只依赖上一阶段的输出契约（schema）。契约清晰，才有可能替换单阶段实现或独立重跑。",
    points: ["每阶段定义显式输入输出", "契约用 dataclass 或 pydantic 表达", "阶段间通过文件或队列解耦"],
    memoryHook: "先画契约，再写实现",
    fileName: "stage_model.py",
    code: `from dataclasses import dataclass\nfrom typing import Iterable\n\n@dataclass\nclass RawRecord:\n    source: str\n    payload: dict\n\n@dataclass\nclass CleanRecord:\n    source: str\n    metric: str\n    value: float\n\ndef clean(records: Iterable[RawRecord]) -> list[CleanRecord]:\n    return [\n        CleanRecord(source=r.source, metric="orders", value=float(r.payload.get("orders", 0)))\n        for r in records\n    ]\n\ndemo = [RawRecord(source="crm", payload={"orders": "12"})]\nprint(clean(demo))`,
    prompt: "为什么流水线各阶段之间需要显式契约？",
    correct: "契约让阶段可以独立测试、替换实现或单独重跑",
    wrong: "契约只是文档，代码里可以按需修改字段",
    output: "[CleanRecord(source='crm', metric='orders', value=12.0)]",
    lanes: ["定义契约", "实现阶段", "组合流水线"],
    laneValues: ["dataclass Raw/Clean", "clean 函数", "调用 clean"],
    log: ["定义契约", "运行清洗", "打印结果"],
    summary: ["阶段拆分先定契约", "契约明确才能独立演进", "dataclass 是轻量表达方式"],
    sourceTitle: "Python dataclasses",
    sourceUrl: "https://docs.python.org/3/library/dataclasses.html"
  }),
  createPythonLesson({
    id: "python-pipeline-checkpoint",
    stageId: "python-automation-pipeline",
    order: 2,
    eyebrowStage: eyebrow,
    title: "断点续跑与 state 持久化",
    concept: "长流水线要能从中断处恢复。做法是把已完成的“阶段+分片”写入 state 文件（JSON 或 SQLite），启动时先读 state 跳过完成分片，只跑剩余任务。",
    points: ["state 用原子写入避免半截", "state 粒度到分片而非整批", "重跑先校验 state 是否合法"],
    memoryHook: "断点续跑靠 state，粒度决定恢复时长",
    fileName: "checkpoint.py",
    code: `import json\nimport os\nimport tempfile\nfrom pathlib import Path\n\nstate_path = Path("pipeline.state.json")\nstate = json.loads(state_path.read_text()) if state_path.exists() else {"done": []}\ntasks = ["shard-a", "shard-b", "shard-c"]\n\nfor task in tasks:\n    if task in state["done"]:\n        continue\n    # 真实场景执行任务\n    state["done"].append(task)\n    tmp = tempfile.NamedTemporaryFile("w", dir=state_path.parent, delete=False, encoding="utf-8")\n    json.dump(state, tmp)\n    tmp.close()\n    os.replace(tmp.name, state_path)\n\nprint(state["done"])`,
    prompt: "为什么每完成一个分片就要写一次 state？",
    correct: "让下一次重跑可以从最近成功的分片开始，恢复窗口更短",
    wrong: "state 只在整个流水线结束时写一次即可",
    output: "['shard-a', 'shard-b', 'shard-c']",
    lanes: ["读取 state", "执行分片", "写回 state"],
    laneValues: ["load JSON", "跳过完成分片", "原子替换 state"],
    log: ["读取 state", "执行 3 个分片", "打印完成列表"],
    summary: ["state 用原子替换", "粒度决定恢复速度", "重跑必须先读 state"],
    sourceTitle: "Python os.replace",
    sourceUrl: "https://docs.python.org/3/library/os.html#os.replace"
  }),
  createPythonLesson({
    id: "python-pipeline-error-recovery",
    stageId: "python-automation-pipeline",
    order: 3,
    eyebrowStage: eyebrow,
    title: "分级错误处理与降级",
    concept: "流水线错误要分级：可重试（网络抖动）、可降级（部分数据源不可用）、致命（配置错误）。分级决定动作：重试、跳过并标记、立即失败。",
    points: ["错误分级驱动策略", "重试要带指数退避", "降级要显式记录，避免静默丢失"],
    memoryHook: "错误先分级，再决定重试/降级/失败",
    fileName: "error_recovery.py",
    code: `import time\n\nclass Retryable(Exception):\n    pass\n\nclass Fatal(Exception):\n    pass\n\ndef fetch(source: str, attempt: int) -> str:\n    if source == "crm" and attempt < 2:\n        raise Retryable("network jitter")\n    if source == "erp":\n        raise Fatal("config missing")\n    return f"{source}:ok"\n\nresults = []\nfor source in ["crm", "erp", "shop"]:\n    for attempt in range(1, 4):\n        try:\n            results.append(fetch(source, attempt))\n            break\n        except Retryable:\n            time.sleep(0.01 * attempt)\n        except Fatal as exc:\n            results.append(f"{source}:degraded ({exc})")\n            break\nprint(results)`,
    prompt: "为什么把错误显式分级比“统一 retry 3 次”更合适？",
    correct: "不同错误的处理策略不同，分级避免对致命错误做无效重试",
    wrong: "统一重试更简单，反正失败最终都会被记录",
    output: "['crm:ok', 'erp:degraded (config missing)', 'shop:ok']",
    lanes: ["识别错误", "选择策略", "记录结果"],
    laneValues: ["Retryable/Fatal", "重试或降级", "写入结果列表"],
    log: ["crm 重试成功", "erp 降级", "shop 正常"],
    summary: ["错误分级是策略基础", "重试带退避避免风暴", "降级需显式记录"],
    sourceTitle: "Python 异常层次",
    sourceUrl: "https://docs.python.org/3/library/exceptions.html"
  }),
  createPythonLesson({
    id: "python-pipeline-artifact-cache",
    stageId: "python-automation-pipeline",
    order: 4,
    eyebrowStage: eyebrow,
    title: "artifact 缓存复用",
    concept: "流水线中间产物（清洗后的数据、编译好的报表）应写入 artifact 存储并用输入指纹作为 key，重跑时命中缓存直接跳过重复计算。",
    points: ["缓存 key 由输入指纹决定", "命中缓存直接跳过计算", "过期策略与容量限制成对出现"],
    memoryHook: "指纹一致 = 复用 artifact",
    fileName: "artifact_cache.py",
    code: `import hashlib\nimport json\nfrom pathlib import Path\n\ncache_dir = Path(".cache")\ncache_dir.mkdir(exist_ok=True)\n\ndef fingerprint(payload: dict) -> str:\n    raw = json.dumps(payload, sort_keys=True).encode()\n    return hashlib.blake2b(raw, digest_size=8).hexdigest()\n\ndef build_report(payload: dict) -> str:\n    key = fingerprint(payload)\n    target = cache_dir / f"{key}.html"\n    if target.exists():\n        return f"hit {key}"\n    target.write_text("<html>report</html>", encoding="utf-8")\n    return f"build {key}"\n\nprint(build_report({"week": 30}))\nprint(build_report({"week": 30}))`,
    prompt: "为什么 artifact 缓存的 key 通常来自输入的稳定指纹？",
    correct: "输入相同就代表输出相同，指纹一致时可以安全复用",
    wrong: "缓存 key 用随机 UUID 更安全",
    output: "build 4c02f2b1a3ce9d17\nhit 4c02f2b1a3ce9d17",
    lanes: ["生成指纹", "查缓存", "命中或构建"],
    laneValues: ["blake2b(payload)", "存在则复用", "否则构建"],
    log: ["第一次构建", "第二次命中缓存", "输出状态"],
    summary: ["key = 输入指纹", "命中缓存跳过计算", "过期策略与容量成对"],
    sourceTitle: "Python hashlib.blake2b",
    sourceUrl: "https://docs.python.org/3/library/hashlib.html#hashlib.blake2b"
  }),
  createPythonLesson({
    id: "python-pipeline-poetry-lock",
    stageId: "python-automation-pipeline",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Poetry / pip-tools 锁定依赖",
    concept: "自动化流水线必须可复现。用 Poetry 或 pip-tools 生成 `poetry.lock` / `requirements.txt` 锁文件，CI 与生产按锁文件安装，避免 minor 版本漂移。",
    points: ["锁文件才是真实依赖", "安装用 --frozen / --no-deps 强制一致", "升级依赖走独立 MR 便于回滚"],
    memoryHook: "锁文件不进仓库，等于每次跑都是新项目",
    fileName: "lock_file.py",
    code: `import subprocess\n\n# 生成锁文件（示例，实际项目在开发机跑一次）\nsubprocess.run(["poetry", "lock", "--no-update"], check=False)\n\n# 生产/CI 严格使用锁文件安装\nresult = subprocess.run(\n    ["poetry", "install", "--no-interaction", "--no-root", "--sync"],\n    capture_output=True,\n    text=True,\n)\nprint("returncode", result.returncode)`,
    prompt: "为什么 CI 中安装依赖应严格按锁文件而不是 `poetry add`？",
    correct: "锁文件保证跨环境版本一致，避免生产偷偷升级导致故障",
    wrong: "CI 每次 `add` 最新版本更好，能立刻拿到新特性",
    output: "returncode 0",
    lanes: ["生成锁文件", "冻结安装", "版本一致"],
    laneValues: ["poetry lock", "poetry install --sync", "returncode=0"],
    log: ["生成锁文件", "按锁文件安装", "打印 returncode"],
    summary: ["锁文件锁定实际版本", "CI 严格 install", "升级依赖走独立流程"],
    sourceTitle: "Poetry 官方文档",
    sourceUrl: "https://python-poetry.org/docs/"
  }),
  createPythonLesson({
    id: "python-pipeline-docker-package",
    stageId: "python-automation-pipeline",
    order: 6,
    eyebrowStage: eyebrow,
    title: "Dockerfile 打包脚本",
    concept: "把自动化脚本打包成镜像，可以在 CI、cron、容器平台复用。多阶段构建：builder 装依赖并编译，runtime 只保留必要文件，用非 root 用户降低权限风险。",
    points: ["多阶段构建瘦身", "非 root 用户运行", "锁文件先复制以最大化缓存"],
    memoryHook: "多阶段 + 非 root = 生产级镜像",
    fileName: "Dockerfile.py",
    code: `# 这里用 Python 字符串表达 Dockerfile 内容，方便版本化\nDOCKERFILE = """\nFROM python:3.12-slim AS builder\nWORKDIR /app\nCOPY pyproject.toml poetry.lock ./\nRUN pip install --no-cache-dir poetry==1.8.3 && \\\n    poetry export -f requirements.txt --output requirements.txt --without-hashes\n\nFROM python:3.12-slim AS runtime\nWORKDIR /app\nRUN useradd --system --no-create-home runner\nCOPY --from=builder /app/requirements.txt ./\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nUSER runner\nENTRYPOINT [\\\"python\\\", \\\"-m\\\", \\\"pipeline\\\"]\n\"\"\"\nprint(DOCKERFILE.strip().splitlines()[0])`,
    prompt: "为什么打包 Python 脚本推荐使用多阶段 Dockerfile？",
    correct: "builder 阶段装完依赖后被丢弃，runtime 镜像更小且减少攻击面",
    wrong: "多阶段只是审美需要，最终镜像大小并没有区别",
    output: "FROM python:3.12-slim AS builder",
    lanes: ["定义构建", "拷贝依赖", "锁定运行时"],
    laneValues: ["builder 阶段", "poetry export", "非 root runtime"],
    log: ["定义 Dockerfile", "分阶段拷贝", "输出首行"],
    summary: ["多阶段瘦身", "非 root 提高安全", "锁文件先复制利于缓存"],
    sourceTitle: "Docker Dockerfile reference",
    sourceUrl: "https://docs.docker.com/reference/dockerfile/"
  }),
  createPythonLesson({
    id: "python-pipeline-cron-deploy",
    stageId: "python-automation-pipeline",
    order: 7,
    eyebrowStage: eyebrow,
    title: "部署到远端 cron / 云函数",
    concept: "自动化脚本落地形态常见两种：Linux `cron` 或云函数（Serverless）。cron 需要显式设置 PATH 和日志重定向，云函数需要注意超时和冷启动，两者都要把执行结果发送到集中日志。",
    points: ["cron 环境几乎为空，PATH 要显式", "日志用 append 重定向便于回查", "云函数关注超时和冷启动"],
    memoryHook: "cron 无 PATH，云函数怕冷启动",
    fileName: "cron_deploy.py",
    code: `import subprocess\nfrom pathlib import Path\n\ncron_entry = "5 * * * * PATH=/usr/local/bin:/usr/bin /usr/bin/env python /opt/pipeline/run.py >> /var/log/pipeline.log 2>&1"\nPath("crontab.txt").write_text(cron_entry + "\\n", encoding="utf-8")\n\nresult = subprocess.run(["crontab", "-l"], capture_output=True, text=True)\nprint(result.returncode)`,
    prompt: "为什么 cron 里显式写 PATH 和日志重定向？",
    correct: "cron 的环境几乎为空，不写清楚会因缺少命令或看不到日志而排查困难",
    wrong: "PATH 由 shell 自动继承，日志会自动打到 syslog",
    output: "0",
    lanes: ["生成 cron 项", "写入 crontab", "验证结果"],
    laneValues: ["定义命令行", "写文件", "crontab -l"],
    log: ["生成 cron 项", "写入 crontab.txt", "查询返回 0"],
    summary: ["cron 需要显式 PATH", "日志 append 便于回查", "云函数关注超时冷启动"],
    sourceTitle: "Linux crontab 文档",
    sourceUrl: "https://man7.org/linux/man-pages/man5/crontab.5.html"
  }),
  createPythonLesson({
    id: "python-pipeline-metrics-log",
    stageId: "python-automation-pipeline",
    order: 8,
    eyebrowStage: eyebrow,
    title: "Prometheus / OpenTelemetry 观测",
    concept: "生产自动化必须可观测：`prometheus_client` 暴露 Counter/Histogram 指标；`opentelemetry` 提供分布式 trace。指标要覆盖“执行次数、失败次数、耗时分布”，trace 用于跨阶段定位瓶颈。",
    points: ["Counter 记录事件次数", "Histogram 观察耗时分布", "trace 跨阶段串联定位瓶颈"],
    memoryHook: "指标看整体，trace 看链路",
    fileName: "metrics_log.py",
    code: `from prometheus_client import Counter, Histogram, generate_latest\nimport time\n\nRUNS = Counter("pipeline_runs_total", "pipeline runs", ["stage", "status"])\nLATENCY = Histogram("pipeline_stage_seconds", "stage latency", ["stage"])\n\ndef run_stage(name: str) -> None:\n    start = time.perf_counter()\n    try:\n        # 模拟工作\n        time.sleep(0.001)\n        RUNS.labels(stage=name, status="ok").inc()\n    finally:\n        LATENCY.labels(stage=name).observe(time.perf_counter() - start)\n\nrun_stage("collect")\nrun_stage("clean")\nprint(generate_latest().decode().splitlines()[0])`,
    prompt: "为什么同时需要 Counter 和 Histogram？",
    correct: "Counter 反映事件量，Histogram 反映耗时分布，两者结合才能定位性能问题",
    wrong: "Histogram 已经包含总量，Counter 是冗余的",
    output: "# HELP pipeline_runs_total pipeline runs",
    lanes: ["注册指标", "执行阶段", "暴露 metrics"],
    laneValues: ["Counter+Histogram", "collect/clean", "generate_latest"],
    log: ["注册指标", "运行两个阶段", "输出首行 HELP"],
    summary: ["Counter 观察事件量", "Histogram 观察分布", "trace 跨阶段串联"],
    sourceTitle: "prometheus_client",
    sourceUrl: "https://github.com/prometheus/client_python"
  })
];

const project = createPythonStageProject({
  id: "python-automation-pipeline-project",
  stageId: "python-automation-pipeline",
  eyebrowStage: eyebrow,
  title: "自动化运营周报流水线",
  brief: "每周从 3 个数据源采集 → 清洗合并 → 生成 HTML 报告 → 通过 Feishu Webhook 推送，具备断点续跑、artifact 缓存与 Prometheus 指标暴露。",
  concept: "把阶段知识整合为可交付流水线：契约拆分、断点续跑、错误分级、artifact 缓存、依赖锁定、容器化部署与可观测。",
  points: ["阶段间通过契约解耦", "state 与 artifact 支撑断点续跑", "指标 + 通知构成闭环"],
  memoryHook: "契约 → state → artifact → 通知 = 闭环",
  fileName: "weekly_report.py",
  code: `from dataclasses import dataclass\nfrom pathlib import Path\nfrom prometheus_client import Counter, Histogram, start_http_server\nimport hashlib\nimport json\nimport os\nimport tempfile\nimport time\nimport urllib.request\n\nRUNS = Counter("weekly_runs_total", "runs", ["stage", "status"])\nLATENCY = Histogram("weekly_stage_seconds", "stage latency", ["stage"])\nSTATE = Path("weekly.state.json")\nCACHE = Path(".weekly-cache")\nCACHE.mkdir(exist_ok=True)\n\n@dataclass\nclass Record:\n    source: str\n    orders: int\n\ndef timed(stage: str):\n    def wrap(fn):\n        def inner(*args, **kwargs):\n            start = time.perf_counter()\n            try:\n                value = fn(*args, **kwargs)\n                RUNS.labels(stage=stage, status="ok").inc()\n                return value\n            except Exception:\n                RUNS.labels(stage=stage, status="fail").inc()\n                raise\n            finally:\n                LATENCY.labels(stage=stage).observe(time.perf_counter() - start)\n        return inner\n    return wrap\n\ndef load_state() -> dict:\n    return json.loads(STATE.read_text()) if STATE.exists() else {"done": []}\n\ndef save_state(state: dict) -> None:\n    tmp = tempfile.NamedTemporaryFile("w", dir=STATE.parent, delete=False, encoding="utf-8")\n    json.dump(state, tmp)\n    tmp.close()\n    os.replace(tmp.name, STATE)\n\n@timed("collect")\ndef collect(source: str) -> Record:\n    # 生产环境替换为真实 HTTP/DB 采集\n    return Record(source=source, orders={"crm": 120, "shop": 90, "erp": 60}[source])\n\n@timed("report")\ndef render(records: list[Record]) -> Path:\n    key = hashlib.blake2b(json.dumps([r.__dict__ for r in records], sort_keys=True).encode(), digest_size=8).hexdigest()\n    target = CACHE / f"{key}.html"\n    if not target.exists():\n        target.write_text("<html>total=" + str(sum(r.orders for r in records)) + "</html>", encoding="utf-8")\n    return target\n\n@timed("notify")\ndef notify(report: Path, webhook: str) -> int:\n    payload = json.dumps({"msg_type": "text", "content": {"text": report.read_text()}}).encode()\n    req = urllib.request.Request(webhook, data=payload, headers={"Content-Type": "application/json"})\n    with urllib.request.urlopen(req, timeout=5) as resp:\n        return resp.status\n\ndef main() -> None:\n    if not os.environ.get("FEISHU_WEBHOOK"):\n        raise SystemExit("missing FEISHU_WEBHOOK")\n    start_http_server(9109)\n    state = load_state()\n    records: list[Record] = []\n    for source in ["crm", "shop", "erp"]:\n        if source in state["done"]:\n            continue\n        records.append(collect(source))\n        state["done"].append(source)\n        save_state(state)\n    report = render(records)\n    status = notify(report, os.environ["FEISHU_WEBHOOK"])\n    print(json.dumps({"status": status, "report": str(report)}, ensure_ascii=False))\n\nif __name__ == "__main__":\n    main()`,
  prompt: "为什么这条流水线要同时具备 state 持久化、artifact 缓存和 Prometheus 指标？",
  correct: "三者分别对应“可续跑、可复用、可观测”，是生产级自动化的最小闭环",
  wrong: "只保留通知即可，其他都属于过度设计",
  correctFeedback: "正确：可续跑、可复用、可观测是自动化流水线的最小生产化闭环。",
  wrongFeedback: "错误：缺少 state 无法续跑，缺少缓存重复计算，缺少指标线上无法排障。",
  additionalWrong: {
    label: "指标暴露只在开发时有用，生产可以省略",
    feedback: "线上出问题时没有指标就等于摸黑操作，生产反而更需要指标。"
  },
  lanes: ["采集数据", "生成 artifact", "通知与观测"],
  laneValues: ["3 个数据源", "缓存 HTML", "Feishu Webhook + metrics"],
  log: ["加载 state", "采集三个数据源", "生成报告并推送"],
  summary: ["契约驱动阶段拆分", "state+artifact 支撑续跑", "指标+通知形成闭环"],
  sourceTitle: "OpenTelemetry Python",
  sourceUrl: "https://opentelemetry.io/docs/languages/python/"
});

export const pythonStageTenAutomationPipelineLessons: LessonSpec[] = [...knowledgeLessons, project];
