import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "Python 语法与运行模型";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-foundations-variable-binding",
    stageId: "python-foundations",
    order: 1,
    eyebrowStage: eyebrow,
    title: "变量绑定与身份",
    concept: "在 Python 中，`a = b` 只是让名字 `a` 指向 `b` 当前引用的对象，不复制数据。`is` 比较两个名字是否指向同一对象，`==` 才比较值；小整数（-5 到 256）会被缓存，因此 `is` 结果可能误导直觉。",
    points: ["赋值只是名字到对象的绑定", "is 比较身份，== 比较值", "小整数缓存让 is 出现意料之外的 True"],
    memoryHook: "赋值不是复制，是贴便签",
    fileName: "variable_binding.py",
    code: `a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a, b)\n\nx = 256\ny = 256\nprint(x is y, x == y)\n\nm = 500\nn = 500\nprint(m is n, m == n)`,
    prompt: "关于这段代码，哪一项描述最准确？",
    correct: "b 与 a 绑定到同一列表对象，因此 a 也被修改；小整数缓存让 x is y 为 True，而 500 不在缓存范围内",
    wrong: "b = a 会复制列表，因此 a 保持 [1, 2, 3] 不变",
    output: "[1, 2, 3, 4] [1, 2, 3, 4]\nTrue True\nFalse True",
    lanes: ["解释器", "对象空间", "标准输出"],
    laneValues: ["解析赋值", "共享列表引用", "打印身份与值"],
    log: ["绑定 a、b 到同一列表", "对 b 追加 4，a 同步变化", "打印 is / == 结果"],
    summary: ["赋值只创建名字，不复制对象", "小整数缓存会影响 is 判断", "需要复制时使用 list() 或 copy 模块"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/classes.html#a-word-about-names-and-objects",
    correctFeedback: "对：Python 的赋值语义只是名字绑定，身份与值是两件事。",
    wrongFeedback: "错：Python 不会隐式复制容器，b = a 只是多一个名字指向同一列表。",
    additionalWrong: {
      label: "is 与 == 在 Python 中完全等价，可以互换使用",
      feedback: "错：is 比身份，== 比值；对 500 这种非缓存整数，两者结果会不同。"
    }
  }),
  createPythonLesson({
    id: "python-foundations-dynamic-types",
    stageId: "python-foundations",
    order: 2,
    eyebrowStage: eyebrow,
    title: "动态类型与 duck typing",
    concept: "Python 是动态类型语言：变量本身没有类型，类型属于对象。`type()` 返回精确类型，`isinstance()` 允许子类。类型注解只是给静态检查器用的，运行时不会强制。",
    points: ["类型属于对象，不是变量", "isinstance 允许子类，type 严格匹配", "注解不影响运行时行为"],
    memoryHook: "会叫的都算鸭，注解只是路标",
    fileName: "dynamic_types.py",
    code: `def total(items: list[int]) -> int:\n    return sum(items)\n\nprint(total([1, 2, 3]))\nprint(total((4, 5, 6)))\n\nclass Duck:\n    def quack(self): print("quack")\n\nclass Robot:\n    def quack(self): print("beep")\n\nfor bird in (Duck(), Robot()):\n    bird.quack()`,
    prompt: "关于这段代码的类型行为，哪一项正确？",
    correct: "注解只是提示，运行时不检查参数类型；只要对象具备所需方法就能被调用",
    wrong: "运行 total((4, 5, 6)) 会因为传入 tuple 而抛出 TypeError",
    output: "6\n15\nquack\nbeep",
    lanes: ["解析注解", "运行时调用", "duck typing"],
    laneValues: ["读取类型提示", "sum 接受可迭代", "按方法调用"],
    log: ["加载函数，忽略注解约束", "sum 处理 list 与 tuple", "循环调用 quack 方法"],
    summary: ["运行时不校验类型注解", "duck typing 关注方法而非类型", "静态检查用 mypy/pyright 独立完成"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/library/typing.html",
    correctFeedback: "对：Python 运行时看行为不看类型，注解服务于工具链。",
    wrongFeedback: "错：sum 接受任何可迭代，tuple 完全可以工作。"
  }),
  createPythonLesson({
    id: "python-foundations-numbers-strings",
    stageId: "python-foundations",
    order: 3,
    eyebrowStage: eyebrow,
    title: "数字与字符串格式化",
    concept: "Python 整数是任意精度，不会像 C 那样溢出。字符串格式化有三种主流写法：f-string 最直观、`str.format` 兼容旧代码、`%` 类似 C printf。优先使用 f-string，性能与可读性都最佳。",
    points: ["int 天然支持大整数", "f-string 支持表达式与格式说明", "% 与 str.format 主要用于兼容"],
    memoryHook: "整数不溢出，格式选 f-string",
    fileName: "numbers_strings.py",
    code: `big = 2 ** 100\nprint(big)\n\nname = "Ada"\nscore = 92.5\n\nprint(f"{name}: {score:.1f}")\nprint("{}: {:.1f}".format(name, score))\nprint("%s: %.1f" % (name, score))`,
    prompt: "这三种格式化写法的关系是什么？",
    correct: "三种写法结果一致；f-string 在 Python 3.6+ 是首选，其它两种主要用于兼容旧代码",
    wrong: "整数 2 ** 100 会溢出返回负数，与 C 语言一致",
    output: "1267650600228229401496703205376\nAda: 92.5\nAda: 92.5\nAda: 92.5",
    lanes: ["求值", "格式化", "输出"],
    laneValues: ["2 ** 100 大整数", "三种模板生成字符串", "print 到 stdout"],
    log: ["计算大整数", "分别执行 f-string / format / %", "打印三行结果"],
    summary: ["int 任意精度，避免溢出焦虑", "f-string 是现代 Python 首选", "格式说明符 :.1f 控制小数位"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals",
    correctFeedback: "对：f-string 内联表达式最清晰，其它写法主要用于旧代码兼容。",
    wrongFeedback: "错：Python 的 int 是任意精度，不会溢出。"
  }),
  createPythonLesson({
    id: "python-foundations-control-flow",
    stageId: "python-foundations",
    order: 4,
    eyebrowStage: eyebrow,
    title: "条件、循环与 match/case",
    concept: "Python 3.10 引入 `match/case` 结构模式匹配，可以按类型、字面量、序列结构解构。`for-else` 和 `while-else` 中的 `else` 只在循环“正常结束”（未 break）时执行，是判断“找没找到”的清晰写法。",
    points: ["match/case 支持结构解构", "for-else 的 else 在未 break 时执行", "循环搭配 else 表达“查无此项”"],
    memoryHook: "match 按形状匹配，for-else 表达“没跳出”",
    fileName: "control_flow.py",
    code: `def classify(value):\n    match value:\n        case 0:\n            return "zero"\n        case [x, y]:\n            return f"pair({x},{y})"\n        case {"kind": kind}:\n            return f"map-{kind}"\n        case _:\n            return "other"\n\nprint(classify(0))\nprint(classify([1, 2]))\nprint(classify({"kind": "user"}))\n\nfor n in (2, 4, 6):\n    if n % 2:\n        break\nelse:\n    print("all even")`,
    prompt: "对这段代码，哪一项描述最准确？",
    correct: "match 会按顺序尝试每个 case 并解构；三次调用未 break，因此 for-else 的 else 会输出 all even",
    wrong: "for-else 的 else 会在每次循环结束时都执行一次",
    output: "zero\npair(1,2)\nmap-user\nall even",
    lanes: ["match 匹配", "解构提取", "循环判断"],
    laneValues: ["按 case 顺序尝试", "捕获 x, y 与 kind", "无 break 触发 else"],
    log: ["classify 三次调用", "match 按结构分派", "for 未 break，执行 else"],
    summary: ["match/case 支持字面量与结构模式", "_ 通配符兜底", "for-else 表达“循环未被 break”"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/controlflow.html#match-statements",
    correctFeedback: "对：match 按顺序做结构匹配，for-else 的 else 只在自然结束时运行。",
    wrongFeedback: "错：for-else 的 else 只在“循环没有被 break”时执行，不是每轮都跑。",
    additionalWrong: {
      label: "match/case 只能匹配整数字面量",
      feedback: "错：match/case 支持序列、映射、类实例等多种结构解构。"
    }
  }),
  createPythonLesson({
    id: "python-foundations-functions-scope",
    stageId: "python-foundations",
    order: 5,
    eyebrowStage: eyebrow,
    title: "函数、作用域与默认值陷阱",
    concept: "默认参数值在函数“定义时”求值一次，如果默认值是可变对象（list、dict），多次调用会共享同一份，从而出现累积效应。闭包默认只读取外层变量，写入需要 `nonlocal` 或 `global`。",
    points: ["默认参数在定义时求值一次", "可变默认值会跨调用累积", "写外层变量需 nonlocal"],
    memoryHook: "可变默认值是历史包袱，用 None 兜底",
    fileName: "functions_scope.py",
    code: `def bad(x, acc=[]):\n    acc.append(x)\n    return acc\n\nprint(bad(1))\nprint(bad(2))\n\ndef make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\n\ncounter = make_counter()\nprint(counter(), counter(), counter())`,
    prompt: "为什么第二次调用 bad(2) 返回 [1, 2] 而不是 [2]？",
    correct: "默认参数 acc=[] 只在函数定义时创建一次，两次调用共享同一列表",
    wrong: "Python 每次调用函数都会重新初始化默认参数，因此结果应该是 [2]",
    output: "[1]\n[1, 2]\n1 2 3",
    lanes: ["定义时求值", "调用共享", "闭包写入"],
    laneValues: ["acc=[] 创建一次", "两次 append 共享列表", "nonlocal 修改 n"],
    log: ["定义时构造默认列表", "调用累积追加", "闭包递增计数"],
    summary: ["默认值只求值一次", "可变默认参数用 None + 内部初始化替代", "闭包写外层变量需要 nonlocal"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/controlflow.html#default-argument-values",
    correctFeedback: "对：这是 Python 经典陷阱，写成 acc=None 再在函数里初始化才安全。",
    wrongFeedback: "错：默认参数只在定义时计算一次，两次调用共享同一个列表。"
  }),
  createPythonLesson({
    id: "python-foundations-exceptions",
    stageId: "python-foundations",
    order: 6,
    eyebrowStage: eyebrow,
    title: "异常层级与 raise from",
    concept: "`try/except/else/finally` 四段结构分工明确：`else` 只在没抛异常时执行，`finally` 无论如何都会执行。`raise NewError from original` 会保留原始异常的链条，便于排查根因。",
    points: ["else 在无异常时执行", "finally 永远执行，用于清理", "raise ... from ... 建立异常链"],
    memoryHook: "四段各司其职，from 留下作案痕迹",
    fileName: "exceptions.py",
    code: `def load(value):\n    try:\n        return int(value)\n    except ValueError as err:\n        raise RuntimeError(f"bad value: {value!r}") from err\n    else:\n        print("no error")\n    finally:\n        print("cleanup")\n\ntry:\n    load("abc")\nexcept RuntimeError as err:\n    print(type(err).__name__, "caused by", type(err.__cause__).__name__)`,
    prompt: "关于这段异常处理，哪一项描述最准确？",
    correct: "except 触发时不执行 else，但 finally 一定执行；raise ... from err 让 __cause__ 保留原始 ValueError",
    wrong: "只要写了 finally，else 也会跟着一起执行一次",
    output: "cleanup\nRuntimeError caused by ValueError",
    lanes: ["try 主体", "异常分派", "finally 清理"],
    laneValues: ["int('abc') 失败", "抛 RuntimeError from err", "打印 cleanup"],
    log: ["进入 try", "捕获 ValueError 并链式抛出", "finally 输出 cleanup"],
    summary: ["else 仅在无异常时运行", "finally 用于资源清理", "raise from 保留原始异常链"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/errors.html#exception-chaining",
    correctFeedback: "对：raise ... from 让 __cause__ 显式指向原因，排障更清晰。",
    wrongFeedback: "错：一旦 except 触发，else 就不会执行；finally 才是无条件执行的分支。",
    additionalWrong: {
      label: "raise ... from ... 是语法糖，不会保留原始异常信息",
      feedback: "错：from 会设置 __cause__，traceback 会明确展示“The above exception was the direct cause of”。"
    }
  }),
  createPythonLesson({
    id: "python-foundations-io-basics",
    stageId: "python-foundations",
    order: 7,
    eyebrowStage: eyebrow,
    title: "输入输出与上下文管理器",
    concept: "`open()` 返回的文件对象是资源，必须及时关闭；`with` 语句会在离开作用域时自动调用 `close()`，即使中间抛异常也不会泄漏。文本读写务必显式声明 `encoding`，跨平台默认值不可靠。",
    points: ["with 保证异常时也能关闭", "显式声明 encoding 避免乱码", "print 默认换行，input 不带换行"],
    memoryHook: "开必用 with，编码要写死",
    fileName: "io_basics.py",
    code: `from pathlib import Path\n\npath = Path("greet.txt")\nwith path.open("w", encoding="utf-8") as f:\n    f.write("你好\\n")\n    f.write("Python\\n")\n\nwith path.open(encoding="utf-8") as f:\n    for line in f:\n        print(line.rstrip())\n\nprint("done")`,
    prompt: "为什么读写文本文件推荐使用 with 并显式声明 encoding？",
    correct: "with 保证异常路径下也会关闭文件；显式编码避免依赖各平台默认值导致的乱码",
    wrong: "with 只是语法糖，可以直接用 open() 不 close()，也不会有资源泄漏",
    output: "你好\nPython\ndone",
    lanes: ["打开文件", "写入内容", "读取回显"],
    laneValues: ["with open w", "写入两行", "逐行 print"],
    log: ["写入 greet.txt", "关闭句柄", "读取并打印"],
    summary: ["文件是资源，用 with 管理", "显式 encoding 提前锁定语义", "print 默认追加换行，f.write 不会"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files",
    correctFeedback: "对：with + 显式 encoding 是 I/O 的最小安全实践。",
    wrongFeedback: "错：不关闭文件会依赖 GC，长脚本容易耗尽 fd 或丢失缓冲。"
  }),
  createPythonLesson({
    id: "python-foundations-main-entry",
    stageId: "python-foundations",
    order: 8,
    eyebrowStage: eyebrow,
    title: "打包运行与 __main__",
    concept: "被 `python file.py` 直接执行时，`__name__ == \"__main__\"`；被 `import` 时不成立。`python -m package` 会把包当模块执行，激活相对导入。命令行参数通过 `sys.argv` 或更结构化的 `argparse` 读取。",
    points: ["__name__ 区分脚本与模块", "python -m 支持包入口", "sys.argv[0] 是脚本名"],
    memoryHook: "__main__ 是入口开关",
    fileName: "main_entry.py",
    code: `import sys\n\ndef greet(name: str) -> None:\n    print(f"hello, {name}")\n\ndef main() -> None:\n    args = sys.argv[1:]\n    target = args[0] if args else "world"\n    greet(target)\n\nif __name__ == "__main__":\n    main()`,
    prompt: "关于 __name__ == \"__main__\" 的作用，哪一项最准确？",
    correct: "只有直接执行时才为 True；被 import 时不会自动运行 main，方便模块被复用",
    wrong: "__name__ == \"__main__\" 只是注释，删掉不影响任何行为",
    output: "hello, world",
    lanes: ["解释器入口", "参数解析", "调用主逻辑"],
    laneValues: ["设置 __name__", "读 sys.argv", "调用 main → greet"],
    log: ["python main_entry.py", "__name__ 判定为 __main__", "打印 hello, world"],
    summary: ["脚本与模块共存靠 __main__ 判断", "python -m 用于运行包", "结构化参数解析用 argparse"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/library/__main__.html",
    correctFeedback: "对：这一行是让文件既能当脚本执行、又能被 import 复用的关键。",
    wrongFeedback: "错：删掉这行后，import 该文件会直接执行 main，副作用无法控制。"
  })
];

const project = createPythonStageProject({
  id: "python-foundations-project",
  stageId: "python-foundations",
  eyebrowStage: eyebrow,
  title: "命令行文本清洗器",
  brief: "构建一个可通过命令行运行的文本清洗脚本：读取输入文件，去除首尾空白、统一小写、按空白切词，最后用 Counter 输出出现频率最高的若干词。",
  concept: "把阶段知识点串成流水线：`if __name__ == \"__main__\"` 打开入口，`sys.argv` / `open` + `with` 完成输入，`str.strip/lower/split` 做规范化，`collections.Counter` 统计词频，最后通过 f-string 打印 top-N。",
  points: ["with + encoding 保证输入安全", "strip/lower/split 组成清洗流水线", "Counter.most_common 输出稳定 top-N"],
  memoryHook: "读入→规范→计数→报告",
  fileName: "text_cleaner.py",
  code: `from __future__ import annotations\n\nimport sys\nfrom collections import Counter\nfrom pathlib import Path\n\n\ndef clean_words(text: str) -> list[str]:\n    return [token for token in text.strip().lower().split() if token]\n\n\ndef top_words(path: Path, top_n: int = 3) -> list[tuple[str, int]]:\n    with path.open(encoding="utf-8") as f:\n        text = f.read()\n    counter = Counter(clean_words(text))\n    return counter.most_common(top_n)\n\n\ndef main() -> None:\n    if len(sys.argv) < 2:\n        print("usage: python text_cleaner.py <file> [top_n]")\n        raise SystemExit(2)\n    path = Path(sys.argv[1])\n    top_n = int(sys.argv[2]) if len(sys.argv) > 2 else 3\n    for word, count in top_words(path, top_n):\n        print(f"{word}\\t{count}")\n\n\nif __name__ == "__main__":\n    main()`,
  prompt: "为什么这个脚本要用 Counter 而不是自己写一个 dict 累加？",
  correct: "Counter 是标准库经过优化的多集合实现，most_common 提供稳定排序，比手写 dict 更简洁且不易出错",
  wrong: "Counter 只是语法糖，运行时性能反而低于手写 dict，因此应尽量避免",
  additionalWrong: {
    label: "Counter 无法保证相同频率的稳定顺序，因此不适合排序输出",
    feedback: "错：Counter.most_common 底层使用 heapq，对同频率元素保持插入顺序，结果可复现。"
  },
  correctFeedback: "对：借助标准库能减少边界 bug，most_common 是 top-N 的标准解法。",
  wrongFeedback: "错：Counter 是 C 层实现的高性能容器，通常比手写字典更快且更少 bug。",
  lanes: ["读取", "清洗", "输出"],
  laneValues: ["原始文本", "strip/lower/split", "Counter"],
  log: ["读入 3 行", "分词 12 词", "输出 top-3"],
  summary: ["脚本入口统一用 __main__ 保护", "with + encoding 读入文本", "Counter.most_common 是 top-N 首选"],
  sourceTitle: "Python Standard Library",
  sourceUrl: "https://docs.python.org/3/library/collections.html#collections.Counter"
});

export const pythonStageZeroFoundationsLessons: LessonSpec[] = [
  ...knowledgeLessons,
  project
];
