import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "异步与服务开发";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-async-services-coroutine",
    stageId: "python-async-services",
    order: 1,
    eyebrowStage: eyebrow,
    title: "协程、事件循环与 asyncio.run",
    concept: "`async def` 定义的函数被调用后不会立即执行，而是返回一个协程对象，必须交给事件循环才会推进。`await` 让当前协程在等待时把控制权交回循环，让其它任务前进。`asyncio.run` 是顶层入口，负责创建/销毁事件循环——协程不是线程，同一循环内是单线程协作式调度。",
    points: ["async def 返回协程对象需被调度", "await 把控制权交回事件循环", "asyncio.run 管理循环生命周期"],
    memoryHook: "协程不跑，是调度器让它跑",
    fileName: "hello_async.py",
    code: `import asyncio\n\nasync def greet(name: str) -> str:\n    await asyncio.sleep(0.1)\n    return f"hello {name}"\n\nasync def main() -> None:\n    coro = greet("Ada")           # 不会执行，仅得到协程对象\n    print(type(coro).__name__)\n    result = await coro           # 交给循环调度\n    print(result)\n\nasyncio.run(main())`,
    prompt: "为什么 `coro = greet('Ada')` 不会立刻打印 `hello Ada`？",
    correct: "调用 async 函数只是构造协程对象，必须通过事件循环 `await` 或调度为 Task 才会推进",
    wrong: "async 函数在被调用的瞬间就已经在后台线程执行，`await` 只是等待结果",
    output: "coroutine\nhello Ada",
    lanes: ["构造协程", "事件循环", "await 结果"],
    laneValues: ["greet 返回 coroutine", "asyncio.run 建立 loop", "打印 hello Ada"],
    log: ["创建 main 协程", "loop 调度 greet 协程", "await 完成返回结果"],
    summary: ["协程对象需要调度器", "asyncio 是单线程协作", "asyncio.run 只应在顶层调用一次"],
    sourceTitle: "asyncio — Coroutines and Tasks",
    sourceUrl: "https://docs.python.org/3/library/asyncio-task.html",
    correctFeedback: "对：async 函数调用只创建协程对象，await 或 create_task 才驱动执行。",
    wrongFeedback: "错：asyncio 不会自动开线程，所有协程都在同一个事件循环内协作运行。",
    additionalWrong: {
      label: "可以在一个已经运行的循环里再次调用 `asyncio.run`",
      feedback: "错：`asyncio.run` 需要独占创建循环，嵌套调用会抛 RuntimeError。"
    }
  }),
  createPythonLesson({
    id: "python-async-services-gather",
    stageId: "python-async-services",
    order: 2,
    eyebrowStage: eyebrow,
    title: "asyncio.gather：并发聚合",
    concept: "`asyncio.gather(*aws)` 并发运行多个协程，返回一个 Future，其结果按传入顺序对齐（不是完成顺序）。默认任一失败会传播异常并取消其它任务；`return_exceptions=True` 时异常会作为结果返回，便于批量抓取多个来源的“部分失败”场景。",
    points: ["gather 并发调度但结果按顺序", "默认异常向上传播并取消同伴", "return_exceptions=True 收集错误对象"],
    memoryHook: "gather 按下发顺序收货，别看谁先到",
    fileName: "gather_fetch.py",
    code: `import asyncio\n\nasync def fetch(name: str, delay: float) -> str:\n    await asyncio.sleep(delay)\n    if name == "bad":\n        raise ValueError("boom")\n    return f"{name}@{delay}"\n\nasync def main() -> None:\n    results = await asyncio.gather(\n        fetch("a", 0.3),\n        fetch("bad", 0.1),\n        fetch("c", 0.2),\n        return_exceptions=True,\n    )\n    for item in results:\n        print(type(item).__name__, item)\n\nasyncio.run(main())`,
    prompt: "关于 `asyncio.gather` 的返回顺序与异常，哪一项描述准确？",
    correct: "结果列表严格按传入顺序对齐；`return_exceptions=True` 时异常对象也作为结果返回而不中断其它任务",
    wrong: "结果按完成时间排序，先完成的先出现在列表最前面",
    output: "str a@0.3\nValueError boom\nstr c@0.2",
    lanes: ["调度并发", "等待完成", "对齐结果"],
    laneValues: ["派发 3 个任务", "sleep 后返回或抛错", "按入参顺序输出"],
    log: ["gather 收到 3 个协程", "0.1s 时 bad 抛错但被捕获为结果", "按传入顺序返回列表"],
    summary: ["gather 并发不并行", "return_exceptions 收敛部分失败", "顺序对齐便于后续 zip 索引"],
    sourceTitle: "asyncio.gather",
    sourceUrl: "https://docs.python.org/3/library/asyncio-task.html#asyncio.gather"
  }),
  createPythonLesson({
    id: "python-async-services-taskgroup",
    stageId: "python-async-services",
    order: 3,
    eyebrowStage: eyebrow,
    title: "TaskGroup：结构化并发",
    concept: "Python 3.11 引入的 `asyncio.TaskGroup` 提供结构化并发：进入 `async with` 块内 `create_task` 派发子任务，退出时保证所有任务都已完成或取消，任一失败会取消其它任务，多个异常合并为 `ExceptionGroup` 抛出。相比 gather，异常语义更清晰、生命周期更明确。",
    points: ["async with 保证任务收敛", "任一失败自动取消其它任务", "多个异常聚合为 ExceptionGroup"],
    memoryHook: "TaskGroup 是并发的作用域",
    fileName: "task_group.py",
    code: `import asyncio\n\nasync def work(name: str, delay: float, fail: bool = False) -> str:\n    await asyncio.sleep(delay)\n    if fail:\n        raise RuntimeError(f"{name} failed")\n    return name\n\nasync def main() -> None:\n    try:\n        async with asyncio.TaskGroup() as tg:\n            tg.create_task(work("a", 0.2))\n            tg.create_task(work("b", 0.1, fail=True))\n            tg.create_task(work("c", 0.3))\n    except* RuntimeError as eg:\n        print("captured:", [str(e) for e in eg.exceptions])\n\nasyncio.run(main())`,
    prompt: "TaskGroup 与 gather 的核心差异是什么？",
    correct: "TaskGroup 通过 `async with` 保证子任务生命周期不逃逸，任一失败自动取消其它任务，多个异常聚合为 ExceptionGroup",
    wrong: "TaskGroup 只是 gather 的语法糖，两者行为完全一致",
    output: "captured: ['b failed']",
    lanes: ["派发子任务", "监控异常", "聚合失败"],
    laneValues: ["create_task × 3", "b 抛出 RuntimeError", "except* 捕获 ExceptionGroup"],
    log: ["进入 TaskGroup 上下文", "b 在 0.1s 抛错，触发其它任务取消", "except* 捕获 RuntimeError 组"],
    summary: ["TaskGroup 是 3.11+ 首选并发原语", "except* 语法专门解构 ExceptionGroup", "生命周期收敛在 async with 块内"],
    sourceTitle: "asyncio.TaskGroup",
    sourceUrl: "https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup",
    correctFeedback: "对：TaskGroup 让并发有作用域，异常有聚合，避免 gather 里“悬空任务”的问题。",
    wrongFeedback: "错：TaskGroup 有独立的取消与异常聚合语义，不等价于 gather。"
  }),
  createPythonLesson({
    id: "python-async-services-wait-for",
    stageId: "python-async-services",
    order: 4,
    eyebrowStage: eyebrow,
    title: "超时控制：wait_for 与 asyncio.timeout",
    concept: "`asyncio.wait_for(aw, timeout)` 包裹单个可等待对象，超时抛 `TimeoutError` 并取消内部任务。Python 3.11 引入的 `async with asyncio.timeout(...)` context manager 允许在一个作用域内对多个 await 统一设置截止时间，语义更接近“整个块最长执行多久”。",
    points: ["wait_for 只包一个 awaitable", "timeout() 覆盖整个 async with 块", "超时会取消并抛 TimeoutError"],
    memoryHook: "wait_for 保一件事，timeout 保一段路",
    fileName: "timeout_demo.py",
    code: `import asyncio\n\nasync def slow(delay: float) -> str:\n    await asyncio.sleep(delay)\n    return f"done {delay}"\n\nasync def main() -> None:\n    try:\n        await asyncio.wait_for(slow(1.0), timeout=0.2)\n    except TimeoutError:\n        print("single timed out")\n\n    try:\n        async with asyncio.timeout(0.3):\n            await slow(0.1)\n            await slow(0.5)\n    except TimeoutError:\n        print("scope timed out")\n\nasyncio.run(main())`,
    prompt: "`asyncio.wait_for` 与 `asyncio.timeout` 的选择依据是什么？",
    correct: "wait_for 适合单个 awaitable；timeout context manager 覆盖整个 async with 块内所有 await，语义是“这段作用域最多花多长时间”",
    wrong: "wait_for 已被彻底废弃，任何超时都必须使用 asyncio.timeout",
    output: "single timed out\nscope timed out",
    lanes: ["派发任务", "计时", "触发取消"],
    laneValues: ["调用 slow(1.0)", "0.2s 触发 timeout", "抛出 TimeoutError"],
    log: ["wait_for 0.2s 到期取消内部任务", "第二个作用域内累计超时", "两次都捕获 TimeoutError"],
    summary: ["超时通过取消实现", "timeout 支持“作用域”粒度", "被取消的协程会收到 CancelledError"],
    sourceTitle: "asyncio.timeout",
    sourceUrl: "https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout"
  }),
  createPythonLesson({
    id: "python-async-services-semaphore",
    stageId: "python-async-services",
    order: 5,
    eyebrowStage: eyebrow,
    title: "Semaphore：限制并发度",
    concept: "无节制地并发派发大量请求会击穿下游连接池和线程池，让整体延迟劣化。`asyncio.Semaphore(n)` 在协程之间共享一个计数令牌，`async with sem:` 保证同时最多 n 个协程进入临界段。它是最简单也是最常用的并发限流原语。",
    points: ["无限并发会击穿下游", "Semaphore 用令牌限制在场人数", "async with 自动获取和释放"],
    memoryHook: "Semaphore 是入场券，人多了排队",
    fileName: "semaphore_demo.py",
    code: `import asyncio\nfrom typing import Sequence\n\nasync def fetch(url: str, sem: asyncio.Semaphore) -> str:\n    async with sem:\n        await asyncio.sleep(0.1)  # 模拟 IO\n        return f"ok {url}"\n\nasync def crawl(urls: Sequence[str], limit: int = 3) -> list[str]:\n    sem = asyncio.Semaphore(limit)\n    tasks = [fetch(u, sem) for u in urls]\n    return await asyncio.gather(*tasks)\n\nresults = asyncio.run(crawl([f"u{i}" for i in range(10)]))\nprint(len(results), results[0])`,
    prompt: "为什么要用 `asyncio.Semaphore` 而不是直接 `asyncio.gather` 10 个任务？",
    correct: "直接并发 10 个任务会把下游连接数打满并放大失败面；Semaphore 让在场协程数被限制在预算内，压平尾延迟",
    wrong: "asyncio 会自动做限流，Semaphore 只是老代码遗留，不再需要",
    output: "10 ok u0",
    lanes: ["派发任务", "获取令牌", "释放并前进"],
    laneValues: ["10 个 fetch 协程", "同时 3 个进入临界", "gather 汇总结果"],
    log: ["gather 派发 10 个协程", "Semaphore 保持并发度 = 3", "全部完成返回 10 个结果"],
    summary: ["并发不等于越多越快", "Semaphore 保护下游连接池", "配合 timeout 组合出更稳的策略"],
    sourceTitle: "asyncio Synchronization Primitives",
    sourceUrl: "https://docs.python.org/3/library/asyncio-sync.html#semaphore",
    correctFeedback: "对：限流是异步客户端的基本功，Semaphore 是最直接的实现。",
    wrongFeedback: "错：asyncio 本身不做业务级限流，需要开发者显式约束。",
    additionalWrong: {
      label: "Semaphore 只能用在多线程里，asyncio 里没有效果",
      feedback: "错：`asyncio.Semaphore` 是异步版本，专门用于协程间协调。"
    }
  }),
  createPythonLesson({
    id: "python-async-services-http-client",
    stageId: "python-async-services",
    order: 6,
    eyebrowStage: eyebrow,
    title: "httpx.AsyncClient：连接池与超时",
    concept: "`httpx.AsyncClient` 长期存活时会复用连接池、DNS 缓存、TLS 会话；每次请求新建客户端会拖慢延迟并耗尽 fd。推荐用 `async with httpx.AsyncClient(timeout=..., limits=...)` 建立客户端并在应用生命周期内复用，超时用 `httpx.Timeout` 精细控制 connect/read/write/pool。",
    points: ["AsyncClient 长期复用连接池", "httpx.Timeout 分段控制", "follow_redirects 默认关闭"],
    memoryHook: "客户端一次建，多次用",
    fileName: "httpx_client.py",
    code: `import asyncio\nimport httpx\n\nasync def main() -> None:\n    timeout = httpx.Timeout(connect=2.0, read=5.0, write=5.0, pool=10.0)\n    limits = httpx.Limits(max_connections=20, max_keepalive_connections=10)\n\n    async with httpx.AsyncClient(\n        timeout=timeout,\n        limits=limits,\n        follow_redirects=True,\n    ) as client:\n        r = await client.get("https://httpbin.org/get")\n        print(r.status_code, r.headers.get("content-type"))\n\nasyncio.run(main())`,
    prompt: "为什么推荐把 `httpx.AsyncClient` 作为长期存活对象而不是每次请求新建？",
    correct: "长期复用可以共享连接池、TLS 会话和 DNS 缓存；每次新建会导致连接握手开销与文件描述符压力",
    wrong: "AsyncClient 是无状态对象，每次新建与复用没有任何性能差异",
    output: "200 application/json",
    lanes: ["构建客户端", "发起请求", "释放资源"],
    laneValues: ["复用连接池", "get 命中 keep-alive", "async with 关闭 client"],
    log: ["创建 AsyncClient 并初始化连接池", "发送 GET 请求并跟随重定向", "上下文结束时释放连接"],
    summary: ["Timeout 分段控制更精细", "Limits 决定池上限", "async with 保证释放"],
    sourceTitle: "HTTPX Async Support",
    sourceUrl: "https://www.python-httpx.org/async/"
  }),
  createPythonLesson({
    id: "python-async-services-async-generator",
    stageId: "python-async-services",
    order: 7,
    eyebrowStage: eyebrow,
    title: "异步生成器与 async for",
    concept: "`async def` 中使用 `yield` 会得到异步生成器，消费方用 `async for` 迭代。每一次 `__anext__` 都可能是一次异步 IO，因此适合流式来源：分页 API、消息队列、SSE、日志追尾。生成器自然按需拉取，不必把所有数据缓存到内存。",
    points: ["async def + yield 是异步生成器", "async for 每次触发 __anext__", "适合分页/流式数据源"],
    memoryHook: "async for 按需拉，每一口都可能等 IO",
    fileName: "async_pages.py",
    code: `import asyncio\nfrom typing import AsyncIterator\n\nasync def paged_items(total: int, page_size: int = 3) -> AsyncIterator[int]:\n    offset = 0\n    while offset < total:\n        await asyncio.sleep(0.05)  # 模拟拉取一页\n        for i in range(offset, min(offset + page_size, total)):\n            yield i\n        offset += page_size\n\nasync def main() -> None:\n    seen = 0\n    async for item in paged_items(7):\n        seen += 1\n    print("total seen", seen)\n\nasyncio.run(main())`,
    prompt: "异步生成器与普通生成器的关键差异是什么？",
    correct: "每次推进都是异步过程：`__anext__` 返回可等待对象，消费方必须用 `async for`，允许在“取下一项”前等待 IO",
    wrong: "异步生成器只是加了 async 关键字的普通生成器，行为完全一样",
    output: "total seen 7",
    lanes: ["生成器构造", "分页拉取", "消费聚合"],
    laneValues: ["paged_items 惰性协程", "每页 sleep 0.05s", "async for 累加 7 条"],
    log: ["构造异步生成器", "分 3 页拉取 7 个元素", "async for 迭代完成"],
    summary: ["流式数据首选异步生成器", "yield 之间可以 await IO", "配合 timeout/backpressure 使用"],
    sourceTitle: "PEP 525 – Asynchronous Generators",
    sourceUrl: "https://peps.python.org/pep-0525/"
  }),
  createPythonLesson({
    id: "python-async-services-error-model",
    stageId: "python-async-services",
    order: 8,
    eyebrowStage: eyebrow,
    title: "服务错误模型：瞬时 vs 永久",
    concept: "服务端与外部集成的错误必须区分“瞬时可重试”（网络超时、5xx、连接重置）与“永久失败”（4xx、参数错误、鉴权失败）。重试要带指数退避 + 抖动，并对非幂等操作使用幂等键。日志应输出结构化上下文：请求 ID、上游、耗时、错误类别，便于事后诊断。",
    points: ["瞬时错误可重试，永久错误立即失败", "重试用指数退避 + 抖动", "非幂等操作需要幂等键"],
    memoryHook: "先分类，再退避，最后带幂等键",
    fileName: "retry_policy.py",
    code: `import asyncio\nimport random\nimport httpx\n\nTRANSIENT = (httpx.TimeoutException, httpx.ConnectError)\n\nasync def call_with_retry(client: httpx.AsyncClient, url: str, *,\n                          idem_key: str, attempts: int = 3) -> httpx.Response:\n    for attempt in range(1, attempts + 1):\n        try:\n            r = await client.post(url, headers={"Idempotency-Key": idem_key})\n            if r.status_code >= 500:\n                raise httpx.HTTPStatusError("upstream 5xx", request=r.request, response=r)\n            return r\n        except TRANSIENT as exc:\n            if attempt == attempts:\n                raise\n            backoff = min(2 ** attempt, 8) + random.random()\n            await asyncio.sleep(backoff)\n    raise RuntimeError("unreachable")`,
    prompt: "关于服务错误模型，哪一项判断是正确的？",
    correct: "只对瞬时错误（超时、连接重置、5xx）重试并使用指数退避 + 抖动；非幂等操作必须携带幂等键防重复副作用",
    wrong: "对所有异常都无脑重试 10 次即可，客户端不需要区分错误类别",
    additionalWrong: {
      label: "永久性 4xx 错误只要重试足够多次就一定能成功",
      feedback: "错：4xx 表示客户端问题（鉴权、参数、业务规则），再多次重试也不会改变结果，只会放大放大压力。"
    },
    output: "200",
    lanes: ["错误分类", "退避重试", "结构化日志"],
    laneValues: ["瞬时/永久判定", "sleep 指数增长", "记录 idem_key"],
    log: ["第 1 次请求超时", "退避 2s + 抖动后重试", "第 2 次返回 200"],
    summary: ["重试必须分类，别打放大攻击", "退避加抖动避免共振", "结构化日志是可诊断性的地基"],
    sourceTitle: "HTTPX Exceptions",
    sourceUrl: "https://www.python-httpx.org/exceptions/",
    correctFeedback: "对：分类 + 退避 + 幂等键是异步服务重试的三件套。",
    wrongFeedback: "错：无差别重试会放大下游压力，尤其在非幂等操作上会造成副作用重复。"
  })
];

const project = createPythonStageProject({
  id: "python-async-services-project",
  stageId: "python-async-services",
  eyebrowStage: eyebrow,
  title: "异步 API 聚合器",
  brief: "用 asyncio + httpx.AsyncClient 并发拉取 3 个上游来源，用 Semaphore 限制在场并发数、用 asyncio.timeout 设定截止时间、用 gather(return_exceptions=True) 收敛部分失败，最终合并为一份聚合视图并暴露为一个 REST 接口。",
  concept: "聚合服务的核心问题是“怎么让部分失败不拖垮整体”。做法是：长期复用 AsyncClient；用 Semaphore 限制上游并发；用 asyncio.timeout 为聚合设定总超时；用 gather + return_exceptions=True 把每个来源的成功/异常并列返回；再由业务层决定是全量失败还是降级返回。",
  points: ["复用 AsyncClient 避免连接抖动", "Semaphore + timeout 双重保护", "return_exceptions 支持部分降级"],
  memoryHook: "聚合三件套：客户端复用、限流、限时",
  fileName: "aggregator.py",
  code: `import asyncio\nimport httpx\nfrom typing import Any\n\nSOURCES = [\n    "https://api.example.com/users/{id}",\n    "https://api.example.com/orders?user={id}",\n    "https://api.example.com/prefs/{id}",\n]\n\nasync def fetch_one(client: httpx.AsyncClient, url: str,\n                    sem: asyncio.Semaphore) -> dict[str, Any]:\n    async with sem:\n        r = await client.get(url)\n        r.raise_for_status()\n        return r.json()\n\nasync def aggregate(user_id: int, *, deadline: float = 1.5) -> dict[str, Any]:\n    urls = [tpl.format(id=user_id) for tpl in SOURCES]\n    sem = asyncio.Semaphore(3)\n    timeout = httpx.Timeout(connect=1.0, read=1.2, write=1.0, pool=2.0)\n\n    async with httpx.AsyncClient(timeout=timeout) as client:\n        try:\n            async with asyncio.timeout(deadline):\n                results = await asyncio.gather(\n                    *(fetch_one(client, u, sem) for u in urls),\n                    return_exceptions=True,\n                )\n        except TimeoutError:\n            return {"user_id": user_id, "status": "partial", "reason": "deadline"}\n\n    payload: dict[str, Any] = {"user_id": user_id, "status": "ok", "sources": {}}\n    for name, res in zip(("profile", "orders", "prefs"), results):\n        if isinstance(res, Exception):\n            payload["status"] = "partial"\n            payload["sources"][name] = {"error": type(res).__name__}\n        else:\n            payload["sources"][name] = res\n    return payload\n\nif __name__ == "__main__":\n    print(asyncio.run(aggregate(42)))`,
  prompt: "在这个异步聚合器里，最合理的失败与超时策略是什么？",
  correct: "长期复用 AsyncClient；用 Semaphore 限制并发、用 asyncio.timeout 设总截止时间；gather(return_exceptions=True) 让每个来源独立成败并在响应中降级为 partial",
  wrong: "每个来源单独 new 一个 AsyncClient，不设总超时，任一失败就整体 500 抛给上游",
  additionalWrong: {
    label: "把所有失败都当作瞬时错误，在聚合器里对每个上游各自重试 20 次，超时也重试",
    feedback: "错：4xx 与鉴权失败不该重试；无限重试会放大下游压力，且违反聚合层的总超时约束。"
  },
  correctFeedback: "对：复用客户端 + 限流 + 限时 + 部分降级，是异步聚合服务的标准姿态。",
  wrongFeedback: "错：每次新建客户端会累积连接开销；无总超时会让慢来源拖垮整个聚合层。",
  lanes: ["并发派发", "限流限时", "结果合并"],
  laneValues: ["3 个上游 GET", "Semaphore + timeout", "合并为一份 JSON"],
  log: ["派发 3 个 fetch 协程", "prefs 上游超时并被降级", "合并结果，status=partial"],
  summary: ["聚合服务要显式建模“部分成功”", "总超时优先于单请求超时", "结构化响应让上游能识别降级"],
  sourceTitle: "asyncio – High-level API",
  sourceUrl: "https://docs.python.org/3/library/asyncio-api-index.html"
});

export const pythonStageThreeAsyncServicesLessons: LessonSpec[] = [
  ...knowledgeLessons,
  project
];
