import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "正则与结构化解析";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-regex-basic-model",
    stageId: "python-regex-parsing",
    order: 1,
    eyebrowStage: eyebrow,
    title: "正则匹配的心智模型",
    concept: "`re.match` 只在字符串起点尝试匹配，`re.search` 扫描整串，`re.findall` 返回所有非重叠匹配。区分它们的锚定行为比记忆语法更重要。",
    points: ["match 锚定在起点", "search 扫描全串", "findall 返回列表"],
    memoryHook: "match 只看开头，search 扫全场",
    fileName: "match.py",
    code: `import re\n\ntext = "order: 3021 status: ok"\nprint(re.match(r"\\d+", text))\nprint(re.search(r"\\d+", text))\nprint(re.findall(r"\\d+", text))`,
    prompt: "上面代码最能说明什么？",
    correct: "match 从起点尝试，search 扫描全串，findall 返回全部匹配",
    wrong: "match 与 search 完全等价，只是名字不同",
    output: "None\n<re.Match object; span=(7, 11), match='3021'>\n['3021']",
    lanes: ["加载模式", "锚定或扫描", "输出结果"],
    laneValues: ["compile \\d+", "match/search/findall", "打印三行"],
    log: ["compile pattern", "run three APIs", "None / span / ['3021']"],
    summary: ["match 只锚定起点", "search 扫描全串", "findall 一次性返回全部命中"],
    sourceTitle: "Python re — Regular expression operations",
    sourceUrl: "https://docs.python.org/3/library/re.html"
  }),
  createPythonLesson({
    id: "python-regex-named-capture",
    stageId: "python-regex-parsing",
    order: 2,
    eyebrowStage: eyebrow,
    title: "命名捕获与结构化提取",
    concept: "用 `(?P<name>...)` 给捕获组命名，`match.groupdict()` 直接返回字典。相比按索引访问，命名捕获能让日志/URL 解析代码更贴近字段语义。",
    points: ["(?P<name>...) 定义命名组", "groupdict 直接得到 dict", "命名捕获便于下游 schema 对齐"],
    memoryHook: "命名捕获 = 正则里的字段名",
    fileName: "named.py",
    code: `import re\n\npattern = re.compile(r"(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(?P<method>GET|POST)\\s+(?P<path>\\S+)")\nline = "10.0.0.7 GET /api/orders"\nprint(pattern.search(line).groupdict())`,
    prompt: "为什么工程代码更推荐命名捕获？",
    correct: "字段名与下游 schema 对齐，比按数字索引更可维护",
    wrong: "命名捕获只是语法糖，运行时开销比编号组更高",
    output: "{'ip': '10.0.0.7', 'method': 'GET', 'path': '/api/orders'}",
    lanes: ["编译模式", "命名捕获", "输出字典"],
    laneValues: ["compile pattern", "search line", "groupdict()"],
    log: ["compile named groups", "match line", "输出字段字典"],
    summary: ["命名捕获让字段自解释", "groupdict 便于直接落库", "避免维护脆弱的索引号"],
    sourceTitle: "Python re — group and groupdict",
    sourceUrl: "https://docs.python.org/3/library/re.html#re.Match.groupdict"
  }),
  createPythonLesson({
    id: "python-regex-flags-verbose",
    stageId: "python-regex-parsing",
    order: 3,
    eyebrowStage: eyebrow,
    title: "忽略大小写与 VERBOSE 模式",
    concept: "`re.IGNORECASE` 让模式忽略大小写，`re.VERBOSE` 允许在正则中插入空白与注释，把复杂表达式写成多行文档。生产代码里的长正则应该用 VERBOSE 提高可读性。",
    points: ["re.I 忽略大小写", "re.X 允许空白与注释", "flags 用 | 组合"],
    memoryHook: "长正则请开 VERBOSE，别让同事猜",
    fileName: "verbose.py",
    code: `import re\n\npattern = re.compile(r"""\n    (?P<year>\\d{4})   # 年\n    -\n    (?P<month>\\d{2})  # 月\n""", re.VERBOSE | re.IGNORECASE)\nprint(pattern.search("date: 2026-07").groupdict())`,
    prompt: "为什么长正则推荐 VERBOSE 模式？",
    correct: "允许空白与注释，让模式接近文档，便于团队维护",
    wrong: "VERBOSE 会显著提升匹配速度，主要用于性能优化",
    output: "{'year': '2026', 'month': '07'}",
    lanes: ["解析多行模式", "命名匹配", "输出字典"],
    laneValues: ["compile VERBOSE", "search date", "groupdict()"],
    log: ["加载多行正则", "命中 2026-07", "打印字典"],
    summary: ["re.X 允许注释和空白", "flags 用 | 组合", "长正则应像文档一样可读"],
    sourceTitle: "Python re — Flags",
    sourceUrl: "https://docs.python.org/3/library/re.html#flags"
  }),
  createPythonLesson({
    id: "python-regex-backtracking",
    stageId: "python-regex-parsing",
    order: 4,
    eyebrowStage: eyebrow,
    title: "回溯陷阱与灾难性正则",
    concept: "嵌套量词如 `(a+)+` 在最坏输入下会指数级回溯，让线程卡死。用非贪婪匹配、锚定或占有量词（Python 3.11+ 的 `(?>...)` 原子分组）避免灾难性正则。",
    points: ["嵌套量词触发指数回溯", "原子分组阻止回溯", "写正则前先想反例输入"],
    memoryHook: "看见 (x+)+ 就要警觉：这就是回溯炸弹",
    fileName: "backtrack.py",
    code: `import re\nimport time\n\nbad = re.compile(r"(a+)+b")\nstart = time.perf_counter()\nprint(bool(bad.match("a" * 20 + "!")))\nprint(f"{time.perf_counter() - start:.4f}s")`,
    prompt: "为什么这段代码会成为性能杀手？",
    correct: "(a+)+ 存在指数级回溯，非法输入会让 CPU 打满",
    wrong: "Python 正则永远是线性时间，不会有性能问题",
    output: "False\n0.4210s",
    lanes: ["编译危险模式", "输入触发回溯", "耗时报告"],
    laneValues: ["compile (a+)+b", "匹配失败前反复回溯", "打印耗时"],
    log: ["compile pattern", "输入 20 个 a + !", "0.4210s"],
    summary: ["嵌套量词等于回溯地雷", "3.11+ 支持原子分组 (?>...)", "对不可信输入设定超时"],
    sourceTitle: "Python re — Regular expression HOWTO",
    sourceUrl: "https://docs.python.org/3/howto/regex.html"
  }),
  createPythonLesson({
    id: "python-csv-dictreader",
    stageId: "python-regex-parsing",
    order: 5,
    eyebrowStage: eyebrow,
    title: "csv.DictReader 结构化读取",
    concept: "`csv.DictReader` 按表头映射每行为 dict，天然承接 schema 校验。搭配 `newline=''` 打开文件才能正确处理 Windows 行尾。",
    points: ["newline='' 避免行尾错乱", "DictReader 用表头映射", "结合 dataclass 或 pydantic 校验"],
    memoryHook: "读 CSV 记得 newline=''，否则跨平台踩雷",
    fileName: "csv_read.py",
    code: `import csv\nfrom io import StringIO\n\nraw = "id,amount\\n1,42\\n2,58\\n"\nreader = csv.DictReader(StringIO(raw))\nrows = [row for row in reader]\nprint(rows[0])\nprint(sum(int(r["amount"]) for r in rows))`,
    prompt: "为什么工程里推荐 DictReader 而不是按索引读？",
    correct: "表头直接映射字段名，schema 变化时定位更清晰",
    wrong: "DictReader 只是内部会自动过滤空行，功能与 reader 相同",
    output: "{'id': '1', 'amount': '42'}\n100",
    lanes: ["打开文本", "映射表头", "聚合字段"],
    laneValues: ["StringIO 输入", "DictReader 生成 dict", "累加 amount"],
    log: ["构造 CSV 文本", "两行映射", "聚合结果 100"],
    summary: ["newline='' 必备", "DictReader 用表头映射", "字段仍是 str，需要显式转换"],
    sourceTitle: "Python csv — CSV File Reading and Writing",
    sourceUrl: "https://docs.python.org/3/library/csv.html"
  }),
  createPythonLesson({
    id: "python-json-schema-validate",
    stageId: "python-regex-parsing",
    order: 6,
    eyebrowStage: eyebrow,
    title: "jsonschema 校验数据契约",
    concept: "解析 JSON 后应先用 `jsonschema.Draft202012Validator` 校验结构，而不是相信调用方。校验器会一次性收集所有错误，便于给上游反馈。",
    points: ["先解析后校验", "iter_errors 收集全部问题", "schema 与代码放同一仓库"],
    memoryHook: "loads 只是解析，validate 才是契约",
    fileName: "schema.py",
    code: `import json\nfrom jsonschema import Draft202012Validator\n\nschema = {\n    "type": "object",\n    "required": ["id", "amount"],\n    "properties": {\n        "id": {"type": "string"},\n        "amount": {"type": "number", "minimum": 0}\n    }\n}\npayload = json.loads('{"id": "o-1", "amount": -3}')\nvalidator = Draft202012Validator(schema)\nfor err in validator.iter_errors(payload):\n    print(err.message)`,
    prompt: "为什么校验器优于手写 if 判断？",
    correct: "schema 是可复用的契约，iter_errors 能一次列出所有问题",
    wrong: "jsonschema 只是包了一层 assert，行为完全等价",
    output: "-3 is less than the minimum of 0",
    lanes: ["加载 schema", "解析 JSON", "收集错误"],
    laneValues: ["Draft202012Validator", "loads payload", "iter_errors 输出"],
    log: ["compile schema", "parse payload", "collect errors"],
    summary: ["schema 是可复用契约", "iter_errors 汇总问题", "上游看到详细错误消息"],
    sourceTitle: "jsonschema documentation",
    sourceUrl: "https://python-jsonschema.readthedocs.io/en/stable/"
  }),
  createPythonLesson({
    id: "python-yaml-safe-load",
    stageId: "python-regex-parsing",
    order: 7,
    eyebrowStage: eyebrow,
    title: "yaml.safe_load 安全解析",
    concept: "永远使用 `yaml.safe_load` 而不是 `yaml.load`。默认 `load` 会执行 YAML 中的构造器，加载不受信任的配置就等于打开 RCE 通道。",
    points: ["safe_load 只构造基础类型", "load 允许任意 Python 对象", "配置文件解析优先安全变体"],
    memoryHook: "yaml.load 是任意代码执行，safe_load 才是配置",
    fileName: "yaml_safe.py",
    code: `import yaml\n\ntext = """\nname: pipeline\nsteps:\n  - fetch\n  - parse\n  - persist\n"""\nconfig = yaml.safe_load(text)\nprint(config["name"], len(config["steps"]))`,
    prompt: "为什么解析外部 YAML 必须用 safe_load？",
    correct: "safe_load 只构造基础类型，避免任意代码执行风险",
    wrong: "safe_load 只是 load 的别名，安全性完全一样",
    output: "pipeline 3",
    lanes: ["读取 YAML", "安全解析", "输出结构"],
    laneValues: ["文本载入", "safe_load", "打印字段"],
    log: ["载入 YAML 文本", "safe_load", "pipeline 3"],
    summary: ["safe_load 是默认选择", "load 允许任意 tag，慎用", "配置解析后仍需 schema 校验"],
    sourceTitle: "PyYAML documentation",
    sourceUrl: "https://pyyaml.org/wiki/PyYAMLDocumentation"
  }),
  createPythonLesson({
    id: "python-parse-error-boundary",
    stageId: "python-regex-parsing",
    order: 8,
    eyebrowStage: eyebrow,
    title: "解析失败的错误边界",
    concept: "解析器应把 `json.JSONDecodeError`、`yaml.YAMLError`、`csv.Error` 转换为业务异常并附带定位信息（行号、字段、原始片段）。避免让底层异常直接冒到调度层。",
    points: ["异常翻译到业务语义", "附带定位便于回查", "对超大输入设定尺寸上限"],
    memoryHook: "解析失败要能告诉运维：哪一行、哪个字段",
    fileName: "boundary.py",
    code: `import json\n\nclass ParseError(Exception):\n    def __init__(self, source: str, cause: Exception):\n        super().__init__(f"{source} 解析失败: {cause}")\n\ndef load(source: str, raw: str) -> dict:\n    try:\n        return json.loads(raw)\n    except json.JSONDecodeError as exc:\n        raise ParseError(source, exc) from exc\n\ntry:\n    load("orders.json", "{ bad json")\nexcept ParseError as exc:\n    print(exc)`,
    prompt: "为什么要把 JSONDecodeError 翻译成 ParseError？",
    correct: "调度层只关心业务语义，异常应附带来源信息便于定位",
    wrong: "重复包装异常只是让 traceback 变长，没有实际收益",
    output: "orders.json 解析失败: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)",
    lanes: ["尝试解析", "捕获异常", "翻译并抛出"],
    laneValues: ["json.loads", "JSONDecodeError", "raise ParseError"],
    log: ["调用 load", "捕获底层异常", "打印业务异常"],
    summary: ["异常翻译保留 cause", "错误消息带上来源", "调度层可按业务异常分类"],
    sourceTitle: "Python json — JSONDecodeError",
    sourceUrl: "https://docs.python.org/3/library/json.html#json.JSONDecodeError"
  })
];

const project = createPythonStageProject({
  id: "python-regex-parsing-project",
  stageId: "python-regex-parsing",
  eyebrowStage: eyebrow,
  title: "多源日志统一解析器",
  brief: "把 nginx access log、app.json 结构化日志、syslog 三种源解析为统一 schema，用 jsonschema 校验后输出。",
  concept: "串联本阶段：命名捕获吃 nginx/syslog，json.loads 直读 app.json，最后用同一份 schema 校验并输出统一记录。",
  points: ["按来源选择解析器", "命名捕获对齐 schema", "校验失败落到 quarantine"],
  memoryHook: "多源解析 = 分流 + 归一 + 校验",
  fileName: "unify.py",
  code: `import json\nimport re\nfrom jsonschema import Draft202012Validator\n\nSCHEMA = {\n    "type": "object",\n    "required": ["source", "level", "message"],\n    "properties": {\n        "source": {"type": "string"},\n        "level": {"type": "string", "enum": ["info", "warn", "error"]},\n        "message": {"type": "string"}\n    }\n}\n\nNGINX = re.compile(r"(?P<ip>\\S+)\\s+\\S+\\s+\\S+\\s+\\[[^\\]]+\\]\\s+\\"(?P<method>\\S+)\\s+(?P<path>\\S+)")\nSYSLOG = re.compile(r"<(?P<pri>\\d+)>\\s+(?P<time>\\S+)\\s+(?P<host>\\S+)\\s+(?P<msg>.+)")\n\ndef parse(source: str, line: str) -> dict:\n    if source == "app.json":\n        record = json.loads(line)\n        return {"source": source, "level": record.get("level", "info"), "message": record.get("msg", "")}\n    if source == "nginx":\n        m = NGINX.search(line)\n        return {"source": source, "level": "info", "message": f"{m['method']} {m['path']}"}\n    m = SYSLOG.search(line)\n    return {"source": source, "level": "warn", "message": m["msg"]}\n\nvalidator = Draft202012Validator(SCHEMA)\nsamples = [\n    ("app.json", '{"level": "error", "msg": "db timeout"}'),\n    ("nginx", '10.0.0.5 - - [24/Jul/2026] "GET /api/health"'),\n    ("syslog", '<34> 2026-07-24T10:00:00 host job failed')\n]\nfor src, line in samples:\n    record = parse(src, line)\n    errors = list(validator.iter_errors(record))\n    if errors:\n        print("quarantine", src, errors[0].message)\n    else:\n        print(json.dumps(record, ensure_ascii=False))`,
  prompt: "为什么统一 schema 是这类脚本的核心？",
  correct: "下游消费者只对齐一份契约，来源差异被解析层吸收",
  wrong: "只要各来源字段够多，就无需统一 schema",
  correctFeedback: "正确：统一 schema 让下游不必关心每种来源的原始格式。",
  wrongFeedback: "错误：字段多而不统一，下游要维护 N 套解析逻辑。",
  additionalWrong: {
    label: "把校验放在下游消费者里更灵活",
    feedback: "校验应尽早在解析层完成，避免把脏数据传递给下游。"
  },
  lanes: ["按源分流", "统一 schema", "校验或隔离"],
  laneValues: ["3 种解析器", "构造 record", "打印或 quarantine"],
  log: ["载入 3 条样本", "解析并统一", "输出 JSON 与 quarantine"],
  summary: ["解析器按源分派", "同一 schema 吸收差异", "校验失败进入 quarantine"],
  sourceTitle: "Python re + jsonschema 组合",
  sourceUrl: "https://docs.python.org/3/library/re.html"
});

export const pythonStageFiveRegexParsingLessons: LessonSpec[] = [...knowledgeLessons, project];
