import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "CLI 与配置化脚本";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-cli-argparse-basics",
    stageId: "python-cli-tools",
    order: 1,
    eyebrowStage: eyebrow,
    title: "argparse 位置参数与选项参数",
    concept: "`argparse.ArgumentParser` 通过 `add_argument` 声明位置参数与选项参数。位置参数按顺序传入，选项参数用 `--name` 前缀触发，可以带默认值和类型转换。",
    points: ["位置参数按顺序解析", "选项参数需要 --long 或 -s 前缀", "type= 自动完成类型转换"],
    memoryHook: "位置定位置，选项靠 --",
    fileName: "cli_basics.py",
    code: `import argparse\n\nparser = argparse.ArgumentParser(prog="pack")\nparser.add_argument("target")\nparser.add_argument("--level", type=int, default=6)\nargs = parser.parse_args(["reports", "--level", "9"])\nprint(args.target, args.level)`,
    prompt: "这段代码最能说明什么？",
    correct: "argparse 会按声明顺序绑定位置参数，选项参数用 --level 触发并转成 int",
    wrong: "argparse 会把所有参数都当作字符串，需要自己再转换类型",
    output: "reports 9",
    lanes: ["解析器构建", "参数解析", "读取结果"],
    laneValues: ["ArgumentParser", "parse_args(list)", "args.target/level"],
    log: ["注册 target/level", "解析 reports --level 9", "reports 9"],
    summary: ["位置参数与选项参数区别在前缀", "type= 处理转换", "default= 提供缺省值"],
    sourceTitle: "Python argparse",
    sourceUrl: "https://docs.python.org/3/library/argparse.html"
  }),
  createPythonLesson({
    id: "python-cli-argparse-subcommands",
    stageId: "python-cli-tools",
    order: 2,
    eyebrowStage: eyebrow,
    title: "argparse subparsers 子命令",
    concept: "`add_subparsers` 让一个入口同时支持多个动作，例如 `tool init` 与 `tool sync`。用 `dest` 记录当前子命令，`set_defaults(func=...)` 绑定处理函数，方便分派。",
    points: ["subparsers 让 CLI 支持多动作", "dest 记录当前命令名", "set_defaults 绑定处理函数"],
    memoryHook: "一个入口，多个动词",
    fileName: "cli_sub.py",
    code: `import argparse\n\ndef do_init(args):\n    print("init", args.name)\n\ndef do_sync(args):\n    print("sync", args.force)\n\nparser = argparse.ArgumentParser()\nsub = parser.add_subparsers(dest="cmd", required=True)\np_init = sub.add_parser("init")\np_init.add_argument("name")\np_init.set_defaults(func=do_init)\np_sync = sub.add_parser("sync")\np_sync.add_argument("--force", action="store_true")\np_sync.set_defaults(func=do_sync)\nargs = parser.parse_args(["sync", "--force"])\nargs.func(args)`,
    prompt: "为什么用 set_defaults(func=...) 而不是自己 if/else 分派？",
    correct: "命令新增或改名时只需要调整子解析器，主入口保持稳定",
    wrong: "set_defaults 只是给参数设默认值，和分派没有关系",
    output: "sync True",
    lanes: ["注册子命令", "解析子命令", "分派处理器"],
    laneValues: ["init/sync", "cmd=sync", "调用 do_sync"],
    log: ["add_subparsers", "解析 sync --force", "sync True"],
    summary: ["subparsers 组织多动词入口", "dest 便于日志或分派", "set_defaults 绑定 handler"],
    sourceTitle: "Python argparse Sub-commands",
    sourceUrl: "https://docs.python.org/3/library/argparse.html#sub-commands"
  }),
  createPythonLesson({
    id: "python-cli-typer-typed",
    stageId: "python-cli-tools",
    order: 3,
    eyebrowStage: eyebrow,
    title: "typer 基于类型标注生成 CLI",
    concept: "`typer` 直接从函数签名生成 CLI：参数类型即校验，`typing.Annotated` + `typer.Option` 补充帮助文本与默认值，比 argparse 更贴近现代 Python。",
    points: ["函数签名即 CLI 契约", "Annotated 携带元数据", "typer 自动生成 --help"],
    memoryHook: "写函数就是写 CLI",
    fileName: "cli_typer.py",
    code: `import typer\nfrom typing import Annotated\n\napp = typer.Typer()\n\n@app.command()\ndef greet(\n    name: str,\n    times: Annotated[int, typer.Option(help="重复次数")] = 1,\n):\n    for _ in range(times):\n        print(f"hi {name}")\n\nif __name__ == "__main__":\n    app()`,
    prompt: "typer 相较 argparse 的核心优势是？",
    correct: "直接从类型注解推导参数与校验，减少样板代码",
    wrong: "typer 会自动并发执行命令，比 argparse 更快",
    output: "hi ada",
    lanes: ["定义命令", "解析类型", "调用函数"],
    laneValues: ["typer.Typer()", "int/str 校验", "print 结果"],
    log: ["注册 greet", "解析 --times 1", "hi ada"],
    summary: ["类型驱动 CLI 生成", "Annotated 提供帮助", "app() 就是入口"],
    sourceTitle: "Typer 官方文档",
    sourceUrl: "https://typer.tiangolo.com/"
  }),
  createPythonLesson({
    id: "python-cli-config-layers",
    stageId: "python-cli-tools",
    order: 4,
    eyebrowStage: eyebrow,
    title: "配置分层合并策略",
    concept: "生产 CLI 常见分层：内置默认 → 配置文件 → 环境变量 → 命令行参数。用连续 `dict` 更新实现优先级，越靠后覆盖越强，避免用户在多环境切换时踩坑。",
    points: ["按优先级由低到高合并", "字典 update 只覆盖显式提供的键", "记录来源方便排错"],
    memoryHook: "命令行永远最有话语权",
    fileName: "cli_config.py",
    code: `defaults = {"host": "localhost", "port": 80, "debug": False}\nfile_cfg = {"host": "example.com"}\nenv_cfg = {"port": 8080}\ncli_cfg = {"debug": True}\n\nmerged = {**defaults, **file_cfg, **env_cfg, **cli_cfg}\nprint(merged)`,
    prompt: "为什么按 defaults → file → env → cli 顺序合并？",
    correct: "越靠后的层级越贴近当次调用意图，需要覆盖前一层",
    wrong: "顺序不重要，dict 会自动按字段优先级合并",
    output: "{'host': 'example.com', 'port': 8080, 'debug': True}",
    lanes: ["构建默认", "叠加环境", "应用命令行"],
    laneValues: ["defaults dict", "file+env 合并", "cli 覆盖"],
    log: ["加载 defaults", "合并 file/env", "cli 生效"],
    summary: ["分层合并比嵌套判断清晰", "只提供显式键避免误覆盖", "记录来源利于排错"],
    sourceTitle: "Python dict 展开合并",
    sourceUrl: "https://docs.python.org/3/library/stdtypes.html#dict"
  }),
  createPythonLesson({
    id: "python-cli-toml-config",
    stageId: "python-cli-tools",
    order: 5,
    eyebrowStage: eyebrow,
    title: "tomllib 读取项目配置",
    concept: "Python 3.11+ 内置 `tomllib`，用二进制模式读取 `pyproject.toml` 或独立配置文件，不再需要第三方库。写入仍需要 `tomli-w`，因为 tomllib 只读。",
    points: ["tomllib 只读，必须用 rb 打开", "TOML 表映射为嵌套字典", "适合放稳定的项目级配置"],
    memoryHook: "tomllib 读，二进制开",
    fileName: "cli_toml.py",
    code: `import tomllib\nfrom pathlib import Path\n\nraw = Path("config.toml").read_bytes()\ncfg = tomllib.loads(raw.decode("utf-8"))\nprint(cfg["service"]["port"], cfg["service"]["name"])`,
    prompt: "为什么 tomllib 要求二进制读取？",
    correct: "TOML 强制 UTF-8，二进制读取避免平台默认编码带来的差异",
    wrong: "文本模式读取速度更慢，所以必须二进制",
    output: "8080 nodepath",
    lanes: ["读取字节", "解析 TOML", "读取字段"],
    laneValues: ["read_bytes", "tomllib.loads", "cfg['service']"],
    log: ["打开 config.toml", "解析成 dict", "8080 nodepath"],
    summary: ["3.11+ 内置 tomllib", "只读接口，写入需 tomli-w", "适合项目稳定配置"],
    sourceTitle: "Python tomllib",
    sourceUrl: "https://docs.python.org/3/library/tomllib.html"
  }),
  createPythonLesson({
    id: "python-cli-env-precedence",
    stageId: "python-cli-tools",
    order: 6,
    eyebrowStage: eyebrow,
    title: "环境变量与 dotenv 覆盖",
    concept: "`os.environ` 是运行时进程的字符串字典。团队协作常用 `.env` 文件为本地开发注入变量，但真实环境应以进程环境为准，避免把敏感值写进版本控制。",
    points: ["os.environ 是字符串字典", "dotenv 只影响进程内视图", ".env 不应进版本控制"],
    memoryHook: "环境变量 = 本机现实",
    fileName: "cli_env.py",
    code: `import os\n\ndef load_dotenv(path: str) -> None:\n    with open(path, "r", encoding="utf-8") as f:\n        for line in f:\n            line = line.strip()\n            if not line or line.startswith("#") or "=" not in line:\n                continue\n            key, _, value = line.partition("=")\n            os.environ.setdefault(key.strip(), value.strip())\n\nload_dotenv(".env")\nprint(os.environ.get("APP_ENV", "dev"))`,
    prompt: "为什么使用 setdefault 而不是直接赋值？",
    correct: "已有的真实环境变量优先，避免 .env 意外覆盖生产配置",
    wrong: "setdefault 只是写法习惯，和赋值完全等价",
    output: "prod",
    lanes: ["读取 dotenv", "填充 os.environ", "读取变量"],
    laneValues: [".env 文件", "setdefault", "APP_ENV=prod"],
    log: ["打开 .env", "写入未存在的键", "prod"],
    summary: ["dotenv 只是开发辅助", "setdefault 保护真实环境", "敏感值走密管而非 .env"],
    sourceTitle: "Python os.environ",
    sourceUrl: "https://docs.python.org/3/library/os.html#os.environ"
  }),
  createPythonLesson({
    id: "python-cli-logging-json",
    stageId: "python-cli-tools",
    order: 7,
    eyebrowStage: eyebrow,
    title: "结构化 JSON 日志",
    concept: "自定义 `logging.Formatter.format` 把日志记录序列化为 JSON 行，方便被 Loki/ELK 抓取。字段固定后下游只需按 key 查询，不需要正则解析人类可读文本。",
    points: ["Formatter 决定输出结构", "JSON Lines 便于聚合", "字段固定后利于告警"],
    memoryHook: "机器读日志，别写散文",
    fileName: "cli_log_json.py",
    code: `import json\nimport logging\n\nclass JsonFormatter(logging.Formatter):\n    def format(self, record: logging.LogRecord) -> str:\n        payload = {\n            "level": record.levelname,\n            "logger": record.name,\n            "msg": record.getMessage(),\n        }\n        return json.dumps(payload, ensure_ascii=False)\n\nhandler = logging.StreamHandler()\nhandler.setFormatter(JsonFormatter())\nlogger = logging.getLogger("cli")\nlogger.setLevel(logging.INFO)\nlogger.addHandler(handler)\nlogger.info("start")`,
    prompt: "结构化 JSON 日志的核心收益是？",
    correct: "字段固定，日志系统可以直接索引与聚合，无需正则",
    wrong: "只是为了让终端输出更好看",
    output: `{"level": "INFO", "logger": "cli", "msg": "start"}`,
    lanes: ["定义 Formatter", "注册 Handler", "写入日志"],
    laneValues: ["JsonFormatter", "StreamHandler", "info('start')"],
    log: ["注册 formatter", "注册 handler", `{"level": "INFO", ...}`],
    summary: ["Formatter 控制输出格式", "JSON Lines 是常见约定", "字段固定利于监控"],
    sourceTitle: "Python logging",
    sourceUrl: "https://docs.python.org/3/library/logging.html"
  }),
  createPythonLesson({
    id: "python-cli-package-entry",
    stageId: "python-cli-tools",
    order: 8,
    eyebrowStage: eyebrow,
    title: "pyproject.toml 注册命令入口",
    concept: "在 `pyproject.toml` 的 `[project.scripts]` 中声明命令名与入口函数，`pip install -e .` 后即可像系统命令一样调用，是可发布 CLI 的标准做法。",
    points: ["scripts 表映射命令→函数", "入口写 module:function", "pip install -e 便于开发调试"],
    memoryHook: "scripts 表 = CLI 的门牌号",
    fileName: "pyproject.toml",
    code: `[project]\nname = "pack-cli"\nversion = "0.1.0"\nrequires-python = ">=3.11"\ndependencies = ["typer>=0.12"]\n\n[project.scripts]\npack = "pack_cli.main:app"\n\n[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"`,
    prompt: "为什么 CLI 应该在 pyproject.toml 声明 scripts？",
    correct: "安装后自动生成可执行入口，用户可以直接运行命令而不用 python -m",
    wrong: "scripts 只是元数据，pip 不会做任何处理",
    output: "pack --help 可用",
    lanes: ["声明入口", "构建元数据", "安装暴露命令"],
    laneValues: ["[project.scripts]", "pack=pack_cli.main:app", "pack 命令可用"],
    log: ["读取 pyproject", "解析 scripts", "生成 pack 可执行"],
    summary: ["scripts 表定义命令入口", "module:function 引用可调用对象", "editable 安装适合开发调试"],
    sourceTitle: "Python packaging entry points",
    sourceUrl: "https://packaging.python.org/en/latest/specifications/entry-points/"
  })
];

const project = createPythonStageProject({
  id: "python-cli-tools-project",
  stageId: "python-cli-tools",
  eyebrowStage: eyebrow,
  title: "可发布的运维 CLI 工具",
  brief: "使用 typer 构建一个支持 --config / --dry-run / --verbose 的运维 CLI，通过 pyproject.toml 注册入口，可执行 pip install -e . 后直接命令调用。",
  concept: "串联本阶段：typer 组织命令、tomllib 加载配置、分层合并覆盖、结构化日志、pyproject.toml 暴露入口。执行时先输出计划，用户显式关闭 dry-run 才落地。",
  points: ["typer 定义命令与参数", "配置分层：默认→toml→env→CLI", "pyproject 注册可执行入口"],
  memoryHook: "CLI 工程化 = 类型 + 分层 + 入口",
  fileName: "packcli/main.py",
  code: `import json\nimport logging\nimport os\nimport tomllib\nfrom pathlib import Path\nfrom typing import Annotated\n\nimport typer\n\napp = typer.Typer(help="运维批处理 CLI")\nlogger = logging.getLogger("pack")\n\nDEFAULTS = {"target": "./out", "workers": 4, "dry_run": True}\n\ndef load_config(path: Path | None) -> dict:\n    if not path or not path.exists():\n        return {}\n    return tomllib.loads(path.read_text(encoding="utf-8"))\n\ndef env_overrides() -> dict:\n    override = {}\n    if "PACK_WORKERS" in os.environ:\n        override["workers"] = int(os.environ["PACK_WORKERS"])\n    return override\n\n@app.command()\ndef run(\n    config: Annotated[Path | None, typer.Option("--config")] = None,\n    dry_run: Annotated[bool, typer.Option("--dry-run/--apply")] = True,\n    verbose: Annotated[bool, typer.Option("--verbose")] = False,\n):\n    logging.basicConfig(level=logging.DEBUG if verbose else logging.INFO)\n    merged = {**DEFAULTS, **load_config(config), **env_overrides(), "dry_run": dry_run}\n    logger.info(json.dumps({"event": "resolved", "config": merged}, ensure_ascii=False))\n    if merged["dry_run"]:\n        typer.echo(f"[dry-run] would write to {merged['target']} with {merged['workers']} workers")\n        return\n    typer.echo(f"applied to {merged['target']}")\n\nif __name__ == "__main__":\n    app()`,
  prompt: "这个 CLI 工具为何默认 --dry-run？",
  correct: "运维脚本会改变系统状态，默认干跑先给出计划，用户显式确认再落地",
  wrong: "dry-run 只是调试选项，正式使用时可以直接删掉",
  correctFeedback: "正确：默认 dry-run 是可回滚的安全底线，配合结构化日志便于审计。",
  wrongFeedback: "错误：dry-run 是安全默认，不是可选调试功能。",
  additionalWrong: {
    label: "只要在测试环境跑过一次，就可以永久关闭 dry-run",
    feedback: "测试环境无法覆盖所有目标机情况，dry-run 是每次调用的安全网。"
  },
  lanes: ["解析入口", "合并配置", "执行或干跑"],
  laneValues: ["typer.run", "defaults→toml→env→cli", "输出计划或落地"],
  log: ["加载 pyproject 入口", "合并四层配置", "输出 dry-run 计划"],
  summary: ["typer 组织命令与类型", "四层配置合并保证确定性", "pyproject scripts 暴露入口"],
  sourceTitle: "Typer + pyproject.toml 组合",
  sourceUrl: "https://typer.tiangolo.com/"
});

export const pythonStageSevenCliToolsLessons: LessonSpec[] = [...knowledgeLessons, project];
