import type { LessonSpec } from "../../../lib/curriculum/types";
import { createPythonLesson, createPythonStageProject } from "./python-lesson-factory";

const eyebrow = "数据结构与标准库";

const knowledgeLessons: LessonSpec[] = [
  createPythonLesson({
    id: "python-data-structures-list-slice",
    stageId: "python-data-structures",
    order: 1,
    eyebrowStage: eyebrow,
    title: "list 切片与拷贝语义",
    concept: "切片 `a[start:stop:step]` 会创建新列表，但列表内的元素仍是引用。`copy.copy` 只做浅拷贝，嵌套结构仍共享；需要完全独立的副本时必须用 `copy.deepcopy`。",
    points: ["切片是浅拷贝的一种", "浅拷贝共享嵌套引用", "deepcopy 递归复制到最底层"],
    memoryHook: "切片只拷贝外壳，deepcopy 才拷内脏",
    fileName: "list_slice.py",
    code: `import copy\n\nmatrix = [[1, 2], [3, 4]]\nshallow = matrix[:]\nshallow[0].append(99)\nprint(matrix)\n\ndeep = copy.deepcopy(matrix)\ndeep[1].append(42)\nprint(matrix)\nprint(deep)`,
    prompt: "为什么修改 shallow[0] 会影响 matrix，而修改 deep[1] 不会？",
    correct: "切片和 copy.copy 只复制最外层容器，内部子列表仍是同一对象；deepcopy 会递归复制",
    wrong: "切片 matrix[:] 是深拷贝，修改 shallow 不应该影响 matrix",
    output: "[[1, 2, 99], [3, 4]]\n[[1, 2, 99], [3, 4]]\n[[1, 2, 99], [3, 4, 42]]",
    lanes: ["切片", "浅拷贝", "深拷贝"],
    laneValues: ["matrix[:]", "共享子列表", "copy.deepcopy 独立"],
    log: ["切片生成新外壳", "修改 shallow[0] 反映到 matrix", "deepcopy 后互不影响"],
    summary: ["切片只复制外层结构", "嵌套容器需 deepcopy", "拷贝语义决定安全边界"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/copy.html",
    correctFeedback: "对：切片、list()、copy.copy 都是浅拷贝，跨引用修改会互相看见。",
    wrongFeedback: "错：切片只复制外层容器，子列表仍是共享引用。"
  }),
  createPythonLesson({
    id: "python-data-structures-tuple-immutable",
    stageId: "python-data-structures",
    order: 2,
    eyebrowStage: eyebrow,
    title: "tuple 与解构、命名元组",
    concept: "tuple 不可变意味着无法重绑定其槽位，但槽位内的可变对象仍可被修改。`namedtuple` 给字段起名，兼具 tuple 的轻量与结构化访问，是函数多返回值的清晰替代。",
    points: ["tuple 不可变仅指顶层槽位", "解构支持 * 收集剩余项", "namedtuple 让字段可命名访问"],
    memoryHook: "元组是冻壳，槽位内的对象可能还会动",
    fileName: "tuple_immutable.py",
    code: `from collections import namedtuple\n\nPoint = namedtuple("Point", "x y")\np = Point(1, 2)\nprint(p.x, p.y, p)\n\nfirst, *middle, last = (1, 2, 3, 4, 5)\nprint(first, middle, last)\n\nbox = ([1, 2], [3, 4])\nbox[0].append(99)\nprint(box)`,
    prompt: "关于这段代码，哪一项描述最准确？",
    correct: "tuple 只保证顶层槽位不可重绑定；内部可变对象仍可被修改；namedtuple 让字段可命名访问",
    wrong: "tuple 完全不可变，因此 box[0].append(99) 会抛 TypeError",
    output: "1 2 Point(x=1, y=2)\n1 [2, 3, 4] 5\n([1, 2, 99], [3, 4])",
    lanes: ["构造", "解构", "内部可变"],
    laneValues: ["Point(1, 2)", "* 收集中间项", "list 可变"],
    log: ["创建 namedtuple", "解构五元组", "追加子列表元素"],
    summary: ["namedtuple 是轻量结构化返回", "* 语法收集变长部分", "不可变≠深层不可变"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/collections.html#collections.namedtuple",
    correctFeedback: "对：tuple 保证的是槽位绑定不变，槽位对象自身仍可能可变。",
    wrongFeedback: "错：tuple 不可变只是浅层语义，box[0] 是 list，可以调用 append。",
    additionalWrong: {
      label: "namedtuple 会显著降低访问性能，只应用于示意",
      feedback: "错：namedtuple 底层仍是 tuple，字段访问是常数时间，生产可用。"
    }
  }),
  createPythonLesson({
    id: "python-data-structures-dict-view",
    stageId: "python-data-structures",
    order: 3,
    eyebrowStage: eyebrow,
    title: "dict 视图、合并与 setdefault",
    concept: "`.keys()/.values()/.items()` 返回“视图对象”，会随原字典变化。Python 3.9+ 支持 `|` 与 `|=` 合并字典。`setdefault` 一步完成“取或设默认”，比先 `in` 再赋值更简洁。",
    points: ["视图对象随字典动态变化", "3.9+ 支持 | 与 |= 合并", "setdefault 减少 if 判断"],
    memoryHook: "视图是活的，| 是新的合并写法",
    fileName: "dict_view.py",
    code: `left = {"a": 1, "b": 2}\nright = {"b": 20, "c": 3}\nmerged = left | right\nprint(merged)\n\nkeys = left.keys()\nleft["c"] = 3\nprint(list(keys))\n\nbuckets: dict[str, list[int]] = {}\nfor pair in [("a", 1), ("a", 2), ("b", 3)]:\n    buckets.setdefault(pair[0], []).append(pair[1])\nprint(buckets)`,
    prompt: "为什么打印 list(keys) 会包含新加入的 'c'？",
    correct: "keys() 返回视图对象，会实时反映原字典的新增与删除",
    wrong: "keys() 返回快照列表，添加 left['c'] 不会影响 keys",
    output: "{'a': 1, 'b': 20, 'c': 3}\n['a', 'b', 'c']\n{'a': [1, 2], 'b': [3]}",
    lanes: ["合并", "视图", "分桶"],
    laneValues: ["left | right", "keys 动态更新", "setdefault + append"],
    log: ["生成 merged", "追加 c 后视图更新", "按 key 聚合值"],
    summary: ["| 与 |= 是首选合并方式", "视图对象是活引用", "setdefault 简化分桶逻辑"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/stdtypes.html#mapping-types-dict",
    correctFeedback: "对：视图是活的，写入原字典后视图立即可见。",
    wrongFeedback: "错：keys/values/items 都是视图对象，不是快照。"
  }),
  createPythonLesson({
    id: "python-data-structures-set-operations",
    stageId: "python-data-structures",
    order: 4,
    eyebrowStage: eyebrow,
    title: "set 运算与 frozenset",
    concept: "set 是哈希集合，`in` 平均 O(1)，支持 `|`、`&`、`-`、`^` 分别对应并、交、差、对称差。`frozenset` 不可变、可哈希，能作为 dict 的 key 或 set 的元素。",
    points: ["集合运算符对应数学操作", "in 是均摊 O(1)", "frozenset 可哈希，可嵌套"],
    memoryHook: "set 抓唯一，frozenset 才能进集合",
    fileName: "set_operations.py",
    code: `a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(a | b)\nprint(a & b)\nprint(a - b)\nprint(a ^ b)\n\nvisited = {frozenset({1, 2}), frozenset({3, 4})}\nprint(frozenset({2, 1}) in visited)`,
    prompt: "为什么 frozenset({2, 1}) in visited 是 True？",
    correct: "frozenset 是可哈希的集合，元素顺序不影响哈希，{2, 1} 与 {1, 2} 等价",
    wrong: "set 元素有顺序，{2, 1} 与 {1, 2} 是两个不同的对象",
    output: "{1, 2, 3, 4, 5, 6}\n{3, 4}\n{1, 2}\n{1, 2, 5, 6}\nTrue",
    lanes: ["并", "交/差", "frozenset 匹配"],
    laneValues: ["a | b", "a & b / a - b / a ^ b", "frozenset in set"],
    log: ["计算并交差", "对称差集", "frozenset 命中"],
    summary: ["集合运算符与数学一致", "frozenset 可作 dict key", "in 判定用集合更高效"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset",
    correctFeedback: "对：集合无序，只要元素相同哈希就相等。",
    wrongFeedback: "错：set/frozenset 是无序集合，{1, 2} 与 {2, 1} 相等。"
  }),
  createPythonLesson({
    id: "python-data-structures-iterator-generator",
    stageId: "python-data-structures",
    order: 5,
    eyebrowStage: eyebrow,
    title: "迭代器与生成器",
    concept: "迭代器实现 `__iter__` 与 `__next__`，用 `StopIteration` 结束循环。`yield` 会把函数变成生成器，按需产出元素，占用恒定内存。生成器表达式 `(x for x in ...)` 是懒惰版列表推导。",
    points: ["迭代器协议靠 __iter__/__next__", "yield 保存执行位置", "生成器表达式内存恒定"],
    memoryHook: "yield 是流水线，需要才产出",
    fileName: "iterator_generator.py",
    code: `def take(iterable, n):\n    it = iter(iterable)\n    for _ in range(n):\n        try:\n            yield next(it)\n        except StopIteration:\n            return\n\ndef squares():\n    i = 0\n    while True:\n        yield i * i\n        i += 1\n\nprint(list(take(squares(), 5)))\nprint(sum(x for x in range(10) if x % 2 == 0))`,
    prompt: "为什么 squares 无限循环，list(take(...)) 却能正常返回？",
    correct: "生成器是惰性的，take 只驱动前 5 次 next()，squares 剩余的迭代永远不会执行",
    wrong: "list() 会先展开整个 squares 再截断，因此这段代码会挂起",
    output: "[0, 1, 4, 9, 16]\n20",
    lanes: ["迭代器", "生成器", "组合消费"],
    laneValues: ["iter/next", "yield 暂停", "list/sum 消费"],
    log: ["创建 squares 生成器", "take 抽取 5 项", "打印列表与偶数和"],
    summary: ["yield 支持无限序列", "生成器表达式适合流式聚合", "iter/next 是低层协议"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/classes.html#generators",
    correctFeedback: "对：懒惰求值让无限流也能被有限消费。",
    wrongFeedback: "错：list() 会按迭代协议逐个取值，squares 只会被驱动 5 次。",
    additionalWrong: {
      label: "生成器函数在定义时就会立即执行到第一个 yield",
      feedback: "错：调用生成器函数只返回生成器对象，函数体在首次 next() 时才开始执行。"
    }
  }),
  createPythonLesson({
    id: "python-data-structures-comprehension",
    stageId: "python-data-structures",
    order: 6,
    eyebrowStage: eyebrow,
    title: "list/dict/set 推导式",
    concept: "推导式把“生成 + 过滤 + 转换”写成一行，避免手写循环 append。相比生成器表达式，list/dict/set 推导式会立即物化结果；只在需要即时消费全部结果时使用。",
    points: ["三种容器共用相似语法", "if 子句用于过滤", "生成器表达式适合大数据流"],
    memoryHook: "推导式一行搞定“筛选 + 转换”",
    fileName: "comprehension.py",
    code: `nums = range(1, 8)\nsquares = [n * n for n in nums if n % 2]\nprint(squares)\n\nlookup = {word: len(word) for word in ("ada", "grace", "linus")}\nprint(lookup)\n\nvowels = {ch for ch in "comprehension" if ch in "aeiou"}\nprint(sorted(vowels))\n\npairs = [(i, j) for i in range(2) for j in range(3)]\nprint(pairs)`,
    prompt: "关于这段代码的推导式行为，哪一项最准确？",
    correct: "三种推导式立即物化结果；嵌套 for 按外层先展开，与手写双层循环等价",
    wrong: "推导式内部使用生成器语义，因此 squares 只是一个懒惰序列，list(squares) 才会算出结果",
    output: "[1, 9, 25, 49]\n{'ada': 3, 'grace': 5, 'linus': 5}\n['e', 'i', 'o']\n[(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)]",
    lanes: ["筛选", "转换", "组合"],
    laneValues: ["if n % 2", "n * n / len(word)", "嵌套 for"],
    log: ["过滤奇数", "构建字典/集合", "笛卡尔展开"],
    summary: ["list/dict/set 推导即时物化", "生成器表达式懒惰", "过滤在 if 子句，转换在表达式头部"],
    sourceTitle: "Python Tutorial",
    sourceUrl: "https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions",
    correctFeedback: "对：把过滤和转换放在同一行，读起来更接近数学定义。",
    wrongFeedback: "错：list 推导式立即返回一个列表；懒惰版本是 (x for x in ...) 生成器表达式。"
  }),
  createPythonLesson({
    id: "python-data-structures-collections",
    stageId: "python-data-structures",
    order: 7,
    eyebrowStage: eyebrow,
    title: "collections 模块要点",
    concept: "`Counter` 统计出现次数、`defaultdict` 按需初始化 value、`deque` 提供两端 O(1) 的插入删除、`OrderedDict` 现代作用是 `move_to_end` 等顺序敏感操作。日常 dict 已保持插入顺序，不再需要 OrderedDict 来记忆顺序。",
    points: ["Counter 天然支持算术运算", "defaultdict 免去 setdefault", "deque 两端 O(1)"],
    memoryHook: "计数用 Counter，两端队列用 deque",
    fileName: "collections_kit.py",
    code: `from collections import Counter, defaultdict, deque, OrderedDict\n\nc = Counter("mississippi")\nprint(c.most_common(2))\n\nd: defaultdict[str, list[int]] = defaultdict(list)\nfor key, value in (("a", 1), ("a", 2), ("b", 3)):\n    d[key].append(value)\nprint(dict(d))\n\nq: deque[int] = deque([1, 2, 3])\nq.appendleft(0)\nq.append(4)\nprint(list(q))\n\no = OrderedDict.fromkeys("abc")\no.move_to_end("a")\nprint(list(o))`,
    prompt: "在现代 Python 中，OrderedDict 相对于普通 dict 的独特价值是什么？",
    correct: "现代 dict 已保证插入顺序，OrderedDict 的独特价值在于 move_to_end 等顺序敏感操作",
    wrong: "OrderedDict 是唯一能保证 dict 遍历顺序的容器，普通 dict 依然无序",
    output: "[('i', 4), ('s', 4)]\n{'a': [1, 2], 'b': [3]}\n[0, 1, 2, 3, 4]\n['b', 'c', 'a']",
    lanes: ["计数", "分桶", "队列"],
    laneValues: ["Counter", "defaultdict(list)", "deque appendleft"],
    log: ["统计字符", "分组累积", "两端插入"],
    summary: ["Counter/defaultdict 减少样板代码", "deque 是首选双端队列", "OrderedDict 强项在顺序 API"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/collections.html",
    correctFeedback: "对：Python 3.7+ 已把插入顺序纳入语言规范，OrderedDict 仍在于 move_to_end 等 API。",
    wrongFeedback: "错：CPython 3.6 起、语言 3.7 起 dict 已保证插入顺序。"
  }),
  createPythonLesson({
    id: "python-data-structures-datetime",
    stageId: "python-data-structures",
    order: 8,
    eyebrowStage: eyebrow,
    title: "datetime 与 zoneinfo 时区",
    concept: "`datetime.now()` 默认返回“朴素时间”（无时区），生产代码应使用带时区的“感知时间”。Python 3.9 引入 `zoneinfo`，可以直接读取系统时区数据库；`astimezone` 用于跨时区转换。",
    points: ["朴素时间 vs 感知时间", "zoneinfo 使用系统 tz 数据", "astimezone 完成时区换算"],
    memoryHook: "线上永远用感知时间，跨区就 astimezone",
    fileName: "datetime_zone.py",
    code: `from datetime import datetime, timezone\nfrom zoneinfo import ZoneInfo\n\nnaive = datetime(2026, 7, 24, 12, 0, 0)\naware = naive.replace(tzinfo=ZoneInfo("Asia/Shanghai"))\nprint(aware.isoformat())\n\nin_utc = aware.astimezone(timezone.utc)\nprint(in_utc.isoformat())\n\nparsed = datetime.fromisoformat("2026-07-24T04:00:00+00:00")\nprint(parsed.astimezone(ZoneInfo("Asia/Shanghai")).isoformat())`,
    prompt: "为什么生产代码建议统一使用带时区的 datetime？",
    correct: "带时区的 datetime 可以安全比较、序列化和转换，避免朴素时间在跨机器场景下的歧义",
    wrong: "朴素 datetime 与感知 datetime 完全等价，只是显示格式不同",
    output: "2026-07-24T12:00:00+08:00\n2026-07-24T04:00:00+00:00\n2026-07-24T12:00:00+08:00",
    lanes: ["构造", "时区绑定", "转换"],
    laneValues: ["datetime()", "ZoneInfo 绑定", "astimezone"],
    log: ["构造朴素时间", "绑定东八区", "转换为 UTC 与回程"],
    summary: ["朴素与感知 datetime 不能混算", "zoneinfo 使用系统 tz 库", "fromisoformat 支持带偏移的 ISO 字符串"],
    sourceTitle: "Python Standard Library",
    sourceUrl: "https://docs.python.org/3/library/zoneinfo.html",
    correctFeedback: "对：带时区 datetime 可以安全比较与序列化，跨机器不会出错。",
    wrongFeedback: "错：朴素 datetime 缺少时区上下文，比较、减法都会出错。",
    additionalWrong: {
      label: "zoneinfo 只在 Python 3.13 起可用，3.9 需要装 backports 才能用",
      feedback: "错：zoneinfo 从 Python 3.9 起就是标准库，3.8 及更早才需要 backports.zoneinfo。"
    }
  })
];

const project = createPythonStageProject({
  id: "python-data-structures-project",
  stageId: "python-data-structures",
  eyebrowStage: eyebrow,
  title: "日志聚合统计器",
  brief: "读取多行日志，按级别用 Counter 计数、按时间段（小时）分桶到 defaultdict，最后输出出现次数最多的前 N 个错误信息。",
  concept: "组合阶段知识点：迭代器读取 → 生成器表达式解析 → Counter/defaultdict 聚合 → datetime.fromisoformat 分桶 → 排序输出 top-N。",
  points: ["Counter 用于按级别统计", "defaultdict 按小时分桶", "fromisoformat 解析时间戳"],
  memoryHook: "解析→计数→按小时分桶→top-N",
  fileName: "log_aggregate.py",
  code: `from __future__ import annotations\n\nfrom collections import Counter, defaultdict\nfrom datetime import datetime\nfrom pathlib import Path\n\n\ndef parse_line(line: str) -> tuple[datetime, str, str] | None:\n    parts = line.strip().split("|", maxsplit=2)\n    if len(parts) < 3:\n        return None\n    ts, level, message = parts\n    try:\n        return datetime.fromisoformat(ts), level.strip(), message.strip()\n    except ValueError:\n        return None\n\n\ndef aggregate(path: Path, top_n: int = 3) -> dict[str, object]:\n    level_counter: Counter[str] = Counter()\n    hourly: defaultdict[int, int] = defaultdict(int)\n    messages: Counter[str] = Counter()\n\n    with path.open(encoding="utf-8") as f:\n        for parsed in (parse_line(line) for line in f):\n            if parsed is None:\n                continue\n            ts, level, message = parsed\n            level_counter[level] += 1\n            hourly[ts.hour] += 1\n            if level == "ERROR":\n                messages[message] += 1\n\n    return {\n        "levels": dict(level_counter),\n        "hourly": dict(sorted(hourly.items())),\n        "top_errors": messages.most_common(top_n),\n    }\n\n\nif __name__ == "__main__":\n    print(aggregate(Path("app.log")))`,
  prompt: "为什么按小时分桶要用 defaultdict(int) 而不是普通 dict？",
  correct: "defaultdict(int) 让第一次访问某小时时自动初始化为 0，避免手写 KeyError 判断",
  wrong: "defaultdict 与普通 dict 完全等价，只是名字不同",
  additionalWrong: {
    label: "分桶应该先遍历一次得到所有小时再初始化 dict，defaultdict 反而更慢",
    feedback: "错：defaultdict 在缺失键时才创建 value，一次遍历完成，比预先扫描更简洁。"
  },
  correctFeedback: "对：defaultdict 让分桶代码保持“读取即累加”的直觉。",
  wrongFeedback: "错：defaultdict 通过 __missing__ 提供缺省值工厂，普通 dict 会抛 KeyError。",
  lanes: ["解析", "聚合", "输出"],
  laneValues: ["fromisoformat 解析", "Counter + defaultdict", "most_common 输出"],
  log: ["读取 20 行日志", "按级别 / 小时聚合", "输出 top-3 错误"],
  summary: ["Counter 与 defaultdict 是聚合双件套", "生成器表达式支撑流式解析", "top-N 用 most_common 直接得到"],
  sourceTitle: "Python Standard Library",
  sourceUrl: "https://docs.python.org/3/library/collections.html"
});

export const pythonStageOneDataStructuresLessons: LessonSpec[] = [
  ...knowledgeLessons,
  project
];
